// clang-format off

#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include "POUS.h"
#include <beremiz/beremiz.h>

#include "iec_types_all.h"
#include "config1.h"

extern PROGRAM0 RESOURCE1__INSTANCE0;

#ifdef DEBUG_PLC
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err][%s:%d]: " _PRNTMSG "\n", __func__, __LINE__, ##__VA_ARGS__)
#else
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err]: " _PRNTMSG "\n", ##__VA_ARGS__)
#endif // DEBUG_PLC

void UnpackVar(void* varp, __IEC_types_enum vartype, void **value_p, void **f_value_p, uint8_t **flags);

int __variables_init_FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4(){
  iec_var_t *st;

  PROGRAM0 *p_PROGRAM0;
  LREAL *p_LREAL;
  ULINT *p_ULINT;
  REAL *p_REAL;
  FB_TIMINGS *p_FB_TIMINGS;
  BOOL *p_BOOL;
  UINT *p_UINT;
  PROC_AI_INIT *p_PROC_AI_INIT;
  FB_AI_INIT *p_FB_AI_INIT;
  TIME *p_TIME;
  STRUCT_AI *p_STRUCT_AI;
  DWORD *p_DWORD;
  BYTE *p_BYTE;
  WORD *p_WORD;
  AICONFIG *p_AICONFIG;
  PROC_AI *p_PROC_AI;
  FB_AISOURCEMLP *p_FB_AISOURCEMLP;
  TITEMAIN *p_TITEMAIN;
  TITEMDIN *p_TITEMDIN;
  TYPE_STATUSAI *p_TYPE_STATUSAI;
  TYPE_COMMANDANALOG *p_TYPE_COMMANDANALOG;
  FB_SUNPACKERCOMMAND *p_FB_SUNPACKERCOMMAND;
  TYPE_ANALOGLIMITFLAGS *p_TYPE_ANALOGLIMITFLAGS;
  TON *p_TON;
  R_TRIG *p_R_TRIG;
  FB_AISOURCEMLP_TIMER *p_FB_AISOURCEMLP_TIMER;
  PROC_AO_INIT *p_PROC_AO_INIT;
  FB_AO_INIT *p_FB_AO_INIT;
  STRUCT_AO *p_STRUCT_AO;
  AOCONFIG *p_AOCONFIG;
  PROC_AO *p_PROC_AO;
  FB_AOSOURCEMLP *p_FB_AOSOURCEMLP;
  TDOUBLEDATA *p_TDOUBLEDATA;
  PROC_DI_INIT *p_PROC_DI_INIT;
  FB_DI_INIT *p_FB_DI_INIT;
  STRUCT_DI *p_STRUCT_DI;
  __IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t *p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t;
  TYPE_RELIABLEBIT *p_TYPE_RELIABLEBIT;
  DICONFIG *p_DICONFIG;
  PROC_DI *p_PROC_DI;
  FB_DISOURCEMLP *p_FB_DISOURCEMLP;
  INT *p_INT;
  UDINT *p_UDINT;
  PROC_DO_INIT *p_PROC_DO_INIT;
  FB_DO_INIT *p_FB_DO_INIT;
  STRUCT_DO *p_STRUCT_DO;
  __IEC___ARRAY_OF_BOOL_16_t *p___IEC___ARRAY_OF_BOOL_16_t;
  DOCONFIG *p_DOCONFIG;
  PROC_DO *p_PROC_DO;
  FB_DOSOURCEMLP *p_FB_DOSOURCEMLP;
  TWORDDATA *p_TWORDDATA;
  OPC_AI_INIT *p_OPC_AI_INIT;
  OPC_AI_GET *p_OPC_AI_GET;
  OPC_AI_SET *p_OPC_AI_SET;
  OPC_PROTECTIONS_GET *p_OPC_PROTECTIONS_GET;
  PROTECTIONSCONFIG *p_PROTECTIONSCONFIG;
  STRUCT_AIPROTECTION *p_STRUCT_AIPROTECTION;
  STRUCT_DIPROTECTION *p_STRUCT_DIPROTECTION;
  OPC_PROTECTIONS_SET *p_OPC_PROTECTIONS_SET;
  OPC_ALGORITMS_SET *p_OPC_ALGORITMS_SET;
  ALGORITMSCONFIG *p_ALGORITMSCONFIG;
  STRUCT_ALG *p_STRUCT_ALG;
  STRUCT_ALGORITMSMANAGER *p_STRUCT_ALGORITMSMANAGER;
  STRUCT_PROTECTIONSMANAGER *p_STRUCT_PROTECTIONSMANAGER;
  STRUCT_ALGTIMERS *p_STRUCT_ALGTIMERS;
  ALGORITMSQUESTIONS *p_ALGORITMSQUESTIONS;
  STRUCT_QUESTION *p_STRUCT_QUESTION;
  OPC_ALGORITMS_GET *p_OPC_ALGORITMS_GET;
  PROC_IM_INIT *p_PROC_IM_INIT;
  FB_KRAN_INIT *p_FB_KRAN_INIT;
  STRUCT_KRAN *p_STRUCT_KRAN;
  FB_SWITCH_INIT *p_FB_SWITCH_INIT;
  STRUCT_SWITCH *p_STRUCT_SWITCH;
  FB_OILPUMP_INIT *p_FB_OILPUMP_INIT;
  STRUCT_OILPUMP *p_STRUCT_OILPUMP;
  FB_SECTIONSWITCH_INIT *p_FB_SECTIONSWITCH_INIT;
  STRUCT_SECTIONSWITCH *p_STRUCT_SECTIONSWITCH;
  FB_ANALOGPARAMETR_INIT *p_FB_ANALOGPARAMETR_INIT;
  STRUCT_ANALOGPARAMETR *p_STRUCT_ANALOGPARAMETR;
  FB_DISCRETPARAMETR_INIT *p_FB_DISCRETPARAMETR_INIT;
  STRUCT_DISCRETPARAMETR *p_STRUCT_DISCRETPARAMETR;
  FB_SINGLESIGNAL_INIT *p_FB_SINGLESIGNAL_INIT;
  STRUCT_SINGLESIGNAL *p_STRUCT_SINGLESIGNAL;
  FB_SINGLEOUTPUT_INIT *p_FB_SINGLEOUTPUT_INIT;
  STRUCT_SINGLEOUTPUT *p_STRUCT_SINGLEOUTPUT;
  IMCONFIG *p_IMCONFIG;
  STRUCT_RESERVEIM *p_STRUCT_RESERVEIM;
  STRUCT_RESERVEIM2 *p_STRUCT_RESERVEIM2;
  IM_SINGLESIGNALS *p_IM_SINGLESIGNALS;
  IM_SINGLEOUTPUTS *p_IM_SINGLEOUTPUTS;
  PROC_IM *p_PROC_IM;
  FB_KRAN *p_FB_KRAN;
  TYPE_STATUSDUALINPUT *p_TYPE_STATUSDUALINPUT;
  TYPE_COMMANDDUALINPUT *p_TYPE_COMMANDDUALINPUT;
  TOF *p_TOF;
  FB_OILPUMP *p_FB_OILPUMP;
  FB_SWITCH *p_FB_SWITCH;
  FB_SECTIONSWITCH *p_FB_SECTIONSWITCH;
  TYPE_BASKETSTATS *p_TYPE_BASKETSTATS;
  FB_MEANDR *p_FB_MEANDR;
  FB_SINGLESIGNAL *p_FB_SINGLESIGNAL;
  FB_SINGLEOUTPUT *p_FB_SINGLEOUTPUT;
  FB_DISCRETPARAMETR *p_FB_DISCRETPARAMETR;
  FB_ANALOGPARAMETR *p_FB_ANALOGPARAMETR;
  OPC_IM_GET *p_OPC_IM_GET;
  OPC_IM_SET *p_OPC_IM_SET;
  PROC_PROTECTIONS_INIT *p_PROC_PROTECTIONS_INIT;
  FB_DIPROTECTION_INIT *p_FB_DIPROTECTION_INIT;
  FB_AIPROTECTION_INIT *p_FB_AIPROTECTION_INIT;
  TYPE_PROTECTIONTAGS *p_TYPE_PROTECTIONTAGS;
  PROC_PROTECTION *p_PROC_PROTECTION;
  FB_DIPROTECTION *p_FB_DIPROTECTION;
  F_TRIG *p_F_TRIG;
  FB_MVPROTECTION *p_FB_MVPROTECTION;
  FB_KRANOPENPROTECTION *p_FB_KRANOPENPROTECTION;
  FB_AIPROTECTION *p_FB_AIPROTECTION;
  PROC_ALGORITMS *p_PROC_ALGORITMS;
  REMONTALG *p_REMONTALG;
  TYPE_MODEGPA *p_TYPE_MODEGPA;
  TYPE_COMMANDSPOTECTIONSMANAGER *p_TYPE_COMMANDSPOTECTIONSMANAGER;
  TESTPROTECTIONALG *p_TESTPROTECTIONALG;
  TESTIMALG *p_TESTIMALG;
  FB_AUTOTENALG *p_FB_AUTOTENALG;
  FB_AUTOPNSALG *p_FB_AUTOPNSALG;
  FB_AUTOAVOMALG *p_FB_AUTOAVOMALG;
  FB_VIBEGPNSALG *p_FB_VIBEGPNSALG;
  STRUCT_PHASEALGORITM *p_STRUCT_PHASEALGORITM;
  FB_PH_ALGORITM *p_FB_PH_ALGORITM;
  FB_PH_TIMER *p_FB_PH_TIMER;
  FB_QUESTION *p_FB_QUESTION;
  TYPE_ANSWERS *p_TYPE_ANSWERS;
  FB_PH_SWITCH *p_FB_PH_SWITCH;
  FB_PH_CUSTOMPHASE *p_FB_PH_CUSTOMPHASE;
  FB_AUTONUALG *p_FB_AUTONUALG;
  FB_PUSKOILSYSTEMALG *p_FB_PUSKOILSYSTEMALG;
  FB_PH_WAITANALOGVALUE *p_FB_PH_WAITANALOGVALUE;
  FB_PH_OILPUMP *p_FB_PH_OILPUMP;
  FB_ANTIPOMPAGALG *p_FB_ANTIPOMPAGALG;
  FB_TABLEVALUE_MIN *p_FB_TABLEVALUE_MIN;
  __IEC___ARRAY_OF_TYPE_TABLEREC_9_t *p___IEC___ARRAY_OF_TYPE_TABLEREC_9_t;
  TYPE_TABLEREC *p_TYPE_TABLEREC;
  FB_TABLEVALUE_MAX *p_FB_TABLEVALUE_MAX;
  FB_RASHODALG *p_FB_RASHODALG;
  FB_ZAPASALG *p_FB_ZAPASALG;
  NOALG *p_NOALG;
  FB_PH_KRAN *p_FB_PH_KRAN;
  FB_PH_SECTIONSWITCH *p_FB_PH_SECTIONSWITCH;
  AOALG *p_AOALG;
  PPUALG *p_PPUALG;
  FILLINGALG *p_FILLINGALG;
  FB_PH_DIPROTECTION *p_FB_PH_DIPROTECTION;
  ENGINERUNALG *p_ENGINERUNALG;
  PUSKKALG *p_PUSKKALG;
  PUSKVALG *p_PUSKVALG;
  TESTDPMGALG *p_TESTDPMGALG;
  TESTPMSALG *p_TESTPMSALG;
  FB_PH_AIPROTECTION *p_FB_PH_AIPROTECTION;
  APUSKALG *p_APUSKALG;
  SEMIAUTOPUSKALG *p_SEMIAUTOPUSKALG;
  FB_ALGORITMSMANAGER *p_FB_ALGORITMSMANAGER;
  FB_PROTECTIONSMANAGER *p_FB_PROTECTIONSMANAGER;

  { // 5306 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ARAIN.WFLAGS
    st = getVariable(5306);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ARAIN.WFLAGS", 64);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TITEMAIN = (TITEMAIN*)&p_FB_AISOURCEMLP->ARAIN;
    p_UINT = (UINT*)&p_TITEMAIN->WFLAGS;
    st->value_p = p_UINT;
  }
  { // 5307 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ARAIN.WRESERVED
    st = getVariable(5307);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ARAIN.WRESERVED", 67);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TITEMAIN = (TITEMAIN*)&p_FB_AISOURCEMLP->ARAIN;
    p_UINT = (UINT*)&p_TITEMAIN->WRESERVED;
    st->value_p = p_UINT;
  }
  { // 5308 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ARAIN.DBLVALUE
    st = getVariable(5308);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ARAIN.DBLVALUE", 66);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TITEMAIN = (TITEMAIN*)&p_FB_AISOURCEMLP->ARAIN;
    p_LREAL = (LREAL*)&p_TITEMAIN->DBLVALUE;
    st->value_p = p_LREAL;
  }
  { // 5309 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ARAIN.NANOSEC
    st = getVariable(5309);
    memcpy(st->IEC_TYPE, "ULINT", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ARAIN.NANOSEC", 65);
    st->size_data = sizeof(ULINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TITEMAIN = (TITEMAIN*)&p_FB_AISOURCEMLP->ARAIN;
    p_ULINT = (ULINT*)&p_TITEMAIN->NANOSEC;
    st->value_p = p_ULINT;
  }
  { // 5310 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ARAIN.RESERVE
    st = getVariable(5310);
    memcpy(st->IEC_TYPE, "ULINT", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ARAIN.RESERVE", 65);
    st->size_data = sizeof(ULINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TITEMAIN = (TITEMAIN*)&p_FB_AISOURCEMLP->ARAIN;
    p_ULINT = (ULINT*)&p_TITEMAIN->RESERVE;
    st->value_p = p_ULINT;
  }
  { // 5311 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ERR_MOD.WFLAGS
    st = getVariable(5311);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ERR_MOD.WFLAGS", 66);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TITEMDIN = (TITEMDIN*)&p_FB_AISOURCEMLP->ERR_MOD;
    p_UINT = (UINT*)&p_TITEMDIN->WFLAGS;
    st->value_p = p_UINT;
  }
  { // 5312 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ERR_MOD.WVALUE
    st = getVariable(5312);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ERR_MOD.WVALUE", 66);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TITEMDIN = (TITEMDIN*)&p_FB_AISOURCEMLP->ERR_MOD;
    p_UINT = (UINT*)&p_TITEMDIN->WVALUE;
    st->value_p = p_UINT;
  }
  { // 5313 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ERR_MOD.NANOSEC
    st = getVariable(5313);
    memcpy(st->IEC_TYPE, "ULINT", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ERR_MOD.NANOSEC", 67);
    st->size_data = sizeof(ULINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TITEMDIN = (TITEMDIN*)&p_FB_AISOURCEMLP->ERR_MOD;
    p_ULINT = (ULINT*)&p_TITEMDIN->NANOSEC;
    st->value_p = p_ULINT;
  }
  { // 5314 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ERR_MOD.RESERVE
    st = getVariable(5314);
    memcpy(st->IEC_TYPE, "ULINT", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ERR_MOD.RESERVE", 67);
    st->size_data = sizeof(ULINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TITEMDIN = (TITEMDIN*)&p_FB_AISOURCEMLP->ERR_MOD;
    p_ULINT = (ULINT*)&p_TITEMDIN->RESERVE;
    st->value_p = p_ULINT;
  }
  { // 5315 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.VALUE
    st = getVariable(5315);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.VALUE", 63);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->VALUE;
    st->value_p = p_LREAL;
  }
  { // 5316 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.STATUS
    st = getVariable(5316);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.STATUS", 64);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_DWORD = (DWORD*)&p_STRUCT_AI->STATUS;
    st->value_p = p_DWORD;
  }
  { // 5317 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.INTERVAL
    st = getVariable(5317);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.INTERVAL", 66);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BYTE = (BYTE*)&p_STRUCT_AI->INTERVAL;
    st->value_p = p_BYTE;
  }
  { // 5318 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.INCOMMAND
    st = getVariable(5318);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.INCOMMAND", 67);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 5319 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.BLCONNECT
    st = getVariable(5319);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.BLCONNECT", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->BLCONNECT;
    st->value_p = p_BOOL;
  }
  { // 5320 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DLL
    st = getVariable(5320);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DLL", 61);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLL;
    st->value_p = p_LREAL;
  }
  { // 5321 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DHL
    st = getVariable(5321);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DHL", 61);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHL;
    st->value_p = p_LREAL;
  }
  { // 5322 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DLA
    st = getVariable(5322);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DLA", 61);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLA;
    st->value_p = p_LREAL;
  }
  { // 5323 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DHA
    st = getVariable(5323);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DHA", 61);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHA;
    st->value_p = p_LREAL;
  }
  { // 5324 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DLW
    st = getVariable(5324);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DLW", 61);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLW;
    st->value_p = p_LREAL;
  }
  { // 5325 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DHW
    st = getVariable(5325);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DHW", 61);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHW;
    st->value_p = p_LREAL;
  }
  { // 5326 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.LL
    st = getVariable(5326);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.LL", 60);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LL;
    st->value_p = p_LREAL;
  }
  { // 5327 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.HL
    st = getVariable(5327);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.HL", 60);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HL;
    st->value_p = p_LREAL;
  }
  { // 5328 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.LA
    st = getVariable(5328);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.LA", 60);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LA;
    st->value_p = p_LREAL;
  }
  { // 5329 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.HA
    st = getVariable(5329);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.HA", 60);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HA;
    st->value_p = p_LREAL;
  }
  { // 5330 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.LW
    st = getVariable(5330);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.LW", 60);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LW;
    st->value_p = p_LREAL;
  }
  { // 5331 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.HW
    st = getVariable(5331);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.HW", 60);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HW;
    st->value_p = p_LREAL;
  }
  { // 5332 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.ISVALIDREF_LA
    st = getVariable(5332);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.ISVALIDREF_LA", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_LA;
    st->value_p = p_BOOL;
  }
  { // 5333 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.ISVALIDREF_HA
    st = getVariable(5333);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.ISVALIDREF_HA", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_HA;
    st->value_p = p_BOOL;
  }
  { // 5334 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.ISVALIDREF_LW
    st = getVariable(5334);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.ISVALIDREF_LW", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_LW;
    st->value_p = p_BOOL;
  }
  { // 5335 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.ISVALIDREF_HW
    st = getVariable(5335);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.ISVALIDREF_HW", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_HW;
    st->value_p = p_BOOL;
  }
  { // 5336 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.INPLL
    st = getVariable(5336);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.INPLL", 63);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->INPLL;
    st->value_p = p_LREAL;
  }
  { // 5337 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.INPHL
    st = getVariable(5337);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.INPHL", 63);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->INPHL;
    st->value_p = p_LREAL;
  }
  { // 5338 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.CURRENTSHOTCIRCUIT
    st = getVariable(5338);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.CURRENTSHOTCIRCUIT", 76);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CURRENTSHOTCIRCUIT;
    st->value_p = p_LREAL;
  }
  { // 5339 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.CURRENTBREAKCIRCUIT
    st = getVariable(5339);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.CURRENTBREAKCIRCUIT", 77);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CURRENTBREAKCIRCUIT;
    st->value_p = p_LREAL;
  }
  { // 5340 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.MAXCHANGESPEED
    st = getVariable(5340);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.MAXCHANGESPEED", 72);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXCHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 5341 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.MAXCHANGESPEEDDOWN
    st = getVariable(5341);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.MAXCHANGESPEEDDOWN", 76);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXCHANGESPEEDDOWN;
    st->value_p = p_LREAL;
  }
  { // 5342 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.CHANGESPEED
    st = getVariable(5342);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.CHANGESPEED", 69);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 5343 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.HISTERESIS
    st = getVariable(5343);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.HISTERESIS", 68);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HISTERESIS;
    st->value_p = p_LREAL;
  }
  { // 5344 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.APERTURFILTER
    st = getVariable(5344);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.APERTURFILTER", 71);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->APERTURFILTER;
    st->value_p = p_LREAL;
  }
  { // 5345 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.EXPONENTIALFILTER
    st = getVariable(5345);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.EXPONENTIALFILTER", 75);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->EXPONENTIALFILTER;
    st->value_p = p_LREAL;
  }
  { // 5346 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.RASSOGLASOVANIE
    st = getVariable(5346);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.RASSOGLASOVANIE", 73);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->RASSOGLASOVANIE;
    st->value_p = p_LREAL;
  }
  { // 5347 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.OPCCOMMANDSDISABLED
    st = getVariable(5347);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.OPCCOMMANDSDISABLED", 77);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 5348 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DISABLED_LA
    st = getVariable(5348);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DISABLED_LA", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_LA;
    st->value_p = p_BOOL;
  }
  { // 5349 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DISABLED_HA
    st = getVariable(5349);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DISABLED_HA", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_HA;
    st->value_p = p_BOOL;
  }
  { // 5350 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DISABLED_LW
    st = getVariable(5350);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DISABLED_LW", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_LW;
    st->value_p = p_BOOL;
  }
  { // 5351 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DISABLED_HW
    st = getVariable(5351);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DISABLED_HW", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_HW;
    st->value_p = p_BOOL;
  }
  { // 5352 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DELAYLA
    st = getVariable(5352);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DELAYLA", 65);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYLA;
    st->value_p = p_TIME;
  }
  { // 5353 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DELAYLW
    st = getVariable(5353);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DELAYLW", 65);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYLW;
    st->value_p = p_TIME;
  }
  { // 5354 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DELAYHW
    st = getVariable(5354);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DELAYHW", 65);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYHW;
    st->value_p = p_TIME;
  }
  { // 5355 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DELAYHA
    st = getVariable(5355);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DELAYHA", 65);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYHA;
    st->value_p = p_TIME;
  }
  { // 5356 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.MINVALUE_ISVALIDREF
    st = getVariable(5356);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.MINVALUE_ISVALIDREF", 77);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->MINVALUE_ISVALIDREF;
    st->value_p = p_BOOL;
  }
  { // 5357 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.MAXVALUE_ISVALIDREF
    st = getVariable(5357);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.MAXVALUE_ISVALIDREF", 77);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->MAXVALUE_ISVALIDREF;
    st->value_p = p_BOOL;
  }
  { // 5358 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.MINVALUE
    st = getVariable(5358);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.MINVALUE", 66);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MINVALUE;
    st->value_p = p_LREAL;
  }
  { // 5359 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.MAXVALUE
    st = getVariable(5359);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.MAXVALUE", 66);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXVALUE;
    st->value_p = p_LREAL;
  }
  { // 5360 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.INOPCCOMMANDSDISABLED
    st = getVariable(5360);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.INOPCCOMMANDSDISABLED", 79);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 5361 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.IMIT
    st = getVariable(5361);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.IMIT", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->IMIT;
    st->value_p = p_BOOL;
  }
  { // 5362 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.REMONT
    st = getVariable(5362);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.REMONT", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->REMONT;
    st->value_p = p_BOOL;
  }
  { // 5363 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.NS
    st = getVariable(5363);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.NS", 60);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS;
    st->value_p = p_BOOL;
  }
  { // 5364 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.NS_MIN
    st = getVariable(5364);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.NS_MIN", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS_MIN;
    st->value_p = p_BOOL;
  }
  { // 5365 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.NS_MAX
    st = getVariable(5365);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.NS_MAX", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS_MAX;
    st->value_p = p_BOOL;
  }
  { // 5366 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.INCOMMAND_ALG
    st = getVariable(5366);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.INCOMMAND_ALG", 71);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 5367 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.INCOMMAND_ARM
    st = getVariable(5367);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.INCOMMAND_ARM", 71);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 5368 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DMAXCHANGESPEED
    st = getVariable(5368);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DMAXCHANGESPEED", 73);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DMAXCHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 5369 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DMAXCHANGESPEEDDOWN
    st = getVariable(5369);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.STRAI.DMAXCHANGESPEEDDOWN", 77);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DMAXCHANGESPEEDDOWN;
    st->value_p = p_LREAL;
  }
  { // 5370 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._STATUSAI.NOTDEFINED
    st = getVariable(5370);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._STATUSAI.NOTDEFINED", 72);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NOTDEFINED;
    st->value_p = p_BYTE;
  }
  { // 5371 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._STATUSAI.LL
    st = getVariable(5371);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._STATUSAI.LL", 64);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LL;
    st->value_p = p_BYTE;
  }
  { // 5372 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._STATUSAI.HL
    st = getVariable(5372);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._STATUSAI.HL", 64);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HL;
    st->value_p = p_BYTE;
  }
  { // 5373 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._STATUSAI.NOTRELIABLE
    st = getVariable(5373);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._STATUSAI.NOTRELIABLE", 73);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NOTRELIABLE;
    st->value_p = p_BYTE;
  }
  { // 5374 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._STATUSAI.NORMAL
    st = getVariable(5374);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._STATUSAI.NORMAL", 68);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NORMAL;
    st->value_p = p_BYTE;
  }
  { // 5375 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._STATUSAI.LW
    st = getVariable(5375);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._STATUSAI.LW", 64);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LW;
    st->value_p = p_BYTE;
  }
  { // 5376 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._STATUSAI.HW
    st = getVariable(5376);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._STATUSAI.HW", 64);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HW;
    st->value_p = p_BYTE;
  }
  { // 5377 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._STATUSAI.LA
    st = getVariable(5377);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._STATUSAI.LA", 64);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LA;
    st->value_p = p_BYTE;
  }
  { // 5378 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._STATUSAI.HA
    st = getVariable(5378);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._STATUSAI.HA", 64);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HA;
    st->value_p = p_BYTE;
  }
  { // 5379 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._COMMANDANALOG.CMD_SETUSTAVKI
    st = getVariable(5379);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._COMMANDANALOG.CMD_SETUSTAVKI", 81);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TYPE_COMMANDANALOG = (TYPE_COMMANDANALOG*)&p_FB_AISOURCEMLP->_COMMANDANALOG;
    p_WORD = (WORD*)&p_TYPE_COMMANDANALOG->CMD_SETUSTAVKI;
    st->value_p = p_WORD;
  }
  { // 5380 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._COMMANDANALOG.CMD_SETREMONT
    st = getVariable(5380);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._COMMANDANALOG.CMD_SETREMONT", 80);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TYPE_COMMANDANALOG = (TYPE_COMMANDANALOG*)&p_FB_AISOURCEMLP->_COMMANDANALOG;
    p_WORD = (WORD*)&p_TYPE_COMMANDANALOG->CMD_SETREMONT;
    st->value_p = p_WORD;
  }
  { // 5381 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._COMMANDANALOG.CMD_RESETREMONT
    st = getVariable(5381);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._COMMANDANALOG.CMD_RESETREMONT", 82);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TYPE_COMMANDANALOG = (TYPE_COMMANDANALOG*)&p_FB_AISOURCEMLP->_COMMANDANALOG;
    p_WORD = (WORD*)&p_TYPE_COMMANDANALOG->CMD_RESETREMONT;
    st->value_p = p_WORD;
  }
  { // 5382 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._COMMANDANALOG.CMD_KVITNOTRELIABLE
    st = getVariable(5382);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._COMMANDANALOG.CMD_KVITNOTRELIABLE", 86);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TYPE_COMMANDANALOG = (TYPE_COMMANDANALOG*)&p_FB_AISOURCEMLP->_COMMANDANALOG;
    p_WORD = (WORD*)&p_TYPE_COMMANDANALOG->CMD_KVITNOTRELIABLE;
    st->value_p = p_WORD;
  }
  { // 5387 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._ANALOGLIMITFLAGS.NONE
    st = getVariable(5387);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._ANALOGLIMITFLAGS.NONE", 74);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->NONE;
    st->value_p = p_BYTE;
  }
  { // 5388 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._ANALOGLIMITFLAGS.LL
    st = getVariable(5388);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._ANALOGLIMITFLAGS.LL", 72);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->LL;
    st->value_p = p_BYTE;
  }
  { // 5389 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._ANALOGLIMITFLAGS.LW
    st = getVariable(5389);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._ANALOGLIMITFLAGS.LW", 72);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->LW;
    st->value_p = p_BYTE;
  }
  { // 5390 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._ANALOGLIMITFLAGS.HW
    st = getVariable(5390);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._ANALOGLIMITFLAGS.HW", 72);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->HW;
    st->value_p = p_BYTE;
  }
  { // 5391 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._ANALOGLIMITFLAGS.LA
    st = getVariable(5391);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._ANALOGLIMITFLAGS.LA", 72);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->LA;
    st->value_p = p_BYTE;
  }
  { // 5392 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._ANALOGLIMITFLAGS.HA
    st = getVariable(5392);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._ANALOGLIMITFLAGS.HA", 72);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->HA;
    st->value_p = p_BYTE;
  }
  { // 5393 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._ANALOGLIMITFLAGS.HL
    st = getVariable(5393);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._ANALOGLIMITFLAGS.HL", 72);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->HL;
    st->value_p = p_BYTE;
  }
  { // 5394 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._ANALOGLIMITFLAGS.SIPUP
    st = getVariable(5394);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._ANALOGLIMITFLAGS.SIPUP", 75);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->SIPUP;
    st->value_p = p_BYTE;
  }
  { // 5395 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._ANALOGLIMITFLAGS.SIPDOWN
    st = getVariable(5395);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._ANALOGLIMITFLAGS.SIPDOWN", 77);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->SIPDOWN;
    st->value_p = p_BYTE;
  }
  { // 5396 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.NOTRELIABLE
    st = getVariable(5396);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.NOTRELIABLE", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_BOOL = (BOOL*)&p_FB_AISOURCEMLP->NOTRELIABLE;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 5397 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._LASTVALUE
    st = getVariable(5397);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._LASTVALUE", 62);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_LREAL = (LREAL*)&p_FB_AISOURCEMLP->_LASTVALUE;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 5398 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.RESETCMDTIMER.IN
    st = getVariable(5398);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.RESETCMDTIMER.IN", 68);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TON = (TON*)&p_FB_AISOURCEMLP->RESETCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 5399 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.RESETCMDTIMER.PT
    st = getVariable(5399);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.RESETCMDTIMER.PT", 68);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TON = (TON*)&p_FB_AISOURCEMLP->RESETCMDTIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 5400 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.RESETCMDTIMER.Q
    st = getVariable(5400);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.RESETCMDTIMER.Q", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TON = (TON*)&p_FB_AISOURCEMLP->RESETCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 5401 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.RESETCMDTIMER.ET
    st = getVariable(5401);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.RESETCMDTIMER.ET", 68);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TON = (TON*)&p_FB_AISOURCEMLP->RESETCMDTIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 5402 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.RESETCMDTIMER
    st = getVariable(5402);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.RESETCMDTIMER", 65);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TON = (TON*)&p_FB_AISOURCEMLP->RESETCMDTIMER;
    st->value_p = (void *)p_TON;
  }
  { // 5403 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._LASTVALUETIMER.IN
    st = getVariable(5403);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._LASTVALUETIMER.IN", 70);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TON = (TON*)&p_FB_AISOURCEMLP->_LASTVALUETIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 5404 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._LASTVALUETIMER.PT
    st = getVariable(5404);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._LASTVALUETIMER.PT", 70);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TON = (TON*)&p_FB_AISOURCEMLP->_LASTVALUETIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 5405 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._LASTVALUETIMER.Q
    st = getVariable(5405);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._LASTVALUETIMER.Q", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TON = (TON*)&p_FB_AISOURCEMLP->_LASTVALUETIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 5406 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._LASTVALUETIMER.ET
    st = getVariable(5406);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._LASTVALUETIMER.ET", 70);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TON = (TON*)&p_FB_AISOURCEMLP->_LASTVALUETIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 5407 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._LASTVALUETIMER
    st = getVariable(5407);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4._LASTVALUETIMER", 67);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_TON = (TON*)&p_FB_AISOURCEMLP->_LASTVALUETIMER;
    st->value_p = (void *)p_TON;
  }
  { // 5408 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.RESETCMDTIMERPRIZNAK
    st = getVariable(5408);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.RESETCMDTIMERPRIZNAK", 72);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_BOOL = (BOOL*)&p_FB_AISOURCEMLP->RESETCMDTIMERPRIZNAK;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 5409 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.K
    st = getVariable(5409);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.K", 53);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_LREAL = (LREAL*)&p_FB_AISOURCEMLP->K;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 5410 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.B
    st = getVariable(5410);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.B", 53);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_LREAL = (LREAL*)&p_FB_AISOURCEMLP->B;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 5411 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.AP
    st = getVariable(5411);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.AP", 54);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_LREAL = (LREAL*)&p_FB_AISOURCEMLP->AP;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 5412 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.RAZNITSA
    st = getVariable(5412);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.RAZNITSA", 60);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_LREAL = (LREAL*)&p_FB_AISOURCEMLP->RAZNITSA;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 5413 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.RABS
    st = getVariable(5413);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.RABS", 56);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_LREAL = (LREAL*)&p_FB_AISOURCEMLP->RABS;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 5414 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.H
    st = getVariable(5414);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.H", 53);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_LREAL = (LREAL*)&p_FB_AISOURCEMLP->H;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 5415 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.MISMATCH
    st = getVariable(5415);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.MISMATCH", 60);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_LREAL = (LREAL*)&p_FB_AISOURCEMLP->MISMATCH;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 5416 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.PARAMETR
    st = getVariable(5416);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.PARAMETR", 60);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_BYTE = (BYTE*)&p_FB_AISOURCEMLP->PARAMETR;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 5417 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.SOURCE
    st = getVariable(5417);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.SOURCE", 58);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_BYTE = (BYTE*)&p_FB_AISOURCEMLP->SOURCE;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 5418 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.CMD
    st = getVariable(5418);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.CMD", 55);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_BYTE = (BYTE*)&p_FB_AISOURCEMLP->CMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 5419 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.LASTCMD
    st = getVariable(5419);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.LASTCMD", 59);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_BYTE = (BYTE*)&p_FB_AISOURCEMLP->LASTCMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 5420 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.SOURCE_FOR_STATUS
    st = getVariable(5420);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.SOURCE_FOR_STATUS", 69);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_BYTE = (BYTE*)&p_FB_AISOURCEMLP->SOURCE_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 5421 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.CMD_FOR_STATUS
    st = getVariable(5421);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.CMD_FOR_STATUS", 66);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_BYTE = (BYTE*)&p_FB_AISOURCEMLP->CMD_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 5422 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.COMMAND_ERROR_FOR_STATUS
    st = getVariable(5422);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.COMMAND_ERROR_FOR_STATUS", 76);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_BYTE = (BYTE*)&p_FB_AISOURCEMLP->COMMAND_ERROR_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 5423 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ONINIT
    st = getVariable(5423);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ONINIT", 58);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_BOOL = (BOOL*)&p_FB_AISOURCEMLP->ONINIT;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 5424 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.OFF_TRIG.CLK
    st = getVariable(5424);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.OFF_TRIG.CLK", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->OFF_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 5425 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.OFF_TRIG.Q
    st = getVariable(5425);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.OFF_TRIG.Q", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->OFF_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 5426 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.OFF_TRIG
    st = getVariable(5426);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.OFF_TRIG", 60);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->OFF_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 5427 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ON_TRIG.CLK
    st = getVariable(5427);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ON_TRIG.CLK", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->ON_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 5428 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ON_TRIG.Q
    st = getVariable(5428);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ON_TRIG.Q", 61);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->ON_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 5429 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ON_TRIG
    st = getVariable(5429);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.ON_TRIG", 59);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->ON_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 5430 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.REMONT_TRIG.CLK
    st = getVariable(5430);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.REMONT_TRIG.CLK", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->REMONT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 5431 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.REMONT_TRIG.Q
    st = getVariable(5431);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.REMONT_TRIG.Q", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->REMONT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 5432 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.REMONT_TRIG
    st = getVariable(5432);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.REMONT_TRIG", 63);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->REMONT_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 5433 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.LL_TRIG.CLK
    st = getVariable(5433);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.LL_TRIG.CLK", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->LL_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 5434 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.LL_TRIG.Q
    st = getVariable(5434);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.LL_TRIG.Q", 61);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->LL_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 5435 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.LL_TRIG
    st = getVariable(5435);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.LL_TRIG", 59);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->LL_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 5436 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.HL_TRIG.CLK
    st = getVariable(5436);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.HL_TRIG.CLK", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->HL_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 5437 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.HL_TRIG.Q
    st = getVariable(5437);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.HL_TRIG.Q", 61);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->HL_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 5438 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.HL_TRIG
    st = getVariable(5438);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.HL_TRIG", 59);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->HL_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 5439 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.NORMAL_TRIG.CLK
    st = getVariable(5439);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.NORMAL_TRIG.CLK", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->NORMAL_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 5440 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.NORMAL_TRIG.Q
    st = getVariable(5440);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.NORMAL_TRIG.Q", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->NORMAL_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 5441 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.NORMAL_TRIG
    st = getVariable(5441);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.NORMAL_TRIG", 63);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->NORMAL_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 5442 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.NEDOSTOVER_TRIG.CLK
    st = getVariable(5442);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.NEDOSTOVER_TRIG.CLK", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->NEDOSTOVER_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 5443 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.NEDOSTOVER_TRIG.Q
    st = getVariable(5443);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.NEDOSTOVER_TRIG.Q", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->NEDOSTOVER_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 5444 PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.NEDOSTOVER_TRIG
    st = getVariable(5444);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4.NEDOSTOVER_TRIG", 67);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_T_OPOR_UPOR_POD_NAGNETATELIA_T4;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->NEDOSTOVER_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }

  return 0;
}

// clang-format on
