// clang-format off

#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include "POUS.h"
#include <beremiz/beremiz.h>

#include "iec_types_all.h"
#include "config1.h"

extern PROGRAM0 RESOURCE1__INSTANCE0;

#ifdef DEBUG_PLC
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err][%s:%d]: " _PRNTMSG "\n", __func__, __LINE__, ##__VA_ARGS__)
#else
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err]: " _PRNTMSG "\n", ##__VA_ARGS__)
#endif // DEBUG_PLC

void UnpackVar(void* varp, __IEC_types_enum vartype, void **value_p, void **f_value_p, uint8_t **flags);

int __variables_init_FB_T_OPOR_POD_NAGNETATELIA_T4_HA(){
  iec_var_t *st;

  PROGRAM0 *p_PROGRAM0;
  LREAL *p_LREAL;
  ULINT *p_ULINT;
  REAL *p_REAL;
  FB_TIMINGS *p_FB_TIMINGS;
  BOOL *p_BOOL;
  UINT *p_UINT;
  PROC_AI_INIT *p_PROC_AI_INIT;
  FB_AI_INIT *p_FB_AI_INIT;
  TIME *p_TIME;
  STRUCT_AI *p_STRUCT_AI;
  DWORD *p_DWORD;
  BYTE *p_BYTE;
  WORD *p_WORD;
  AICONFIG *p_AICONFIG;
  PROC_AI *p_PROC_AI;
  FB_AISOURCEMLP *p_FB_AISOURCEMLP;
  TITEMAIN *p_TITEMAIN;
  TITEMDIN *p_TITEMDIN;
  TYPE_STATUSAI *p_TYPE_STATUSAI;
  TYPE_COMMANDANALOG *p_TYPE_COMMANDANALOG;
  FB_SUNPACKERCOMMAND *p_FB_SUNPACKERCOMMAND;
  TYPE_ANALOGLIMITFLAGS *p_TYPE_ANALOGLIMITFLAGS;
  TON *p_TON;
  R_TRIG *p_R_TRIG;
  FB_AISOURCEMLP_TIMER *p_FB_AISOURCEMLP_TIMER;
  PROC_AO_INIT *p_PROC_AO_INIT;
  FB_AO_INIT *p_FB_AO_INIT;
  STRUCT_AO *p_STRUCT_AO;
  AOCONFIG *p_AOCONFIG;
  PROC_AO *p_PROC_AO;
  FB_AOSOURCEMLP *p_FB_AOSOURCEMLP;
  TDOUBLEDATA *p_TDOUBLEDATA;
  PROC_DI_INIT *p_PROC_DI_INIT;
  FB_DI_INIT *p_FB_DI_INIT;
  STRUCT_DI *p_STRUCT_DI;
  __IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t *p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t;
  TYPE_RELIABLEBIT *p_TYPE_RELIABLEBIT;
  DICONFIG *p_DICONFIG;
  PROC_DI *p_PROC_DI;
  FB_DISOURCEMLP *p_FB_DISOURCEMLP;
  INT *p_INT;
  UDINT *p_UDINT;
  PROC_DO_INIT *p_PROC_DO_INIT;
  FB_DO_INIT *p_FB_DO_INIT;
  STRUCT_DO *p_STRUCT_DO;
  __IEC___ARRAY_OF_BOOL_16_t *p___IEC___ARRAY_OF_BOOL_16_t;
  DOCONFIG *p_DOCONFIG;
  PROC_DO *p_PROC_DO;
  FB_DOSOURCEMLP *p_FB_DOSOURCEMLP;
  TWORDDATA *p_TWORDDATA;
  OPC_AI_INIT *p_OPC_AI_INIT;
  OPC_AI_GET *p_OPC_AI_GET;
  OPC_AI_SET *p_OPC_AI_SET;
  OPC_PROTECTIONS_GET *p_OPC_PROTECTIONS_GET;
  PROTECTIONSCONFIG *p_PROTECTIONSCONFIG;
  STRUCT_AIPROTECTION *p_STRUCT_AIPROTECTION;
  STRUCT_DIPROTECTION *p_STRUCT_DIPROTECTION;
  OPC_PROTECTIONS_SET *p_OPC_PROTECTIONS_SET;
  OPC_ALGORITMS_SET *p_OPC_ALGORITMS_SET;
  ALGORITMSCONFIG *p_ALGORITMSCONFIG;
  STRUCT_ALG *p_STRUCT_ALG;
  STRUCT_ALGORITMSMANAGER *p_STRUCT_ALGORITMSMANAGER;
  STRUCT_PROTECTIONSMANAGER *p_STRUCT_PROTECTIONSMANAGER;
  STRUCT_ALGTIMERS *p_STRUCT_ALGTIMERS;
  ALGORITMSQUESTIONS *p_ALGORITMSQUESTIONS;
  STRUCT_QUESTION *p_STRUCT_QUESTION;
  OPC_ALGORITMS_GET *p_OPC_ALGORITMS_GET;
  PROC_IM_INIT *p_PROC_IM_INIT;
  FB_KRAN_INIT *p_FB_KRAN_INIT;
  STRUCT_KRAN *p_STRUCT_KRAN;
  FB_SWITCH_INIT *p_FB_SWITCH_INIT;
  STRUCT_SWITCH *p_STRUCT_SWITCH;
  FB_OILPUMP_INIT *p_FB_OILPUMP_INIT;
  STRUCT_OILPUMP *p_STRUCT_OILPUMP;
  FB_SECTIONSWITCH_INIT *p_FB_SECTIONSWITCH_INIT;
  STRUCT_SECTIONSWITCH *p_STRUCT_SECTIONSWITCH;
  FB_ANALOGPARAMETR_INIT *p_FB_ANALOGPARAMETR_INIT;
  STRUCT_ANALOGPARAMETR *p_STRUCT_ANALOGPARAMETR;
  FB_DISCRETPARAMETR_INIT *p_FB_DISCRETPARAMETR_INIT;
  STRUCT_DISCRETPARAMETR *p_STRUCT_DISCRETPARAMETR;
  FB_SINGLESIGNAL_INIT *p_FB_SINGLESIGNAL_INIT;
  STRUCT_SINGLESIGNAL *p_STRUCT_SINGLESIGNAL;
  FB_SINGLEOUTPUT_INIT *p_FB_SINGLEOUTPUT_INIT;
  STRUCT_SINGLEOUTPUT *p_STRUCT_SINGLEOUTPUT;
  IMCONFIG *p_IMCONFIG;
  STRUCT_RESERVEIM *p_STRUCT_RESERVEIM;
  STRUCT_RESERVEIM2 *p_STRUCT_RESERVEIM2;
  IM_SINGLESIGNALS *p_IM_SINGLESIGNALS;
  IM_SINGLEOUTPUTS *p_IM_SINGLEOUTPUTS;
  PROC_IM *p_PROC_IM;
  FB_KRAN *p_FB_KRAN;
  TYPE_STATUSDUALINPUT *p_TYPE_STATUSDUALINPUT;
  TYPE_COMMANDDUALINPUT *p_TYPE_COMMANDDUALINPUT;
  TOF *p_TOF;
  FB_OILPUMP *p_FB_OILPUMP;
  FB_SWITCH *p_FB_SWITCH;
  FB_SECTIONSWITCH *p_FB_SECTIONSWITCH;
  TYPE_BASKETSTATS *p_TYPE_BASKETSTATS;
  FB_MEANDR *p_FB_MEANDR;
  FB_SINGLESIGNAL *p_FB_SINGLESIGNAL;
  FB_SINGLEOUTPUT *p_FB_SINGLEOUTPUT;
  FB_DISCRETPARAMETR *p_FB_DISCRETPARAMETR;
  FB_ANALOGPARAMETR *p_FB_ANALOGPARAMETR;
  OPC_IM_GET *p_OPC_IM_GET;
  OPC_IM_SET *p_OPC_IM_SET;
  PROC_PROTECTIONS_INIT *p_PROC_PROTECTIONS_INIT;
  FB_DIPROTECTION_INIT *p_FB_DIPROTECTION_INIT;
  FB_AIPROTECTION_INIT *p_FB_AIPROTECTION_INIT;
  TYPE_PROTECTIONTAGS *p_TYPE_PROTECTIONTAGS;
  PROC_PROTECTION *p_PROC_PROTECTION;
  FB_DIPROTECTION *p_FB_DIPROTECTION;
  F_TRIG *p_F_TRIG;
  FB_MVPROTECTION *p_FB_MVPROTECTION;
  FB_KRANOPENPROTECTION *p_FB_KRANOPENPROTECTION;
  FB_AIPROTECTION *p_FB_AIPROTECTION;
  PROC_ALGORITMS *p_PROC_ALGORITMS;
  REMONTALG *p_REMONTALG;
  TYPE_MODEGPA *p_TYPE_MODEGPA;
  TYPE_COMMANDSPOTECTIONSMANAGER *p_TYPE_COMMANDSPOTECTIONSMANAGER;
  TESTPROTECTIONALG *p_TESTPROTECTIONALG;
  TESTIMALG *p_TESTIMALG;
  FB_AUTOTENALG *p_FB_AUTOTENALG;
  FB_AUTOPNSALG *p_FB_AUTOPNSALG;
  FB_AUTOAVOMALG *p_FB_AUTOAVOMALG;
  FB_VIBEGPNSALG *p_FB_VIBEGPNSALG;
  STRUCT_PHASEALGORITM *p_STRUCT_PHASEALGORITM;
  FB_PH_ALGORITM *p_FB_PH_ALGORITM;
  FB_PH_TIMER *p_FB_PH_TIMER;
  FB_QUESTION *p_FB_QUESTION;
  TYPE_ANSWERS *p_TYPE_ANSWERS;
  FB_PH_SWITCH *p_FB_PH_SWITCH;
  FB_PH_CUSTOMPHASE *p_FB_PH_CUSTOMPHASE;
  FB_AUTONUALG *p_FB_AUTONUALG;
  FB_PUSKOILSYSTEMALG *p_FB_PUSKOILSYSTEMALG;
  FB_PH_WAITANALOGVALUE *p_FB_PH_WAITANALOGVALUE;
  FB_PH_OILPUMP *p_FB_PH_OILPUMP;
  FB_ANTIPOMPAGALG *p_FB_ANTIPOMPAGALG;
  FB_TABLEVALUE_MIN *p_FB_TABLEVALUE_MIN;
  __IEC___ARRAY_OF_TYPE_TABLEREC_9_t *p___IEC___ARRAY_OF_TYPE_TABLEREC_9_t;
  TYPE_TABLEREC *p_TYPE_TABLEREC;
  FB_TABLEVALUE_MAX *p_FB_TABLEVALUE_MAX;
  FB_RASHODALG *p_FB_RASHODALG;
  FB_ZAPASALG *p_FB_ZAPASALG;
  NOALG *p_NOALG;
  FB_PH_KRAN *p_FB_PH_KRAN;
  FB_PH_SECTIONSWITCH *p_FB_PH_SECTIONSWITCH;
  AOALG *p_AOALG;
  PPUALG *p_PPUALG;
  FILLINGALG *p_FILLINGALG;
  FB_PH_DIPROTECTION *p_FB_PH_DIPROTECTION;
  ENGINERUNALG *p_ENGINERUNALG;
  PUSKKALG *p_PUSKKALG;
  PUSKVALG *p_PUSKVALG;
  TESTDPMGALG *p_TESTDPMGALG;
  TESTPMSALG *p_TESTPMSALG;
  FB_PH_AIPROTECTION *p_FB_PH_AIPROTECTION;
  APUSKALG *p_APUSKALG;
  SEMIAUTOPUSKALG *p_SEMIAUTOPUSKALG;
  FB_ALGORITMSMANAGER *p_FB_ALGORITMSMANAGER;
  FB_PROTECTIONSMANAGER *p_FB_PROTECTIONSMANAGER;

  { // 39677 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.VALUE
    st = getVariable(39677);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.VALUE", 67);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->VALUE;
    st->value_p = p_LREAL;
  }
  { // 39678 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.STATUS
    st = getVariable(39678);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.STATUS", 68);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_DWORD = (DWORD*)&p_STRUCT_AI->STATUS;
    st->value_p = p_DWORD;
  }
  { // 39679 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.INTERVAL
    st = getVariable(39679);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.INTERVAL", 70);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BYTE = (BYTE*)&p_STRUCT_AI->INTERVAL;
    st->value_p = p_BYTE;
  }
  { // 39680 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.INCOMMAND
    st = getVariable(39680);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.INCOMMAND", 71);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 39681 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.BLCONNECT
    st = getVariable(39681);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.BLCONNECT", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->BLCONNECT;
    st->value_p = p_BOOL;
  }
  { // 39682 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DLL
    st = getVariable(39682);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DLL", 65);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLL;
    st->value_p = p_LREAL;
  }
  { // 39683 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DHL
    st = getVariable(39683);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DHL", 65);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHL;
    st->value_p = p_LREAL;
  }
  { // 39684 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DLA
    st = getVariable(39684);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DLA", 65);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLA;
    st->value_p = p_LREAL;
  }
  { // 39685 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DHA
    st = getVariable(39685);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DHA", 65);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHA;
    st->value_p = p_LREAL;
  }
  { // 39686 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DLW
    st = getVariable(39686);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DLW", 65);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLW;
    st->value_p = p_LREAL;
  }
  { // 39687 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DHW
    st = getVariable(39687);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DHW", 65);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHW;
    st->value_p = p_LREAL;
  }
  { // 39688 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.LL
    st = getVariable(39688);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.LL", 64);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LL;
    st->value_p = p_LREAL;
  }
  { // 39689 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.HL
    st = getVariable(39689);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.HL", 64);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HL;
    st->value_p = p_LREAL;
  }
  { // 39690 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.LA
    st = getVariable(39690);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.LA", 64);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LA;
    st->value_p = p_LREAL;
  }
  { // 39691 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.HA
    st = getVariable(39691);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.HA", 64);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HA;
    st->value_p = p_LREAL;
  }
  { // 39692 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.LW
    st = getVariable(39692);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.LW", 64);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LW;
    st->value_p = p_LREAL;
  }
  { // 39693 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.HW
    st = getVariable(39693);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.HW", 64);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HW;
    st->value_p = p_LREAL;
  }
  { // 39694 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.ISVALIDREF_LA
    st = getVariable(39694);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.ISVALIDREF_LA", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_LA;
    st->value_p = p_BOOL;
  }
  { // 39695 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.ISVALIDREF_HA
    st = getVariable(39695);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.ISVALIDREF_HA", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_HA;
    st->value_p = p_BOOL;
  }
  { // 39696 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.ISVALIDREF_LW
    st = getVariable(39696);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.ISVALIDREF_LW", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_LW;
    st->value_p = p_BOOL;
  }
  { // 39697 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.ISVALIDREF_HW
    st = getVariable(39697);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.ISVALIDREF_HW", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_HW;
    st->value_p = p_BOOL;
  }
  { // 39698 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.INPLL
    st = getVariable(39698);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.INPLL", 67);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->INPLL;
    st->value_p = p_LREAL;
  }
  { // 39699 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.INPHL
    st = getVariable(39699);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.INPHL", 67);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->INPHL;
    st->value_p = p_LREAL;
  }
  { // 39700 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.CURRENTSHOTCIRCUIT
    st = getVariable(39700);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.CURRENTSHOTCIRCUIT", 80);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CURRENTSHOTCIRCUIT;
    st->value_p = p_LREAL;
  }
  { // 39701 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.CURRENTBREAKCIRCUIT
    st = getVariable(39701);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.CURRENTBREAKCIRCUIT", 81);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CURRENTBREAKCIRCUIT;
    st->value_p = p_LREAL;
  }
  { // 39702 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.MAXCHANGESPEED
    st = getVariable(39702);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.MAXCHANGESPEED", 76);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXCHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 39703 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.MAXCHANGESPEEDDOWN
    st = getVariable(39703);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.MAXCHANGESPEEDDOWN", 80);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXCHANGESPEEDDOWN;
    st->value_p = p_LREAL;
  }
  { // 39704 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.CHANGESPEED
    st = getVariable(39704);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.CHANGESPEED", 73);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 39705 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.HISTERESIS
    st = getVariable(39705);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.HISTERESIS", 72);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HISTERESIS;
    st->value_p = p_LREAL;
  }
  { // 39706 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.APERTURFILTER
    st = getVariable(39706);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.APERTURFILTER", 75);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->APERTURFILTER;
    st->value_p = p_LREAL;
  }
  { // 39707 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.EXPONENTIALFILTER
    st = getVariable(39707);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.EXPONENTIALFILTER", 79);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->EXPONENTIALFILTER;
    st->value_p = p_LREAL;
  }
  { // 39708 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.RASSOGLASOVANIE
    st = getVariable(39708);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.RASSOGLASOVANIE", 77);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->RASSOGLASOVANIE;
    st->value_p = p_LREAL;
  }
  { // 39709 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.OPCCOMMANDSDISABLED
    st = getVariable(39709);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.OPCCOMMANDSDISABLED", 81);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 39710 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DISABLED_LA
    st = getVariable(39710);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DISABLED_LA", 73);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_LA;
    st->value_p = p_BOOL;
  }
  { // 39711 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DISABLED_HA
    st = getVariable(39711);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DISABLED_HA", 73);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_HA;
    st->value_p = p_BOOL;
  }
  { // 39712 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DISABLED_LW
    st = getVariable(39712);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DISABLED_LW", 73);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_LW;
    st->value_p = p_BOOL;
  }
  { // 39713 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DISABLED_HW
    st = getVariable(39713);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DISABLED_HW", 73);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_HW;
    st->value_p = p_BOOL;
  }
  { // 39714 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DELAYLA
    st = getVariable(39714);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DELAYLA", 69);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYLA;
    st->value_p = p_TIME;
  }
  { // 39715 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DELAYLW
    st = getVariable(39715);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DELAYLW", 69);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYLW;
    st->value_p = p_TIME;
  }
  { // 39716 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DELAYHW
    st = getVariable(39716);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DELAYHW", 69);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYHW;
    st->value_p = p_TIME;
  }
  { // 39717 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DELAYHA
    st = getVariable(39717);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DELAYHA", 69);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYHA;
    st->value_p = p_TIME;
  }
  { // 39718 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.MINVALUE_ISVALIDREF
    st = getVariable(39718);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.MINVALUE_ISVALIDREF", 81);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->MINVALUE_ISVALIDREF;
    st->value_p = p_BOOL;
  }
  { // 39719 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.MAXVALUE_ISVALIDREF
    st = getVariable(39719);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.MAXVALUE_ISVALIDREF", 81);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->MAXVALUE_ISVALIDREF;
    st->value_p = p_BOOL;
  }
  { // 39720 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.MINVALUE
    st = getVariable(39720);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.MINVALUE", 70);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MINVALUE;
    st->value_p = p_LREAL;
  }
  { // 39721 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.MAXVALUE
    st = getVariable(39721);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.MAXVALUE", 70);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXVALUE;
    st->value_p = p_LREAL;
  }
  { // 39722 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.INOPCCOMMANDSDISABLED
    st = getVariable(39722);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.INOPCCOMMANDSDISABLED", 83);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 39723 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.IMIT
    st = getVariable(39723);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.IMIT", 66);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->IMIT;
    st->value_p = p_BOOL;
  }
  { // 39724 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.REMONT
    st = getVariable(39724);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.REMONT", 68);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->REMONT;
    st->value_p = p_BOOL;
  }
  { // 39725 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.NS
    st = getVariable(39725);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.NS", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS;
    st->value_p = p_BOOL;
  }
  { // 39726 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.NS_MIN
    st = getVariable(39726);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.NS_MIN", 68);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS_MIN;
    st->value_p = p_BOOL;
  }
  { // 39727 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.NS_MAX
    st = getVariable(39727);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.NS_MAX", 68);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS_MAX;
    st->value_p = p_BOOL;
  }
  { // 39728 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.INCOMMAND_ALG
    st = getVariable(39728);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.INCOMMAND_ALG", 75);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 39729 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.INCOMMAND_ARM
    st = getVariable(39729);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.INCOMMAND_ARM", 75);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 39730 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DMAXCHANGESPEED
    st = getVariable(39730);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DMAXCHANGESPEED", 77);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DMAXCHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 39731 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DMAXCHANGESPEEDDOWN
    st = getVariable(39731);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.AI.DMAXCHANGESPEEDDOWN", 81);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DMAXCHANGESPEEDDOWN;
    st->value_p = p_LREAL;
  }
  { // 39732 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.CONTROLLIMIT
    st = getVariable(39732);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.CONTROLLIMIT", 78);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BYTE = (BYTE*)&p_STRUCT_AIPROTECTION->CONTROLLIMIT;
    st->value_p = p_BYTE;
  }
  { // 39733 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.DELAY
    st = getVariable(39733);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.DELAY", 71);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_TIME = (TIME*)&p_STRUCT_AIPROTECTION->DELAY;
    st->value_p = p_TIME;
  }
  { // 39734 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.INTAG
    st = getVariable(39734);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.INTAG", 71);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BYTE = (BYTE*)&p_STRUCT_AIPROTECTION->INTAG;
    st->value_p = p_BYTE;
  }
  { // 39735 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.INRUNONSTART
    st = getVariable(39735);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.INRUNONSTART", 78);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->INRUNONSTART;
    st->value_p = p_BOOL;
  }
  { // 39736 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.INCANRUN
    st = getVariable(39736);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.INCANRUN", 74);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->INCANRUN;
    st->value_p = p_BOOL;
  }
  { // 39737 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.INOPCCOMMANDSDISABLED
    st = getVariable(39737);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.INOPCCOMMANDSDISABLED", 87);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 39738 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.INCOMMAND
    st = getVariable(39738);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.INCOMMAND", 75);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_WORD = (WORD*)&p_STRUCT_AIPROTECTION->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 39739 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.INCOMMAND_ALG
    st = getVariable(39739);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.INCOMMAND_ALG", 79);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_WORD = (WORD*)&p_STRUCT_AIPROTECTION->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 39740 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.INCOMMAND_ARM
    st = getVariable(39740);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.INCOMMAND_ARM", 79);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_WORD = (WORD*)&p_STRUCT_AIPROTECTION->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 39741 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.TAG
    st = getVariable(39741);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.TAG", 69);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BYTE = (BYTE*)&p_STRUCT_AIPROTECTION->TAG;
    st->value_p = p_BYTE;
  }
  { // 39742 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.STATUS
    st = getVariable(39742);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.STATUS", 72);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_DWORD = (DWORD*)&p_STRUCT_AIPROTECTION->STATUS;
    st->value_p = p_DWORD;
  }
  { // 39743 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.CANRUN
    st = getVariable(39743);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.CANRUN", 72);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->CANRUN;
    st->value_p = p_BOOL;
  }
  { // 39744 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.OPCCOMMANDSDISABLED
    st = getVariable(39744);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.OPCCOMMANDSDISABLED", 85);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 39745 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.ISRUNNING
    st = getVariable(39745);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.ISRUNNING", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->ISRUNNING;
    st->value_p = p_BOOL;
  }
  { // 39746 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.HASERROR
    st = getVariable(39746);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.HASERROR", 74);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->HASERROR;
    st->value_p = p_BOOL;
  }
  { // 39747 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.ISENDED
    st = getVariable(39747);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.ISENDED", 73);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->ISENDED;
    st->value_p = p_BOOL;
  }
  { // 39748 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.REMONT
    st = getVariable(39748);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.REMONT", 72);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->REMONT;
    st->value_p = p_BOOL;
  }
  { // 39749 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.CHECK
    st = getVariable(39749);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.CHECK", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->CHECK;
    st->value_p = p_BOOL;
  }
  { // 39750 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.SIGNALING
    st = getVariable(39750);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.SIGNALING", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->SIGNALING;
    st->value_p = p_BOOL;
  }
  { // 39751 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.SIGNALINGTP
    st = getVariable(39751);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.SIGNALINGTP", 77);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->SIGNALINGTP;
    st->value_p = p_BOOL;
  }
  { // 39752 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.RUNONSTART
    st = getVariable(39752);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.STRAIP.RUNONSTART", 76);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->RUNONSTART;
    st->value_p = p_BOOL;
  }
  { // 39757 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._SIGNALINGTP.IN
    st = getVariable(39757);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._SIGNALINGTP.IN", 74);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    p_BOOL = (BOOL*)&p_TOF->IN;
    st->value_p = p_BOOL;
  }
  { // 39758 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._SIGNALINGTP.PT
    st = getVariable(39758);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._SIGNALINGTP.PT", 74);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    p_TIME = (TIME*)&p_TOF->PT;
    st->value_p = p_TIME;
  }
  { // 39759 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._SIGNALINGTP.Q
    st = getVariable(39759);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._SIGNALINGTP.Q", 73);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    p_BOOL = (BOOL*)&p_TOF->Q;
    st->value_p = p_BOOL;
  }
  { // 39760 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._SIGNALINGTP.ET
    st = getVariable(39760);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._SIGNALINGTP.ET", 74);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    p_TIME = (TIME*)&p_TOF->ET;
    st->value_p = p_TIME;
  }
  { // 39761 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._SIGNALINGTP
    st = getVariable(39761);
    memcpy(st->IEC_TYPE, "TOF", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._SIGNALINGTP", 71);
    st->size_data = sizeof(TOF);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    st->value_p = (void *)p_TOF;
  }
  { // 39762 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._STATUSAI.NOTDEFINED
    st = getVariable(39762);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._STATUSAI.NOTDEFINED", 79);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NOTDEFINED;
    st->value_p = p_BYTE;
  }
  { // 39763 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._STATUSAI.LL
    st = getVariable(39763);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._STATUSAI.LL", 71);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LL;
    st->value_p = p_BYTE;
  }
  { // 39764 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._STATUSAI.HL
    st = getVariable(39764);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._STATUSAI.HL", 71);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HL;
    st->value_p = p_BYTE;
  }
  { // 39765 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._STATUSAI.NOTRELIABLE
    st = getVariable(39765);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._STATUSAI.NOTRELIABLE", 80);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NOTRELIABLE;
    st->value_p = p_BYTE;
  }
  { // 39766 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._STATUSAI.NORMAL
    st = getVariable(39766);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._STATUSAI.NORMAL", 75);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NORMAL;
    st->value_p = p_BYTE;
  }
  { // 39767 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._STATUSAI.LW
    st = getVariable(39767);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._STATUSAI.LW", 71);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LW;
    st->value_p = p_BYTE;
  }
  { // 39768 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._STATUSAI.HW
    st = getVariable(39768);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._STATUSAI.HW", 71);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HW;
    st->value_p = p_BYTE;
  }
  { // 39769 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._STATUSAI.LA
    st = getVariable(39769);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._STATUSAI.LA", 71);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LA;
    st->value_p = p_BYTE;
  }
  { // 39770 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._STATUSAI.HA
    st = getVariable(39770);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA._STATUSAI.HA", 71);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HA;
    st->value_p = p_BYTE;
  }
  { // 39771 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SOURCE
    st = getVariable(39771);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SOURCE", 65);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->SOURCE;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 39772 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.CMD
    st = getVariable(39772);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.CMD", 62);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->CMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 39773 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.LASTCMD
    st = getVariable(39773);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.LASTCMD", 66);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->LASTCMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 39774 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SOURCE_FOR_STATUS
    st = getVariable(39774);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SOURCE_FOR_STATUS", 76);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->SOURCE_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 39775 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.CMD_FOR_STATUS
    st = getVariable(39775);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.CMD_FOR_STATUS", 73);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->CMD_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 39776 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.COMMAND_ERROR_FOR_STATUS
    st = getVariable(39776);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.COMMAND_ERROR_FOR_STATUS", 83);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->COMMAND_ERROR_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 39777 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.RESETCMDTIMER.IN
    st = getVariable(39777);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.RESETCMDTIMER.IN", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 39778 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.RESETCMDTIMER.PT
    st = getVariable(39778);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.RESETCMDTIMER.PT", 75);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 39779 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.RESETCMDTIMER.Q
    st = getVariable(39779);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.RESETCMDTIMER.Q", 74);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 39780 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.RESETCMDTIMER.ET
    st = getVariable(39780);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.RESETCMDTIMER.ET", 75);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 39781 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.RESETCMDTIMER
    st = getVariable(39781);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.RESETCMDTIMER", 72);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    st->value_p = (void *)p_TON;
  }
  { // 39782 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.RESETCMDTIMERPRIZNAK
    st = getVariable(39782);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.RESETCMDTIMERPRIZNAK", 79);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_BOOL = (BOOL*)&p_FB_AIPROTECTION->RESETCMDTIMERPRIZNAK;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 39783 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SIGNALINTIMER.IN
    st = getVariable(39783);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SIGNALINTIMER.IN", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 39784 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SIGNALINTIMER.PT
    st = getVariable(39784);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SIGNALINTIMER.PT", 75);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 39785 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SIGNALINTIMER.Q
    st = getVariable(39785);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SIGNALINTIMER.Q", 74);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 39786 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SIGNALINTIMER.ET
    st = getVariable(39786);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SIGNALINTIMER.ET", 75);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 39787 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SIGNALINTIMER
    st = getVariable(39787);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SIGNALINTIMER", 72);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    st->value_p = (void *)p_TON;
  }
  { // 39788 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.TIMER.IN
    st = getVariable(39788);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.TIMER.IN", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 39789 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.TIMER.PT
    st = getVariable(39789);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.TIMER.PT", 67);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 39790 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.TIMER.Q
    st = getVariable(39790);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.TIMER.Q", 66);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 39791 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.TIMER.ET
    st = getVariable(39791);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.TIMER.ET", 67);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 39792 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.TIMER
    st = getVariable(39792);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.TIMER", 64);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    st->value_p = (void *)p_TON;
  }
  { // 39793 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SIGNALINGTRIG.CLK
    st = getVariable(39793);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SIGNALINGTRIG.CLK", 76);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_R_TRIG = (R_TRIG*)&p_FB_AIPROTECTION->SIGNALINGTRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 39794 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SIGNALINGTRIG.Q
    st = getVariable(39794);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SIGNALINGTRIG.Q", 74);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_R_TRIG = (R_TRIG*)&p_FB_AIPROTECTION->SIGNALINGTRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 39795 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SIGNALINGTRIG
    st = getVariable(39795);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SIGNALINGTRIG", 72);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_R_TRIG = (R_TRIG*)&p_FB_AIPROTECTION->SIGNALINGTRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 39796 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SIGNALINGFTRIG.CLK
    st = getVariable(39796);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SIGNALINGFTRIG.CLK", 77);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_F_TRIG = (F_TRIG*)&p_FB_AIPROTECTION->SIGNALINGFTRIG;
    p_BOOL = (BOOL*)&p_F_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 39797 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SIGNALINGFTRIG.Q
    st = getVariable(39797);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SIGNALINGFTRIG.Q", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_F_TRIG = (F_TRIG*)&p_FB_AIPROTECTION->SIGNALINGFTRIG;
    p_BOOL = (BOOL*)&p_F_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 39798 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SIGNALINGFTRIG
    st = getVariable(39798);
    memcpy(st->IEC_TYPE, "F_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SIGNALINGFTRIG", 73);
    st->size_data = sizeof(F_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_F_TRIG = (F_TRIG*)&p_FB_AIPROTECTION->SIGNALINGFTRIG;
    st->value_p = (void *)p_F_TRIG;
  }
  { // 39799 PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SIGNALINGAI
    st = getVariable(39799);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_T_OPOR_POD_NAGNETATELIA_T4_HA.SIGNALINGAI", 70);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_T_OPOR_POD_NAGNETATELIA_T4_HA;
    p_BOOL = (BOOL*)&p_FB_AIPROTECTION->SIGNALINGAI;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }

  return 0;
}

// clang-format on
