FUNCTION anyDiscretPS : BOOL

VAR_INPUT
	im : ImConfig;
END_VAR

















anyDiscretPS:= TRUE;
    (*Im.SingleSignals.BEAO_srabotal.Q                     OR 
    Im.SingleSignals.Vozb_ProboiVentila.Q	 OR
    Im.SingleSignals.Vozb_AsinchHod.Q	           OR
    Im.SingleSignals.NS_ForsingVozbugdenia.Q       OR
    Im.SingleSignals.Vozb_AutoUprVozbuditela_off.Q OR
    Im.SingleSignals.Vozb_KontaktorON.Q*)