FUNCTION anyProtectionInRemont : BOOL

VAR_INPUT
	protections : ProtectionsConfig;
END_VAR

















anyProtectioninRemont:=
protections.Topornogo_podshipnika_EDT_1.Remont OR
protections.Toy_podshipnika_EDT_2.Remont OR
protections.Toy_podshipnika_kol_EDT_3.remont OR
protections.Toy_podshipnika_kol_EDT_4.Remont OR
protections.To_podshipnika_shest_red_EDT_5.Remont OR
protections.To_podshipnika_shest_red_EDT_6.Remont OR
protections.To_podshipnika_N_EDT_7.Remont OR
protections.To_podshipnika_svob_konca_EDT_8.Remont OR
protections.Ty_podshipnika_rab_kol_EDT_9.Remont OR
protections.Typornogo_podshipnika_nerab_kolodok_HT_10.Remont OR
protections.Tgaza_na_vyhode_H.Remont OR
protections.Os_sdvig_nagnetatelja_plus.Remont OR
protections.Os_sdvig_nagnetatelja_minus.Remont OR
protections.Pgaza_na_vyhode_nagnetatelia_GPA_STOP.Remont OR
protections.Pgaza_na_vhode_nagnetatelia_GPA_STOP.Remont OR
protections.Pgaza_na_vyhode_nagnetatelia.Remont OR
protections.dPmaslo_gaz.Remont OR
protections.Pmaslo_sm_nizkoe.Remont OR
protections.Pmaslo_sm_vysokoe.Remont OR
protections.Vibro_skorost_OPED_T1.Remont OR
protections.Vibro_skorost_OPED_T2.Remont OR
protections.Vibro_skorost_OYP_kolesa_ED_T3.Remont OR
protections.Vibro_skorost_OP_kolesa_RH_T4.Remont OR
protections.Vibro_skorost_OP_shesterni_RED_T5.Remont OR
protections.Vibro_skorost_OP_shesterni_RED_T6.Remont OR
protections.dPmaslo_gaz_less100.Remont OR
protections.Reg_vozb_off.Remont OR
protections.Fail_chastotnii_pusk.Remont OR
protections.Off_avar_vikluchatel.Remont OR
protections.AOKC_SHKC.Remont OR
protections.AO_PRU.Remont OR
protections.AO_ot_SHU.Remont OR
protections.mvOff.Remont OR
protections.Kran1_sdvig.Remont OR
protections.Kran2_sdvig.Remont;