FUNCTION autoRunProtections : BOOL

VAR_IN_OUT
	protections : ProtectionsConfig;
END_VAR





    runAiProtection(protections.Topornogo_podshipnika_EDT_1); 

    runAiProtection(protections.Toy_podshipnika_EDT_2);
    
    runAiProtection(protections.Toy_podshipnika_kol_EDT_3);

    runAiProtection(protections.Toy_podshipnika_kol_EDT_4);

    runAiProtection(protections.To_podshipnika_shest_red_EDT_5);

    runAiProtection(protections.To_podshipnika_shest_red_EDT_6);

    runAiProtection(protections.To_podshipnika_N_EDT_7);

    runAiProtection(protections.To_podshipnika_svob_konca_EDT_8);

    runAiProtection(protections.Ty_podshipnika_rab_kol_EDT_9);

    runAiProtection(protections.Typornogo_podshipnika_nerab_kolodok_HT_10);

    runAiProtection(protections.Tgaza_na_vyhode_H);

    runAiProtection(protections.Os_sdvig_nagnetatelja_plus);

    runAiProtection(protections.Os_sdvig_nagnetatelja_minus);

    runAiProtection(protections.Pgaza_na_vyhode_nagnetatelia_GPA_STOP);

    runAiProtection(protections.Pgaza_na_vhode_nagnetatelia_GPA_STOP);

    runAiProtection(protections.Pgaza_na_vyhode_nagnetatelia);

    runAiProtection(protections.dPmaslo_gaz);

    runAiProtection(protections.Pmaslo_sm_nizkoe);

    runAiProtection(protections.Pmaslo_sm_vysokoe);

    runAiProtection(protections.Vibro_skorost_OPED_T1);

    runAiProtection(protections.Vibro_skorost_OPED_T2);    

    runAiProtection(protections.Vibro_skorost_OYP_kolesa_ED_T3);

    runAiProtection(protections.Vibro_skorost_OP_kolesa_RH_T4);

    runAiProtection(protections.Vibro_skorost_OP_shesterni_RED_T5);

    runAiProtection(protections.Vibro_skorost_OP_shesterni_RED_T6);    
    

    runDiProtection(protections.dPmaslo_gaz_less100);

    runDiProtection(protections.AO_PRU);

    runDiProtection(protections.Reg_vozb_off);

    runDiProtection(protections.Fail_chastotnii_pusk);

    runDiProtection(protections.AOKC_SHKC);

    runDiProtection(protections.mvOff);

    runDiProtection(protections.AO_ot_SHU);
    
    runDiProtection(protections.Off_avar_vikluchatel);
    
    runDiProtection(protections.Kran1_sdvig);
    
    runDiProtection(protections.Kran2_sdvig);