TYPE
AlgoritmsConfig : STRUCT 
	autoNu : struct_Alg;
	AutoPns : struct_Alg;
	AutoAvom : struct_Alg;
	AutoTen : struct_Alg;
	AntiPompag : struct_Alg;
	testIm : struct_Alg;
	TestProtection : struct_Alg;
	Remont : struct_Alg;
	ppu : struct_Alg;
	puskOilSystem : struct_Alg;
	engineRun : struct_Alg;
	filling : struct_Alg;
	LineToRing : struct_Alg;
	RingToLine : struct_Alg;
	Apusk : struct_Alg;
	SemiAutoPusk : struct_Alg;
	no : struct_Alg;
	vibegPNS : struct_Alg;
	ao : struct_Alg;
	testPms : struct_Alg;
	testdPmg : struct_Alg;
	puskV : struct_Alg;
	puskK : struct_Alg;
	Pusk_F_faza1 : struct_Alg;
	Pusk_F_faza2 : struct_Alg;
	Pusk_TH_faza : struct_Alg;
	Prov_PMS_ALG : struct_Alg;
	Prov_opressovka_ALG : struct_Alg;
	Pusk_SEC_faza_chastotny : struct_Alg;
	Pusk_SEC_faza_reactor : struct_Alg;
END_STRUCT;
END_TYPE
