TYPE
AlgoritmsQuestions : STRUCT 
	vibegPNS_algContinue : struct_Question;
	testPms_algContinue : struct_Question;
	testdPmg_algContinue : struct_Question;
	puskK_questionFilling : struct_Question;
	puskK_questionUnload : struct_Question;
	puskV_questionEngine : struct_Question;
	puskV_questionMVoff : struct_Question;
	SemiAutoPusk_cmdRun1ph : struct_Question;
	SemiAutoPusk_cmdRun2ph : struct_Question;
	SemiAutoPusk_cmdRun3ph : struct_Question;
	SemiAutoPusk_cmdRun4ph : struct_Question;
END_STRUCT;
END_TYPE
