TYPE
DiConfig : STRUCT (*Входные дискретные параметры*)
	di_0 : struct_DI;
	di_1 : struct_DI;
	di_2 : struct_DI;
	di_3 : struct_DI;
	di_4 : struct_DI;
	di_5 : struct_DI;
	di_6 : struct_DI;
	di_7 : struct_DI;
	di_8 : struct_DI;
	di_9 : struct_DI;
	di_10 : struct_DI;
	di_11 : struct_DI;
	di_12 : struct_DI;
	di_13 : struct_DI;
	di_14 : struct_DI;
	di_15 : struct_DI;
	di_16 : struct_DI;
	di_17 : struct_DI;
	di_18 : struct_DI;
	di_19 : struct_DI;
	di_20 : struct_DI;
	di_21 : struct_DI;
END_STRUCT;
END_TYPE
