TYPE
IM_singleOutputs : STRUCT 
	Rabota_EGPA : struct_singleOutput;
	Neispr_EGPA : struct_singleOutput;
	Avary_EGPA : struct_singleOutput;
	U_lamp_SHU : struct_singleOutput;
	AO_knopka_ind : struct_singleOutput;
	Pusk_SHUP : struct_singleOutput;
	Stop_SHUP : struct_singleOutput;
	NO_fonar : struct_singleOutput;
	PC_fonar : struct_singleOutput;
	AC_fonar : struct_singleOutput;
	Kr1_smazka : struct_singleOutput;
	Kr2_smazka : struct_singleOutput;
	Kr4_open_from_alg : struct_singleOutput;
	Synch_rej_K1 : struct_singleOutput;
END_STRUCT;
END_TYPE
