TYPE
ImConfig : STRUCT 
	Kran1 : struct_Kran;
	Kran2 : struct_Kran;
	Kran3 : struct_Kran;
	Kran3b : struct_Kran;
	Kran4 : struct_Kran;
	Kran5 : struct_Kran;
	Kran6 : struct_Kran;
	nu1 : struct_OilPump;
	nu2 : struct_OilPump;
	pns : struct_Switch;
	v1_Avom : struct_Switch;
	v2_Avom : struct_Switch;
	v3_Avom : struct_Switch;
	v4_Avom : struct_Switch;
	mv : struct_SectionSwitch;
	Reserve_IM1 : struct_ReserveIM;
	Reserve_IM2 : struct_ReserveIM2;
	SingleSignals : IM_singleSignals;
	SingleOutputs : IM_singleOutputs;
	KaloriferAVOM : struct_Switch;
	CMN : struct_Switch;
	TEN_kollectora : struct_Switch;
	TEN_MB : struct_Switch;
END_STRUCT;
END_TYPE
