TYPE
struct_AlgTimers : STRUCT 
	AutoPns_OffTimer : UINT;
	AutoPns_OnTimer : UINT;
	vibegPNS_Timer : UINT;
	NO_waitCloseKran : UINT;
	AO_waitKran : UINT;
	testPms_BreakTest : UINT;
	testdPmg_BreakTest : UINT;
	puskOilSystem_BreakPuskTimer_Poil : UINT;
	engineRun_BreakPuskTimer : UINT;
	filling_BreakPuskTimer : UINT;
	filling_waitAfterKran4 : UINT;
	filling_waitAfterKran5 : UINT;
	puskK_wait720 : UINT;
	puskV_wait600 : UINT;
	No_wait120 : UINT;
	No_wait600 : UINT;
	No_wait5 : UINT;
END_STRUCT;
END_TYPE
