// clang-format off

#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include "POUS.h"
#include <beremiz/beremiz.h>

#include "iec_types_all.h"
#include "config1.h"

extern PROGRAM0 RESOURCE1__INSTANCE0;

#ifdef DEBUG_PLC
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err][%s:%d]: " _PRNTMSG "\n", __func__, __LINE__, ##__VA_ARGS__)
#else
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err]: " _PRNTMSG "\n", ##__VA_ARGS__)
#endif // DEBUG_PLC

void UnpackVar(void* varp, __IEC_types_enum vartype, void **value_p, void **f_value_p, uint8_t **flags);

int __variables_init_FB_ZAPAS(){
  iec_var_t *st;

  PROGRAM0 *p_PROGRAM0;
  LREAL *p_LREAL;
  ULINT *p_ULINT;
  REAL *p_REAL;
  FB_TIMINGS *p_FB_TIMINGS;
  BOOL *p_BOOL;
  UINT *p_UINT;
  PROC_AI_INIT *p_PROC_AI_INIT;
  FB_AI_INIT *p_FB_AI_INIT;
  TIME *p_TIME;
  STRUCT_AI *p_STRUCT_AI;
  DWORD *p_DWORD;
  BYTE *p_BYTE;
  WORD *p_WORD;
  AICONFIG *p_AICONFIG;
  PROC_AI *p_PROC_AI;
  FB_AISOURCEMLP *p_FB_AISOURCEMLP;
  TITEMAIN *p_TITEMAIN;
  TITEMDIN *p_TITEMDIN;
  TYPE_STATUSAI *p_TYPE_STATUSAI;
  TYPE_COMMANDANALOG *p_TYPE_COMMANDANALOG;
  FB_SUNPACKERCOMMAND *p_FB_SUNPACKERCOMMAND;
  TYPE_ANALOGLIMITFLAGS *p_TYPE_ANALOGLIMITFLAGS;
  TON *p_TON;
  R_TRIG *p_R_TRIG;
  FB_AISOURCEMLP_TIMER *p_FB_AISOURCEMLP_TIMER;
  PROC_AO_INIT *p_PROC_AO_INIT;
  FB_AO_INIT *p_FB_AO_INIT;
  STRUCT_AO *p_STRUCT_AO;
  AOCONFIG *p_AOCONFIG;
  PROC_AO *p_PROC_AO;
  FB_AOSOURCEMLP *p_FB_AOSOURCEMLP;
  TDOUBLEDATA *p_TDOUBLEDATA;
  PROC_DI_INIT *p_PROC_DI_INIT;
  FB_DI_INIT *p_FB_DI_INIT;
  STRUCT_DI *p_STRUCT_DI;
  __IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t *p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t;
  TYPE_RELIABLEBIT *p_TYPE_RELIABLEBIT;
  DICONFIG *p_DICONFIG;
  PROC_DI *p_PROC_DI;
  FB_DISOURCEMLP *p_FB_DISOURCEMLP;
  INT *p_INT;
  UDINT *p_UDINT;
  PROC_DO_INIT *p_PROC_DO_INIT;
  FB_DO_INIT *p_FB_DO_INIT;
  STRUCT_DO *p_STRUCT_DO;
  __IEC___ARRAY_OF_BOOL_16_t *p___IEC___ARRAY_OF_BOOL_16_t;
  DOCONFIG *p_DOCONFIG;
  PROC_DO *p_PROC_DO;
  FB_DOSOURCEMLP *p_FB_DOSOURCEMLP;
  TWORDDATA *p_TWORDDATA;
  OPC_ALGORITMS_SET *p_OPC_ALGORITMS_SET;
  ALGORITMSCONFIG *p_ALGORITMSCONFIG;
  STRUCT_ALG *p_STRUCT_ALG;
  STRUCT_ALGORITMSMANAGER *p_STRUCT_ALGORITMSMANAGER;
  STRUCT_PROTECTIONSMANAGER *p_STRUCT_PROTECTIONSMANAGER;
  STRUCT_ALGTIMERS *p_STRUCT_ALGTIMERS;
  ALGORITMSQUESTIONS *p_ALGORITMSQUESTIONS;
  STRUCT_QUESTION *p_STRUCT_QUESTION;
  OPC_ALGORITMS_GET *p_OPC_ALGORITMS_GET;
  PROC_IM_INIT *p_PROC_IM_INIT;
  FB_KRAN_INIT *p_FB_KRAN_INIT;
  STRUCT_KRAN *p_STRUCT_KRAN;
  FB_SWITCH_INIT *p_FB_SWITCH_INIT;
  STRUCT_SWITCH *p_STRUCT_SWITCH;
  FB_OILPUMP_INIT *p_FB_OILPUMP_INIT;
  STRUCT_OILPUMP *p_STRUCT_OILPUMP;
  FB_SECTIONSWITCH_INIT *p_FB_SECTIONSWITCH_INIT;
  STRUCT_SECTIONSWITCH *p_STRUCT_SECTIONSWITCH;
  FB_ANALOGPARAMETR_INIT *p_FB_ANALOGPARAMETR_INIT;
  STRUCT_ANALOGPARAMETR *p_STRUCT_ANALOGPARAMETR;
  FB_DISCRETPARAMETR_INIT *p_FB_DISCRETPARAMETR_INIT;
  STRUCT_DISCRETPARAMETR *p_STRUCT_DISCRETPARAMETR;
  FB_SINGLESIGNAL_INIT *p_FB_SINGLESIGNAL_INIT;
  STRUCT_SINGLESIGNAL *p_STRUCT_SINGLESIGNAL;
  FB_SINGLEOUTPUT_INIT *p_FB_SINGLEOUTPUT_INIT;
  STRUCT_SINGLEOUTPUT *p_STRUCT_SINGLEOUTPUT;
  IMCONFIG *p_IMCONFIG;
  STRUCT_RESERVEIM *p_STRUCT_RESERVEIM;
  STRUCT_RESERVEIM2 *p_STRUCT_RESERVEIM2;
  IM_SINGLESIGNALS *p_IM_SINGLESIGNALS;
  IM_SINGLEOUTPUTS *p_IM_SINGLEOUTPUTS;
  PROC_IM *p_PROC_IM;
  FB_KRAN *p_FB_KRAN;
  TYPE_STATUSDUALINPUT *p_TYPE_STATUSDUALINPUT;
  TYPE_COMMANDDUALINPUT *p_TYPE_COMMANDDUALINPUT;
  TOF *p_TOF;
  FB_OILPUMP *p_FB_OILPUMP;
  FB_SWITCH *p_FB_SWITCH;
  FB_SECTIONSWITCH *p_FB_SECTIONSWITCH;
  TYPE_BASKETSTATS *p_TYPE_BASKETSTATS;
  FB_MEANDR *p_FB_MEANDR;
  FB_SINGLESIGNAL *p_FB_SINGLESIGNAL;
  FB_SINGLEOUTPUT *p_FB_SINGLEOUTPUT;
  PROC_PROTECTIONS_INIT *p_PROC_PROTECTIONS_INIT;
  FB_DIPROTECTION_INIT *p_FB_DIPROTECTION_INIT;
  STRUCT_DIPROTECTION *p_STRUCT_DIPROTECTION;
  FB_AIPROTECTION_INIT *p_FB_AIPROTECTION_INIT;
  STRUCT_AIPROTECTION *p_STRUCT_AIPROTECTION;
  PROTECTIONSCONFIG *p_PROTECTIONSCONFIG;
  TYPE_PROTECTIONTAGS *p_TYPE_PROTECTIONTAGS;
  PROC_PROTECTION *p_PROC_PROTECTION;
  FB_MVPROTECTION *p_FB_MVPROTECTION;
  F_TRIG *p_F_TRIG;
  FB_DIPROTECTION *p_FB_DIPROTECTION;
  FB_KRANOPENPROTECTION *p_FB_KRANOPENPROTECTION;
  FB_AIPROTECTION *p_FB_AIPROTECTION;
  PROC_ALGORITMS *p_PROC_ALGORITMS;
  REMONTALG *p_REMONTALG;
  TYPE_MODEGPA *p_TYPE_MODEGPA;
  TYPE_COMMANDSPOTECTIONSMANAGER *p_TYPE_COMMANDSPOTECTIONSMANAGER;
  TESTPROTECTIONALG *p_TESTPROTECTIONALG;
  TESTIMALG *p_TESTIMALG;
  FB_AUTOTENALG *p_FB_AUTOTENALG;
  FB_AUTOPNSALG *p_FB_AUTOPNSALG;
  FB_AUTOAVOMALG *p_FB_AUTOAVOMALG;
  FB_VIBEGPNSALG *p_FB_VIBEGPNSALG;
  STRUCT_PHASEALGORITM *p_STRUCT_PHASEALGORITM;
  FB_PH_ALGORITM *p_FB_PH_ALGORITM;
  FB_PH_TIMER *p_FB_PH_TIMER;
  FB_QUESTION *p_FB_QUESTION;
  TYPE_ANSWERS *p_TYPE_ANSWERS;
  FB_PH_SWITCH *p_FB_PH_SWITCH;
  FB_PH_CUSTOMPHASE *p_FB_PH_CUSTOMPHASE;
  FB_AUTONUALG *p_FB_AUTONUALG;
  FB_PUSKOILSYSTEMALG *p_FB_PUSKOILSYSTEMALG;
  FB_PH_WAITANALOGVALUE *p_FB_PH_WAITANALOGVALUE;
  FB_PH_OILPUMP *p_FB_PH_OILPUMP;
  FB_ANTIPOMPAGALG *p_FB_ANTIPOMPAGALG;
  FB_TABLEVALUE_MIN *p_FB_TABLEVALUE_MIN;
  __IEC___ARRAY_OF_TYPE_TABLEREC_9_t *p___IEC___ARRAY_OF_TYPE_TABLEREC_9_t;
  TYPE_TABLEREC *p_TYPE_TABLEREC;
  FB_TABLEVALUE_MAX *p_FB_TABLEVALUE_MAX;
  FB_RASHODALG *p_FB_RASHODALG;
  FB_ZAPASALG *p_FB_ZAPASALG;
  NOALG *p_NOALG;
  FB_PH_KRAN *p_FB_PH_KRAN;
  FB_PH_SECTIONSWITCH *p_FB_PH_SECTIONSWITCH;
  AOALG *p_AOALG;
  PPUALG *p_PPUALG;
  FILLINGALG *p_FILLINGALG;
  FB_PH_DIPROTECTION *p_FB_PH_DIPROTECTION;
  ENGINERUNALG *p_ENGINERUNALG;
  PUSKKALG *p_PUSKKALG;
  PUSKVALG *p_PUSKVALG;
  TESTDPMGALG *p_TESTDPMGALG;
  TESTPMSALG *p_TESTPMSALG;
  FB_PH_AIPROTECTION *p_FB_PH_AIPROTECTION;
  APUSKALG *p_APUSKALG;
  SEMIAUTOPUSKALG *p_SEMIAUTOPUSKALG;
  FB_ALGORITMSMANAGER *p_FB_ALGORITMSMANAGER;
  FB_PROTECTIONSMANAGER *p_FB_PROTECTIONSMANAGER;

  { // 60208 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.VALUE
    st = getVariable(60208);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.VALUE", 61);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->VALUE;
    st->value_p = p_LREAL;
  }
  { // 60209 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.STATUS
    st = getVariable(60209);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.STATUS", 62);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_DWORD = (DWORD*)&p_STRUCT_AI->STATUS;
    st->value_p = p_DWORD;
  }
  { // 60210 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.INTERVAL
    st = getVariable(60210);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.INTERVAL", 64);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_BYTE = (BYTE*)&p_STRUCT_AI->INTERVAL;
    st->value_p = p_BYTE;
  }
  { // 60211 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.INCOMMAND
    st = getVariable(60211);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.INCOMMAND", 65);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 60212 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.BLCONNECT
    st = getVariable(60212);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.BLCONNECT", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_BOOL = (BOOL*)&p_STRUCT_AI->BLCONNECT;
    st->value_p = p_BOOL;
  }
  { // 60213 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DLL
    st = getVariable(60213);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DLL", 59);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLL;
    st->value_p = p_LREAL;
  }
  { // 60214 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DHL
    st = getVariable(60214);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DHL", 59);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHL;
    st->value_p = p_LREAL;
  }
  { // 60215 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DLA
    st = getVariable(60215);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DLA", 59);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLA;
    st->value_p = p_LREAL;
  }
  { // 60216 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DHA
    st = getVariable(60216);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DHA", 59);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHA;
    st->value_p = p_LREAL;
  }
  { // 60217 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DLW
    st = getVariable(60217);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DLW", 59);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLW;
    st->value_p = p_LREAL;
  }
  { // 60218 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DHW
    st = getVariable(60218);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DHW", 59);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHW;
    st->value_p = p_LREAL;
  }
  { // 60219 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.LL
    st = getVariable(60219);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.LL", 58);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LL;
    st->value_p = p_LREAL;
  }
  { // 60220 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.HL
    st = getVariable(60220);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.HL", 58);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HL;
    st->value_p = p_LREAL;
  }
  { // 60221 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.LA
    st = getVariable(60221);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.LA", 58);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LA;
    st->value_p = p_LREAL;
  }
  { // 60222 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.HA
    st = getVariable(60222);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.HA", 58);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HA;
    st->value_p = p_LREAL;
  }
  { // 60223 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.LW
    st = getVariable(60223);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.LW", 58);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LW;
    st->value_p = p_LREAL;
  }
  { // 60224 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.HW
    st = getVariable(60224);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.HW", 58);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HW;
    st->value_p = p_LREAL;
  }
  { // 60225 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.ISVALIDREF_LA
    st = getVariable(60225);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.ISVALIDREF_LA", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_LA;
    st->value_p = p_BOOL;
  }
  { // 60226 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.ISVALIDREF_HA
    st = getVariable(60226);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.ISVALIDREF_HA", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_HA;
    st->value_p = p_BOOL;
  }
  { // 60227 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.ISVALIDREF_LW
    st = getVariable(60227);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.ISVALIDREF_LW", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_LW;
    st->value_p = p_BOOL;
  }
  { // 60228 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.ISVALIDREF_HW
    st = getVariable(60228);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.ISVALIDREF_HW", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_HW;
    st->value_p = p_BOOL;
  }
  { // 60229 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.INPLL
    st = getVariable(60229);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.INPLL", 61);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->INPLL;
    st->value_p = p_LREAL;
  }
  { // 60230 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.INPHL
    st = getVariable(60230);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.INPHL", 61);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->INPHL;
    st->value_p = p_LREAL;
  }
  { // 60231 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.CURRENTSHOTCIRCUIT
    st = getVariable(60231);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.CURRENTSHOTCIRCUIT", 74);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CURRENTSHOTCIRCUIT;
    st->value_p = p_LREAL;
  }
  { // 60232 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.CURRENTBREAKCIRCUIT
    st = getVariable(60232);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.CURRENTBREAKCIRCUIT", 75);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CURRENTBREAKCIRCUIT;
    st->value_p = p_LREAL;
  }
  { // 60233 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.MAXCHANGESPEED
    st = getVariable(60233);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.MAXCHANGESPEED", 70);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXCHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 60234 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.MAXCHANGESPEEDDOWN
    st = getVariable(60234);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.MAXCHANGESPEEDDOWN", 74);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXCHANGESPEEDDOWN;
    st->value_p = p_LREAL;
  }
  { // 60235 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.CHANGESPEED
    st = getVariable(60235);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.CHANGESPEED", 67);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 60236 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.HISTERESIS
    st = getVariable(60236);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.HISTERESIS", 66);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HISTERESIS;
    st->value_p = p_LREAL;
  }
  { // 60237 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.APERTURFILTER
    st = getVariable(60237);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.APERTURFILTER", 69);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->APERTURFILTER;
    st->value_p = p_LREAL;
  }
  { // 60238 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.EXPONENTIALFILTER
    st = getVariable(60238);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.EXPONENTIALFILTER", 73);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->EXPONENTIALFILTER;
    st->value_p = p_LREAL;
  }
  { // 60239 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.RASSOGLASOVANIE
    st = getVariable(60239);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.RASSOGLASOVANIE", 71);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->RASSOGLASOVANIE;
    st->value_p = p_LREAL;
  }
  { // 60240 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.OPCCOMMANDSDISABLED
    st = getVariable(60240);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.OPCCOMMANDSDISABLED", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_BOOL = (BOOL*)&p_STRUCT_AI->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 60241 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DISABLED_LA
    st = getVariable(60241);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DISABLED_LA", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_LA;
    st->value_p = p_BOOL;
  }
  { // 60242 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DISABLED_HA
    st = getVariable(60242);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DISABLED_HA", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_HA;
    st->value_p = p_BOOL;
  }
  { // 60243 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DISABLED_LW
    st = getVariable(60243);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DISABLED_LW", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_LW;
    st->value_p = p_BOOL;
  }
  { // 60244 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DISABLED_HW
    st = getVariable(60244);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DISABLED_HW", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_HW;
    st->value_p = p_BOOL;
  }
  { // 60245 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DELAYLA
    st = getVariable(60245);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DELAYLA", 63);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYLA;
    st->value_p = p_TIME;
  }
  { // 60246 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DELAYLW
    st = getVariable(60246);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DELAYLW", 63);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYLW;
    st->value_p = p_TIME;
  }
  { // 60247 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DELAYHW
    st = getVariable(60247);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DELAYHW", 63);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYHW;
    st->value_p = p_TIME;
  }
  { // 60248 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DELAYHA
    st = getVariable(60248);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DELAYHA", 63);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYHA;
    st->value_p = p_TIME;
  }
  { // 60249 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.MINVALUE_ISVALIDREF
    st = getVariable(60249);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.MINVALUE_ISVALIDREF", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_BOOL = (BOOL*)&p_STRUCT_AI->MINVALUE_ISVALIDREF;
    st->value_p = p_BOOL;
  }
  { // 60250 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.MAXVALUE_ISVALIDREF
    st = getVariable(60250);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.MAXVALUE_ISVALIDREF", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_BOOL = (BOOL*)&p_STRUCT_AI->MAXVALUE_ISVALIDREF;
    st->value_p = p_BOOL;
  }
  { // 60251 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.MINVALUE
    st = getVariable(60251);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.MINVALUE", 64);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MINVALUE;
    st->value_p = p_LREAL;
  }
  { // 60252 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.MAXVALUE
    st = getVariable(60252);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.MAXVALUE", 64);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXVALUE;
    st->value_p = p_LREAL;
  }
  { // 60253 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.INOPCCOMMANDSDISABLED
    st = getVariable(60253);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.INOPCCOMMANDSDISABLED", 77);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_BOOL = (BOOL*)&p_STRUCT_AI->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 60254 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.IMIT
    st = getVariable(60254);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.IMIT", 60);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_BOOL = (BOOL*)&p_STRUCT_AI->IMIT;
    st->value_p = p_BOOL;
  }
  { // 60255 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.REMONT
    st = getVariable(60255);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.REMONT", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_BOOL = (BOOL*)&p_STRUCT_AI->REMONT;
    st->value_p = p_BOOL;
  }
  { // 60256 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.NS
    st = getVariable(60256);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.NS", 58);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS;
    st->value_p = p_BOOL;
  }
  { // 60257 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.NS_MIN
    st = getVariable(60257);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.NS_MIN", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS_MIN;
    st->value_p = p_BOOL;
  }
  { // 60258 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.NS_MAX
    st = getVariable(60258);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.NS_MAX", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS_MAX;
    st->value_p = p_BOOL;
  }
  { // 60259 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.INCOMMAND_ALG
    st = getVariable(60259);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.INCOMMAND_ALG", 69);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 60260 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.INCOMMAND_ARM
    st = getVariable(60260);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.INCOMMAND_ARM", 69);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 60261 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DMAXCHANGESPEED
    st = getVariable(60261);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DMAXCHANGESPEED", 71);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DMAXCHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 60262 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DMAXCHANGESPEEDDOWN
    st = getVariable(60262);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_ACTUAL.DMAXCHANGESPEEDDOWN", 75);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->Q_ACTUAL;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DMAXCHANGESPEEDDOWN;
    st->value_p = p_LREAL;
  }
  { // 60263 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.VALUE
    st = getVariable(60263);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.VALUE", 58);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->VALUE;
    st->value_p = p_LREAL;
  }
  { // 60264 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.STATUS
    st = getVariable(60264);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.STATUS", 59);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_DWORD = (DWORD*)&p_STRUCT_AI->STATUS;
    st->value_p = p_DWORD;
  }
  { // 60265 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.INTERVAL
    st = getVariable(60265);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.INTERVAL", 61);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_BYTE = (BYTE*)&p_STRUCT_AI->INTERVAL;
    st->value_p = p_BYTE;
  }
  { // 60266 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.INCOMMAND
    st = getVariable(60266);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.INCOMMAND", 62);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 60267 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.BLCONNECT
    st = getVariable(60267);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.BLCONNECT", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->BLCONNECT;
    st->value_p = p_BOOL;
  }
  { // 60268 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DLL
    st = getVariable(60268);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DLL", 56);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLL;
    st->value_p = p_LREAL;
  }
  { // 60269 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DHL
    st = getVariable(60269);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DHL", 56);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHL;
    st->value_p = p_LREAL;
  }
  { // 60270 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DLA
    st = getVariable(60270);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DLA", 56);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLA;
    st->value_p = p_LREAL;
  }
  { // 60271 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DHA
    st = getVariable(60271);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DHA", 56);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHA;
    st->value_p = p_LREAL;
  }
  { // 60272 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DLW
    st = getVariable(60272);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DLW", 56);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLW;
    st->value_p = p_LREAL;
  }
  { // 60273 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DHW
    st = getVariable(60273);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DHW", 56);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHW;
    st->value_p = p_LREAL;
  }
  { // 60274 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.LL
    st = getVariable(60274);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.LL", 55);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LL;
    st->value_p = p_LREAL;
  }
  { // 60275 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.HL
    st = getVariable(60275);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.HL", 55);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HL;
    st->value_p = p_LREAL;
  }
  { // 60276 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.LA
    st = getVariable(60276);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.LA", 55);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LA;
    st->value_p = p_LREAL;
  }
  { // 60277 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.HA
    st = getVariable(60277);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.HA", 55);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HA;
    st->value_p = p_LREAL;
  }
  { // 60278 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.LW
    st = getVariable(60278);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.LW", 55);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LW;
    st->value_p = p_LREAL;
  }
  { // 60279 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.HW
    st = getVariable(60279);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.HW", 55);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HW;
    st->value_p = p_LREAL;
  }
  { // 60280 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.ISVALIDREF_LA
    st = getVariable(60280);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.ISVALIDREF_LA", 66);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_LA;
    st->value_p = p_BOOL;
  }
  { // 60281 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.ISVALIDREF_HA
    st = getVariable(60281);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.ISVALIDREF_HA", 66);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_HA;
    st->value_p = p_BOOL;
  }
  { // 60282 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.ISVALIDREF_LW
    st = getVariable(60282);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.ISVALIDREF_LW", 66);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_LW;
    st->value_p = p_BOOL;
  }
  { // 60283 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.ISVALIDREF_HW
    st = getVariable(60283);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.ISVALIDREF_HW", 66);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_HW;
    st->value_p = p_BOOL;
  }
  { // 60284 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.INPLL
    st = getVariable(60284);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.INPLL", 58);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->INPLL;
    st->value_p = p_LREAL;
  }
  { // 60285 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.INPHL
    st = getVariable(60285);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.INPHL", 58);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->INPHL;
    st->value_p = p_LREAL;
  }
  { // 60286 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.CURRENTSHOTCIRCUIT
    st = getVariable(60286);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.CURRENTSHOTCIRCUIT", 71);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CURRENTSHOTCIRCUIT;
    st->value_p = p_LREAL;
  }
  { // 60287 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.CURRENTBREAKCIRCUIT
    st = getVariable(60287);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.CURRENTBREAKCIRCUIT", 72);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CURRENTBREAKCIRCUIT;
    st->value_p = p_LREAL;
  }
  { // 60288 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.MAXCHANGESPEED
    st = getVariable(60288);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.MAXCHANGESPEED", 67);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXCHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 60289 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.MAXCHANGESPEEDDOWN
    st = getVariable(60289);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.MAXCHANGESPEEDDOWN", 71);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXCHANGESPEEDDOWN;
    st->value_p = p_LREAL;
  }
  { // 60290 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.CHANGESPEED
    st = getVariable(60290);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.CHANGESPEED", 64);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 60291 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.HISTERESIS
    st = getVariable(60291);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.HISTERESIS", 63);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HISTERESIS;
    st->value_p = p_LREAL;
  }
  { // 60292 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.APERTURFILTER
    st = getVariable(60292);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.APERTURFILTER", 66);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->APERTURFILTER;
    st->value_p = p_LREAL;
  }
  { // 60293 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.EXPONENTIALFILTER
    st = getVariable(60293);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.EXPONENTIALFILTER", 70);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->EXPONENTIALFILTER;
    st->value_p = p_LREAL;
  }
  { // 60294 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.RASSOGLASOVANIE
    st = getVariable(60294);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.RASSOGLASOVANIE", 68);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->RASSOGLASOVANIE;
    st->value_p = p_LREAL;
  }
  { // 60295 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.OPCCOMMANDSDISABLED
    st = getVariable(60295);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.OPCCOMMANDSDISABLED", 72);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 60296 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DISABLED_LA
    st = getVariable(60296);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DISABLED_LA", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_LA;
    st->value_p = p_BOOL;
  }
  { // 60297 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DISABLED_HA
    st = getVariable(60297);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DISABLED_HA", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_HA;
    st->value_p = p_BOOL;
  }
  { // 60298 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DISABLED_LW
    st = getVariable(60298);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DISABLED_LW", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_LW;
    st->value_p = p_BOOL;
  }
  { // 60299 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DISABLED_HW
    st = getVariable(60299);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DISABLED_HW", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_HW;
    st->value_p = p_BOOL;
  }
  { // 60300 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DELAYLA
    st = getVariable(60300);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DELAYLA", 60);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYLA;
    st->value_p = p_TIME;
  }
  { // 60301 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DELAYLW
    st = getVariable(60301);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DELAYLW", 60);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYLW;
    st->value_p = p_TIME;
  }
  { // 60302 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DELAYHW
    st = getVariable(60302);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DELAYHW", 60);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYHW;
    st->value_p = p_TIME;
  }
  { // 60303 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DELAYHA
    st = getVariable(60303);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DELAYHA", 60);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYHA;
    st->value_p = p_TIME;
  }
  { // 60304 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.MINVALUE_ISVALIDREF
    st = getVariable(60304);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.MINVALUE_ISVALIDREF", 72);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->MINVALUE_ISVALIDREF;
    st->value_p = p_BOOL;
  }
  { // 60305 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.MAXVALUE_ISVALIDREF
    st = getVariable(60305);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.MAXVALUE_ISVALIDREF", 72);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->MAXVALUE_ISVALIDREF;
    st->value_p = p_BOOL;
  }
  { // 60306 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.MINVALUE
    st = getVariable(60306);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.MINVALUE", 61);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MINVALUE;
    st->value_p = p_LREAL;
  }
  { // 60307 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.MAXVALUE
    st = getVariable(60307);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.MAXVALUE", 61);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXVALUE;
    st->value_p = p_LREAL;
  }
  { // 60308 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.INOPCCOMMANDSDISABLED
    st = getVariable(60308);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.INOPCCOMMANDSDISABLED", 74);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 60309 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.IMIT
    st = getVariable(60309);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.IMIT", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->IMIT;
    st->value_p = p_BOOL;
  }
  { // 60310 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.REMONT
    st = getVariable(60310);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.REMONT", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->REMONT;
    st->value_p = p_BOOL;
  }
  { // 60311 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.NS
    st = getVariable(60311);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.NS", 55);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS;
    st->value_p = p_BOOL;
  }
  { // 60312 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.NS_MIN
    st = getVariable(60312);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.NS_MIN", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS_MIN;
    st->value_p = p_BOOL;
  }
  { // 60313 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.NS_MAX
    st = getVariable(60313);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.NS_MAX", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS_MAX;
    st->value_p = p_BOOL;
  }
  { // 60314 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.INCOMMAND_ALG
    st = getVariable(60314);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.INCOMMAND_ALG", 66);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 60315 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.INCOMMAND_ARM
    st = getVariable(60315);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.INCOMMAND_ARM", 66);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 60316 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DMAXCHANGESPEED
    st = getVariable(60316);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DMAXCHANGESPEED", 68);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DMAXCHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 60317 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DMAXCHANGESPEEDDOWN
    st = getVariable(60317);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.STRAI.DMAXCHANGESPEEDDOWN", 72);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_ZAPASALG->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DMAXCHANGESPEEDDOWN;
    st->value_p = p_LREAL;
  }
  { // 60318 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_MIN
    st = getVariable(60318);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_MIN", 52);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_LREAL = (LREAL*)&p_FB_ZAPASALG->Q_MIN;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 60319 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_MAX
    st = getVariable(60319);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS.Q_MAX", 52);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_LREAL = (LREAL*)&p_FB_ZAPASALG->Q_MAX;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 60320 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS._STATUSAI.NOTDEFINED
    st = getVariable(60320);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS._STATUSAI.NOTDEFINED", 67);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_ZAPASALG->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NOTDEFINED;
    st->value_p = p_BYTE;
  }
  { // 60321 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS._STATUSAI.LL
    st = getVariable(60321);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS._STATUSAI.LL", 59);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_ZAPASALG->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LL;
    st->value_p = p_BYTE;
  }
  { // 60322 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS._STATUSAI.HL
    st = getVariable(60322);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS._STATUSAI.HL", 59);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_ZAPASALG->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HL;
    st->value_p = p_BYTE;
  }
  { // 60323 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS._STATUSAI.NOTRELIABLE
    st = getVariable(60323);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS._STATUSAI.NOTRELIABLE", 68);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_ZAPASALG->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NOTRELIABLE;
    st->value_p = p_BYTE;
  }
  { // 60324 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS._STATUSAI.NORMAL
    st = getVariable(60324);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS._STATUSAI.NORMAL", 63);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_ZAPASALG->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NORMAL;
    st->value_p = p_BYTE;
  }
  { // 60325 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS._STATUSAI.LW
    st = getVariable(60325);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS._STATUSAI.LW", 59);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_ZAPASALG->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LW;
    st->value_p = p_BYTE;
  }
  { // 60326 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS._STATUSAI.HW
    st = getVariable(60326);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS._STATUSAI.HW", 59);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_ZAPASALG->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HW;
    st->value_p = p_BYTE;
  }
  { // 60327 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS._STATUSAI.LA
    st = getVariable(60327);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS._STATUSAI.LA", 59);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_ZAPASALG->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LA;
    st->value_p = p_BYTE;
  }
  { // 60328 PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS._STATUSAI.HA
    st = getVariable(60328);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ANTIPOMPAG.FB_ZAPAS._STATUSAI.HA", 59);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_ANTIPOMPAGALG = (FB_ANTIPOMPAGALG*)&p_PROC_ALGORITMS->FB_ANTIPOMPAG;
    p_FB_ZAPASALG = (FB_ZAPASALG*)&p_FB_ANTIPOMPAGALG->FB_ZAPAS;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_ZAPASALG->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HA;
    st->value_p = p_BYTE;
  }

  return 0;
}

// clang-format on
