// clang-format off

#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include "POUS.h"
#include <beremiz/beremiz.h>

#include "iec_types_all.h"
#include "config1.h"

extern PROGRAM0 RESOURCE1__INSTANCE0;

#ifdef DEBUG_PLC
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err][%s:%d]: " _PRNTMSG "\n", __func__, __LINE__, ##__VA_ARGS__)
#else
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err]: " _PRNTMSG "\n", ##__VA_ARGS__)
#endif // DEBUG_PLC

void UnpackVar(void* varp, __IEC_types_enum vartype, void **value_p, void **f_value_p, uint8_t **flags);

int __variables_init_FB_KRAN6OPEN(){
  iec_var_t *st;

  PROGRAM0 *p_PROGRAM0;
  LREAL *p_LREAL;
  ULINT *p_ULINT;
  REAL *p_REAL;
  FB_TIMINGS *p_FB_TIMINGS;
  BOOL *p_BOOL;
  UINT *p_UINT;
  PROC_AI_INIT *p_PROC_AI_INIT;
  FB_AI_INIT *p_FB_AI_INIT;
  STRUCT_AI *p_STRUCT_AI;
  DWORD *p_DWORD;
  BYTE *p_BYTE;
  WORD *p_WORD;
  TIME *p_TIME;
  AICONFIG *p_AICONFIG;
  PROC_AI *p_PROC_AI;
  FB_AISOURCEMLP *p_FB_AISOURCEMLP;
  TITEMAIN *p_TITEMAIN;
  TITEMDIN *p_TITEMDIN;
  TYPE_STATUSAI *p_TYPE_STATUSAI;
  TYPE_COMMANDANALOG *p_TYPE_COMMANDANALOG;
  FB_SUNPACKERCOMMAND *p_FB_SUNPACKERCOMMAND;
  TYPE_ANALOGLIMITFLAGS *p_TYPE_ANALOGLIMITFLAGS;
  TON *p_TON;
  R_TRIG *p_R_TRIG;
  FB_AISOURCEMLP_TIMER *p_FB_AISOURCEMLP_TIMER;
  PROC_AO_INIT *p_PROC_AO_INIT;
  FB_AO_INIT *p_FB_AO_INIT;
  STRUCT_AO *p_STRUCT_AO;
  AOCONFIG *p_AOCONFIG;
  PROC_AO *p_PROC_AO;
  FB_AOSOURCEMLP *p_FB_AOSOURCEMLP;
  TDOUBLEDATA *p_TDOUBLEDATA;
  PROC_DI_INIT *p_PROC_DI_INIT;
  FB_DI_INIT *p_FB_DI_INIT;
  STRUCT_DI *p_STRUCT_DI;
  __IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t *p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t;
  TYPE_RELIABLEBIT *p_TYPE_RELIABLEBIT;
  DICONFIG *p_DICONFIG;
  PROC_DI *p_PROC_DI;
  FB_DISOURCEMLP *p_FB_DISOURCEMLP;
  INT *p_INT;
  UDINT *p_UDINT;
  PROC_DO_INIT *p_PROC_DO_INIT;
  FB_DO_INIT *p_FB_DO_INIT;
  STRUCT_DO *p_STRUCT_DO;
  DOCONFIG *p_DOCONFIG;
  PROC_DO *p_PROC_DO;
  FB_DOSOURCEMLP *p_FB_DOSOURCEMLP;
  TWORDDATA *p_TWORDDATA;
  OPC_ALGORITMS_SET *p_OPC_ALGORITMS_SET;
  ALGORITMSCONFIG *p_ALGORITMSCONFIG;
  STRUCT_ALG *p_STRUCT_ALG;
  STRUCT_ALGORITMSMANAGER *p_STRUCT_ALGORITMSMANAGER;
  STRUCT_PROTECTIONSMANAGER *p_STRUCT_PROTECTIONSMANAGER;
  STRUCT_ALGTIMERS *p_STRUCT_ALGTIMERS;
  ALGORITMSQUESTIONS *p_ALGORITMSQUESTIONS;
  STRUCT_QUESTION *p_STRUCT_QUESTION;
  OPC_ALGORITMS_GET *p_OPC_ALGORITMS_GET;
  PROC_IM_INIT *p_PROC_IM_INIT;
  FB_KRAN_INIT *p_FB_KRAN_INIT;
  STRUCT_KRAN *p_STRUCT_KRAN;
  FB_SWITCH_INIT *p_FB_SWITCH_INIT;
  STRUCT_SWITCH *p_STRUCT_SWITCH;
  FB_OILPUMP_INIT *p_FB_OILPUMP_INIT;
  STRUCT_OILPUMP *p_STRUCT_OILPUMP;
  FB_SECTIONSWITCH_INIT *p_FB_SECTIONSWITCH_INIT;
  STRUCT_SECTIONSWITCH *p_STRUCT_SECTIONSWITCH;
  FB_ANALOGPARAMETR_INIT *p_FB_ANALOGPARAMETR_INIT;
  STRUCT_ANALOGPARAMETR *p_STRUCT_ANALOGPARAMETR;
  FB_DISCRETPARAMETR_INIT *p_FB_DISCRETPARAMETR_INIT;
  STRUCT_DISCRETPARAMETR *p_STRUCT_DISCRETPARAMETR;
  FB_SINGLESIGNAL_INIT *p_FB_SINGLESIGNAL_INIT;
  STRUCT_SINGLESIGNAL *p_STRUCT_SINGLESIGNAL;
  FB_SINGLEOUTPUT_INIT *p_FB_SINGLEOUTPUT_INIT;
  STRUCT_SINGLEOUTPUT *p_STRUCT_SINGLEOUTPUT;
  IMCONFIG *p_IMCONFIG;
  STRUCT_RESERVEIM *p_STRUCT_RESERVEIM;
  STRUCT_RESERVEIM2 *p_STRUCT_RESERVEIM2;
  IM_SINGLESIGNALS *p_IM_SINGLESIGNALS;
  IM_SINGLEOUTPUTS *p_IM_SINGLEOUTPUTS;
  PROC_IM *p_PROC_IM;
  FB_KRAN *p_FB_KRAN;
  TYPE_STATUSDUALINPUT *p_TYPE_STATUSDUALINPUT;
  TYPE_COMMANDDUALINPUT *p_TYPE_COMMANDDUALINPUT;
  TOF *p_TOF;
  FB_OILPUMP *p_FB_OILPUMP;
  FB_SWITCH *p_FB_SWITCH;
  FB_SECTIONSWITCH *p_FB_SECTIONSWITCH;
  TYPE_BASKETSTATS *p_TYPE_BASKETSTATS;
  FB_MEANDR *p_FB_MEANDR;
  FB_SINGLESIGNAL *p_FB_SINGLESIGNAL;
  FB_SINGLEOUTPUT *p_FB_SINGLEOUTPUT;
  PROC_PROTECTIONS_INIT *p_PROC_PROTECTIONS_INIT;
  FB_DIPROTECTION_INIT *p_FB_DIPROTECTION_INIT;
  STRUCT_DIPROTECTION *p_STRUCT_DIPROTECTION;
  FB_AIPROTECTION_INIT *p_FB_AIPROTECTION_INIT;
  STRUCT_AIPROTECTION *p_STRUCT_AIPROTECTION;
  PROTECTIONSCONFIG *p_PROTECTIONSCONFIG;
  TYPE_PROTECTIONTAGS *p_TYPE_PROTECTIONTAGS;
  PROC_PROTECTION *p_PROC_PROTECTION;
  FB_MVPROTECTION *p_FB_MVPROTECTION;
  F_TRIG *p_F_TRIG;
  FB_DIPROTECTION *p_FB_DIPROTECTION;
  FB_KRANOPENPROTECTION *p_FB_KRANOPENPROTECTION;
  FB_AIPROTECTION *p_FB_AIPROTECTION;
  PROC_ALGORITMS *p_PROC_ALGORITMS;
  REMONTALG *p_REMONTALG;
  TYPE_MODEGPA *p_TYPE_MODEGPA;
  TYPE_COMMANDSPOTECTIONSMANAGER *p_TYPE_COMMANDSPOTECTIONSMANAGER;
  TESTPROTECTIONALG *p_TESTPROTECTIONALG;
  TESTIMALG *p_TESTIMALG;
  FB_AUTOTENALG *p_FB_AUTOTENALG;
  FB_AUTOPNSALG *p_FB_AUTOPNSALG;
  FB_AUTOAVOMALG *p_FB_AUTOAVOMALG;
  FB_VIBEGPNSALG *p_FB_VIBEGPNSALG;
  STRUCT_PHASEALGORITM *p_STRUCT_PHASEALGORITM;
  FB_PH_ALGORITM *p_FB_PH_ALGORITM;
  FB_PH_TIMER *p_FB_PH_TIMER;
  FB_QUESTION *p_FB_QUESTION;
  TYPE_ANSWERS *p_TYPE_ANSWERS;
  FB_PH_SWITCH *p_FB_PH_SWITCH;
  FB_PH_CUSTOMPHASE *p_FB_PH_CUSTOMPHASE;
  FB_AUTONUALG *p_FB_AUTONUALG;
  FB_PUSKOILSYSTEMALG *p_FB_PUSKOILSYSTEMALG;
  FB_PH_WAITANALOGVALUE *p_FB_PH_WAITANALOGVALUE;
  FB_PH_OILPUMP *p_FB_PH_OILPUMP;
  FB_ANTIPOMPAGALG *p_FB_ANTIPOMPAGALG;
  FB_TABLEVALUE_MIN *p_FB_TABLEVALUE_MIN;
  __IEC___ARRAY_OF_TYPE_TABLEREC_9_t *p___IEC___ARRAY_OF_TYPE_TABLEREC_9_t;
  TYPE_TABLEREC *p_TYPE_TABLEREC;
  FB_TABLEVALUE_MAX *p_FB_TABLEVALUE_MAX;
  FB_RASHODALG *p_FB_RASHODALG;
  FB_ZAPASALG *p_FB_ZAPASALG;
  NOALG *p_NOALG;
  FB_PH_KRAN *p_FB_PH_KRAN;
  FB_PH_SECTIONSWITCH *p_FB_PH_SECTIONSWITCH;
  AOALG *p_AOALG;
  PPUALG *p_PPUALG;
  FILLINGALG *p_FILLINGALG;
  FB_PH_DIPROTECTION *p_FB_PH_DIPROTECTION;
  ENGINERUNALG *p_ENGINERUNALG;
  PUSKKALG *p_PUSKKALG;
  PUSKVALG *p_PUSKVALG;
  TESTDPMGALG *p_TESTDPMGALG;
  TESTPMSALG *p_TESTPMSALG;
  FB_PH_AIPROTECTION *p_FB_PH_AIPROTECTION;
  APUSKALG *p_APUSKALG;
  SEMIAUTOPUSKALG *p_SEMIAUTOPUSKALG;
  PUSK_FIRST_FAZA1 *p_PUSK_FIRST_FAZA1;
  PUSK_FIRST_FAZA2 *p_PUSK_FIRST_FAZA2;
  PUSK_THIRD_FAZA *p_PUSK_THIRD_FAZA;
  PROV_PMS *p_PROV_PMS;
  PROV_OPRESSOVKA *p_PROV_OPRESSOVKA;
  PUSK_SECOND_FAZA_CHASTOTNY *p_PUSK_SECOND_FAZA_CHASTOTNY;
  PUSK_SECOND_FAZA_REACTOR *p_PUSK_SECOND_FAZA_REACTOR;
  FB_ALGORITMSMANAGER *p_FB_ALGORITMSMANAGER;
  FB_PROTECTIONSMANAGER *p_FB_PROTECTIONSMANAGER;

  { // 60816 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.INCOMMAND
    st = getVariable(60816);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.INCOMMAND", 58);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_WORD = (WORD*)&p_STRUCT_KRAN->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 60817 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.STATUS
    st = getVariable(60817);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.STATUS", 55);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_DWORD = (DWORD*)&p_STRUCT_KRAN->STATUS;
    st->value_p = p_DWORD;
  }
  { // 60818 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.ONSTATUS
    st = getVariable(60818);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.ONSTATUS", 57);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BYTE = (BYTE*)&p_STRUCT_KRAN->ONSTATUS;
    st->value_p = p_BYTE;
  }
  { // 60819 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.INOPCCOMMANDSDISABLED
    st = getVariable(60819);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.INOPCCOMMANDSDISABLED", 70);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 60820 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.SDVIG
    st = getVariable(60820);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.SDVIG", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->SDVIG;
    st->value_p = p_BOOL;
  }
  { // 60821 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.NS
    st = getVariable(60821);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.NS", 51);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->NS;
    st->value_p = p_BOOL;
  }
  { // 60822 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.DP
    st = getVariable(60822);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.DP", 51);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->DP;
    st->value_p = p_BOOL;
  }
  { // 60823 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.COMMANDFAULT
    st = getVariable(60823);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.COMMANDFAULT", 61);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->COMMANDFAULT;
    st->value_p = p_BOOL;
  }
  { // 60824 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.ACCIDENT
    st = getVariable(60824);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.ACCIDENT", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->ACCIDENT;
    st->value_p = p_BOOL;
  }
  { // 60825 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.AUTO
    st = getVariable(60825);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.AUTO", 53);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->AUTO;
    st->value_p = p_BOOL;
  }
  { // 60826 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.MANUAL
    st = getVariable(60826);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.MANUAL", 55);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->MANUAL;
    st->value_p = p_BOOL;
  }
  { // 60827 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.LOCAL
    st = getVariable(60827);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.LOCAL", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->LOCAL;
    st->value_p = p_BOOL;
  }
  { // 60828 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.DISTANCE
    st = getVariable(60828);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.DISTANCE", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->DISTANCE;
    st->value_p = p_BOOL;
  }
  { // 60829 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.ERRORPOWEROFF
    st = getVariable(60829);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.ERRORPOWEROFF", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->ERRORPOWEROFF;
    st->value_p = p_BOOL;
  }
  { // 60830 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.ERRORBLOCK
    st = getVariable(60830);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.ERRORBLOCK", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->ERRORBLOCK;
    st->value_p = p_BOOL;
  }
  { // 60831 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.SO
    st = getVariable(60831);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.SO", 51);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->SO;
    st->value_p = p_BOOL;
  }
  { // 60832 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.SZ
    st = getVariable(60832);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.SZ", 51);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->SZ;
    st->value_p = p_BOOL;
  }
  { // 60833 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.OPCCOMMANDSDISABLED
    st = getVariable(60833);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.OPCCOMMANDSDISABLED", 68);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 60834 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.LASTCMDISON
    st = getVariable(60834);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.LASTCMDISON", 60);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->LASTCMDISON;
    st->value_p = p_BOOL;
  }
  { // 60835 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.ISVALIDREF_STATON
    st = getVariable(60835);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.ISVALIDREF_STATON", 66);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->ISVALIDREF_STATON;
    st->value_p = p_BOOL;
  }
  { // 60836 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.ISVALIDREF_STATOFF
    st = getVariable(60836);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.ISVALIDREF_STATOFF", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->ISVALIDREF_STATOFF;
    st->value_p = p_BOOL;
  }
  { // 60837 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.ISVALIDREF_CMDON
    st = getVariable(60837);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.ISVALIDREF_CMDON", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->ISVALIDREF_CMDON;
    st->value_p = p_BOOL;
  }
  { // 60838 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.ISVALIDREF_CMDOFF
    st = getVariable(60838);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.ISVALIDREF_CMDOFF", 66);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->ISVALIDREF_CMDOFF;
    st->value_p = p_BOOL;
  }
  { // 60839 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.ISVALIDREF_INSO
    st = getVariable(60839);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.ISVALIDREF_INSO", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->ISVALIDREF_INSO;
    st->value_p = p_BOOL;
  }
  { // 60840 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.ISVALIDREF_INSZ
    st = getVariable(60840);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.ISVALIDREF_INSZ", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->ISVALIDREF_INSZ;
    st->value_p = p_BOOL;
  }
  { // 60841 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.ISVALIDREF_INDP
    st = getVariable(60841);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.ISVALIDREF_INDP", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->ISVALIDREF_INDP;
    st->value_p = p_BOOL;
  }
  { // 60842 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.CONTINUEHOLDCOMMAND
    st = getVariable(60842);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.CONTINUEHOLDCOMMAND", 68);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_TIME = (TIME*)&p_STRUCT_KRAN->CONTINUEHOLDCOMMAND;
    st->value_p = p_TIME;
  }
  { // 60843 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.INCOMMAND_ALG
    st = getVariable(60843);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.INCOMMAND_ALG", 62);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_WORD = (WORD*)&p_STRUCT_KRAN->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 60844 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.INCOMMAND_ARM
    st = getVariable(60844);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.INCOMMAND_ARM", 62);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_WORD = (WORD*)&p_STRUCT_KRAN->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 60845 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.CMDON
    st = getVariable(60845);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.CMDON", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->CMDON;
    st->value_p = p_BOOL;
  }
  { // 60846 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.CMDOFF
    st = getVariable(60846);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.CMDOFF", 55);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->CMDOFF;
    st->value_p = p_BOOL;
  }
  { // 60847 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.RELIABILITY
    st = getVariable(60847);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.IM.RELIABILITY", 60);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 60848 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.STRPH.RUN
    st = getVariable(60848);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.STRPH.RUN", 55);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_KRAN->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->RUN;
    st->value_p = p_BOOL;
  }
  { // 60849 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.STRPH.RESET
    st = getVariable(60849);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.STRPH.RESET", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_KRAN->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->RESET;
    st->value_p = p_BOOL;
  }
  { // 60850 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.STRPH.START
    st = getVariable(60850);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.STRPH.START", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_KRAN->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->START;
    st->value_p = p_BOOL;
  }
  { // 60851 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.STRPH.ERROR
    st = getVariable(60851);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.STRPH.ERROR", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_KRAN->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->ERROR;
    st->value_p = p_BOOL;
  }
  { // 60852 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.STRPH.TOP
    st = getVariable(60852);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.STRPH.TOP", 55);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_KRAN->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->TOP;
    st->value_p = p_BOOL;
  }
  { // 60853 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.STRPH.STARTSTATUS
    st = getVariable(60853);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.STRPH.STARTSTATUS", 63);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_KRAN->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->STARTSTATUS;
    st->value_p = p_DWORD;
  }
  { // 60854 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.STRPH.ERRORSTATUS
    st = getVariable(60854);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.STRPH.ERRORSTATUS", 63);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_KRAN->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->ERRORSTATUS;
    st->value_p = p_DWORD;
  }
  { // 60855 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.STRPH.TOPSTATUS
    st = getVariable(60855);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.STRPH.TOPSTATUS", 61);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_KRAN->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->TOPSTATUS;
    st->value_p = p_DWORD;
  }
  { // 60856 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.PHASENUMBER
    st = getVariable(60856);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.PHASENUMBER", 57);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_UINT = (UINT*)&p_FB_PH_KRAN->PHASENUMBER;
    UnpackVar(p_UINT, UINT_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 60857 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.COMMANDFAULT_TRIG.CLK
    st = getVariable(60857);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.COMMANDFAULT_TRIG.CLK", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_KRAN->COMMANDFAULT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 60858 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.COMMANDFAULT_TRIG.Q
    st = getVariable(60858);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.COMMANDFAULT_TRIG.Q", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_KRAN->COMMANDFAULT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 60859 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.COMMANDFAULT_TRIG
    st = getVariable(60859);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.COMMANDFAULT_TRIG", 63);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_KRAN->COMMANDFAULT_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 60860 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.RESET_TRIG.CLK
    st = getVariable(60860);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.RESET_TRIG.CLK", 60);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_KRAN->RESET_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 60861 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.RESET_TRIG.Q
    st = getVariable(60861);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.RESET_TRIG.Q", 58);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_KRAN->RESET_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 60862 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.RESET_TRIG
    st = getVariable(60862);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN.RESET_TRIG", 56);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_KRAN->RESET_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 60863 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN._STATUSDUALINPUT.STATUS_NOTDEFINED
    st = getVariable(60863);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN._STATUSDUALINPUT.STATUS_NOTDEFINED", 80);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_KRAN->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_NOTDEFINED;
    st->value_p = p_BYTE;
  }
  { // 60864 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN._STATUSDUALINPUT.STATUS_ON
    st = getVariable(60864);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN._STATUSDUALINPUT.STATUS_ON", 72);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_KRAN->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ON;
    st->value_p = p_BYTE;
  }
  { // 60865 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN._STATUSDUALINPUT.STATUS_OFF
    st = getVariable(60865);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN._STATUSDUALINPUT.STATUS_OFF", 73);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_KRAN->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_OFF;
    st->value_p = p_BYTE;
  }
  { // 60866 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN._STATUSDUALINPUT.STATUS_TRANSITIONAL
    st = getVariable(60866);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN._STATUSDUALINPUT.STATUS_TRANSITIONAL", 82);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_KRAN->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_TRANSITIONAL;
    st->value_p = p_BYTE;
  }
  { // 60867 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN._STATUSDUALINPUT.STATUS_ERROR
    st = getVariable(60867);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_KRAN6OPEN._STATUSDUALINPUT.STATUS_ERROR", 75);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_NOALG->FB_KRAN6OPEN;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_KRAN->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ERROR;
    st->value_p = p_BYTE;
  }
  { // 67612 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.INCOMMAND
    st = getVariable(67612);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.INCOMMAND", 58);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_WORD = (WORD*)&p_STRUCT_KRAN->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 67613 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.STATUS
    st = getVariable(67613);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.STATUS", 55);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_DWORD = (DWORD*)&p_STRUCT_KRAN->STATUS;
    st->value_p = p_DWORD;
  }
  { // 67614 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.ONSTATUS
    st = getVariable(67614);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.ONSTATUS", 57);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BYTE = (BYTE*)&p_STRUCT_KRAN->ONSTATUS;
    st->value_p = p_BYTE;
  }
  { // 67615 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.INOPCCOMMANDSDISABLED
    st = getVariable(67615);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.INOPCCOMMANDSDISABLED", 70);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 67616 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.SDVIG
    st = getVariable(67616);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.SDVIG", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->SDVIG;
    st->value_p = p_BOOL;
  }
  { // 67617 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.NS
    st = getVariable(67617);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.NS", 51);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->NS;
    st->value_p = p_BOOL;
  }
  { // 67618 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.DP
    st = getVariable(67618);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.DP", 51);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->DP;
    st->value_p = p_BOOL;
  }
  { // 67619 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.COMMANDFAULT
    st = getVariable(67619);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.COMMANDFAULT", 61);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->COMMANDFAULT;
    st->value_p = p_BOOL;
  }
  { // 67620 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.ACCIDENT
    st = getVariable(67620);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.ACCIDENT", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->ACCIDENT;
    st->value_p = p_BOOL;
  }
  { // 67621 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.AUTO
    st = getVariable(67621);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.AUTO", 53);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->AUTO;
    st->value_p = p_BOOL;
  }
  { // 67622 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.MANUAL
    st = getVariable(67622);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.MANUAL", 55);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->MANUAL;
    st->value_p = p_BOOL;
  }
  { // 67623 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.LOCAL
    st = getVariable(67623);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.LOCAL", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->LOCAL;
    st->value_p = p_BOOL;
  }
  { // 67624 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.DISTANCE
    st = getVariable(67624);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.DISTANCE", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->DISTANCE;
    st->value_p = p_BOOL;
  }
  { // 67625 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.ERRORPOWEROFF
    st = getVariable(67625);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.ERRORPOWEROFF", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->ERRORPOWEROFF;
    st->value_p = p_BOOL;
  }
  { // 67626 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.ERRORBLOCK
    st = getVariable(67626);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.ERRORBLOCK", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->ERRORBLOCK;
    st->value_p = p_BOOL;
  }
  { // 67627 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.SO
    st = getVariable(67627);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.SO", 51);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->SO;
    st->value_p = p_BOOL;
  }
  { // 67628 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.SZ
    st = getVariable(67628);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.SZ", 51);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->SZ;
    st->value_p = p_BOOL;
  }
  { // 67629 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.OPCCOMMANDSDISABLED
    st = getVariable(67629);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.OPCCOMMANDSDISABLED", 68);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 67630 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.LASTCMDISON
    st = getVariable(67630);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.LASTCMDISON", 60);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->LASTCMDISON;
    st->value_p = p_BOOL;
  }
  { // 67631 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.ISVALIDREF_STATON
    st = getVariable(67631);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.ISVALIDREF_STATON", 66);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->ISVALIDREF_STATON;
    st->value_p = p_BOOL;
  }
  { // 67632 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.ISVALIDREF_STATOFF
    st = getVariable(67632);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.ISVALIDREF_STATOFF", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->ISVALIDREF_STATOFF;
    st->value_p = p_BOOL;
  }
  { // 67633 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.ISVALIDREF_CMDON
    st = getVariable(67633);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.ISVALIDREF_CMDON", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->ISVALIDREF_CMDON;
    st->value_p = p_BOOL;
  }
  { // 67634 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.ISVALIDREF_CMDOFF
    st = getVariable(67634);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.ISVALIDREF_CMDOFF", 66);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->ISVALIDREF_CMDOFF;
    st->value_p = p_BOOL;
  }
  { // 67635 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.ISVALIDREF_INSO
    st = getVariable(67635);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.ISVALIDREF_INSO", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->ISVALIDREF_INSO;
    st->value_p = p_BOOL;
  }
  { // 67636 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.ISVALIDREF_INSZ
    st = getVariable(67636);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.ISVALIDREF_INSZ", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->ISVALIDREF_INSZ;
    st->value_p = p_BOOL;
  }
  { // 67637 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.ISVALIDREF_INDP
    st = getVariable(67637);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.ISVALIDREF_INDP", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->ISVALIDREF_INDP;
    st->value_p = p_BOOL;
  }
  { // 67638 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.CONTINUEHOLDCOMMAND
    st = getVariable(67638);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.CONTINUEHOLDCOMMAND", 68);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_TIME = (TIME*)&p_STRUCT_KRAN->CONTINUEHOLDCOMMAND;
    st->value_p = p_TIME;
  }
  { // 67639 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.INCOMMAND_ALG
    st = getVariable(67639);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.INCOMMAND_ALG", 62);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_WORD = (WORD*)&p_STRUCT_KRAN->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 67640 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.INCOMMAND_ARM
    st = getVariable(67640);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.INCOMMAND_ARM", 62);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_WORD = (WORD*)&p_STRUCT_KRAN->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 67641 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.CMDON
    st = getVariable(67641);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.CMDON", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->CMDON;
    st->value_p = p_BOOL;
  }
  { // 67642 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.CMDOFF
    st = getVariable(67642);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.CMDOFF", 55);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->CMDOFF;
    st->value_p = p_BOOL;
  }
  { // 67643 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.RELIABILITY
    st = getVariable(67643);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.IM.RELIABILITY", 60);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_KRAN = (STRUCT_KRAN*)&p_FB_PH_KRAN->IM;
    p_BOOL = (BOOL*)&p_STRUCT_KRAN->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 67644 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.STRPH.RUN
    st = getVariable(67644);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.STRPH.RUN", 55);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_KRAN->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->RUN;
    st->value_p = p_BOOL;
  }
  { // 67645 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.STRPH.RESET
    st = getVariable(67645);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.STRPH.RESET", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_KRAN->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->RESET;
    st->value_p = p_BOOL;
  }
  { // 67646 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.STRPH.START
    st = getVariable(67646);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.STRPH.START", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_KRAN->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->START;
    st->value_p = p_BOOL;
  }
  { // 67647 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.STRPH.ERROR
    st = getVariable(67647);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.STRPH.ERROR", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_KRAN->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->ERROR;
    st->value_p = p_BOOL;
  }
  { // 67648 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.STRPH.TOP
    st = getVariable(67648);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.STRPH.TOP", 55);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_KRAN->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->TOP;
    st->value_p = p_BOOL;
  }
  { // 67649 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.STRPH.STARTSTATUS
    st = getVariable(67649);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.STRPH.STARTSTATUS", 63);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_KRAN->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->STARTSTATUS;
    st->value_p = p_DWORD;
  }
  { // 67650 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.STRPH.ERRORSTATUS
    st = getVariable(67650);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.STRPH.ERRORSTATUS", 63);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_KRAN->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->ERRORSTATUS;
    st->value_p = p_DWORD;
  }
  { // 67651 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.STRPH.TOPSTATUS
    st = getVariable(67651);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.STRPH.TOPSTATUS", 61);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_KRAN->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->TOPSTATUS;
    st->value_p = p_DWORD;
  }
  { // 67652 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.PHASENUMBER
    st = getVariable(67652);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.PHASENUMBER", 57);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_UINT = (UINT*)&p_FB_PH_KRAN->PHASENUMBER;
    UnpackVar(p_UINT, UINT_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 67653 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.COMMANDFAULT_TRIG.CLK
    st = getVariable(67653);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.COMMANDFAULT_TRIG.CLK", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_KRAN->COMMANDFAULT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 67654 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.COMMANDFAULT_TRIG.Q
    st = getVariable(67654);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.COMMANDFAULT_TRIG.Q", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_KRAN->COMMANDFAULT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 67655 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.COMMANDFAULT_TRIG
    st = getVariable(67655);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.COMMANDFAULT_TRIG", 63);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_KRAN->COMMANDFAULT_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 67656 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.RESET_TRIG.CLK
    st = getVariable(67656);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.RESET_TRIG.CLK", 60);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_KRAN->RESET_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 67657 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.RESET_TRIG.Q
    st = getVariable(67657);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.RESET_TRIG.Q", 58);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_KRAN->RESET_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 67658 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.RESET_TRIG
    st = getVariable(67658);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN.RESET_TRIG", 56);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_KRAN->RESET_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 67659 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN._STATUSDUALINPUT.STATUS_NOTDEFINED
    st = getVariable(67659);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN._STATUSDUALINPUT.STATUS_NOTDEFINED", 80);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_KRAN->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_NOTDEFINED;
    st->value_p = p_BYTE;
  }
  { // 67660 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN._STATUSDUALINPUT.STATUS_ON
    st = getVariable(67660);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN._STATUSDUALINPUT.STATUS_ON", 72);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_KRAN->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ON;
    st->value_p = p_BYTE;
  }
  { // 67661 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN._STATUSDUALINPUT.STATUS_OFF
    st = getVariable(67661);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN._STATUSDUALINPUT.STATUS_OFF", 73);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_KRAN->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_OFF;
    st->value_p = p_BYTE;
  }
  { // 67662 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN._STATUSDUALINPUT.STATUS_TRANSITIONAL
    st = getVariable(67662);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN._STATUSDUALINPUT.STATUS_TRANSITIONAL", 82);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_KRAN->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_TRANSITIONAL;
    st->value_p = p_BYTE;
  }
  { // 67663 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN._STATUSDUALINPUT.STATUS_ERROR
    st = getVariable(67663);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_KRAN6OPEN._STATUSDUALINPUT.STATUS_ERROR", 75);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_KRAN = (FB_PH_KRAN*)&p_AOALG->FB_KRAN6OPEN;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_KRAN->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ERROR;
    st->value_p = p_BYTE;
  }

  return 0;
}

// clang-format on
