// clang-format off

#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include "POUS.h"
#include <beremiz/beremiz.h>

#include "iec_types_all.h"
#include "config1.h"

extern PROGRAM0 RESOURCE1__INSTANCE0;

#ifdef DEBUG_PLC
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err][%s:%d]: " _PRNTMSG "\n", __func__, __LINE__, ##__VA_ARGS__)
#else
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err]: " _PRNTMSG "\n", ##__VA_ARGS__)
#endif // DEBUG_PLC

void UnpackVar(void* varp, __IEC_types_enum vartype, void **value_p, void **f_value_p, uint8_t **flags);

int __variables_init_FB_SRAB_BEAO(){
  iec_var_t *st;

  PROGRAM0 *p_PROGRAM0;
  LREAL *p_LREAL;
  ULINT *p_ULINT;
  REAL *p_REAL;
  FB_TIMINGS *p_FB_TIMINGS;
  BOOL *p_BOOL;
  UINT *p_UINT;
  PROC_AI_INIT *p_PROC_AI_INIT;
  FB_AI_INIT *p_FB_AI_INIT;
  TIME *p_TIME;
  STRUCT_AI *p_STRUCT_AI;
  DWORD *p_DWORD;
  BYTE *p_BYTE;
  WORD *p_WORD;
  AICONFIG *p_AICONFIG;
  PROC_AI *p_PROC_AI;
  FB_AISOURCEMLP *p_FB_AISOURCEMLP;
  TITEMAIN *p_TITEMAIN;
  TITEMDIN *p_TITEMDIN;
  TYPE_STATUSAI *p_TYPE_STATUSAI;
  TYPE_COMMANDANALOG *p_TYPE_COMMANDANALOG;
  FB_SUNPACKERCOMMAND *p_FB_SUNPACKERCOMMAND;
  TYPE_ANALOGLIMITFLAGS *p_TYPE_ANALOGLIMITFLAGS;
  TON *p_TON;
  R_TRIG *p_R_TRIG;
  FB_AISOURCEMLP_TIMER *p_FB_AISOURCEMLP_TIMER;
  PROC_AO_INIT *p_PROC_AO_INIT;
  FB_AO_INIT *p_FB_AO_INIT;
  STRUCT_AO *p_STRUCT_AO;
  AOCONFIG *p_AOCONFIG;
  PROC_AO *p_PROC_AO;
  FB_AOSOURCEMLP *p_FB_AOSOURCEMLP;
  TDOUBLEDATA *p_TDOUBLEDATA;
  PROC_DI_INIT *p_PROC_DI_INIT;
  FB_DI_INIT *p_FB_DI_INIT;
  STRUCT_DI *p_STRUCT_DI;
  __IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t *p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t;
  TYPE_RELIABLEBIT *p_TYPE_RELIABLEBIT;
  DICONFIG *p_DICONFIG;
  PROC_DI *p_PROC_DI;
  FB_DISOURCEMLP *p_FB_DISOURCEMLP;
  INT *p_INT;
  UDINT *p_UDINT;
  PROC_DO_INIT *p_PROC_DO_INIT;
  FB_DO_INIT *p_FB_DO_INIT;
  STRUCT_DO *p_STRUCT_DO;
  __IEC___ARRAY_OF_BOOL_16_t *p___IEC___ARRAY_OF_BOOL_16_t;
  DOCONFIG *p_DOCONFIG;
  PROC_DO *p_PROC_DO;
  FB_DOSOURCEMLP *p_FB_DOSOURCEMLP;
  TWORDDATA *p_TWORDDATA;
  OPC_PROTECTIONS_GET *p_OPC_PROTECTIONS_GET;
  PROTECTIONSCONFIG *p_PROTECTIONSCONFIG;
  STRUCT_AIPROTECTION *p_STRUCT_AIPROTECTION;
  STRUCT_DIPROTECTION *p_STRUCT_DIPROTECTION;
  OPC_PROTECTIONS_SET *p_OPC_PROTECTIONS_SET;
  OPC_ALGORITMS_SET *p_OPC_ALGORITMS_SET;
  ALGORITMSCONFIG *p_ALGORITMSCONFIG;
  STRUCT_ALG *p_STRUCT_ALG;
  STRUCT_ALGORITMSMANAGER *p_STRUCT_ALGORITMSMANAGER;
  STRUCT_PROTECTIONSMANAGER *p_STRUCT_PROTECTIONSMANAGER;
  STRUCT_ALGTIMERS *p_STRUCT_ALGTIMERS;
  ALGORITMSQUESTIONS *p_ALGORITMSQUESTIONS;
  STRUCT_QUESTION *p_STRUCT_QUESTION;
  OPC_ALGORITMS_GET *p_OPC_ALGORITMS_GET;
  PROC_IM_INIT *p_PROC_IM_INIT;
  FB_KRAN_INIT *p_FB_KRAN_INIT;
  STRUCT_KRAN *p_STRUCT_KRAN;
  FB_SWITCH_INIT *p_FB_SWITCH_INIT;
  STRUCT_SWITCH *p_STRUCT_SWITCH;
  FB_OILPUMP_INIT *p_FB_OILPUMP_INIT;
  STRUCT_OILPUMP *p_STRUCT_OILPUMP;
  FB_SECTIONSWITCH_INIT *p_FB_SECTIONSWITCH_INIT;
  STRUCT_SECTIONSWITCH *p_STRUCT_SECTIONSWITCH;
  FB_ANALOGPARAMETR_INIT *p_FB_ANALOGPARAMETR_INIT;
  STRUCT_ANALOGPARAMETR *p_STRUCT_ANALOGPARAMETR;
  FB_DISCRETPARAMETR_INIT *p_FB_DISCRETPARAMETR_INIT;
  STRUCT_DISCRETPARAMETR *p_STRUCT_DISCRETPARAMETR;
  FB_SINGLESIGNAL_INIT *p_FB_SINGLESIGNAL_INIT;
  STRUCT_SINGLESIGNAL *p_STRUCT_SINGLESIGNAL;
  FB_SINGLEOUTPUT_INIT *p_FB_SINGLEOUTPUT_INIT;
  STRUCT_SINGLEOUTPUT *p_STRUCT_SINGLEOUTPUT;
  IMCONFIG *p_IMCONFIG;
  STRUCT_RESERVEIM *p_STRUCT_RESERVEIM;
  STRUCT_RESERVEIM2 *p_STRUCT_RESERVEIM2;
  IM_SINGLESIGNALS *p_IM_SINGLESIGNALS;
  IM_SINGLEOUTPUTS *p_IM_SINGLEOUTPUTS;
  PROC_IM *p_PROC_IM;
  FB_KRAN *p_FB_KRAN;
  TYPE_STATUSDUALINPUT *p_TYPE_STATUSDUALINPUT;
  TYPE_COMMANDDUALINPUT *p_TYPE_COMMANDDUALINPUT;
  TOF *p_TOF;
  FB_OILPUMP *p_FB_OILPUMP;
  FB_SWITCH *p_FB_SWITCH;
  FB_SECTIONSWITCH *p_FB_SECTIONSWITCH;
  TYPE_BASKETSTATS *p_TYPE_BASKETSTATS;
  FB_MEANDR *p_FB_MEANDR;
  FB_SINGLESIGNAL *p_FB_SINGLESIGNAL;
  FB_SINGLEOUTPUT *p_FB_SINGLEOUTPUT;
  FB_DISCRETPARAMETR *p_FB_DISCRETPARAMETR;
  FB_ANALOGPARAMETR *p_FB_ANALOGPARAMETR;
  OPC_IM_GET *p_OPC_IM_GET;
  OPC_IM_SET *p_OPC_IM_SET;
  PROC_PROTECTIONS_INIT *p_PROC_PROTECTIONS_INIT;
  FB_DIPROTECTION_INIT *p_FB_DIPROTECTION_INIT;
  FB_AIPROTECTION_INIT *p_FB_AIPROTECTION_INIT;
  TYPE_PROTECTIONTAGS *p_TYPE_PROTECTIONTAGS;
  PROC_PROTECTION *p_PROC_PROTECTION;
  FB_DIPROTECTION *p_FB_DIPROTECTION;
  F_TRIG *p_F_TRIG;
  FB_MVPROTECTION *p_FB_MVPROTECTION;
  FB_KRANOPENPROTECTION *p_FB_KRANOPENPROTECTION;
  FB_AIPROTECTION *p_FB_AIPROTECTION;
  PROC_ALGORITMS *p_PROC_ALGORITMS;
  REMONTALG *p_REMONTALG;
  TYPE_MODEGPA *p_TYPE_MODEGPA;
  TYPE_COMMANDSPOTECTIONSMANAGER *p_TYPE_COMMANDSPOTECTIONSMANAGER;
  TESTPROTECTIONALG *p_TESTPROTECTIONALG;
  TESTIMALG *p_TESTIMALG;
  FB_AUTOTENALG *p_FB_AUTOTENALG;
  FB_AUTOPNSALG *p_FB_AUTOPNSALG;
  FB_AUTOAVOMALG *p_FB_AUTOAVOMALG;
  FB_VIBEGPNSALG *p_FB_VIBEGPNSALG;
  STRUCT_PHASEALGORITM *p_STRUCT_PHASEALGORITM;
  FB_PH_ALGORITM *p_FB_PH_ALGORITM;
  FB_PH_TIMER *p_FB_PH_TIMER;
  FB_QUESTION *p_FB_QUESTION;
  TYPE_ANSWERS *p_TYPE_ANSWERS;
  FB_PH_SWITCH *p_FB_PH_SWITCH;
  FB_PH_CUSTOMPHASE *p_FB_PH_CUSTOMPHASE;
  FB_AUTONUALG *p_FB_AUTONUALG;
  FB_PUSKOILSYSTEMALG *p_FB_PUSKOILSYSTEMALG;
  FB_PH_WAITANALOGVALUE *p_FB_PH_WAITANALOGVALUE;
  FB_PH_OILPUMP *p_FB_PH_OILPUMP;
  FB_ANTIPOMPAGALG *p_FB_ANTIPOMPAGALG;
  FB_TABLEVALUE_MIN *p_FB_TABLEVALUE_MIN;
  __IEC___ARRAY_OF_TYPE_TABLEREC_9_t *p___IEC___ARRAY_OF_TYPE_TABLEREC_9_t;
  TYPE_TABLEREC *p_TYPE_TABLEREC;
  FB_TABLEVALUE_MAX *p_FB_TABLEVALUE_MAX;
  FB_RASHODALG *p_FB_RASHODALG;
  FB_ZAPASALG *p_FB_ZAPASALG;
  NOALG *p_NOALG;
  FB_PH_KRAN *p_FB_PH_KRAN;
  FB_PH_SECTIONSWITCH *p_FB_PH_SECTIONSWITCH;
  AOALG *p_AOALG;
  PPUALG *p_PPUALG;
  FILLINGALG *p_FILLINGALG;
  FB_PH_DIPROTECTION *p_FB_PH_DIPROTECTION;
  ENGINERUNALG *p_ENGINERUNALG;
  PUSKKALG *p_PUSKKALG;
  PUSKVALG *p_PUSKVALG;
  TESTDPMGALG *p_TESTDPMGALG;
  TESTPMSALG *p_TESTPMSALG;
  FB_PH_AIPROTECTION *p_FB_PH_AIPROTECTION;
  APUSKALG *p_APUSKALG;
  SEMIAUTOPUSKALG *p_SEMIAUTOPUSKALG;
  FB_ALGORITMSMANAGER *p_FB_ALGORITMSMANAGER;
  FB_PROTECTIONSMANAGER *p_FB_PROTECTIONSMANAGER;

  { // 31506 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.DI.RELIABILITY
    st = getVariable(31506);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.DI.RELIABILITY", 53);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_SINGLESIGNAL = (STRUCT_SINGLESIGNAL*)&p_FB_DIPROTECTION->DI;
    p_BOOL = (BOOL*)&p_STRUCT_SINGLESIGNAL->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 31507 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.DI.INVERSE
    st = getVariable(31507);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.DI.INVERSE", 49);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_SINGLESIGNAL = (STRUCT_SINGLESIGNAL*)&p_FB_DIPROTECTION->DI;
    p_BOOL = (BOOL*)&p_STRUCT_SINGLESIGNAL->INVERSE;
    st->value_p = p_BOOL;
  }
  { // 31508 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.DI.DELAYON
    st = getVariable(31508);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.DI.DELAYON", 49);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_SINGLESIGNAL = (STRUCT_SINGLESIGNAL*)&p_FB_DIPROTECTION->DI;
    p_TIME = (TIME*)&p_STRUCT_SINGLESIGNAL->DELAYON;
    st->value_p = p_TIME;
  }
  { // 31509 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.DI.DELAYOFF
    st = getVariable(31509);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.DI.DELAYOFF", 50);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_SINGLESIGNAL = (STRUCT_SINGLESIGNAL*)&p_FB_DIPROTECTION->DI;
    p_TIME = (TIME*)&p_STRUCT_SINGLESIGNAL->DELAYOFF;
    st->value_p = p_TIME;
  }
  { // 31510 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.DI.Q
    st = getVariable(31510);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.DI.Q", 43);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_SINGLESIGNAL = (STRUCT_SINGLESIGNAL*)&p_FB_DIPROTECTION->DI;
    p_BOOL = (BOOL*)&p_STRUCT_SINGLESIGNAL->Q;
    st->value_p = p_BOOL;
  }
  { // 31511 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.DI.STATUS
    st = getVariable(31511);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.DI.STATUS", 48);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_SINGLESIGNAL = (STRUCT_SINGLESIGNAL*)&p_FB_DIPROTECTION->DI;
    p_DWORD = (DWORD*)&p_STRUCT_SINGLESIGNAL->STATUS;
    st->value_p = p_DWORD;
  }
  { // 31512 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.DI.DISABLED_SIG
    st = getVariable(31512);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.DI.DISABLED_SIG", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_SINGLESIGNAL = (STRUCT_SINGLESIGNAL*)&p_FB_DIPROTECTION->DI;
    p_BOOL = (BOOL*)&p_STRUCT_SINGLESIGNAL->DISABLED_SIG;
    st->value_p = p_BOOL;
  }
  { // 31513 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.DELAY
    st = getVariable(31513);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.DELAY", 51);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_TIME = (TIME*)&p_STRUCT_DIPROTECTION->DELAY;
    st->value_p = p_TIME;
  }
  { // 31514 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.INTAG
    st = getVariable(31514);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.INTAG", 51);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BYTE = (BYTE*)&p_STRUCT_DIPROTECTION->INTAG;
    st->value_p = p_BYTE;
  }
  { // 31515 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.INRUNONSTART
    st = getVariable(31515);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.INRUNONSTART", 58);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->INRUNONSTART;
    st->value_p = p_BOOL;
  }
  { // 31516 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.INCANRUN
    st = getVariable(31516);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.INCANRUN", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->INCANRUN;
    st->value_p = p_BOOL;
  }
  { // 31517 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.INOPCCOMMANDSDISABLED
    st = getVariable(31517);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.INOPCCOMMANDSDISABLED", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 31518 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.INCOMMAND
    st = getVariable(31518);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.INCOMMAND", 55);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_WORD = (WORD*)&p_STRUCT_DIPROTECTION->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 31519 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.INCOMMAND_ALG
    st = getVariable(31519);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.INCOMMAND_ALG", 59);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_WORD = (WORD*)&p_STRUCT_DIPROTECTION->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 31520 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.INCOMMAND_ARM
    st = getVariable(31520);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.INCOMMAND_ARM", 59);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_WORD = (WORD*)&p_STRUCT_DIPROTECTION->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 31521 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.TAG
    st = getVariable(31521);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.TAG", 49);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BYTE = (BYTE*)&p_STRUCT_DIPROTECTION->TAG;
    st->value_p = p_BYTE;
  }
  { // 31522 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.STATUS
    st = getVariable(31522);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.STATUS", 52);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_DWORD = (DWORD*)&p_STRUCT_DIPROTECTION->STATUS;
    st->value_p = p_DWORD;
  }
  { // 31523 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.CANRUN
    st = getVariable(31523);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.CANRUN", 52);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->CANRUN;
    st->value_p = p_BOOL;
  }
  { // 31524 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.OPCCOMMANDSDISABLED
    st = getVariable(31524);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.OPCCOMMANDSDISABLED", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 31525 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.ISRUNNING
    st = getVariable(31525);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.ISRUNNING", 55);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->ISRUNNING;
    st->value_p = p_BOOL;
  }
  { // 31526 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.HASERROR
    st = getVariable(31526);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.HASERROR", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->HASERROR;
    st->value_p = p_BOOL;
  }
  { // 31527 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.ISENDED
    st = getVariable(31527);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.ISENDED", 53);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->ISENDED;
    st->value_p = p_BOOL;
  }
  { // 31528 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.REMONT
    st = getVariable(31528);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.REMONT", 52);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->REMONT;
    st->value_p = p_BOOL;
  }
  { // 31529 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.CHECK
    st = getVariable(31529);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.CHECK", 51);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->CHECK;
    st->value_p = p_BOOL;
  }
  { // 31530 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.SIGNALING
    st = getVariable(31530);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.SIGNALING", 55);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->SIGNALING;
    st->value_p = p_BOOL;
  }
  { // 31531 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.SIGNALINGTP
    st = getVariable(31531);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.SIGNALINGTP", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->SIGNALINGTP;
    st->value_p = p_BOOL;
  }
  { // 31532 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.RUNONSTART
    st = getVariable(31532);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.STRDIP.RUNONSTART", 56);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->RUNONSTART;
    st->value_p = p_BOOL;
  }
  { // 31537 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO._PROTECTIONTAGS.NOTHING
    st = getVariable(31537);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO._PROTECTIONTAGS.NOTHING", 62);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_TYPE_PROTECTIONTAGS = (TYPE_PROTECTIONTAGS*)&p_FB_DIPROTECTION->_PROTECTIONTAGS;
    p_BYTE = (BYTE*)&p_TYPE_PROTECTIONTAGS->NOTHING;
    st->value_p = p_BYTE;
  }
  { // 31538 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO._PROTECTIONTAGS.AOB
    st = getVariable(31538);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO._PROTECTIONTAGS.AOB", 58);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_TYPE_PROTECTIONTAGS = (TYPE_PROTECTIONTAGS*)&p_FB_DIPROTECTION->_PROTECTIONTAGS;
    p_BYTE = (BYTE*)&p_TYPE_PROTECTIONTAGS->AOB;
    st->value_p = p_BYTE;
  }
  { // 31539 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO._PROTECTIONTAGS.AOS
    st = getVariable(31539);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO._PROTECTIONTAGS.AOS", 58);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_TYPE_PROTECTIONTAGS = (TYPE_PROTECTIONTAGS*)&p_FB_DIPROTECTION->_PROTECTIONTAGS;
    p_BYTE = (BYTE*)&p_TYPE_PROTECTIONTAGS->AOS;
    st->value_p = p_BYTE;
  }
  { // 31540 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO._PROTECTIONTAGS.AOPOJ
    st = getVariable(31540);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO._PROTECTIONTAGS.AOPOJ", 60);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_TYPE_PROTECTIONTAGS = (TYPE_PROTECTIONTAGS*)&p_FB_DIPROTECTION->_PROTECTIONTAGS;
    p_BYTE = (BYTE*)&p_TYPE_PROTECTIONTAGS->AOPOJ;
    st->value_p = p_BYTE;
  }
  { // 31541 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO._SIGNALINGTP.IN
    st = getVariable(31541);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO._SIGNALINGTP.IN", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_TOF = (TOF*)&p_FB_DIPROTECTION->_SIGNALINGTP;
    p_BOOL = (BOOL*)&p_TOF->IN;
    st->value_p = p_BOOL;
  }
  { // 31542 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO._SIGNALINGTP.PT
    st = getVariable(31542);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO._SIGNALINGTP.PT", 54);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_TOF = (TOF*)&p_FB_DIPROTECTION->_SIGNALINGTP;
    p_TIME = (TIME*)&p_TOF->PT;
    st->value_p = p_TIME;
  }
  { // 31543 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO._SIGNALINGTP.Q
    st = getVariable(31543);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO._SIGNALINGTP.Q", 53);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_TOF = (TOF*)&p_FB_DIPROTECTION->_SIGNALINGTP;
    p_BOOL = (BOOL*)&p_TOF->Q;
    st->value_p = p_BOOL;
  }
  { // 31544 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO._SIGNALINGTP.ET
    st = getVariable(31544);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO._SIGNALINGTP.ET", 54);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_TOF = (TOF*)&p_FB_DIPROTECTION->_SIGNALINGTP;
    p_TIME = (TIME*)&p_TOF->ET;
    st->value_p = p_TIME;
  }
  { // 31545 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO._SIGNALINGTP
    st = getVariable(31545);
    memcpy(st->IEC_TYPE, "TOF", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO._SIGNALINGTP", 51);
    st->size_data = sizeof(TOF);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_TOF = (TOF*)&p_FB_DIPROTECTION->_SIGNALINGTP;
    st->value_p = (void *)p_TOF;
  }
  { // 31546 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.TIMER.IN
    st = getVariable(31546);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.TIMER.IN", 47);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_TON = (TON*)&p_FB_DIPROTECTION->TIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 31547 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.TIMER.PT
    st = getVariable(31547);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.TIMER.PT", 47);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_TON = (TON*)&p_FB_DIPROTECTION->TIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 31548 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.TIMER.Q
    st = getVariable(31548);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.TIMER.Q", 46);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_TON = (TON*)&p_FB_DIPROTECTION->TIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 31549 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.TIMER.ET
    st = getVariable(31549);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.TIMER.ET", 47);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_TON = (TON*)&p_FB_DIPROTECTION->TIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 31550 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.TIMER
    st = getVariable(31550);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.TIMER", 44);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_TON = (TON*)&p_FB_DIPROTECTION->TIMER;
    st->value_p = (void *)p_TON;
  }
  { // 31551 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SIGNALINGTRIG.CLK
    st = getVariable(31551);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SIGNALINGTRIG.CLK", 56);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_R_TRIG = (R_TRIG*)&p_FB_DIPROTECTION->SIGNALINGTRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 31552 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SIGNALINGTRIG.Q
    st = getVariable(31552);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SIGNALINGTRIG.Q", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_R_TRIG = (R_TRIG*)&p_FB_DIPROTECTION->SIGNALINGTRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 31553 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SIGNALINGTRIG
    st = getVariable(31553);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SIGNALINGTRIG", 52);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_R_TRIG = (R_TRIG*)&p_FB_DIPROTECTION->SIGNALINGTRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 31554 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SIGNALINGFTRIG.CLK
    st = getVariable(31554);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SIGNALINGFTRIG.CLK", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_F_TRIG = (F_TRIG*)&p_FB_DIPROTECTION->SIGNALINGFTRIG;
    p_BOOL = (BOOL*)&p_F_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 31555 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SIGNALINGFTRIG.Q
    st = getVariable(31555);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SIGNALINGFTRIG.Q", 55);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_F_TRIG = (F_TRIG*)&p_FB_DIPROTECTION->SIGNALINGFTRIG;
    p_BOOL = (BOOL*)&p_F_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 31556 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SIGNALINGFTRIG
    st = getVariable(31556);
    memcpy(st->IEC_TYPE, "F_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SIGNALINGFTRIG", 53);
    st->size_data = sizeof(F_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_F_TRIG = (F_TRIG*)&p_FB_DIPROTECTION->SIGNALINGFTRIG;
    st->value_p = (void *)p_F_TRIG;
  }
  { // 31557 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SIGNALINGDI
    st = getVariable(31557);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SIGNALINGDI", 50);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_BOOL = (BOOL*)&p_FB_DIPROTECTION->SIGNALINGDI;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 31558 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SOURCE
    st = getVariable(31558);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SOURCE", 45);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_BYTE = (BYTE*)&p_FB_DIPROTECTION->SOURCE;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 31559 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.CMD
    st = getVariable(31559);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.CMD", 42);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_BYTE = (BYTE*)&p_FB_DIPROTECTION->CMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 31560 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.LASTCMD
    st = getVariable(31560);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.LASTCMD", 46);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_BYTE = (BYTE*)&p_FB_DIPROTECTION->LASTCMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 31561 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SOURCE_FOR_STATUS
    st = getVariable(31561);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SOURCE_FOR_STATUS", 56);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_BYTE = (BYTE*)&p_FB_DIPROTECTION->SOURCE_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 31562 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.CMD_FOR_STATUS
    st = getVariable(31562);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.CMD_FOR_STATUS", 53);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_BYTE = (BYTE*)&p_FB_DIPROTECTION->CMD_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 31563 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.COMMAND_ERROR_FOR_STATUS
    st = getVariable(31563);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.COMMAND_ERROR_FOR_STATUS", 63);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_BYTE = (BYTE*)&p_FB_DIPROTECTION->COMMAND_ERROR_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 31564 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.RESETCMDTIMER.IN
    st = getVariable(31564);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.RESETCMDTIMER.IN", 55);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_TON = (TON*)&p_FB_DIPROTECTION->RESETCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 31565 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.RESETCMDTIMER.PT
    st = getVariable(31565);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.RESETCMDTIMER.PT", 55);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_TON = (TON*)&p_FB_DIPROTECTION->RESETCMDTIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 31566 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.RESETCMDTIMER.Q
    st = getVariable(31566);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.RESETCMDTIMER.Q", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_TON = (TON*)&p_FB_DIPROTECTION->RESETCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 31567 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.RESETCMDTIMER.ET
    st = getVariable(31567);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.RESETCMDTIMER.ET", 55);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_TON = (TON*)&p_FB_DIPROTECTION->RESETCMDTIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 31568 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.RESETCMDTIMER
    st = getVariable(31568);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.RESETCMDTIMER", 52);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_TON = (TON*)&p_FB_DIPROTECTION->RESETCMDTIMER;
    st->value_p = (void *)p_TON;
  }
  { // 31569 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.RESETCMDTIMERPRIZNAK
    st = getVariable(31569);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.RESETCMDTIMERPRIZNAK", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_BOOL = (BOOL*)&p_FB_DIPROTECTION->RESETCMDTIMERPRIZNAK;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 31570 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SIGNALINTIMER.IN
    st = getVariable(31570);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SIGNALINTIMER.IN", 55);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_TON = (TON*)&p_FB_DIPROTECTION->SIGNALINTIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 31571 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SIGNALINTIMER.PT
    st = getVariable(31571);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SIGNALINTIMER.PT", 55);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_TON = (TON*)&p_FB_DIPROTECTION->SIGNALINTIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 31572 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SIGNALINTIMER.Q
    st = getVariable(31572);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SIGNALINTIMER.Q", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_TON = (TON*)&p_FB_DIPROTECTION->SIGNALINTIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 31573 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SIGNALINTIMER.ET
    st = getVariable(31573);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SIGNALINTIMER.ET", 55);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_TON = (TON*)&p_FB_DIPROTECTION->SIGNALINTIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 31574 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SIGNALINTIMER
    st = getVariable(31574);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.SIGNALINTIMER", 52);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_TON = (TON*)&p_FB_DIPROTECTION->SIGNALINTIMER;
    st->value_p = (void *)p_TON;
  }
  { // 31575 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.RUNONSTART_TRIG.CLK
    st = getVariable(31575);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.RUNONSTART_TRIG.CLK", 58);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_R_TRIG = (R_TRIG*)&p_FB_DIPROTECTION->RUNONSTART_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 31576 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.RUNONSTART_TRIG.Q
    st = getVariable(31576);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.RUNONSTART_TRIG.Q", 56);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_R_TRIG = (R_TRIG*)&p_FB_DIPROTECTION->RUNONSTART_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 31577 PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.RUNONSTART_TRIG
    st = getVariable(31577);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_SRAB_BEAO.RUNONSTART_TRIG", 54);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_SRAB_BEAO;
    p_R_TRIG = (R_TRIG*)&p_FB_DIPROTECTION->RUNONSTART_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }

  return 0;
}

// clang-format on
