// clang-format off

#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include "POUS.h"
#include <beremiz/beremiz.h>

#include "iec_types_all.h"
#include "config1.h"

extern PROGRAM0 RESOURCE1__INSTANCE0;

#ifdef DEBUG_PLC
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err][%s:%d]: " _PRNTMSG "\n", __func__, __LINE__, ##__VA_ARGS__)
#else
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err]: " _PRNTMSG "\n", ##__VA_ARGS__)
#endif // DEBUG_PLC

void UnpackVar(void* varp, __IEC_types_enum vartype, void **value_p, void **f_value_p, uint8_t **flags);

int __variables_init_FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2(){
  iec_var_t *st;

  PROGRAM0 *p_PROGRAM0;
  LREAL *p_LREAL;
  ULINT *p_ULINT;
  REAL *p_REAL;
  FB_TIMINGS *p_FB_TIMINGS;
  BOOL *p_BOOL;
  UINT *p_UINT;
  PROC_AI_INIT *p_PROC_AI_INIT;
  FB_AI_INIT *p_FB_AI_INIT;
  STRUCT_AI *p_STRUCT_AI;
  DWORD *p_DWORD;
  BYTE *p_BYTE;
  WORD *p_WORD;
  TIME *p_TIME;
  AICONFIG *p_AICONFIG;
  PROC_AI *p_PROC_AI;
  FB_AISOURCEMLP *p_FB_AISOURCEMLP;
  TITEMAIN *p_TITEMAIN;
  TITEMDIN *p_TITEMDIN;
  TYPE_STATUSAI *p_TYPE_STATUSAI;
  TYPE_COMMANDANALOG *p_TYPE_COMMANDANALOG;
  FB_SUNPACKERCOMMAND *p_FB_SUNPACKERCOMMAND;
  TYPE_ANALOGLIMITFLAGS *p_TYPE_ANALOGLIMITFLAGS;
  TON *p_TON;
  R_TRIG *p_R_TRIG;
  FB_AISOURCEMLP_TIMER *p_FB_AISOURCEMLP_TIMER;
  PROC_AO_INIT *p_PROC_AO_INIT;
  FB_AO_INIT *p_FB_AO_INIT;
  STRUCT_AO *p_STRUCT_AO;
  AOCONFIG *p_AOCONFIG;
  PROC_AO *p_PROC_AO;
  FB_AOSOURCEMLP *p_FB_AOSOURCEMLP;
  TDOUBLEDATA *p_TDOUBLEDATA;
  PROC_DI_INIT *p_PROC_DI_INIT;
  FB_DI_INIT *p_FB_DI_INIT;
  STRUCT_DI *p_STRUCT_DI;
  __IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t *p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t;
  TYPE_RELIABLEBIT *p_TYPE_RELIABLEBIT;
  DICONFIG *p_DICONFIG;
  PROC_DI *p_PROC_DI;
  FB_DISOURCEMLP *p_FB_DISOURCEMLP;
  INT *p_INT;
  UDINT *p_UDINT;
  PROC_DO_INIT *p_PROC_DO_INIT;
  FB_DO_INIT *p_FB_DO_INIT;
  STRUCT_DO *p_STRUCT_DO;
  DOCONFIG *p_DOCONFIG;
  PROC_DO *p_PROC_DO;
  FB_DOSOURCEMLP *p_FB_DOSOURCEMLP;
  TWORDDATA *p_TWORDDATA;
  OPC_ALGORITMS_SET *p_OPC_ALGORITMS_SET;
  ALGORITMSCONFIG *p_ALGORITMSCONFIG;
  STRUCT_ALG *p_STRUCT_ALG;
  STRUCT_ALGORITMSMANAGER *p_STRUCT_ALGORITMSMANAGER;
  STRUCT_PROTECTIONSMANAGER *p_STRUCT_PROTECTIONSMANAGER;
  STRUCT_ALGTIMERS *p_STRUCT_ALGTIMERS;
  ALGORITMSQUESTIONS *p_ALGORITMSQUESTIONS;
  STRUCT_QUESTION *p_STRUCT_QUESTION;
  OPC_ALGORITMS_GET *p_OPC_ALGORITMS_GET;
  PROC_IM_INIT *p_PROC_IM_INIT;
  FB_KRAN_INIT *p_FB_KRAN_INIT;
  STRUCT_KRAN *p_STRUCT_KRAN;
  FB_SWITCH_INIT *p_FB_SWITCH_INIT;
  STRUCT_SWITCH *p_STRUCT_SWITCH;
  FB_OILPUMP_INIT *p_FB_OILPUMP_INIT;
  STRUCT_OILPUMP *p_STRUCT_OILPUMP;
  FB_SECTIONSWITCH_INIT *p_FB_SECTIONSWITCH_INIT;
  STRUCT_SECTIONSWITCH *p_STRUCT_SECTIONSWITCH;
  FB_ANALOGPARAMETR_INIT *p_FB_ANALOGPARAMETR_INIT;
  STRUCT_ANALOGPARAMETR *p_STRUCT_ANALOGPARAMETR;
  FB_DISCRETPARAMETR_INIT *p_FB_DISCRETPARAMETR_INIT;
  STRUCT_DISCRETPARAMETR *p_STRUCT_DISCRETPARAMETR;
  FB_SINGLESIGNAL_INIT *p_FB_SINGLESIGNAL_INIT;
  STRUCT_SINGLESIGNAL *p_STRUCT_SINGLESIGNAL;
  FB_SINGLEOUTPUT_INIT *p_FB_SINGLEOUTPUT_INIT;
  STRUCT_SINGLEOUTPUT *p_STRUCT_SINGLEOUTPUT;
  IMCONFIG *p_IMCONFIG;
  STRUCT_RESERVEIM *p_STRUCT_RESERVEIM;
  STRUCT_RESERVEIM2 *p_STRUCT_RESERVEIM2;
  IM_SINGLESIGNALS *p_IM_SINGLESIGNALS;
  IM_SINGLEOUTPUTS *p_IM_SINGLEOUTPUTS;
  PROC_IM *p_PROC_IM;
  FB_KRAN *p_FB_KRAN;
  TYPE_STATUSDUALINPUT *p_TYPE_STATUSDUALINPUT;
  TYPE_COMMANDDUALINPUT *p_TYPE_COMMANDDUALINPUT;
  TOF *p_TOF;
  FB_OILPUMP *p_FB_OILPUMP;
  FB_SWITCH *p_FB_SWITCH;
  FB_SECTIONSWITCH *p_FB_SECTIONSWITCH;
  TYPE_BASKETSTATS *p_TYPE_BASKETSTATS;
  FB_MEANDR *p_FB_MEANDR;
  FB_SINGLESIGNAL *p_FB_SINGLESIGNAL;
  FB_SINGLEOUTPUT *p_FB_SINGLEOUTPUT;
  PROC_PROTECTIONS_INIT *p_PROC_PROTECTIONS_INIT;
  FB_DIPROTECTION_INIT *p_FB_DIPROTECTION_INIT;
  STRUCT_DIPROTECTION *p_STRUCT_DIPROTECTION;
  FB_AIPROTECTION_INIT *p_FB_AIPROTECTION_INIT;
  STRUCT_AIPROTECTION *p_STRUCT_AIPROTECTION;
  PROTECTIONSCONFIG *p_PROTECTIONSCONFIG;
  TYPE_PROTECTIONTAGS *p_TYPE_PROTECTIONTAGS;
  PROC_PROTECTION *p_PROC_PROTECTION;
  FB_MVPROTECTION *p_FB_MVPROTECTION;
  F_TRIG *p_F_TRIG;
  FB_DIPROTECTION *p_FB_DIPROTECTION;
  FB_KRANOPENPROTECTION *p_FB_KRANOPENPROTECTION;
  FB_AIPROTECTION *p_FB_AIPROTECTION;
  PROC_ALGORITMS *p_PROC_ALGORITMS;
  REMONTALG *p_REMONTALG;
  TYPE_MODEGPA *p_TYPE_MODEGPA;
  TYPE_COMMANDSPOTECTIONSMANAGER *p_TYPE_COMMANDSPOTECTIONSMANAGER;
  TESTPROTECTIONALG *p_TESTPROTECTIONALG;
  TESTIMALG *p_TESTIMALG;
  FB_AUTOTENALG *p_FB_AUTOTENALG;
  FB_AUTOPNSALG *p_FB_AUTOPNSALG;
  FB_AUTOAVOMALG *p_FB_AUTOAVOMALG;
  FB_VIBEGPNSALG *p_FB_VIBEGPNSALG;
  STRUCT_PHASEALGORITM *p_STRUCT_PHASEALGORITM;
  FB_PH_ALGORITM *p_FB_PH_ALGORITM;
  FB_PH_TIMER *p_FB_PH_TIMER;
  FB_QUESTION *p_FB_QUESTION;
  TYPE_ANSWERS *p_TYPE_ANSWERS;
  FB_PH_SWITCH *p_FB_PH_SWITCH;
  FB_PH_CUSTOMPHASE *p_FB_PH_CUSTOMPHASE;
  FB_AUTONUALG *p_FB_AUTONUALG;
  FB_PUSKOILSYSTEMALG *p_FB_PUSKOILSYSTEMALG;
  FB_PH_WAITANALOGVALUE *p_FB_PH_WAITANALOGVALUE;
  FB_PH_OILPUMP *p_FB_PH_OILPUMP;
  FB_ANTIPOMPAGALG *p_FB_ANTIPOMPAGALG;
  FB_TABLEVALUE_MIN *p_FB_TABLEVALUE_MIN;
  __IEC___ARRAY_OF_TYPE_TABLEREC_9_t *p___IEC___ARRAY_OF_TYPE_TABLEREC_9_t;
  TYPE_TABLEREC *p_TYPE_TABLEREC;
  FB_TABLEVALUE_MAX *p_FB_TABLEVALUE_MAX;
  FB_RASHODALG *p_FB_RASHODALG;
  FB_ZAPASALG *p_FB_ZAPASALG;
  NOALG *p_NOALG;
  FB_PH_KRAN *p_FB_PH_KRAN;
  FB_PH_SECTIONSWITCH *p_FB_PH_SECTIONSWITCH;
  AOALG *p_AOALG;
  PPUALG *p_PPUALG;
  FILLINGALG *p_FILLINGALG;
  FB_PH_DIPROTECTION *p_FB_PH_DIPROTECTION;
  ENGINERUNALG *p_ENGINERUNALG;
  PUSKKALG *p_PUSKKALG;
  PUSKVALG *p_PUSKVALG;
  TESTDPMGALG *p_TESTDPMGALG;
  TESTPMSALG *p_TESTPMSALG;
  FB_PH_AIPROTECTION *p_FB_PH_AIPROTECTION;
  APUSKALG *p_APUSKALG;
  SEMIAUTOPUSKALG *p_SEMIAUTOPUSKALG;
  FB_ALGORITMSMANAGER *p_FB_ALGORITMSMANAGER;
  FB_PROTECTIONSMANAGER *p_FB_PROTECTIONSMANAGER;

  { // 30192 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.VALUE
    st = getVariable(30192);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.VALUE", 69);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->VALUE;
    st->value_p = p_LREAL;
  }
  { // 30193 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.STATUS
    st = getVariable(30193);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.STATUS", 70);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_DWORD = (DWORD*)&p_STRUCT_AI->STATUS;
    st->value_p = p_DWORD;
  }
  { // 30194 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.INTERVAL
    st = getVariable(30194);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.INTERVAL", 72);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BYTE = (BYTE*)&p_STRUCT_AI->INTERVAL;
    st->value_p = p_BYTE;
  }
  { // 30195 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.INCOMMAND
    st = getVariable(30195);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.INCOMMAND", 73);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 30196 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.BLCONNECT
    st = getVariable(30196);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.BLCONNECT", 73);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->BLCONNECT;
    st->value_p = p_BOOL;
  }
  { // 30197 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DLL
    st = getVariable(30197);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DLL", 67);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLL;
    st->value_p = p_LREAL;
  }
  { // 30198 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DHL
    st = getVariable(30198);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DHL", 67);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHL;
    st->value_p = p_LREAL;
  }
  { // 30199 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DLA
    st = getVariable(30199);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DLA", 67);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLA;
    st->value_p = p_LREAL;
  }
  { // 30200 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DHA
    st = getVariable(30200);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DHA", 67);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHA;
    st->value_p = p_LREAL;
  }
  { // 30201 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DLW
    st = getVariable(30201);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DLW", 67);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLW;
    st->value_p = p_LREAL;
  }
  { // 30202 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DHW
    st = getVariable(30202);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DHW", 67);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHW;
    st->value_p = p_LREAL;
  }
  { // 30203 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.LL
    st = getVariable(30203);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.LL", 66);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LL;
    st->value_p = p_LREAL;
  }
  { // 30204 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.HL
    st = getVariable(30204);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.HL", 66);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HL;
    st->value_p = p_LREAL;
  }
  { // 30205 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.LA
    st = getVariable(30205);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.LA", 66);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LA;
    st->value_p = p_LREAL;
  }
  { // 30206 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.HA
    st = getVariable(30206);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.HA", 66);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HA;
    st->value_p = p_LREAL;
  }
  { // 30207 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.LW
    st = getVariable(30207);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.LW", 66);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LW;
    st->value_p = p_LREAL;
  }
  { // 30208 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.HW
    st = getVariable(30208);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.HW", 66);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HW;
    st->value_p = p_LREAL;
  }
  { // 30209 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.ISVALIDREF_LA
    st = getVariable(30209);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.ISVALIDREF_LA", 77);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_LA;
    st->value_p = p_BOOL;
  }
  { // 30210 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.ISVALIDREF_HA
    st = getVariable(30210);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.ISVALIDREF_HA", 77);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_HA;
    st->value_p = p_BOOL;
  }
  { // 30211 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.ISVALIDREF_LW
    st = getVariable(30211);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.ISVALIDREF_LW", 77);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_LW;
    st->value_p = p_BOOL;
  }
  { // 30212 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.ISVALIDREF_HW
    st = getVariable(30212);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.ISVALIDREF_HW", 77);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_HW;
    st->value_p = p_BOOL;
  }
  { // 30213 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.INPLL
    st = getVariable(30213);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.INPLL", 69);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->INPLL;
    st->value_p = p_LREAL;
  }
  { // 30214 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.INPHL
    st = getVariable(30214);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.INPHL", 69);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->INPHL;
    st->value_p = p_LREAL;
  }
  { // 30215 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.CURRENTSHOTCIRCUIT
    st = getVariable(30215);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.CURRENTSHOTCIRCUIT", 82);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CURRENTSHOTCIRCUIT;
    st->value_p = p_LREAL;
  }
  { // 30216 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.CURRENTBREAKCIRCUIT
    st = getVariable(30216);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.CURRENTBREAKCIRCUIT", 83);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CURRENTBREAKCIRCUIT;
    st->value_p = p_LREAL;
  }
  { // 30217 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.MAXCHANGESPEED
    st = getVariable(30217);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.MAXCHANGESPEED", 78);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXCHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 30218 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.MAXCHANGESPEEDDOWN
    st = getVariable(30218);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.MAXCHANGESPEEDDOWN", 82);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXCHANGESPEEDDOWN;
    st->value_p = p_LREAL;
  }
  { // 30219 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.CHANGESPEED
    st = getVariable(30219);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.CHANGESPEED", 75);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 30220 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.HISTERESIS
    st = getVariable(30220);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.HISTERESIS", 74);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HISTERESIS;
    st->value_p = p_LREAL;
  }
  { // 30221 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.APERTURFILTER
    st = getVariable(30221);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.APERTURFILTER", 77);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->APERTURFILTER;
    st->value_p = p_LREAL;
  }
  { // 30222 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.EXPONENTIALFILTER
    st = getVariable(30222);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.EXPONENTIALFILTER", 81);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->EXPONENTIALFILTER;
    st->value_p = p_LREAL;
  }
  { // 30223 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.RASSOGLASOVANIE
    st = getVariable(30223);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.RASSOGLASOVANIE", 79);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->RASSOGLASOVANIE;
    st->value_p = p_LREAL;
  }
  { // 30224 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.OPCCOMMANDSDISABLED
    st = getVariable(30224);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.OPCCOMMANDSDISABLED", 83);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 30225 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DISABLED_LA
    st = getVariable(30225);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DISABLED_LA", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_LA;
    st->value_p = p_BOOL;
  }
  { // 30226 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DISABLED_HA
    st = getVariable(30226);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DISABLED_HA", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_HA;
    st->value_p = p_BOOL;
  }
  { // 30227 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DISABLED_LW
    st = getVariable(30227);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DISABLED_LW", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_LW;
    st->value_p = p_BOOL;
  }
  { // 30228 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DISABLED_HW
    st = getVariable(30228);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DISABLED_HW", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_HW;
    st->value_p = p_BOOL;
  }
  { // 30229 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DELAYLA
    st = getVariable(30229);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DELAYLA", 71);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYLA;
    st->value_p = p_TIME;
  }
  { // 30230 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DELAYLW
    st = getVariable(30230);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DELAYLW", 71);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYLW;
    st->value_p = p_TIME;
  }
  { // 30231 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DELAYHW
    st = getVariable(30231);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DELAYHW", 71);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYHW;
    st->value_p = p_TIME;
  }
  { // 30232 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DELAYHA
    st = getVariable(30232);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DELAYHA", 71);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYHA;
    st->value_p = p_TIME;
  }
  { // 30233 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.MINVALUE_ISVALIDREF
    st = getVariable(30233);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.MINVALUE_ISVALIDREF", 83);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->MINVALUE_ISVALIDREF;
    st->value_p = p_BOOL;
  }
  { // 30234 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.MAXVALUE_ISVALIDREF
    st = getVariable(30234);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.MAXVALUE_ISVALIDREF", 83);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->MAXVALUE_ISVALIDREF;
    st->value_p = p_BOOL;
  }
  { // 30235 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.MINVALUE
    st = getVariable(30235);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.MINVALUE", 72);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MINVALUE;
    st->value_p = p_LREAL;
  }
  { // 30236 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.MAXVALUE
    st = getVariable(30236);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.MAXVALUE", 72);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXVALUE;
    st->value_p = p_LREAL;
  }
  { // 30237 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.INOPCCOMMANDSDISABLED
    st = getVariable(30237);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.INOPCCOMMANDSDISABLED", 85);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 30238 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.IMIT
    st = getVariable(30238);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.IMIT", 68);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->IMIT;
    st->value_p = p_BOOL;
  }
  { // 30239 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.REMONT
    st = getVariable(30239);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.REMONT", 70);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->REMONT;
    st->value_p = p_BOOL;
  }
  { // 30240 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.NS
    st = getVariable(30240);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.NS", 66);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS;
    st->value_p = p_BOOL;
  }
  { // 30241 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.NS_MIN
    st = getVariable(30241);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.NS_MIN", 70);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS_MIN;
    st->value_p = p_BOOL;
  }
  { // 30242 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.NS_MAX
    st = getVariable(30242);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.NS_MAX", 70);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS_MAX;
    st->value_p = p_BOOL;
  }
  { // 30243 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.INCOMMAND_ALG
    st = getVariable(30243);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.INCOMMAND_ALG", 77);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 30244 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.INCOMMAND_ARM
    st = getVariable(30244);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.INCOMMAND_ARM", 77);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 30245 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DMAXCHANGESPEED
    st = getVariable(30245);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DMAXCHANGESPEED", 79);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DMAXCHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 30246 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DMAXCHANGESPEEDDOWN
    st = getVariable(30246);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.AI.DMAXCHANGESPEEDDOWN", 83);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DMAXCHANGESPEEDDOWN;
    st->value_p = p_LREAL;
  }
  { // 30247 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.CONTROLLIMIT
    st = getVariable(30247);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.CONTROLLIMIT", 80);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BYTE = (BYTE*)&p_STRUCT_AIPROTECTION->CONTROLLIMIT;
    st->value_p = p_BYTE;
  }
  { // 30248 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.DELAY
    st = getVariable(30248);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.DELAY", 73);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_TIME = (TIME*)&p_STRUCT_AIPROTECTION->DELAY;
    st->value_p = p_TIME;
  }
  { // 30249 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.INTAG
    st = getVariable(30249);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.INTAG", 73);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BYTE = (BYTE*)&p_STRUCT_AIPROTECTION->INTAG;
    st->value_p = p_BYTE;
  }
  { // 30250 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.INRUNONSTART
    st = getVariable(30250);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.INRUNONSTART", 80);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->INRUNONSTART;
    st->value_p = p_BOOL;
  }
  { // 30251 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.INCANRUN
    st = getVariable(30251);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.INCANRUN", 76);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->INCANRUN;
    st->value_p = p_BOOL;
  }
  { // 30252 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.INOPCCOMMANDSDISABLED
    st = getVariable(30252);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.INOPCCOMMANDSDISABLED", 89);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 30253 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.INCOMMAND
    st = getVariable(30253);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.INCOMMAND", 77);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_WORD = (WORD*)&p_STRUCT_AIPROTECTION->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 30254 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.INCOMMAND_ALG
    st = getVariable(30254);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.INCOMMAND_ALG", 81);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_WORD = (WORD*)&p_STRUCT_AIPROTECTION->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 30255 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.INCOMMAND_ARM
    st = getVariable(30255);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.INCOMMAND_ARM", 81);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_WORD = (WORD*)&p_STRUCT_AIPROTECTION->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 30256 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.TAG
    st = getVariable(30256);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.TAG", 71);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BYTE = (BYTE*)&p_STRUCT_AIPROTECTION->TAG;
    st->value_p = p_BYTE;
  }
  { // 30257 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.STATUS
    st = getVariable(30257);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.STATUS", 74);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_DWORD = (DWORD*)&p_STRUCT_AIPROTECTION->STATUS;
    st->value_p = p_DWORD;
  }
  { // 30258 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.CANRUN
    st = getVariable(30258);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.CANRUN", 74);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->CANRUN;
    st->value_p = p_BOOL;
  }
  { // 30259 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.OPCCOMMANDSDISABLED
    st = getVariable(30259);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.OPCCOMMANDSDISABLED", 87);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 30260 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.ISRUNNING
    st = getVariable(30260);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.ISRUNNING", 77);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->ISRUNNING;
    st->value_p = p_BOOL;
  }
  { // 30261 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.HASERROR
    st = getVariable(30261);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.HASERROR", 76);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->HASERROR;
    st->value_p = p_BOOL;
  }
  { // 30262 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.ISENDED
    st = getVariable(30262);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.ISENDED", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->ISENDED;
    st->value_p = p_BOOL;
  }
  { // 30263 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.REMONT
    st = getVariable(30263);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.REMONT", 74);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->REMONT;
    st->value_p = p_BOOL;
  }
  { // 30264 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.CHECK
    st = getVariable(30264);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.CHECK", 73);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->CHECK;
    st->value_p = p_BOOL;
  }
  { // 30265 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.SIGNALING
    st = getVariable(30265);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.SIGNALING", 77);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->SIGNALING;
    st->value_p = p_BOOL;
  }
  { // 30266 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.SIGNALINGTP
    st = getVariable(30266);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.SIGNALINGTP", 79);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->SIGNALINGTP;
    st->value_p = p_BOOL;
  }
  { // 30267 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.RUNONSTART
    st = getVariable(30267);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.STRAIP.RUNONSTART", 78);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->RUNONSTART;
    st->value_p = p_BOOL;
  }
  { // 30272 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._SIGNALINGTP.IN
    st = getVariable(30272);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._SIGNALINGTP.IN", 76);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    p_BOOL = (BOOL*)&p_TOF->IN;
    st->value_p = p_BOOL;
  }
  { // 30273 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._SIGNALINGTP.PT
    st = getVariable(30273);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._SIGNALINGTP.PT", 76);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    p_TIME = (TIME*)&p_TOF->PT;
    st->value_p = p_TIME;
  }
  { // 30274 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._SIGNALINGTP.Q
    st = getVariable(30274);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._SIGNALINGTP.Q", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    p_BOOL = (BOOL*)&p_TOF->Q;
    st->value_p = p_BOOL;
  }
  { // 30275 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._SIGNALINGTP.ET
    st = getVariable(30275);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._SIGNALINGTP.ET", 76);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    p_TIME = (TIME*)&p_TOF->ET;
    st->value_p = p_TIME;
  }
  { // 30276 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._SIGNALINGTP
    st = getVariable(30276);
    memcpy(st->IEC_TYPE, "TOF", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._SIGNALINGTP", 73);
    st->size_data = sizeof(TOF);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    st->value_p = (void *)p_TOF;
  }
  { // 30277 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._STATUSAI.NOTDEFINED
    st = getVariable(30277);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._STATUSAI.NOTDEFINED", 81);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NOTDEFINED;
    st->value_p = p_BYTE;
  }
  { // 30278 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._STATUSAI.LL
    st = getVariable(30278);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._STATUSAI.LL", 73);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LL;
    st->value_p = p_BYTE;
  }
  { // 30279 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._STATUSAI.HL
    st = getVariable(30279);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._STATUSAI.HL", 73);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HL;
    st->value_p = p_BYTE;
  }
  { // 30280 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._STATUSAI.NOTRELIABLE
    st = getVariable(30280);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._STATUSAI.NOTRELIABLE", 82);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NOTRELIABLE;
    st->value_p = p_BYTE;
  }
  { // 30281 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._STATUSAI.NORMAL
    st = getVariable(30281);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._STATUSAI.NORMAL", 77);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NORMAL;
    st->value_p = p_BYTE;
  }
  { // 30282 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._STATUSAI.LW
    st = getVariable(30282);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._STATUSAI.LW", 73);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LW;
    st->value_p = p_BYTE;
  }
  { // 30283 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._STATUSAI.HW
    st = getVariable(30283);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._STATUSAI.HW", 73);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HW;
    st->value_p = p_BYTE;
  }
  { // 30284 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._STATUSAI.LA
    st = getVariable(30284);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._STATUSAI.LA", 73);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LA;
    st->value_p = p_BYTE;
  }
  { // 30285 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._STATUSAI.HA
    st = getVariable(30285);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2._STATUSAI.HA", 73);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HA;
    st->value_p = p_BYTE;
  }
  { // 30286 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SOURCE
    st = getVariable(30286);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SOURCE", 67);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->SOURCE;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 30287 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.CMD
    st = getVariable(30287);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.CMD", 64);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->CMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 30288 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.LASTCMD
    st = getVariable(30288);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.LASTCMD", 68);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->LASTCMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 30289 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SOURCE_FOR_STATUS
    st = getVariable(30289);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SOURCE_FOR_STATUS", 78);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->SOURCE_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 30290 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.CMD_FOR_STATUS
    st = getVariable(30290);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.CMD_FOR_STATUS", 75);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->CMD_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 30291 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.COMMAND_ERROR_FOR_STATUS
    st = getVariable(30291);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.COMMAND_ERROR_FOR_STATUS", 85);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->COMMAND_ERROR_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 30292 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.RESETCMDTIMER.IN
    st = getVariable(30292);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.RESETCMDTIMER.IN", 77);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 30293 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.RESETCMDTIMER.PT
    st = getVariable(30293);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.RESETCMDTIMER.PT", 77);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 30294 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.RESETCMDTIMER.Q
    st = getVariable(30294);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.RESETCMDTIMER.Q", 76);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 30295 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.RESETCMDTIMER.ET
    st = getVariable(30295);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.RESETCMDTIMER.ET", 77);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 30296 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.RESETCMDTIMER
    st = getVariable(30296);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.RESETCMDTIMER", 74);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    st->value_p = (void *)p_TON;
  }
  { // 30297 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.RESETCMDTIMERPRIZNAK
    st = getVariable(30297);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.RESETCMDTIMERPRIZNAK", 81);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_BOOL = (BOOL*)&p_FB_AIPROTECTION->RESETCMDTIMERPRIZNAK;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 30298 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SIGNALINTIMER.IN
    st = getVariable(30298);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SIGNALINTIMER.IN", 77);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 30299 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SIGNALINTIMER.PT
    st = getVariable(30299);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SIGNALINTIMER.PT", 77);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 30300 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SIGNALINTIMER.Q
    st = getVariable(30300);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SIGNALINTIMER.Q", 76);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 30301 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SIGNALINTIMER.ET
    st = getVariable(30301);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SIGNALINTIMER.ET", 77);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 30302 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SIGNALINTIMER
    st = getVariable(30302);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SIGNALINTIMER", 74);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    st->value_p = (void *)p_TON;
  }
  { // 30303 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.TIMER.IN
    st = getVariable(30303);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.TIMER.IN", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 30304 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.TIMER.PT
    st = getVariable(30304);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.TIMER.PT", 69);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 30305 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.TIMER.Q
    st = getVariable(30305);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.TIMER.Q", 68);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 30306 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.TIMER.ET
    st = getVariable(30306);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.TIMER.ET", 69);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 30307 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.TIMER
    st = getVariable(30307);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.TIMER", 66);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    st->value_p = (void *)p_TON;
  }
  { // 30308 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SIGNALINGTRIG.CLK
    st = getVariable(30308);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SIGNALINGTRIG.CLK", 78);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_R_TRIG = (R_TRIG*)&p_FB_AIPROTECTION->SIGNALINGTRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 30309 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SIGNALINGTRIG.Q
    st = getVariable(30309);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SIGNALINGTRIG.Q", 76);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_R_TRIG = (R_TRIG*)&p_FB_AIPROTECTION->SIGNALINGTRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 30310 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SIGNALINGTRIG
    st = getVariable(30310);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SIGNALINGTRIG", 74);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_R_TRIG = (R_TRIG*)&p_FB_AIPROTECTION->SIGNALINGTRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 30311 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SIGNALINGFTRIG.CLK
    st = getVariable(30311);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SIGNALINGFTRIG.CLK", 79);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_F_TRIG = (F_TRIG*)&p_FB_AIPROTECTION->SIGNALINGFTRIG;
    p_BOOL = (BOOL*)&p_F_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 30312 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SIGNALINGFTRIG.Q
    st = getVariable(30312);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SIGNALINGFTRIG.Q", 77);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_F_TRIG = (F_TRIG*)&p_FB_AIPROTECTION->SIGNALINGFTRIG;
    p_BOOL = (BOOL*)&p_F_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 30313 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SIGNALINGFTRIG
    st = getVariable(30313);
    memcpy(st->IEC_TYPE, "F_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SIGNALINGFTRIG", 75);
    st->size_data = sizeof(F_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_F_TRIG = (F_TRIG*)&p_FB_AIPROTECTION->SIGNALINGFTRIG;
    st->value_p = (void *)p_F_TRIG;
  }
  { // 30314 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SIGNALINGAI
    st = getVariable(30314);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2.SIGNALINGAI", 72);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_RAB_KOL_EDT_9_2;
    p_BOOL = (BOOL*)&p_FB_AIPROTECTION->SIGNALINGAI;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }

  return 0;
}

// clang-format on
