// clang-format off

#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include "POUS.h"
#include <beremiz/beremiz.h>

#include "iec_types_all.h"
#include "config1.h"

extern PROGRAM0 RESOURCE1__INSTANCE0;

#ifdef DEBUG_PLC
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err][%s:%d]: " _PRNTMSG "\n", __func__, __LINE__, ##__VA_ARGS__)
#else
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err]: " _PRNTMSG "\n", ##__VA_ARGS__)
#endif // DEBUG_PLC

void UnpackVar(void* varp, __IEC_types_enum vartype, void **value_p, void **f_value_p, uint8_t **flags);

int __variables_init_FB_AUTOAVOMOFF(){
  iec_var_t *st;

  PROGRAM0 *p_PROGRAM0;
  LREAL *p_LREAL;
  ULINT *p_ULINT;
  REAL *p_REAL;
  FB_TIMINGS *p_FB_TIMINGS;
  BOOL *p_BOOL;
  UINT *p_UINT;
  PROC_AI_INIT *p_PROC_AI_INIT;
  FB_AI_INIT *p_FB_AI_INIT;
  TIME *p_TIME;
  STRUCT_AI *p_STRUCT_AI;
  DWORD *p_DWORD;
  BYTE *p_BYTE;
  WORD *p_WORD;
  AICONFIG *p_AICONFIG;
  PROC_AI *p_PROC_AI;
  FB_AISOURCEMLP *p_FB_AISOURCEMLP;
  TITEMAIN *p_TITEMAIN;
  TITEMDIN *p_TITEMDIN;
  TYPE_STATUSAI *p_TYPE_STATUSAI;
  TYPE_COMMANDANALOG *p_TYPE_COMMANDANALOG;
  FB_SUNPACKERCOMMAND *p_FB_SUNPACKERCOMMAND;
  TYPE_ANALOGLIMITFLAGS *p_TYPE_ANALOGLIMITFLAGS;
  TON *p_TON;
  R_TRIG *p_R_TRIG;
  FB_AISOURCEMLP_TIMER *p_FB_AISOURCEMLP_TIMER;
  PROC_AO_INIT *p_PROC_AO_INIT;
  FB_AO_INIT *p_FB_AO_INIT;
  STRUCT_AO *p_STRUCT_AO;
  AOCONFIG *p_AOCONFIG;
  PROC_AO *p_PROC_AO;
  FB_AOSOURCEMLP *p_FB_AOSOURCEMLP;
  TDOUBLEDATA *p_TDOUBLEDATA;
  PROC_DI_INIT *p_PROC_DI_INIT;
  FB_DI_INIT *p_FB_DI_INIT;
  STRUCT_DI *p_STRUCT_DI;
  __IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t *p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t;
  TYPE_RELIABLEBIT *p_TYPE_RELIABLEBIT;
  DICONFIG *p_DICONFIG;
  PROC_DI *p_PROC_DI;
  FB_DISOURCEMLP *p_FB_DISOURCEMLP;
  INT *p_INT;
  UDINT *p_UDINT;
  PROC_DO_INIT *p_PROC_DO_INIT;
  FB_DO_INIT *p_FB_DO_INIT;
  STRUCT_DO *p_STRUCT_DO;
  __IEC___ARRAY_OF_BOOL_16_t *p___IEC___ARRAY_OF_BOOL_16_t;
  DOCONFIG *p_DOCONFIG;
  PROC_DO *p_PROC_DO;
  FB_DOSOURCEMLP *p_FB_DOSOURCEMLP;
  TWORDDATA *p_TWORDDATA;
  OPC_ALGORITMS_SET *p_OPC_ALGORITMS_SET;
  ALGORITMSCONFIG *p_ALGORITMSCONFIG;
  STRUCT_ALG *p_STRUCT_ALG;
  STRUCT_ALGORITMSMANAGER *p_STRUCT_ALGORITMSMANAGER;
  STRUCT_PROTECTIONSMANAGER *p_STRUCT_PROTECTIONSMANAGER;
  STRUCT_ALGTIMERS *p_STRUCT_ALGTIMERS;
  ALGORITMSQUESTIONS *p_ALGORITMSQUESTIONS;
  STRUCT_QUESTION *p_STRUCT_QUESTION;
  OPC_ALGORITMS_GET *p_OPC_ALGORITMS_GET;
  PROC_IM_INIT *p_PROC_IM_INIT;
  FB_KRAN_INIT *p_FB_KRAN_INIT;
  STRUCT_KRAN *p_STRUCT_KRAN;
  FB_SWITCH_INIT *p_FB_SWITCH_INIT;
  STRUCT_SWITCH *p_STRUCT_SWITCH;
  FB_OILPUMP_INIT *p_FB_OILPUMP_INIT;
  STRUCT_OILPUMP *p_STRUCT_OILPUMP;
  FB_SECTIONSWITCH_INIT *p_FB_SECTIONSWITCH_INIT;
  STRUCT_SECTIONSWITCH *p_STRUCT_SECTIONSWITCH;
  FB_ANALOGPARAMETR_INIT *p_FB_ANALOGPARAMETR_INIT;
  STRUCT_ANALOGPARAMETR *p_STRUCT_ANALOGPARAMETR;
  FB_DISCRETPARAMETR_INIT *p_FB_DISCRETPARAMETR_INIT;
  STRUCT_DISCRETPARAMETR *p_STRUCT_DISCRETPARAMETR;
  FB_SINGLESIGNAL_INIT *p_FB_SINGLESIGNAL_INIT;
  STRUCT_SINGLESIGNAL *p_STRUCT_SINGLESIGNAL;
  FB_SINGLEOUTPUT_INIT *p_FB_SINGLEOUTPUT_INIT;
  STRUCT_SINGLEOUTPUT *p_STRUCT_SINGLEOUTPUT;
  IMCONFIG *p_IMCONFIG;
  STRUCT_RESERVEIM *p_STRUCT_RESERVEIM;
  STRUCT_RESERVEIM2 *p_STRUCT_RESERVEIM2;
  IM_SINGLESIGNALS *p_IM_SINGLESIGNALS;
  IM_SINGLEOUTPUTS *p_IM_SINGLEOUTPUTS;
  PROC_IM *p_PROC_IM;
  FB_KRAN *p_FB_KRAN;
  TYPE_STATUSDUALINPUT *p_TYPE_STATUSDUALINPUT;
  TYPE_COMMANDDUALINPUT *p_TYPE_COMMANDDUALINPUT;
  TOF *p_TOF;
  FB_OILPUMP *p_FB_OILPUMP;
  FB_SWITCH *p_FB_SWITCH;
  FB_SECTIONSWITCH *p_FB_SECTIONSWITCH;
  TYPE_BASKETSTATS *p_TYPE_BASKETSTATS;
  FB_MEANDR *p_FB_MEANDR;
  FB_SINGLESIGNAL *p_FB_SINGLESIGNAL;
  FB_SINGLEOUTPUT *p_FB_SINGLEOUTPUT;
  PROC_PROTECTIONS_INIT *p_PROC_PROTECTIONS_INIT;
  FB_DIPROTECTION_INIT *p_FB_DIPROTECTION_INIT;
  STRUCT_DIPROTECTION *p_STRUCT_DIPROTECTION;
  FB_AIPROTECTION_INIT *p_FB_AIPROTECTION_INIT;
  STRUCT_AIPROTECTION *p_STRUCT_AIPROTECTION;
  PROTECTIONSCONFIG *p_PROTECTIONSCONFIG;
  TYPE_PROTECTIONTAGS *p_TYPE_PROTECTIONTAGS;
  PROC_PROTECTION *p_PROC_PROTECTION;
  FB_MVPROTECTION *p_FB_MVPROTECTION;
  F_TRIG *p_F_TRIG;
  FB_DIPROTECTION *p_FB_DIPROTECTION;
  FB_KRANOPENPROTECTION *p_FB_KRANOPENPROTECTION;
  FB_AIPROTECTION *p_FB_AIPROTECTION;
  PROC_ALGORITMS *p_PROC_ALGORITMS;
  REMONTALG *p_REMONTALG;
  TYPE_MODEGPA *p_TYPE_MODEGPA;
  TYPE_COMMANDSPOTECTIONSMANAGER *p_TYPE_COMMANDSPOTECTIONSMANAGER;
  TESTPROTECTIONALG *p_TESTPROTECTIONALG;
  TESTIMALG *p_TESTIMALG;
  FB_AUTOTENALG *p_FB_AUTOTENALG;
  FB_AUTOPNSALG *p_FB_AUTOPNSALG;
  FB_AUTOAVOMALG *p_FB_AUTOAVOMALG;
  FB_VIBEGPNSALG *p_FB_VIBEGPNSALG;
  STRUCT_PHASEALGORITM *p_STRUCT_PHASEALGORITM;
  FB_PH_ALGORITM *p_FB_PH_ALGORITM;
  FB_PH_TIMER *p_FB_PH_TIMER;
  FB_QUESTION *p_FB_QUESTION;
  TYPE_ANSWERS *p_TYPE_ANSWERS;
  FB_PH_SWITCH *p_FB_PH_SWITCH;
  FB_PH_CUSTOMPHASE *p_FB_PH_CUSTOMPHASE;
  FB_AUTONUALG *p_FB_AUTONUALG;
  FB_PUSKOILSYSTEMALG *p_FB_PUSKOILSYSTEMALG;
  FB_PH_WAITANALOGVALUE *p_FB_PH_WAITANALOGVALUE;
  FB_PH_OILPUMP *p_FB_PH_OILPUMP;
  FB_ANTIPOMPAGALG *p_FB_ANTIPOMPAGALG;
  FB_TABLEVALUE_MIN *p_FB_TABLEVALUE_MIN;
  __IEC___ARRAY_OF_TYPE_TABLEREC_9_t *p___IEC___ARRAY_OF_TYPE_TABLEREC_9_t;
  TYPE_TABLEREC *p_TYPE_TABLEREC;
  FB_TABLEVALUE_MAX *p_FB_TABLEVALUE_MAX;
  FB_RASHODALG *p_FB_RASHODALG;
  FB_ZAPASALG *p_FB_ZAPASALG;
  NOALG *p_NOALG;
  FB_PH_KRAN *p_FB_PH_KRAN;
  FB_PH_SECTIONSWITCH *p_FB_PH_SECTIONSWITCH;
  AOALG *p_AOALG;
  PPUALG *p_PPUALG;
  FILLINGALG *p_FILLINGALG;
  FB_PH_DIPROTECTION *p_FB_PH_DIPROTECTION;
  ENGINERUNALG *p_ENGINERUNALG;
  PUSKKALG *p_PUSKKALG;
  PUSKVALG *p_PUSKVALG;
  TESTDPMGALG *p_TESTDPMGALG;
  TESTPMSALG *p_TESTPMSALG;
  FB_PH_AIPROTECTION *p_FB_PH_AIPROTECTION;
  APUSKALG *p_APUSKALG;
  SEMIAUTOPUSKALG *p_SEMIAUTOPUSKALG;
  FB_ALGORITMSMANAGER *p_FB_ALGORITMSMANAGER;
  FB_PROTECTIONSMANAGER *p_FB_PROTECTIONSMANAGER;

  { // 61991 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.INRUNONSTART
    st = getVariable(61991);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.INRUNONSTART", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->INRUNONSTART;
    st->value_p = p_BOOL;
  }
  { // 61992 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.INCANRUN
    st = getVariable(61992);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.INCANRUN", 60);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->INCANRUN;
    st->value_p = p_BOOL;
  }
  { // 61993 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.INHASERROR
    st = getVariable(61993);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.INHASERROR", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->INHASERROR;
    st->value_p = p_BOOL;
  }
  { // 61994 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.INENDED
    st = getVariable(61994);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.INENDED", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->INENDED;
    st->value_p = p_BOOL;
  }
  { // 61995 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.INOPCCOMMANDSDISABLED
    st = getVariable(61995);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.INOPCCOMMANDSDISABLED", 73);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 61996 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.INCOMMAND
    st = getVariable(61996);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.INCOMMAND", 61);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_WORD = (WORD*)&p_STRUCT_ALG->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 61997 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.INCOMMAND_ARM
    st = getVariable(61997);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.INCOMMAND_ARM", 65);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_WORD = (WORD*)&p_STRUCT_ALG->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 61998 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.INCOMMAND_ALG
    st = getVariable(61998);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.INCOMMAND_ALG", 65);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_WORD = (WORD*)&p_STRUCT_ALG->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 61999 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.STATUS
    st = getVariable(61999);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.STATUS", 58);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_DWORD = (DWORD*)&p_STRUCT_ALG->STATUS;
    st->value_p = p_DWORD;
  }
  { // 62000 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.CANRUN
    st = getVariable(62000);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.CANRUN", 58);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->CANRUN;
    st->value_p = p_BOOL;
  }
  { // 62001 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.OPCCOMMANDSDISABLED
    st = getVariable(62001);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.OPCCOMMANDSDISABLED", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 62002 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.ISRUNING
    st = getVariable(62002);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.ISRUNING", 60);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->ISRUNING;
    st->value_p = p_BOOL;
  }
  { // 62003 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.HASERROR
    st = getVariable(62003);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.HASERROR", 60);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->HASERROR;
    st->value_p = p_BOOL;
  }
  { // 62004 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.ISENDED
    st = getVariable(62004);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.ISENDED", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->ISENDED;
    st->value_p = p_BOOL;
  }
  { // 62005 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.RUNONSTART
    st = getVariable(62005);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.RUNONSTART", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->RUNONSTART;
    st->value_p = p_BOOL;
  }
  { // 62006 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.START
    st = getVariable(62006);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.START", 57);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_DWORD = (DWORD*)&p_STRUCT_ALG->START;
    st->value_p = p_DWORD;
  }
  { // 62007 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.ERROR
    st = getVariable(62007);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.ERROR", 57);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_DWORD = (DWORD*)&p_STRUCT_ALG->ERROR;
    st->value_p = p_DWORD;
  }
  { // 62008 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.TOP
    st = getVariable(62008);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.ALG.TOP", 55);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_DWORD = (DWORD*)&p_STRUCT_ALG->TOP;
    st->value_p = p_DWORD;
  }
  { // 62009 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.PHASENUMBER
    st = getVariable(62009);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.PHASENUMBER", 59);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_UINT = (UINT*)&p_FB_PH_ALGORITM->PHASENUMBER;
    UnpackVar(p_UINT, UINT_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 62010 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.WAITCOMPLETION
    st = getVariable(62010);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.WAITCOMPLETION", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_BOOL = (BOOL*)&p_FB_PH_ALGORITM->WAITCOMPLETION;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 62011 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.STRPH.RUN
    st = getVariable(62011);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.STRPH.RUN", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_ALGORITM->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->RUN;
    st->value_p = p_BOOL;
  }
  { // 62012 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.STRPH.RESET
    st = getVariable(62012);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.STRPH.RESET", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_ALGORITM->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->RESET;
    st->value_p = p_BOOL;
  }
  { // 62013 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.STRPH.START
    st = getVariable(62013);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.STRPH.START", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_ALGORITM->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->START;
    st->value_p = p_BOOL;
  }
  { // 62014 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.STRPH.ERROR
    st = getVariable(62014);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.STRPH.ERROR", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_ALGORITM->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->ERROR;
    st->value_p = p_BOOL;
  }
  { // 62015 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.STRPH.TOP
    st = getVariable(62015);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.STRPH.TOP", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_ALGORITM->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->TOP;
    st->value_p = p_BOOL;
  }
  { // 62016 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.STRPH.STARTSTATUS
    st = getVariable(62016);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.STRPH.STARTSTATUS", 65);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_ALGORITM->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->STARTSTATUS;
    st->value_p = p_DWORD;
  }
  { // 62017 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.STRPH.ERRORSTATUS
    st = getVariable(62017);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.STRPH.ERRORSTATUS", 65);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_ALGORITM->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->ERRORSTATUS;
    st->value_p = p_DWORD;
  }
  { // 62018 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.STRPH.TOPSTATUS
    st = getVariable(62018);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.STRPH.TOPSTATUS", 63);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_ALGORITM->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->TOPSTATUS;
    st->value_p = p_DWORD;
  }
  { // 62019 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.COMMANDFAULT_TRIG.CLK
    st = getVariable(62019);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.COMMANDFAULT_TRIG.CLK", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_ALGORITM->COMMANDFAULT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 62020 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.COMMANDFAULT_TRIG.Q
    st = getVariable(62020);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.COMMANDFAULT_TRIG.Q", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_ALGORITM->COMMANDFAULT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 62021 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.COMMANDFAULT_TRIG
    st = getVariable(62021);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.COMMANDFAULT_TRIG", 65);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_ALGORITM->COMMANDFAULT_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 62022 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.RESET_TRIG.CLK
    st = getVariable(62022);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.RESET_TRIG.CLK", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_ALGORITM->RESET_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 62023 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.RESET_TRIG.Q
    st = getVariable(62023);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.RESET_TRIG.Q", 60);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_ALGORITM->RESET_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 62024 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.RESET_TRIG
    st = getVariable(62024);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF.RESET_TRIG", 58);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_ALGORITM->RESET_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 62025 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_NOTDEFINED
    st = getVariable(62025);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_NOTDEFINED", 82);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_ALGORITM->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_NOTDEFINED;
    st->value_p = p_BYTE;
  }
  { // 62026 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_ON
    st = getVariable(62026);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_ON", 74);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_ALGORITM->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ON;
    st->value_p = p_BYTE;
  }
  { // 62027 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_OFF
    st = getVariable(62027);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_OFF", 75);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_ALGORITM->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_OFF;
    st->value_p = p_BYTE;
  }
  { // 62028 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_TRANSITIONAL
    st = getVariable(62028);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_TRANSITIONAL", 84);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_ALGORITM->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_TRANSITIONAL;
    st->value_p = p_BYTE;
  }
  { // 62029 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_ERROR
    st = getVariable(62029);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_ERROR", 77);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_NOALG->FB_AUTOAVOMOFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_ALGORITM->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ERROR;
    st->value_p = p_BYTE;
  }
  { // 68696 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.INRUNONSTART
    st = getVariable(68696);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.INRUNONSTART", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->INRUNONSTART;
    st->value_p = p_BOOL;
  }
  { // 68697 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.INCANRUN
    st = getVariable(68697);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.INCANRUN", 60);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->INCANRUN;
    st->value_p = p_BOOL;
  }
  { // 68698 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.INHASERROR
    st = getVariable(68698);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.INHASERROR", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->INHASERROR;
    st->value_p = p_BOOL;
  }
  { // 68699 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.INENDED
    st = getVariable(68699);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.INENDED", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->INENDED;
    st->value_p = p_BOOL;
  }
  { // 68700 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.INOPCCOMMANDSDISABLED
    st = getVariable(68700);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.INOPCCOMMANDSDISABLED", 73);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 68701 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.INCOMMAND
    st = getVariable(68701);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.INCOMMAND", 61);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_WORD = (WORD*)&p_STRUCT_ALG->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 68702 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.INCOMMAND_ARM
    st = getVariable(68702);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.INCOMMAND_ARM", 65);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_WORD = (WORD*)&p_STRUCT_ALG->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 68703 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.INCOMMAND_ALG
    st = getVariable(68703);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.INCOMMAND_ALG", 65);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_WORD = (WORD*)&p_STRUCT_ALG->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 68704 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.STATUS
    st = getVariable(68704);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.STATUS", 58);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_DWORD = (DWORD*)&p_STRUCT_ALG->STATUS;
    st->value_p = p_DWORD;
  }
  { // 68705 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.CANRUN
    st = getVariable(68705);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.CANRUN", 58);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->CANRUN;
    st->value_p = p_BOOL;
  }
  { // 68706 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.OPCCOMMANDSDISABLED
    st = getVariable(68706);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.OPCCOMMANDSDISABLED", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 68707 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.ISRUNING
    st = getVariable(68707);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.ISRUNING", 60);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->ISRUNING;
    st->value_p = p_BOOL;
  }
  { // 68708 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.HASERROR
    st = getVariable(68708);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.HASERROR", 60);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->HASERROR;
    st->value_p = p_BOOL;
  }
  { // 68709 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.ISENDED
    st = getVariable(68709);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.ISENDED", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->ISENDED;
    st->value_p = p_BOOL;
  }
  { // 68710 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.RUNONSTART
    st = getVariable(68710);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.RUNONSTART", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->RUNONSTART;
    st->value_p = p_BOOL;
  }
  { // 68711 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.START
    st = getVariable(68711);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.START", 57);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_DWORD = (DWORD*)&p_STRUCT_ALG->START;
    st->value_p = p_DWORD;
  }
  { // 68712 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.ERROR
    st = getVariable(68712);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.ERROR", 57);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_DWORD = (DWORD*)&p_STRUCT_ALG->ERROR;
    st->value_p = p_DWORD;
  }
  { // 68713 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.TOP
    st = getVariable(68713);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.ALG.TOP", 55);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_DWORD = (DWORD*)&p_STRUCT_ALG->TOP;
    st->value_p = p_DWORD;
  }
  { // 68714 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.PHASENUMBER
    st = getVariable(68714);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.PHASENUMBER", 59);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_UINT = (UINT*)&p_FB_PH_ALGORITM->PHASENUMBER;
    UnpackVar(p_UINT, UINT_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 68715 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.WAITCOMPLETION
    st = getVariable(68715);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.WAITCOMPLETION", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_BOOL = (BOOL*)&p_FB_PH_ALGORITM->WAITCOMPLETION;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 68716 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.STRPH.RUN
    st = getVariable(68716);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.STRPH.RUN", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_ALGORITM->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->RUN;
    st->value_p = p_BOOL;
  }
  { // 68717 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.STRPH.RESET
    st = getVariable(68717);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.STRPH.RESET", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_ALGORITM->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->RESET;
    st->value_p = p_BOOL;
  }
  { // 68718 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.STRPH.START
    st = getVariable(68718);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.STRPH.START", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_ALGORITM->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->START;
    st->value_p = p_BOOL;
  }
  { // 68719 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.STRPH.ERROR
    st = getVariable(68719);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.STRPH.ERROR", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_ALGORITM->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->ERROR;
    st->value_p = p_BOOL;
  }
  { // 68720 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.STRPH.TOP
    st = getVariable(68720);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.STRPH.TOP", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_ALGORITM->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->TOP;
    st->value_p = p_BOOL;
  }
  { // 68721 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.STRPH.STARTSTATUS
    st = getVariable(68721);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.STRPH.STARTSTATUS", 65);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_ALGORITM->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->STARTSTATUS;
    st->value_p = p_DWORD;
  }
  { // 68722 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.STRPH.ERRORSTATUS
    st = getVariable(68722);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.STRPH.ERRORSTATUS", 65);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_ALGORITM->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->ERRORSTATUS;
    st->value_p = p_DWORD;
  }
  { // 68723 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.STRPH.TOPSTATUS
    st = getVariable(68723);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.STRPH.TOPSTATUS", 63);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_ALGORITM->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->TOPSTATUS;
    st->value_p = p_DWORD;
  }
  { // 68724 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.COMMANDFAULT_TRIG.CLK
    st = getVariable(68724);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.COMMANDFAULT_TRIG.CLK", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_ALGORITM->COMMANDFAULT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 68725 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.COMMANDFAULT_TRIG.Q
    st = getVariable(68725);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.COMMANDFAULT_TRIG.Q", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_ALGORITM->COMMANDFAULT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 68726 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.COMMANDFAULT_TRIG
    st = getVariable(68726);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.COMMANDFAULT_TRIG", 65);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_ALGORITM->COMMANDFAULT_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 68727 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.RESET_TRIG.CLK
    st = getVariable(68727);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.RESET_TRIG.CLK", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_ALGORITM->RESET_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 68728 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.RESET_TRIG.Q
    st = getVariable(68728);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.RESET_TRIG.Q", 60);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_ALGORITM->RESET_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 68729 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.RESET_TRIG
    st = getVariable(68729);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF.RESET_TRIG", 58);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_ALGORITM->RESET_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 68730 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_NOTDEFINED
    st = getVariable(68730);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_NOTDEFINED", 82);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_ALGORITM->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_NOTDEFINED;
    st->value_p = p_BYTE;
  }
  { // 68731 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_ON
    st = getVariable(68731);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_ON", 74);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_ALGORITM->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ON;
    st->value_p = p_BYTE;
  }
  { // 68732 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_OFF
    st = getVariable(68732);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_OFF", 75);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_ALGORITM->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_OFF;
    st->value_p = p_BYTE;
  }
  { // 68733 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_TRANSITIONAL
    st = getVariable(68733);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_TRANSITIONAL", 84);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_ALGORITM->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_TRANSITIONAL;
    st->value_p = p_BYTE;
  }
  { // 68734 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_ERROR
    st = getVariable(68734);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_ERROR", 77);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_AOALG->FB_AUTOAVOMOFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_ALGORITM->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ERROR;
    st->value_p = p_BYTE;
  }
  { // 99287 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.INRUNONSTART
    st = getVariable(99287);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.INRUNONSTART", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->INRUNONSTART;
    st->value_p = p_BOOL;
  }
  { // 99288 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.INCANRUN
    st = getVariable(99288);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.INCANRUN", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->INCANRUN;
    st->value_p = p_BOOL;
  }
  { // 99289 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.INHASERROR
    st = getVariable(99289);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.INHASERROR", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->INHASERROR;
    st->value_p = p_BOOL;
  }
  { // 99290 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.INENDED
    st = getVariable(99290);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.INENDED", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->INENDED;
    st->value_p = p_BOOL;
  }
  { // 99291 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.INOPCCOMMANDSDISABLED
    st = getVariable(99291);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.INOPCCOMMANDSDISABLED", 76);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 99292 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.INCOMMAND
    st = getVariable(99292);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.INCOMMAND", 64);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_WORD = (WORD*)&p_STRUCT_ALG->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 99293 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.INCOMMAND_ARM
    st = getVariable(99293);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.INCOMMAND_ARM", 68);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_WORD = (WORD*)&p_STRUCT_ALG->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 99294 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.INCOMMAND_ALG
    st = getVariable(99294);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.INCOMMAND_ALG", 68);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_WORD = (WORD*)&p_STRUCT_ALG->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 99295 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.STATUS
    st = getVariable(99295);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.STATUS", 61);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_DWORD = (DWORD*)&p_STRUCT_ALG->STATUS;
    st->value_p = p_DWORD;
  }
  { // 99296 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.CANRUN
    st = getVariable(99296);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.CANRUN", 61);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->CANRUN;
    st->value_p = p_BOOL;
  }
  { // 99297 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.OPCCOMMANDSDISABLED
    st = getVariable(99297);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.OPCCOMMANDSDISABLED", 74);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 99298 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.ISRUNING
    st = getVariable(99298);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.ISRUNING", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->ISRUNING;
    st->value_p = p_BOOL;
  }
  { // 99299 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.HASERROR
    st = getVariable(99299);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.HASERROR", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->HASERROR;
    st->value_p = p_BOOL;
  }
  { // 99300 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.ISENDED
    st = getVariable(99300);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.ISENDED", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->ISENDED;
    st->value_p = p_BOOL;
  }
  { // 99301 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.RUNONSTART
    st = getVariable(99301);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.RUNONSTART", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_BOOL = (BOOL*)&p_STRUCT_ALG->RUNONSTART;
    st->value_p = p_BOOL;
  }
  { // 99302 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.START
    st = getVariable(99302);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.START", 60);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_DWORD = (DWORD*)&p_STRUCT_ALG->START;
    st->value_p = p_DWORD;
  }
  { // 99303 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.ERROR
    st = getVariable(99303);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.ERROR", 60);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_DWORD = (DWORD*)&p_STRUCT_ALG->ERROR;
    st->value_p = p_DWORD;
  }
  { // 99304 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.TOP
    st = getVariable(99304);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.ALG.TOP", 58);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_ALG = (STRUCT_ALG*)&p_FB_PH_ALGORITM->ALG;
    p_DWORD = (DWORD*)&p_STRUCT_ALG->TOP;
    st->value_p = p_DWORD;
  }
  { // 99305 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.PHASENUMBER
    st = getVariable(99305);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.PHASENUMBER", 62);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_UINT = (UINT*)&p_FB_PH_ALGORITM->PHASENUMBER;
    UnpackVar(p_UINT, UINT_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 99306 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.WAITCOMPLETION
    st = getVariable(99306);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.WAITCOMPLETION", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_BOOL = (BOOL*)&p_FB_PH_ALGORITM->WAITCOMPLETION;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 99307 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.STRPH.RUN
    st = getVariable(99307);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.STRPH.RUN", 60);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_ALGORITM->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->RUN;
    st->value_p = p_BOOL;
  }
  { // 99308 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.STRPH.RESET
    st = getVariable(99308);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.STRPH.RESET", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_ALGORITM->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->RESET;
    st->value_p = p_BOOL;
  }
  { // 99309 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.STRPH.START
    st = getVariable(99309);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.STRPH.START", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_ALGORITM->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->START;
    st->value_p = p_BOOL;
  }
  { // 99310 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.STRPH.ERROR
    st = getVariable(99310);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.STRPH.ERROR", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_ALGORITM->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->ERROR;
    st->value_p = p_BOOL;
  }
  { // 99311 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.STRPH.TOP
    st = getVariable(99311);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.STRPH.TOP", 60);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_ALGORITM->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->TOP;
    st->value_p = p_BOOL;
  }
  { // 99312 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.STRPH.STARTSTATUS
    st = getVariable(99312);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.STRPH.STARTSTATUS", 68);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_ALGORITM->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->STARTSTATUS;
    st->value_p = p_DWORD;
  }
  { // 99313 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.STRPH.ERRORSTATUS
    st = getVariable(99313);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.STRPH.ERRORSTATUS", 68);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_ALGORITM->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->ERRORSTATUS;
    st->value_p = p_DWORD;
  }
  { // 99314 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.STRPH.TOPSTATUS
    st = getVariable(99314);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.STRPH.TOPSTATUS", 66);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_ALGORITM->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->TOPSTATUS;
    st->value_p = p_DWORD;
  }
  { // 99315 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.COMMANDFAULT_TRIG.CLK
    st = getVariable(99315);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.COMMANDFAULT_TRIG.CLK", 72);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_ALGORITM->COMMANDFAULT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 99316 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.COMMANDFAULT_TRIG.Q
    st = getVariable(99316);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.COMMANDFAULT_TRIG.Q", 70);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_ALGORITM->COMMANDFAULT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 99317 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.COMMANDFAULT_TRIG
    st = getVariable(99317);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.COMMANDFAULT_TRIG", 68);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_ALGORITM->COMMANDFAULT_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 99318 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.RESET_TRIG.CLK
    st = getVariable(99318);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.RESET_TRIG.CLK", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_ALGORITM->RESET_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 99319 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.RESET_TRIG.Q
    st = getVariable(99319);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.RESET_TRIG.Q", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_ALGORITM->RESET_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 99320 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.RESET_TRIG
    st = getVariable(99320);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF.RESET_TRIG", 61);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_ALGORITM->RESET_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 99321 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_NOTDEFINED
    st = getVariable(99321);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_NOTDEFINED", 85);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_ALGORITM->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_NOTDEFINED;
    st->value_p = p_BYTE;
  }
  { // 99322 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_ON
    st = getVariable(99322);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_ON", 77);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_ALGORITM->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ON;
    st->value_p = p_BYTE;
  }
  { // 99323 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_OFF
    st = getVariable(99323);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_OFF", 78);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_ALGORITM->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_OFF;
    st->value_p = p_BYTE;
  }
  { // 99324 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_TRANSITIONAL
    st = getVariable(99324);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_TRANSITIONAL", 87);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_ALGORITM->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_TRANSITIONAL;
    st->value_p = p_BYTE;
  }
  { // 99325 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_ERROR
    st = getVariable(99325);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_AUTOAVOMOFF._STATUSDUALINPUT.STATUS_ERROR", 80);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_ALGORITM = (FB_PH_ALGORITM*)&p_PUSKVALG->FB_AUTOAVOMOFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_ALGORITM->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ERROR;
    st->value_p = p_BYTE;
  }

  return 0;
}

// clang-format on
