// clang-format off

#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include "POUS.h"
#include <beremiz/beremiz.h>

#include "iec_types_all.h"
#include "config1.h"

extern PROGRAM0 RESOURCE1__INSTANCE0;

#ifdef DEBUG_PLC
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err][%s:%d]: " _PRNTMSG "\n", __func__, __LINE__, ##__VA_ARGS__)
#else
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err]: " _PRNTMSG "\n", ##__VA_ARGS__)
#endif // DEBUG_PLC

void UnpackVar(void* varp, __IEC_types_enum vartype, void **value_p, void **f_value_p, uint8_t **flags);

int __variables_init_DI_10(){
  iec_var_t *st;

  PROGRAM0 *p_PROGRAM0;
  LREAL *p_LREAL;
  ULINT *p_ULINT;
  REAL *p_REAL;
  FB_TIMINGS *p_FB_TIMINGS;
  BOOL *p_BOOL;
  UINT *p_UINT;
  PROC_AI_INIT *p_PROC_AI_INIT;
  FB_AI_INIT *p_FB_AI_INIT;
  TIME *p_TIME;
  STRUCT_AI *p_STRUCT_AI;
  DWORD *p_DWORD;
  BYTE *p_BYTE;
  WORD *p_WORD;
  AICONFIG *p_AICONFIG;
  PROC_AI *p_PROC_AI;
  FB_AISOURCEMLP *p_FB_AISOURCEMLP;
  TITEMAIN *p_TITEMAIN;
  TITEMDIN *p_TITEMDIN;
  TYPE_STATUSAI *p_TYPE_STATUSAI;
  TYPE_COMMANDANALOG *p_TYPE_COMMANDANALOG;
  FB_SUNPACKERCOMMAND *p_FB_SUNPACKERCOMMAND;
  TYPE_ANALOGLIMITFLAGS *p_TYPE_ANALOGLIMITFLAGS;
  TON *p_TON;
  R_TRIG *p_R_TRIG;
  FB_AISOURCEMLP_TIMER *p_FB_AISOURCEMLP_TIMER;
  PROC_AO_INIT *p_PROC_AO_INIT;
  FB_AO_INIT *p_FB_AO_INIT;
  STRUCT_AO *p_STRUCT_AO;
  AOCONFIG *p_AOCONFIG;
  PROC_AO *p_PROC_AO;
  FB_AOSOURCEMLP *p_FB_AOSOURCEMLP;
  TDOUBLEDATA *p_TDOUBLEDATA;
  PROC_DI_INIT *p_PROC_DI_INIT;
  FB_DI_INIT *p_FB_DI_INIT;
  STRUCT_DI *p_STRUCT_DI;
  __IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t *p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t;
  TYPE_RELIABLEBIT *p_TYPE_RELIABLEBIT;
  DICONFIG *p_DICONFIG;
  PROC_DI *p_PROC_DI;
  FB_DISOURCEMLP *p_FB_DISOURCEMLP;
  INT *p_INT;
  UDINT *p_UDINT;
  PROC_DO_INIT *p_PROC_DO_INIT;
  FB_DO_INIT *p_FB_DO_INIT;
  STRUCT_DO *p_STRUCT_DO;
  __IEC___ARRAY_OF_BOOL_16_t *p___IEC___ARRAY_OF_BOOL_16_t;
  DOCONFIG *p_DOCONFIG;
  PROC_DO *p_PROC_DO;
  FB_DOSOURCEMLP *p_FB_DOSOURCEMLP;
  TWORDDATA *p_TWORDDATA;
  OPC_ALGORITMS_SET *p_OPC_ALGORITMS_SET;
  ALGORITMSCONFIG *p_ALGORITMSCONFIG;
  STRUCT_ALG *p_STRUCT_ALG;
  STRUCT_ALGORITMSMANAGER *p_STRUCT_ALGORITMSMANAGER;
  STRUCT_PROTECTIONSMANAGER *p_STRUCT_PROTECTIONSMANAGER;
  STRUCT_ALGTIMERS *p_STRUCT_ALGTIMERS;
  ALGORITMSQUESTIONS *p_ALGORITMSQUESTIONS;
  STRUCT_QUESTION *p_STRUCT_QUESTION;
  OPC_ALGORITMS_GET *p_OPC_ALGORITMS_GET;
  PROC_IM_INIT *p_PROC_IM_INIT;
  FB_KRAN_INIT *p_FB_KRAN_INIT;
  STRUCT_KRAN *p_STRUCT_KRAN;
  FB_SWITCH_INIT *p_FB_SWITCH_INIT;
  STRUCT_SWITCH *p_STRUCT_SWITCH;
  FB_OILPUMP_INIT *p_FB_OILPUMP_INIT;
  STRUCT_OILPUMP *p_STRUCT_OILPUMP;
  FB_SECTIONSWITCH_INIT *p_FB_SECTIONSWITCH_INIT;
  STRUCT_SECTIONSWITCH *p_STRUCT_SECTIONSWITCH;
  FB_ANALOGPARAMETR_INIT *p_FB_ANALOGPARAMETR_INIT;
  STRUCT_ANALOGPARAMETR *p_STRUCT_ANALOGPARAMETR;
  FB_DISCRETPARAMETR_INIT *p_FB_DISCRETPARAMETR_INIT;
  STRUCT_DISCRETPARAMETR *p_STRUCT_DISCRETPARAMETR;
  FB_SINGLESIGNAL_INIT *p_FB_SINGLESIGNAL_INIT;
  STRUCT_SINGLESIGNAL *p_STRUCT_SINGLESIGNAL;
  FB_SINGLEOUTPUT_INIT *p_FB_SINGLEOUTPUT_INIT;
  STRUCT_SINGLEOUTPUT *p_STRUCT_SINGLEOUTPUT;
  IMCONFIG *p_IMCONFIG;
  STRUCT_RESERVEIM *p_STRUCT_RESERVEIM;
  STRUCT_RESERVEIM2 *p_STRUCT_RESERVEIM2;
  IM_SINGLESIGNALS *p_IM_SINGLESIGNALS;
  IM_SINGLEOUTPUTS *p_IM_SINGLEOUTPUTS;
  PROC_IM *p_PROC_IM;
  FB_KRAN *p_FB_KRAN;
  TYPE_STATUSDUALINPUT *p_TYPE_STATUSDUALINPUT;
  TYPE_COMMANDDUALINPUT *p_TYPE_COMMANDDUALINPUT;
  TOF *p_TOF;
  FB_OILPUMP *p_FB_OILPUMP;
  FB_SWITCH *p_FB_SWITCH;
  FB_SECTIONSWITCH *p_FB_SECTIONSWITCH;
  TYPE_BASKETSTATS *p_TYPE_BASKETSTATS;
  FB_MEANDR *p_FB_MEANDR;
  FB_SINGLESIGNAL *p_FB_SINGLESIGNAL;
  FB_SINGLEOUTPUT *p_FB_SINGLEOUTPUT;
  PROC_PROTECTIONS_INIT *p_PROC_PROTECTIONS_INIT;
  FB_DIPROTECTION_INIT *p_FB_DIPROTECTION_INIT;
  STRUCT_DIPROTECTION *p_STRUCT_DIPROTECTION;
  FB_AIPROTECTION_INIT *p_FB_AIPROTECTION_INIT;
  STRUCT_AIPROTECTION *p_STRUCT_AIPROTECTION;
  PROTECTIONSCONFIG *p_PROTECTIONSCONFIG;
  TYPE_PROTECTIONTAGS *p_TYPE_PROTECTIONTAGS;
  PROC_PROTECTION *p_PROC_PROTECTION;
  FB_MVPROTECTION *p_FB_MVPROTECTION;
  F_TRIG *p_F_TRIG;
  FB_DIPROTECTION *p_FB_DIPROTECTION;
  FB_KRANOPENPROTECTION *p_FB_KRANOPENPROTECTION;
  FB_AIPROTECTION *p_FB_AIPROTECTION;
  PROC_ALGORITMS *p_PROC_ALGORITMS;
  REMONTALG *p_REMONTALG;
  TYPE_MODEGPA *p_TYPE_MODEGPA;
  TYPE_COMMANDSPOTECTIONSMANAGER *p_TYPE_COMMANDSPOTECTIONSMANAGER;
  TESTPROTECTIONALG *p_TESTPROTECTIONALG;
  TESTIMALG *p_TESTIMALG;
  FB_AUTOTENALG *p_FB_AUTOTENALG;
  FB_AUTOPNSALG *p_FB_AUTOPNSALG;
  FB_AUTOAVOMALG *p_FB_AUTOAVOMALG;
  FB_VIBEGPNSALG *p_FB_VIBEGPNSALG;
  STRUCT_PHASEALGORITM *p_STRUCT_PHASEALGORITM;
  FB_PH_ALGORITM *p_FB_PH_ALGORITM;
  FB_PH_TIMER *p_FB_PH_TIMER;
  FB_QUESTION *p_FB_QUESTION;
  TYPE_ANSWERS *p_TYPE_ANSWERS;
  FB_PH_SWITCH *p_FB_PH_SWITCH;
  FB_PH_CUSTOMPHASE *p_FB_PH_CUSTOMPHASE;
  FB_AUTONUALG *p_FB_AUTONUALG;
  FB_PUSKOILSYSTEMALG *p_FB_PUSKOILSYSTEMALG;
  FB_PH_WAITANALOGVALUE *p_FB_PH_WAITANALOGVALUE;
  FB_PH_OILPUMP *p_FB_PH_OILPUMP;
  FB_ANTIPOMPAGALG *p_FB_ANTIPOMPAGALG;
  FB_TABLEVALUE_MIN *p_FB_TABLEVALUE_MIN;
  __IEC___ARRAY_OF_TYPE_TABLEREC_9_t *p___IEC___ARRAY_OF_TYPE_TABLEREC_9_t;
  TYPE_TABLEREC *p_TYPE_TABLEREC;
  FB_TABLEVALUE_MAX *p_FB_TABLEVALUE_MAX;
  FB_RASHODALG *p_FB_RASHODALG;
  FB_ZAPASALG *p_FB_ZAPASALG;
  NOALG *p_NOALG;
  FB_PH_KRAN *p_FB_PH_KRAN;
  FB_PH_SECTIONSWITCH *p_FB_PH_SECTIONSWITCH;
  AOALG *p_AOALG;
  PPUALG *p_PPUALG;
  FILLINGALG *p_FILLINGALG;
  FB_PH_DIPROTECTION *p_FB_PH_DIPROTECTION;
  ENGINERUNALG *p_ENGINERUNALG;
  PUSKKALG *p_PUSKKALG;
  PUSKVALG *p_PUSKVALG;
  TESTDPMGALG *p_TESTDPMGALG;
  TESTPMSALG *p_TESTPMSALG;
  FB_PH_AIPROTECTION *p_FB_PH_AIPROTECTION;
  APUSKALG *p_APUSKALG;
  SEMIAUTOPUSKALG *p_SEMIAUTOPUSKALG;
  FB_ALGORITMSMANAGER *p_FB_ALGORITMSMANAGER;
  FB_PROTECTIONSMANAGER *p_FB_PROTECTIONSMANAGER;

  { // 16014 PROGRAM0.DI_PROC.DI_10.ARDIN.WFLAGS
    st = getVariable(16014);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.ARDIN.WFLAGS", 35);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_TITEMDIN = (TITEMDIN*)&p_FB_DISOURCEMLP->ARDIN;
    p_UINT = (UINT*)&p_TITEMDIN->WFLAGS;
    st->value_p = p_UINT;
  }
  { // 16015 PROGRAM0.DI_PROC.DI_10.ARDIN.WVALUE
    st = getVariable(16015);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.ARDIN.WVALUE", 35);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_TITEMDIN = (TITEMDIN*)&p_FB_DISOURCEMLP->ARDIN;
    p_UINT = (UINT*)&p_TITEMDIN->WVALUE;
    st->value_p = p_UINT;
  }
  { // 16016 PROGRAM0.DI_PROC.DI_10.ARDIN.NANOSEC
    st = getVariable(16016);
    memcpy(st->IEC_TYPE, "ULINT", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.ARDIN.NANOSEC", 36);
    st->size_data = sizeof(ULINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_TITEMDIN = (TITEMDIN*)&p_FB_DISOURCEMLP->ARDIN;
    p_ULINT = (ULINT*)&p_TITEMDIN->NANOSEC;
    st->value_p = p_ULINT;
  }
  { // 16017 PROGRAM0.DI_PROC.DI_10.ARDIN.RESERVE
    st = getVariable(16017);
    memcpy(st->IEC_TYPE, "ULINT", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.ARDIN.RESERVE", 36);
    st->size_data = sizeof(ULINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_TITEMDIN = (TITEMDIN*)&p_FB_DISOURCEMLP->ARDIN;
    p_ULINT = (ULINT*)&p_TITEMDIN->RESERVE;
    st->value_p = p_ULINT;
  }
  { // 16018 PROGRAM0.DI_PROC.DI_10.ERR_MOD.WFLAGS
    st = getVariable(16018);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.ERR_MOD.WFLAGS", 37);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_TITEMDIN = (TITEMDIN*)&p_FB_DISOURCEMLP->ERR_MOD;
    p_UINT = (UINT*)&p_TITEMDIN->WFLAGS;
    st->value_p = p_UINT;
  }
  { // 16019 PROGRAM0.DI_PROC.DI_10.ERR_MOD.WVALUE
    st = getVariable(16019);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.ERR_MOD.WVALUE", 37);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_TITEMDIN = (TITEMDIN*)&p_FB_DISOURCEMLP->ERR_MOD;
    p_UINT = (UINT*)&p_TITEMDIN->WVALUE;
    st->value_p = p_UINT;
  }
  { // 16020 PROGRAM0.DI_PROC.DI_10.ERR_MOD.NANOSEC
    st = getVariable(16020);
    memcpy(st->IEC_TYPE, "ULINT", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.ERR_MOD.NANOSEC", 38);
    st->size_data = sizeof(ULINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_TITEMDIN = (TITEMDIN*)&p_FB_DISOURCEMLP->ERR_MOD;
    p_ULINT = (ULINT*)&p_TITEMDIN->NANOSEC;
    st->value_p = p_ULINT;
  }
  { // 16021 PROGRAM0.DI_PROC.DI_10.ERR_MOD.RESERVE
    st = getVariable(16021);
    memcpy(st->IEC_TYPE, "ULINT", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.ERR_MOD.RESERVE", 38);
    st->size_data = sizeof(ULINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_TITEMDIN = (TITEMDIN*)&p_FB_DISOURCEMLP->ERR_MOD;
    p_ULINT = (ULINT*)&p_TITEMDIN->RESERVE;
    st->value_p = p_ULINT;
  }
  { // 16022 PROGRAM0.DI_PROC.DI_10.STRDI.IMIT
    st = getVariable(16022);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.IMIT", 33);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p_BOOL = (BOOL*)&p_STRUCT_DI->IMIT;
    st->value_p = p_BOOL;
  }
  { // 16023 PROGRAM0.DI_PROC.DI_10.STRDI.VALUE
    st = getVariable(16023);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.VALUE", 34);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p_WORD = (WORD*)&p_STRUCT_DI->VALUE;
    st->value_p = p_WORD;
  }
  { // 16024 PROGRAM0.DI_PROC.DI_10.STRDI.RELIABILITY
    st = getVariable(16024);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.RELIABILITY", 40);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p_WORD = (WORD*)&p_STRUCT_DI->RELIABILITY;
    st->value_p = p_WORD;
  }
  { // 16025 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[0].VALUE
    st = getVariable(16025);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[0].VALUE", 42);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[0];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 16026 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[0].RELIABILITY
    st = getVariable(16026);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[0].RELIABILITY", 48);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[0];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 16027 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[0]._INVERSED
    st = getVariable(16027);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[0]._INVERSED", 46);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[0];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 16028 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[1].VALUE
    st = getVariable(16028);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[1].VALUE", 42);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[1];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 16029 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[1].RELIABILITY
    st = getVariable(16029);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[1].RELIABILITY", 48);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[1];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 16030 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[1]._INVERSED
    st = getVariable(16030);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[1]._INVERSED", 46);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[1];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 16031 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[2].VALUE
    st = getVariable(16031);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[2].VALUE", 42);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[2];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 16032 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[2].RELIABILITY
    st = getVariable(16032);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[2].RELIABILITY", 48);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[2];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 16033 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[2]._INVERSED
    st = getVariable(16033);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[2]._INVERSED", 46);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[2];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 16034 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[3].VALUE
    st = getVariable(16034);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[3].VALUE", 42);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[3];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 16035 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[3].RELIABILITY
    st = getVariable(16035);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[3].RELIABILITY", 48);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[3];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 16036 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[3]._INVERSED
    st = getVariable(16036);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[3]._INVERSED", 46);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[3];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 16037 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[4].VALUE
    st = getVariable(16037);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[4].VALUE", 42);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[4];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 16038 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[4].RELIABILITY
    st = getVariable(16038);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[4].RELIABILITY", 48);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[4];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 16039 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[4]._INVERSED
    st = getVariable(16039);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[4]._INVERSED", 46);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[4];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 16040 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[5].VALUE
    st = getVariable(16040);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[5].VALUE", 42);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[5];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 16041 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[5].RELIABILITY
    st = getVariable(16041);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[5].RELIABILITY", 48);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[5];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 16042 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[5]._INVERSED
    st = getVariable(16042);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[5]._INVERSED", 46);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[5];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 16043 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[6].VALUE
    st = getVariable(16043);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[6].VALUE", 42);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[6];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 16044 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[6].RELIABILITY
    st = getVariable(16044);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[6].RELIABILITY", 48);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[6];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 16045 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[6]._INVERSED
    st = getVariable(16045);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[6]._INVERSED", 46);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[6];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 16046 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[7].VALUE
    st = getVariable(16046);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[7].VALUE", 42);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[7];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 16047 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[7].RELIABILITY
    st = getVariable(16047);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[7].RELIABILITY", 48);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[7];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 16048 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[7]._INVERSED
    st = getVariable(16048);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[7]._INVERSED", 46);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[7];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 16049 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[8].VALUE
    st = getVariable(16049);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[8].VALUE", 42);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[8];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 16050 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[8].RELIABILITY
    st = getVariable(16050);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[8].RELIABILITY", 48);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[8];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 16051 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[8]._INVERSED
    st = getVariable(16051);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[8]._INVERSED", 46);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[8];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 16052 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[9].VALUE
    st = getVariable(16052);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[9].VALUE", 42);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[9];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 16053 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[9].RELIABILITY
    st = getVariable(16053);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[9].RELIABILITY", 48);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[9];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 16054 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[9]._INVERSED
    st = getVariable(16054);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[9]._INVERSED", 46);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[9];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 16055 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[10].VALUE
    st = getVariable(16055);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[10].VALUE", 43);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[10];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 16056 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[10].RELIABILITY
    st = getVariable(16056);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[10].RELIABILITY", 49);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[10];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 16057 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[10]._INVERSED
    st = getVariable(16057);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[10]._INVERSED", 47);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[10];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 16058 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[11].VALUE
    st = getVariable(16058);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[11].VALUE", 43);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[11];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 16059 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[11].RELIABILITY
    st = getVariable(16059);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[11].RELIABILITY", 49);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[11];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 16060 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[11]._INVERSED
    st = getVariable(16060);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[11]._INVERSED", 47);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[11];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 16061 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[12].VALUE
    st = getVariable(16061);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[12].VALUE", 43);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[12];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 16062 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[12].RELIABILITY
    st = getVariable(16062);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[12].RELIABILITY", 49);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[12];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 16063 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[12]._INVERSED
    st = getVariable(16063);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[12]._INVERSED", 47);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[12];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 16064 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[13].VALUE
    st = getVariable(16064);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[13].VALUE", 43);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[13];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 16065 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[13].RELIABILITY
    st = getVariable(16065);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[13].RELIABILITY", 49);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[13];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 16066 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[13]._INVERSED
    st = getVariable(16066);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[13]._INVERSED", 47);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[13];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 16067 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[14].VALUE
    st = getVariable(16067);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[14].VALUE", 43);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[14];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 16068 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[14].RELIABILITY
    st = getVariable(16068);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[14].RELIABILITY", 49);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[14];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 16069 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[14]._INVERSED
    st = getVariable(16069);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[14]._INVERSED", 47);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[14];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 16070 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[15].VALUE
    st = getVariable(16070);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[15].VALUE", 43);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[15];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 16071 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[15].RELIABILITY
    st = getVariable(16071);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[15].RELIABILITY", 49);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[15];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 16072 PROGRAM0.DI_PROC.DI_10.STRDI.BITS[15]._INVERSED
    st = getVariable(16072);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BITS[15]._INVERSED", 47);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[15];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 16073 PROGRAM0.DI_PROC.DI_10.STRDI.BLCONNECT
    st = getVariable(16073);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.STRDI.BLCONNECT", 38);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p_BOOL = (BOOL*)&p_STRUCT_DI->BLCONNECT;
    st->value_p = p_BOOL;
  }
  { // 16074 PROGRAM0.DI_PROC.DI_10.BOUNCE
    st = getVariable(16074);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.BOUNCE", 29);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_BOOL = (BOOL*)&p_FB_DISOURCEMLP->BOUNCE;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 16075 PROGRAM0.DI_PROC.DI_10._VALUE
    st = getVariable(16075);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10._VALUE", 29);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_WORD = (WORD*)&p_FB_DISOURCEMLP->_VALUE;
    UnpackVar(p_WORD, WORD_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 16076 PROGRAM0.DI_PROC.DI_10._RELIABILITY
    st = getVariable(16076);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10._RELIABILITY", 35);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_BOOL = (BOOL*)&p_FB_DISOURCEMLP->_RELIABILITY;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 16077 PROGRAM0.DI_PROC.DI_10.BITNUMBER
    st = getVariable(16077);
    memcpy(st->IEC_TYPE, "INT", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.BITNUMBER", 32);
    st->size_data = sizeof(INT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_INT = (INT*)&p_FB_DISOURCEMLP->BITNUMBER;
    UnpackVar(p_INT, INT_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 16078 PROGRAM0.DI_PROC.DI_10.BITNUM
    st = getVariable(16078);
    memcpy(st->IEC_TYPE, "INT", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_10.BITNUM", 29);
    st->size_data = sizeof(INT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_10;
    p_INT = (INT*)&p_FB_DISOURCEMLP->BITNUM;
    UnpackVar(p_INT, INT_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }

  return 0;
}

// clang-format on
