// clang-format off

#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include "POUS.h"
#include <beremiz/beremiz.h>

#include "iec_types_all.h"
#include "config1.h"

extern PROGRAM0 RESOURCE1__INSTANCE0;

#ifdef DEBUG_PLC
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err][%s:%d]: " _PRNTMSG "\n", __func__, __LINE__, ##__VA_ARGS__)
#else
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err]: " _PRNTMSG "\n", ##__VA_ARGS__)
#endif // DEBUG_PLC

void UnpackVar(void* varp, __IEC_types_enum vartype, void **value_p, void **f_value_p, uint8_t **flags);

int __variables_init_FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1(){
  iec_var_t *st;

  PROGRAM0 *p_PROGRAM0;
  LREAL *p_LREAL;
  ULINT *p_ULINT;
  REAL *p_REAL;
  FB_TIMINGS *p_FB_TIMINGS;
  BOOL *p_BOOL;
  UINT *p_UINT;
  PROC_AI_INIT *p_PROC_AI_INIT;
  FB_AI_INIT *p_FB_AI_INIT;
  STRUCT_AI *p_STRUCT_AI;
  DWORD *p_DWORD;
  BYTE *p_BYTE;
  WORD *p_WORD;
  TIME *p_TIME;
  AICONFIG *p_AICONFIG;
  PROC_AI *p_PROC_AI;
  FB_AISOURCEMLP *p_FB_AISOURCEMLP;
  TITEMAIN *p_TITEMAIN;
  TITEMDIN *p_TITEMDIN;
  TYPE_STATUSAI *p_TYPE_STATUSAI;
  TYPE_COMMANDANALOG *p_TYPE_COMMANDANALOG;
  FB_SUNPACKERCOMMAND *p_FB_SUNPACKERCOMMAND;
  TYPE_ANALOGLIMITFLAGS *p_TYPE_ANALOGLIMITFLAGS;
  TON *p_TON;
  R_TRIG *p_R_TRIG;
  FB_AISOURCEMLP_TIMER *p_FB_AISOURCEMLP_TIMER;
  PROC_AO_INIT *p_PROC_AO_INIT;
  FB_AO_INIT *p_FB_AO_INIT;
  STRUCT_AO *p_STRUCT_AO;
  AOCONFIG *p_AOCONFIG;
  PROC_AO *p_PROC_AO;
  FB_AOSOURCEMLP *p_FB_AOSOURCEMLP;
  TDOUBLEDATA *p_TDOUBLEDATA;
  PROC_DI_INIT *p_PROC_DI_INIT;
  FB_DI_INIT *p_FB_DI_INIT;
  STRUCT_DI *p_STRUCT_DI;
  __IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t *p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t;
  TYPE_RELIABLEBIT *p_TYPE_RELIABLEBIT;
  DICONFIG *p_DICONFIG;
  PROC_DI *p_PROC_DI;
  FB_DISOURCEMLP *p_FB_DISOURCEMLP;
  INT *p_INT;
  UDINT *p_UDINT;
  PROC_DO_INIT *p_PROC_DO_INIT;
  FB_DO_INIT *p_FB_DO_INIT;
  STRUCT_DO *p_STRUCT_DO;
  DOCONFIG *p_DOCONFIG;
  PROC_DO *p_PROC_DO;
  FB_DOSOURCEMLP *p_FB_DOSOURCEMLP;
  TWORDDATA *p_TWORDDATA;
  OPC_ALGORITMS_SET *p_OPC_ALGORITMS_SET;
  ALGORITMSCONFIG *p_ALGORITMSCONFIG;
  STRUCT_ALG *p_STRUCT_ALG;
  STRUCT_ALGORITMSMANAGER *p_STRUCT_ALGORITMSMANAGER;
  STRUCT_PROTECTIONSMANAGER *p_STRUCT_PROTECTIONSMANAGER;
  STRUCT_ALGTIMERS *p_STRUCT_ALGTIMERS;
  ALGORITMSQUESTIONS *p_ALGORITMSQUESTIONS;
  STRUCT_QUESTION *p_STRUCT_QUESTION;
  OPC_ALGORITMS_GET *p_OPC_ALGORITMS_GET;
  PROC_IM_INIT *p_PROC_IM_INIT;
  FB_KRAN_INIT *p_FB_KRAN_INIT;
  STRUCT_KRAN *p_STRUCT_KRAN;
  FB_SWITCH_INIT *p_FB_SWITCH_INIT;
  STRUCT_SWITCH *p_STRUCT_SWITCH;
  FB_OILPUMP_INIT *p_FB_OILPUMP_INIT;
  STRUCT_OILPUMP *p_STRUCT_OILPUMP;
  FB_SECTIONSWITCH_INIT *p_FB_SECTIONSWITCH_INIT;
  STRUCT_SECTIONSWITCH *p_STRUCT_SECTIONSWITCH;
  FB_ANALOGPARAMETR_INIT *p_FB_ANALOGPARAMETR_INIT;
  STRUCT_ANALOGPARAMETR *p_STRUCT_ANALOGPARAMETR;
  FB_DISCRETPARAMETR_INIT *p_FB_DISCRETPARAMETR_INIT;
  STRUCT_DISCRETPARAMETR *p_STRUCT_DISCRETPARAMETR;
  FB_SINGLESIGNAL_INIT *p_FB_SINGLESIGNAL_INIT;
  STRUCT_SINGLESIGNAL *p_STRUCT_SINGLESIGNAL;
  FB_SINGLEOUTPUT_INIT *p_FB_SINGLEOUTPUT_INIT;
  STRUCT_SINGLEOUTPUT *p_STRUCT_SINGLEOUTPUT;
  IMCONFIG *p_IMCONFIG;
  STRUCT_RESERVEIM *p_STRUCT_RESERVEIM;
  STRUCT_RESERVEIM2 *p_STRUCT_RESERVEIM2;
  IM_SINGLESIGNALS *p_IM_SINGLESIGNALS;
  IM_SINGLEOUTPUTS *p_IM_SINGLEOUTPUTS;
  PROC_IM *p_PROC_IM;
  FB_KRAN *p_FB_KRAN;
  TYPE_STATUSDUALINPUT *p_TYPE_STATUSDUALINPUT;
  TYPE_COMMANDDUALINPUT *p_TYPE_COMMANDDUALINPUT;
  TOF *p_TOF;
  FB_OILPUMP *p_FB_OILPUMP;
  FB_SWITCH *p_FB_SWITCH;
  FB_SECTIONSWITCH *p_FB_SECTIONSWITCH;
  TYPE_BASKETSTATS *p_TYPE_BASKETSTATS;
  FB_MEANDR *p_FB_MEANDR;
  FB_SINGLESIGNAL *p_FB_SINGLESIGNAL;
  FB_SINGLEOUTPUT *p_FB_SINGLEOUTPUT;
  PROC_PROTECTIONS_INIT *p_PROC_PROTECTIONS_INIT;
  FB_DIPROTECTION_INIT *p_FB_DIPROTECTION_INIT;
  STRUCT_DIPROTECTION *p_STRUCT_DIPROTECTION;
  FB_AIPROTECTION_INIT *p_FB_AIPROTECTION_INIT;
  STRUCT_AIPROTECTION *p_STRUCT_AIPROTECTION;
  PROTECTIONSCONFIG *p_PROTECTIONSCONFIG;
  TYPE_PROTECTIONTAGS *p_TYPE_PROTECTIONTAGS;
  PROC_PROTECTION *p_PROC_PROTECTION;
  FB_MVPROTECTION *p_FB_MVPROTECTION;
  F_TRIG *p_F_TRIG;
  FB_DIPROTECTION *p_FB_DIPROTECTION;
  FB_KRANOPENPROTECTION *p_FB_KRANOPENPROTECTION;
  FB_AIPROTECTION *p_FB_AIPROTECTION;
  PROC_ALGORITMS *p_PROC_ALGORITMS;
  REMONTALG *p_REMONTALG;
  TYPE_MODEGPA *p_TYPE_MODEGPA;
  TYPE_COMMANDSPOTECTIONSMANAGER *p_TYPE_COMMANDSPOTECTIONSMANAGER;
  TESTPROTECTIONALG *p_TESTPROTECTIONALG;
  TESTIMALG *p_TESTIMALG;
  FB_AUTOTENALG *p_FB_AUTOTENALG;
  FB_AUTOPNSALG *p_FB_AUTOPNSALG;
  FB_AUTOAVOMALG *p_FB_AUTOAVOMALG;
  FB_VIBEGPNSALG *p_FB_VIBEGPNSALG;
  STRUCT_PHASEALGORITM *p_STRUCT_PHASEALGORITM;
  FB_PH_ALGORITM *p_FB_PH_ALGORITM;
  FB_PH_TIMER *p_FB_PH_TIMER;
  FB_QUESTION *p_FB_QUESTION;
  TYPE_ANSWERS *p_TYPE_ANSWERS;
  FB_PH_SWITCH *p_FB_PH_SWITCH;
  FB_PH_CUSTOMPHASE *p_FB_PH_CUSTOMPHASE;
  FB_AUTONUALG *p_FB_AUTONUALG;
  FB_PUSKOILSYSTEMALG *p_FB_PUSKOILSYSTEMALG;
  FB_PH_WAITANALOGVALUE *p_FB_PH_WAITANALOGVALUE;
  FB_PH_OILPUMP *p_FB_PH_OILPUMP;
  FB_ANTIPOMPAGALG *p_FB_ANTIPOMPAGALG;
  FB_TABLEVALUE_MIN *p_FB_TABLEVALUE_MIN;
  __IEC___ARRAY_OF_TYPE_TABLEREC_9_t *p___IEC___ARRAY_OF_TYPE_TABLEREC_9_t;
  TYPE_TABLEREC *p_TYPE_TABLEREC;
  FB_TABLEVALUE_MAX *p_FB_TABLEVALUE_MAX;
  FB_RASHODALG *p_FB_RASHODALG;
  FB_ZAPASALG *p_FB_ZAPASALG;
  NOALG *p_NOALG;
  FB_PH_KRAN *p_FB_PH_KRAN;
  FB_PH_SECTIONSWITCH *p_FB_PH_SECTIONSWITCH;
  AOALG *p_AOALG;
  PPUALG *p_PPUALG;
  FILLINGALG *p_FILLINGALG;
  FB_PH_DIPROTECTION *p_FB_PH_DIPROTECTION;
  ENGINERUNALG *p_ENGINERUNALG;
  PUSKKALG *p_PUSKKALG;
  PUSKVALG *p_PUSKVALG;
  TESTDPMGALG *p_TESTDPMGALG;
  TESTPMSALG *p_TESTPMSALG;
  FB_PH_AIPROTECTION *p_FB_PH_AIPROTECTION;
  APUSKALG *p_APUSKALG;
  SEMIAUTOPUSKALG *p_SEMIAUTOPUSKALG;
  FB_ALGORITMSMANAGER *p_FB_ALGORITMSMANAGER;
  FB_PROTECTIONSMANAGER *p_FB_PROTECTIONSMANAGER;

  { // 31053 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.VALUE
    st = getVariable(31053);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.VALUE", 68);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->VALUE;
    st->value_p = p_LREAL;
  }
  { // 31054 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.STATUS
    st = getVariable(31054);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.STATUS", 69);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_DWORD = (DWORD*)&p_STRUCT_AI->STATUS;
    st->value_p = p_DWORD;
  }
  { // 31055 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.INTERVAL
    st = getVariable(31055);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.INTERVAL", 71);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BYTE = (BYTE*)&p_STRUCT_AI->INTERVAL;
    st->value_p = p_BYTE;
  }
  { // 31056 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.INCOMMAND
    st = getVariable(31056);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.INCOMMAND", 72);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 31057 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.BLCONNECT
    st = getVariable(31057);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.BLCONNECT", 72);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->BLCONNECT;
    st->value_p = p_BOOL;
  }
  { // 31058 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DLL
    st = getVariable(31058);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DLL", 66);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLL;
    st->value_p = p_LREAL;
  }
  { // 31059 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DHL
    st = getVariable(31059);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DHL", 66);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHL;
    st->value_p = p_LREAL;
  }
  { // 31060 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DLA
    st = getVariable(31060);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DLA", 66);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLA;
    st->value_p = p_LREAL;
  }
  { // 31061 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DHA
    st = getVariable(31061);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DHA", 66);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHA;
    st->value_p = p_LREAL;
  }
  { // 31062 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DLW
    st = getVariable(31062);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DLW", 66);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLW;
    st->value_p = p_LREAL;
  }
  { // 31063 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DHW
    st = getVariable(31063);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DHW", 66);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHW;
    st->value_p = p_LREAL;
  }
  { // 31064 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.LL
    st = getVariable(31064);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.LL", 65);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LL;
    st->value_p = p_LREAL;
  }
  { // 31065 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.HL
    st = getVariable(31065);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.HL", 65);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HL;
    st->value_p = p_LREAL;
  }
  { // 31066 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.LA
    st = getVariable(31066);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.LA", 65);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LA;
    st->value_p = p_LREAL;
  }
  { // 31067 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.HA
    st = getVariable(31067);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.HA", 65);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HA;
    st->value_p = p_LREAL;
  }
  { // 31068 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.LW
    st = getVariable(31068);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.LW", 65);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LW;
    st->value_p = p_LREAL;
  }
  { // 31069 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.HW
    st = getVariable(31069);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.HW", 65);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HW;
    st->value_p = p_LREAL;
  }
  { // 31070 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.ISVALIDREF_LA
    st = getVariable(31070);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.ISVALIDREF_LA", 76);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_LA;
    st->value_p = p_BOOL;
  }
  { // 31071 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.ISVALIDREF_HA
    st = getVariable(31071);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.ISVALIDREF_HA", 76);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_HA;
    st->value_p = p_BOOL;
  }
  { // 31072 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.ISVALIDREF_LW
    st = getVariable(31072);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.ISVALIDREF_LW", 76);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_LW;
    st->value_p = p_BOOL;
  }
  { // 31073 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.ISVALIDREF_HW
    st = getVariable(31073);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.ISVALIDREF_HW", 76);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_HW;
    st->value_p = p_BOOL;
  }
  { // 31074 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.INPLL
    st = getVariable(31074);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.INPLL", 68);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->INPLL;
    st->value_p = p_LREAL;
  }
  { // 31075 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.INPHL
    st = getVariable(31075);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.INPHL", 68);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->INPHL;
    st->value_p = p_LREAL;
  }
  { // 31076 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.CURRENTSHOTCIRCUIT
    st = getVariable(31076);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.CURRENTSHOTCIRCUIT", 81);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CURRENTSHOTCIRCUIT;
    st->value_p = p_LREAL;
  }
  { // 31077 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.CURRENTBREAKCIRCUIT
    st = getVariable(31077);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.CURRENTBREAKCIRCUIT", 82);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CURRENTBREAKCIRCUIT;
    st->value_p = p_LREAL;
  }
  { // 31078 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.MAXCHANGESPEED
    st = getVariable(31078);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.MAXCHANGESPEED", 77);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXCHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 31079 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.MAXCHANGESPEEDDOWN
    st = getVariable(31079);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.MAXCHANGESPEEDDOWN", 81);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXCHANGESPEEDDOWN;
    st->value_p = p_LREAL;
  }
  { // 31080 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.CHANGESPEED
    st = getVariable(31080);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.CHANGESPEED", 74);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 31081 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.HISTERESIS
    st = getVariable(31081);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.HISTERESIS", 73);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HISTERESIS;
    st->value_p = p_LREAL;
  }
  { // 31082 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.APERTURFILTER
    st = getVariable(31082);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.APERTURFILTER", 76);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->APERTURFILTER;
    st->value_p = p_LREAL;
  }
  { // 31083 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.EXPONENTIALFILTER
    st = getVariable(31083);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.EXPONENTIALFILTER", 80);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->EXPONENTIALFILTER;
    st->value_p = p_LREAL;
  }
  { // 31084 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.RASSOGLASOVANIE
    st = getVariable(31084);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.RASSOGLASOVANIE", 78);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->RASSOGLASOVANIE;
    st->value_p = p_LREAL;
  }
  { // 31085 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.OPCCOMMANDSDISABLED
    st = getVariable(31085);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.OPCCOMMANDSDISABLED", 82);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 31086 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DISABLED_LA
    st = getVariable(31086);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DISABLED_LA", 74);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_LA;
    st->value_p = p_BOOL;
  }
  { // 31087 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DISABLED_HA
    st = getVariable(31087);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DISABLED_HA", 74);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_HA;
    st->value_p = p_BOOL;
  }
  { // 31088 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DISABLED_LW
    st = getVariable(31088);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DISABLED_LW", 74);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_LW;
    st->value_p = p_BOOL;
  }
  { // 31089 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DISABLED_HW
    st = getVariable(31089);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DISABLED_HW", 74);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_HW;
    st->value_p = p_BOOL;
  }
  { // 31090 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DELAYLA
    st = getVariable(31090);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DELAYLA", 70);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYLA;
    st->value_p = p_TIME;
  }
  { // 31091 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DELAYLW
    st = getVariable(31091);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DELAYLW", 70);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYLW;
    st->value_p = p_TIME;
  }
  { // 31092 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DELAYHW
    st = getVariable(31092);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DELAYHW", 70);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYHW;
    st->value_p = p_TIME;
  }
  { // 31093 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DELAYHA
    st = getVariable(31093);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DELAYHA", 70);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYHA;
    st->value_p = p_TIME;
  }
  { // 31094 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.MINVALUE_ISVALIDREF
    st = getVariable(31094);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.MINVALUE_ISVALIDREF", 82);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->MINVALUE_ISVALIDREF;
    st->value_p = p_BOOL;
  }
  { // 31095 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.MAXVALUE_ISVALIDREF
    st = getVariable(31095);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.MAXVALUE_ISVALIDREF", 82);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->MAXVALUE_ISVALIDREF;
    st->value_p = p_BOOL;
  }
  { // 31096 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.MINVALUE
    st = getVariable(31096);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.MINVALUE", 71);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MINVALUE;
    st->value_p = p_LREAL;
  }
  { // 31097 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.MAXVALUE
    st = getVariable(31097);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.MAXVALUE", 71);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXVALUE;
    st->value_p = p_LREAL;
  }
  { // 31098 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.INOPCCOMMANDSDISABLED
    st = getVariable(31098);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.INOPCCOMMANDSDISABLED", 84);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 31099 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.IMIT
    st = getVariable(31099);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.IMIT", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->IMIT;
    st->value_p = p_BOOL;
  }
  { // 31100 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.REMONT
    st = getVariable(31100);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.REMONT", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->REMONT;
    st->value_p = p_BOOL;
  }
  { // 31101 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.NS
    st = getVariable(31101);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.NS", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS;
    st->value_p = p_BOOL;
  }
  { // 31102 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.NS_MIN
    st = getVariable(31102);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.NS_MIN", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS_MIN;
    st->value_p = p_BOOL;
  }
  { // 31103 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.NS_MAX
    st = getVariable(31103);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.NS_MAX", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS_MAX;
    st->value_p = p_BOOL;
  }
  { // 31104 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.INCOMMAND_ALG
    st = getVariable(31104);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.INCOMMAND_ALG", 76);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 31105 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.INCOMMAND_ARM
    st = getVariable(31105);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.INCOMMAND_ARM", 76);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 31106 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DMAXCHANGESPEED
    st = getVariable(31106);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DMAXCHANGESPEED", 78);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DMAXCHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 31107 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DMAXCHANGESPEEDDOWN
    st = getVariable(31107);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.AI.DMAXCHANGESPEEDDOWN", 82);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DMAXCHANGESPEEDDOWN;
    st->value_p = p_LREAL;
  }
  { // 31108 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.CONTROLLIMIT
    st = getVariable(31108);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.CONTROLLIMIT", 79);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BYTE = (BYTE*)&p_STRUCT_AIPROTECTION->CONTROLLIMIT;
    st->value_p = p_BYTE;
  }
  { // 31109 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.DELAY
    st = getVariable(31109);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.DELAY", 72);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_TIME = (TIME*)&p_STRUCT_AIPROTECTION->DELAY;
    st->value_p = p_TIME;
  }
  { // 31110 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.INTAG
    st = getVariable(31110);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.INTAG", 72);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BYTE = (BYTE*)&p_STRUCT_AIPROTECTION->INTAG;
    st->value_p = p_BYTE;
  }
  { // 31111 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.INRUNONSTART
    st = getVariable(31111);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.INRUNONSTART", 79);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->INRUNONSTART;
    st->value_p = p_BOOL;
  }
  { // 31112 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.INCANRUN
    st = getVariable(31112);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.INCANRUN", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->INCANRUN;
    st->value_p = p_BOOL;
  }
  { // 31113 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.INOPCCOMMANDSDISABLED
    st = getVariable(31113);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.INOPCCOMMANDSDISABLED", 88);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 31114 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.INCOMMAND
    st = getVariable(31114);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.INCOMMAND", 76);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_WORD = (WORD*)&p_STRUCT_AIPROTECTION->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 31115 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.INCOMMAND_ALG
    st = getVariable(31115);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.INCOMMAND_ALG", 80);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_WORD = (WORD*)&p_STRUCT_AIPROTECTION->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 31116 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.INCOMMAND_ARM
    st = getVariable(31116);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.INCOMMAND_ARM", 80);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_WORD = (WORD*)&p_STRUCT_AIPROTECTION->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 31117 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.TAG
    st = getVariable(31117);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.TAG", 70);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BYTE = (BYTE*)&p_STRUCT_AIPROTECTION->TAG;
    st->value_p = p_BYTE;
  }
  { // 31118 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.STATUS
    st = getVariable(31118);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.STATUS", 73);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_DWORD = (DWORD*)&p_STRUCT_AIPROTECTION->STATUS;
    st->value_p = p_DWORD;
  }
  { // 31119 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.CANRUN
    st = getVariable(31119);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.CANRUN", 73);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->CANRUN;
    st->value_p = p_BOOL;
  }
  { // 31120 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.OPCCOMMANDSDISABLED
    st = getVariable(31120);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.OPCCOMMANDSDISABLED", 86);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 31121 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.ISRUNNING
    st = getVariable(31121);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.ISRUNNING", 76);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->ISRUNNING;
    st->value_p = p_BOOL;
  }
  { // 31122 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.HASERROR
    st = getVariable(31122);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.HASERROR", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->HASERROR;
    st->value_p = p_BOOL;
  }
  { // 31123 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.ISENDED
    st = getVariable(31123);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.ISENDED", 74);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->ISENDED;
    st->value_p = p_BOOL;
  }
  { // 31124 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.REMONT
    st = getVariable(31124);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.REMONT", 73);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->REMONT;
    st->value_p = p_BOOL;
  }
  { // 31125 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.CHECK
    st = getVariable(31125);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.CHECK", 72);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->CHECK;
    st->value_p = p_BOOL;
  }
  { // 31126 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.SIGNALING
    st = getVariable(31126);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.SIGNALING", 76);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->SIGNALING;
    st->value_p = p_BOOL;
  }
  { // 31127 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.SIGNALINGTP
    st = getVariable(31127);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.SIGNALINGTP", 78);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->SIGNALINGTP;
    st->value_p = p_BOOL;
  }
  { // 31128 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.RUNONSTART
    st = getVariable(31128);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.STRAIP.RUNONSTART", 77);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->RUNONSTART;
    st->value_p = p_BOOL;
  }
  { // 31133 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._SIGNALINGTP.IN
    st = getVariable(31133);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._SIGNALINGTP.IN", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    p_BOOL = (BOOL*)&p_TOF->IN;
    st->value_p = p_BOOL;
  }
  { // 31134 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._SIGNALINGTP.PT
    st = getVariable(31134);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._SIGNALINGTP.PT", 75);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    p_TIME = (TIME*)&p_TOF->PT;
    st->value_p = p_TIME;
  }
  { // 31135 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._SIGNALINGTP.Q
    st = getVariable(31135);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._SIGNALINGTP.Q", 74);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    p_BOOL = (BOOL*)&p_TOF->Q;
    st->value_p = p_BOOL;
  }
  { // 31136 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._SIGNALINGTP.ET
    st = getVariable(31136);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._SIGNALINGTP.ET", 75);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    p_TIME = (TIME*)&p_TOF->ET;
    st->value_p = p_TIME;
  }
  { // 31137 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._SIGNALINGTP
    st = getVariable(31137);
    memcpy(st->IEC_TYPE, "TOF", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._SIGNALINGTP", 72);
    st->size_data = sizeof(TOF);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    st->value_p = (void *)p_TOF;
  }
  { // 31138 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._STATUSAI.NOTDEFINED
    st = getVariable(31138);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._STATUSAI.NOTDEFINED", 80);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NOTDEFINED;
    st->value_p = p_BYTE;
  }
  { // 31139 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._STATUSAI.LL
    st = getVariable(31139);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._STATUSAI.LL", 72);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LL;
    st->value_p = p_BYTE;
  }
  { // 31140 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._STATUSAI.HL
    st = getVariable(31140);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._STATUSAI.HL", 72);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HL;
    st->value_p = p_BYTE;
  }
  { // 31141 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._STATUSAI.NOTRELIABLE
    st = getVariable(31141);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._STATUSAI.NOTRELIABLE", 81);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NOTRELIABLE;
    st->value_p = p_BYTE;
  }
  { // 31142 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._STATUSAI.NORMAL
    st = getVariable(31142);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._STATUSAI.NORMAL", 76);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NORMAL;
    st->value_p = p_BYTE;
  }
  { // 31143 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._STATUSAI.LW
    st = getVariable(31143);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._STATUSAI.LW", 72);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LW;
    st->value_p = p_BYTE;
  }
  { // 31144 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._STATUSAI.HW
    st = getVariable(31144);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._STATUSAI.HW", 72);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HW;
    st->value_p = p_BYTE;
  }
  { // 31145 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._STATUSAI.LA
    st = getVariable(31145);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._STATUSAI.LA", 72);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LA;
    st->value_p = p_BYTE;
  }
  { // 31146 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._STATUSAI.HA
    st = getVariable(31146);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1._STATUSAI.HA", 72);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HA;
    st->value_p = p_BYTE;
  }
  { // 31147 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SOURCE
    st = getVariable(31147);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SOURCE", 66);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->SOURCE;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 31148 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.CMD
    st = getVariable(31148);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.CMD", 63);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->CMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 31149 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.LASTCMD
    st = getVariable(31149);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.LASTCMD", 67);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->LASTCMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 31150 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SOURCE_FOR_STATUS
    st = getVariable(31150);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SOURCE_FOR_STATUS", 77);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->SOURCE_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 31151 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.CMD_FOR_STATUS
    st = getVariable(31151);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.CMD_FOR_STATUS", 74);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->CMD_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 31152 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.COMMAND_ERROR_FOR_STATUS
    st = getVariable(31152);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.COMMAND_ERROR_FOR_STATUS", 84);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->COMMAND_ERROR_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 31153 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.RESETCMDTIMER.IN
    st = getVariable(31153);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.RESETCMDTIMER.IN", 76);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 31154 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.RESETCMDTIMER.PT
    st = getVariable(31154);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.RESETCMDTIMER.PT", 76);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 31155 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.RESETCMDTIMER.Q
    st = getVariable(31155);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.RESETCMDTIMER.Q", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 31156 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.RESETCMDTIMER.ET
    st = getVariable(31156);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.RESETCMDTIMER.ET", 76);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 31157 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.RESETCMDTIMER
    st = getVariable(31157);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.RESETCMDTIMER", 73);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    st->value_p = (void *)p_TON;
  }
  { // 31158 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.RESETCMDTIMERPRIZNAK
    st = getVariable(31158);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.RESETCMDTIMERPRIZNAK", 80);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_BOOL = (BOOL*)&p_FB_AIPROTECTION->RESETCMDTIMERPRIZNAK;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 31159 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SIGNALINTIMER.IN
    st = getVariable(31159);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SIGNALINTIMER.IN", 76);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 31160 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SIGNALINTIMER.PT
    st = getVariable(31160);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SIGNALINTIMER.PT", 76);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 31161 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SIGNALINTIMER.Q
    st = getVariable(31161);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SIGNALINTIMER.Q", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 31162 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SIGNALINTIMER.ET
    st = getVariable(31162);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SIGNALINTIMER.ET", 76);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 31163 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SIGNALINTIMER
    st = getVariable(31163);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SIGNALINTIMER", 73);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    st->value_p = (void *)p_TON;
  }
  { // 31164 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.TIMER.IN
    st = getVariable(31164);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.TIMER.IN", 68);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 31165 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.TIMER.PT
    st = getVariable(31165);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.TIMER.PT", 68);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 31166 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.TIMER.Q
    st = getVariable(31166);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.TIMER.Q", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 31167 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.TIMER.ET
    st = getVariable(31167);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.TIMER.ET", 68);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 31168 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.TIMER
    st = getVariable(31168);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.TIMER", 65);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    st->value_p = (void *)p_TON;
  }
  { // 31169 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SIGNALINGTRIG.CLK
    st = getVariable(31169);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SIGNALINGTRIG.CLK", 77);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_R_TRIG = (R_TRIG*)&p_FB_AIPROTECTION->SIGNALINGTRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 31170 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SIGNALINGTRIG.Q
    st = getVariable(31170);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SIGNALINGTRIG.Q", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_R_TRIG = (R_TRIG*)&p_FB_AIPROTECTION->SIGNALINGTRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 31171 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SIGNALINGTRIG
    st = getVariable(31171);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SIGNALINGTRIG", 73);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_R_TRIG = (R_TRIG*)&p_FB_AIPROTECTION->SIGNALINGTRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 31172 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SIGNALINGFTRIG.CLK
    st = getVariable(31172);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SIGNALINGFTRIG.CLK", 78);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_F_TRIG = (F_TRIG*)&p_FB_AIPROTECTION->SIGNALINGFTRIG;
    p_BOOL = (BOOL*)&p_F_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 31173 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SIGNALINGFTRIG.Q
    st = getVariable(31173);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SIGNALINGFTRIG.Q", 76);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_F_TRIG = (F_TRIG*)&p_FB_AIPROTECTION->SIGNALINGFTRIG;
    p_BOOL = (BOOL*)&p_F_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 31174 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SIGNALINGFTRIG
    st = getVariable(31174);
    memcpy(st->IEC_TYPE, "F_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SIGNALINGFTRIG", 74);
    st->size_data = sizeof(F_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_F_TRIG = (F_TRIG*)&p_FB_AIPROTECTION->SIGNALINGFTRIG;
    st->value_p = (void *)p_F_TRIG;
  }
  { // 31175 PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SIGNALINGAI
    st = getVariable(31175);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1.SIGNALINGAI", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TGORJACHEGO_VOZDUHA_ED_KANAL_1;
    p_BOOL = (BOOL*)&p_FB_AIPROTECTION->SIGNALINGAI;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }

  return 0;
}

// clang-format on
