// clang-format off

#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include "POUS.h"
#include <beremiz/beremiz.h>

#include "iec_types_all.h"
#include "config1.h"

extern PROGRAM0 RESOURCE1__INSTANCE0;

#ifdef DEBUG_PLC
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err][%s:%d]: " _PRNTMSG "\n", __func__, __LINE__, ##__VA_ARGS__)
#else
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err]: " _PRNTMSG "\n", ##__VA_ARGS__)
#endif // DEBUG_PLC

void UnpackVar(void* varp, __IEC_types_enum vartype, void **value_p, void **f_value_p, uint8_t **flags);

int __variables_init_FB_TOY_PODSHIPNIKA_KOL_EDT_4(){
  iec_var_t *st;

  PROGRAM0 *p_PROGRAM0;
  LREAL *p_LREAL;
  ULINT *p_ULINT;
  REAL *p_REAL;
  FB_TIMINGS *p_FB_TIMINGS;
  BOOL *p_BOOL;
  UINT *p_UINT;
  PROC_AI_INIT *p_PROC_AI_INIT;
  FB_AI_INIT *p_FB_AI_INIT;
  STRUCT_AI *p_STRUCT_AI;
  DWORD *p_DWORD;
  BYTE *p_BYTE;
  WORD *p_WORD;
  TIME *p_TIME;
  AICONFIG *p_AICONFIG;
  PROC_AI *p_PROC_AI;
  FB_AISOURCEMLP *p_FB_AISOURCEMLP;
  TITEMAIN *p_TITEMAIN;
  TITEMDIN *p_TITEMDIN;
  TYPE_STATUSAI *p_TYPE_STATUSAI;
  TYPE_COMMANDANALOG *p_TYPE_COMMANDANALOG;
  FB_SUNPACKERCOMMAND *p_FB_SUNPACKERCOMMAND;
  TYPE_ANALOGLIMITFLAGS *p_TYPE_ANALOGLIMITFLAGS;
  TON *p_TON;
  R_TRIG *p_R_TRIG;
  FB_AISOURCEMLP_TIMER *p_FB_AISOURCEMLP_TIMER;
  PROC_AO_INIT *p_PROC_AO_INIT;
  FB_AO_INIT *p_FB_AO_INIT;
  STRUCT_AO *p_STRUCT_AO;
  AOCONFIG *p_AOCONFIG;
  PROC_AO *p_PROC_AO;
  FB_AOSOURCEMLP *p_FB_AOSOURCEMLP;
  TDOUBLEDATA *p_TDOUBLEDATA;
  PROC_DI_INIT *p_PROC_DI_INIT;
  FB_DI_INIT *p_FB_DI_INIT;
  STRUCT_DI *p_STRUCT_DI;
  __IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t *p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t;
  TYPE_RELIABLEBIT *p_TYPE_RELIABLEBIT;
  DICONFIG *p_DICONFIG;
  PROC_DI *p_PROC_DI;
  FB_DISOURCEMLP *p_FB_DISOURCEMLP;
  INT *p_INT;
  UDINT *p_UDINT;
  PROC_DO_INIT *p_PROC_DO_INIT;
  FB_DO_INIT *p_FB_DO_INIT;
  STRUCT_DO *p_STRUCT_DO;
  DOCONFIG *p_DOCONFIG;
  PROC_DO *p_PROC_DO;
  FB_DOSOURCEMLP *p_FB_DOSOURCEMLP;
  TWORDDATA *p_TWORDDATA;
  OPC_ALGORITMS_SET *p_OPC_ALGORITMS_SET;
  ALGORITMSCONFIG *p_ALGORITMSCONFIG;
  STRUCT_ALG *p_STRUCT_ALG;
  STRUCT_ALGORITMSMANAGER *p_STRUCT_ALGORITMSMANAGER;
  STRUCT_PROTECTIONSMANAGER *p_STRUCT_PROTECTIONSMANAGER;
  STRUCT_ALGTIMERS *p_STRUCT_ALGTIMERS;
  ALGORITMSQUESTIONS *p_ALGORITMSQUESTIONS;
  STRUCT_QUESTION *p_STRUCT_QUESTION;
  OPC_ALGORITMS_GET *p_OPC_ALGORITMS_GET;
  PROC_IM_INIT *p_PROC_IM_INIT;
  FB_KRAN_INIT *p_FB_KRAN_INIT;
  STRUCT_KRAN *p_STRUCT_KRAN;
  FB_SWITCH_INIT *p_FB_SWITCH_INIT;
  STRUCT_SWITCH *p_STRUCT_SWITCH;
  FB_OILPUMP_INIT *p_FB_OILPUMP_INIT;
  STRUCT_OILPUMP *p_STRUCT_OILPUMP;
  FB_SECTIONSWITCH_INIT *p_FB_SECTIONSWITCH_INIT;
  STRUCT_SECTIONSWITCH *p_STRUCT_SECTIONSWITCH;
  FB_ANALOGPARAMETR_INIT *p_FB_ANALOGPARAMETR_INIT;
  STRUCT_ANALOGPARAMETR *p_STRUCT_ANALOGPARAMETR;
  FB_DISCRETPARAMETR_INIT *p_FB_DISCRETPARAMETR_INIT;
  STRUCT_DISCRETPARAMETR *p_STRUCT_DISCRETPARAMETR;
  FB_SINGLESIGNAL_INIT *p_FB_SINGLESIGNAL_INIT;
  STRUCT_SINGLESIGNAL *p_STRUCT_SINGLESIGNAL;
  FB_SINGLEOUTPUT_INIT *p_FB_SINGLEOUTPUT_INIT;
  STRUCT_SINGLEOUTPUT *p_STRUCT_SINGLEOUTPUT;
  IMCONFIG *p_IMCONFIG;
  STRUCT_RESERVEIM *p_STRUCT_RESERVEIM;
  STRUCT_RESERVEIM2 *p_STRUCT_RESERVEIM2;
  IM_SINGLESIGNALS *p_IM_SINGLESIGNALS;
  IM_SINGLEOUTPUTS *p_IM_SINGLEOUTPUTS;
  PROC_IM *p_PROC_IM;
  FB_KRAN *p_FB_KRAN;
  TYPE_STATUSDUALINPUT *p_TYPE_STATUSDUALINPUT;
  TYPE_COMMANDDUALINPUT *p_TYPE_COMMANDDUALINPUT;
  TOF *p_TOF;
  FB_OILPUMP *p_FB_OILPUMP;
  FB_SWITCH *p_FB_SWITCH;
  FB_SECTIONSWITCH *p_FB_SECTIONSWITCH;
  TYPE_BASKETSTATS *p_TYPE_BASKETSTATS;
  FB_MEANDR *p_FB_MEANDR;
  FB_SINGLESIGNAL *p_FB_SINGLESIGNAL;
  FB_SINGLEOUTPUT *p_FB_SINGLEOUTPUT;
  PROC_PROTECTIONS_INIT *p_PROC_PROTECTIONS_INIT;
  FB_DIPROTECTION_INIT *p_FB_DIPROTECTION_INIT;
  STRUCT_DIPROTECTION *p_STRUCT_DIPROTECTION;
  FB_AIPROTECTION_INIT *p_FB_AIPROTECTION_INIT;
  STRUCT_AIPROTECTION *p_STRUCT_AIPROTECTION;
  PROTECTIONSCONFIG *p_PROTECTIONSCONFIG;
  TYPE_PROTECTIONTAGS *p_TYPE_PROTECTIONTAGS;
  PROC_PROTECTION *p_PROC_PROTECTION;
  FB_MVPROTECTION *p_FB_MVPROTECTION;
  F_TRIG *p_F_TRIG;
  FB_DIPROTECTION *p_FB_DIPROTECTION;
  FB_KRANOPENPROTECTION *p_FB_KRANOPENPROTECTION;
  FB_AIPROTECTION *p_FB_AIPROTECTION;
  PROC_ALGORITMS *p_PROC_ALGORITMS;
  REMONTALG *p_REMONTALG;
  TYPE_MODEGPA *p_TYPE_MODEGPA;
  TYPE_COMMANDSPOTECTIONSMANAGER *p_TYPE_COMMANDSPOTECTIONSMANAGER;
  TESTPROTECTIONALG *p_TESTPROTECTIONALG;
  TESTIMALG *p_TESTIMALG;
  FB_AUTOTENALG *p_FB_AUTOTENALG;
  FB_AUTOPNSALG *p_FB_AUTOPNSALG;
  FB_AUTOAVOMALG *p_FB_AUTOAVOMALG;
  FB_VIBEGPNSALG *p_FB_VIBEGPNSALG;
  STRUCT_PHASEALGORITM *p_STRUCT_PHASEALGORITM;
  FB_PH_ALGORITM *p_FB_PH_ALGORITM;
  FB_PH_TIMER *p_FB_PH_TIMER;
  FB_QUESTION *p_FB_QUESTION;
  TYPE_ANSWERS *p_TYPE_ANSWERS;
  FB_PH_SWITCH *p_FB_PH_SWITCH;
  FB_PH_CUSTOMPHASE *p_FB_PH_CUSTOMPHASE;
  FB_AUTONUALG *p_FB_AUTONUALG;
  FB_PUSKOILSYSTEMALG *p_FB_PUSKOILSYSTEMALG;
  FB_PH_WAITANALOGVALUE *p_FB_PH_WAITANALOGVALUE;
  FB_PH_OILPUMP *p_FB_PH_OILPUMP;
  FB_ANTIPOMPAGALG *p_FB_ANTIPOMPAGALG;
  FB_TABLEVALUE_MIN *p_FB_TABLEVALUE_MIN;
  __IEC___ARRAY_OF_TYPE_TABLEREC_9_t *p___IEC___ARRAY_OF_TYPE_TABLEREC_9_t;
  TYPE_TABLEREC *p_TYPE_TABLEREC;
  FB_TABLEVALUE_MAX *p_FB_TABLEVALUE_MAX;
  FB_RASHODALG *p_FB_RASHODALG;
  FB_ZAPASALG *p_FB_ZAPASALG;
  NOALG *p_NOALG;
  FB_PH_KRAN *p_FB_PH_KRAN;
  FB_PH_SECTIONSWITCH *p_FB_PH_SECTIONSWITCH;
  AOALG *p_AOALG;
  PPUALG *p_PPUALG;
  FILLINGALG *p_FILLINGALG;
  FB_PH_DIPROTECTION *p_FB_PH_DIPROTECTION;
  ENGINERUNALG *p_ENGINERUNALG;
  PUSKKALG *p_PUSKKALG;
  PUSKVALG *p_PUSKVALG;
  TESTDPMGALG *p_TESTDPMGALG;
  TESTPMSALG *p_TESTPMSALG;
  FB_PH_AIPROTECTION *p_FB_PH_AIPROTECTION;
  APUSKALG *p_APUSKALG;
  SEMIAUTOPUSKALG *p_SEMIAUTOPUSKALG;
  PUSK_FIRST_FAZA1 *p_PUSK_FIRST_FAZA1;
  PUSK_FIRST_FAZA2 *p_PUSK_FIRST_FAZA2;
  PUSK_THIRD_FAZA *p_PUSK_THIRD_FAZA;
  PROV_PMS *p_PROV_PMS;
  PROV_OPRESSOVKA *p_PROV_OPRESSOVKA;
  PUSK_SECOND_FAZA_CHASTOTNY *p_PUSK_SECOND_FAZA_CHASTOTNY;
  PUSK_SECOND_FAZA_REACTOR *p_PUSK_SECOND_FAZA_REACTOR;
  FB_ALGORITMSMANAGER *p_FB_ALGORITMSMANAGER;
  FB_PROTECTIONSMANAGER *p_FB_PROTECTIONSMANAGER;

  { // 29277 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.VALUE
    st = getVariable(29277);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.VALUE", 63);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->VALUE;
    st->value_p = p_LREAL;
  }
  { // 29278 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.STATUS
    st = getVariable(29278);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.STATUS", 64);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_DWORD = (DWORD*)&p_STRUCT_AI->STATUS;
    st->value_p = p_DWORD;
  }
  { // 29279 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.INTERVAL
    st = getVariable(29279);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.INTERVAL", 66);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BYTE = (BYTE*)&p_STRUCT_AI->INTERVAL;
    st->value_p = p_BYTE;
  }
  { // 29280 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.INCOMMAND
    st = getVariable(29280);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.INCOMMAND", 67);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 29281 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.BLCONNECT
    st = getVariable(29281);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.BLCONNECT", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->BLCONNECT;
    st->value_p = p_BOOL;
  }
  { // 29282 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DLL
    st = getVariable(29282);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DLL", 61);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLL;
    st->value_p = p_LREAL;
  }
  { // 29283 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DHL
    st = getVariable(29283);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DHL", 61);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHL;
    st->value_p = p_LREAL;
  }
  { // 29284 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DLA
    st = getVariable(29284);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DLA", 61);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLA;
    st->value_p = p_LREAL;
  }
  { // 29285 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DHA
    st = getVariable(29285);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DHA", 61);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHA;
    st->value_p = p_LREAL;
  }
  { // 29286 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DLW
    st = getVariable(29286);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DLW", 61);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLW;
    st->value_p = p_LREAL;
  }
  { // 29287 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DHW
    st = getVariable(29287);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DHW", 61);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHW;
    st->value_p = p_LREAL;
  }
  { // 29288 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.LL
    st = getVariable(29288);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.LL", 60);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LL;
    st->value_p = p_LREAL;
  }
  { // 29289 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.HL
    st = getVariable(29289);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.HL", 60);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HL;
    st->value_p = p_LREAL;
  }
  { // 29290 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.LA
    st = getVariable(29290);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.LA", 60);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LA;
    st->value_p = p_LREAL;
  }
  { // 29291 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.HA
    st = getVariable(29291);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.HA", 60);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HA;
    st->value_p = p_LREAL;
  }
  { // 29292 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.LW
    st = getVariable(29292);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.LW", 60);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LW;
    st->value_p = p_LREAL;
  }
  { // 29293 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.HW
    st = getVariable(29293);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.HW", 60);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HW;
    st->value_p = p_LREAL;
  }
  { // 29294 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.ISVALIDREF_LA
    st = getVariable(29294);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.ISVALIDREF_LA", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_LA;
    st->value_p = p_BOOL;
  }
  { // 29295 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.ISVALIDREF_HA
    st = getVariable(29295);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.ISVALIDREF_HA", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_HA;
    st->value_p = p_BOOL;
  }
  { // 29296 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.ISVALIDREF_LW
    st = getVariable(29296);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.ISVALIDREF_LW", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_LW;
    st->value_p = p_BOOL;
  }
  { // 29297 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.ISVALIDREF_HW
    st = getVariable(29297);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.ISVALIDREF_HW", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_HW;
    st->value_p = p_BOOL;
  }
  { // 29298 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.INPLL
    st = getVariable(29298);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.INPLL", 63);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->INPLL;
    st->value_p = p_LREAL;
  }
  { // 29299 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.INPHL
    st = getVariable(29299);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.INPHL", 63);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->INPHL;
    st->value_p = p_LREAL;
  }
  { // 29300 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.CURRENTSHOTCIRCUIT
    st = getVariable(29300);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.CURRENTSHOTCIRCUIT", 76);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CURRENTSHOTCIRCUIT;
    st->value_p = p_LREAL;
  }
  { // 29301 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.CURRENTBREAKCIRCUIT
    st = getVariable(29301);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.CURRENTBREAKCIRCUIT", 77);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CURRENTBREAKCIRCUIT;
    st->value_p = p_LREAL;
  }
  { // 29302 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.MAXCHANGESPEED
    st = getVariable(29302);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.MAXCHANGESPEED", 72);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXCHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 29303 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.MAXCHANGESPEEDDOWN
    st = getVariable(29303);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.MAXCHANGESPEEDDOWN", 76);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXCHANGESPEEDDOWN;
    st->value_p = p_LREAL;
  }
  { // 29304 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.CHANGESPEED
    st = getVariable(29304);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.CHANGESPEED", 69);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 29305 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.HISTERESIS
    st = getVariable(29305);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.HISTERESIS", 68);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HISTERESIS;
    st->value_p = p_LREAL;
  }
  { // 29306 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.APERTURFILTER
    st = getVariable(29306);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.APERTURFILTER", 71);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->APERTURFILTER;
    st->value_p = p_LREAL;
  }
  { // 29307 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.EXPONENTIALFILTER
    st = getVariable(29307);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.EXPONENTIALFILTER", 75);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->EXPONENTIALFILTER;
    st->value_p = p_LREAL;
  }
  { // 29308 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.RASSOGLASOVANIE
    st = getVariable(29308);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.RASSOGLASOVANIE", 73);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->RASSOGLASOVANIE;
    st->value_p = p_LREAL;
  }
  { // 29309 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.OPCCOMMANDSDISABLED
    st = getVariable(29309);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.OPCCOMMANDSDISABLED", 77);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 29310 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DISABLED_LA
    st = getVariable(29310);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DISABLED_LA", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_LA;
    st->value_p = p_BOOL;
  }
  { // 29311 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DISABLED_HA
    st = getVariable(29311);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DISABLED_HA", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_HA;
    st->value_p = p_BOOL;
  }
  { // 29312 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DISABLED_LW
    st = getVariable(29312);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DISABLED_LW", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_LW;
    st->value_p = p_BOOL;
  }
  { // 29313 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DISABLED_HW
    st = getVariable(29313);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DISABLED_HW", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_HW;
    st->value_p = p_BOOL;
  }
  { // 29314 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DELAYLA
    st = getVariable(29314);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DELAYLA", 65);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYLA;
    st->value_p = p_TIME;
  }
  { // 29315 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DELAYLW
    st = getVariable(29315);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DELAYLW", 65);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYLW;
    st->value_p = p_TIME;
  }
  { // 29316 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DELAYHW
    st = getVariable(29316);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DELAYHW", 65);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYHW;
    st->value_p = p_TIME;
  }
  { // 29317 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DELAYHA
    st = getVariable(29317);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DELAYHA", 65);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYHA;
    st->value_p = p_TIME;
  }
  { // 29318 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.MINVALUE_ISVALIDREF
    st = getVariable(29318);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.MINVALUE_ISVALIDREF", 77);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->MINVALUE_ISVALIDREF;
    st->value_p = p_BOOL;
  }
  { // 29319 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.MAXVALUE_ISVALIDREF
    st = getVariable(29319);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.MAXVALUE_ISVALIDREF", 77);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->MAXVALUE_ISVALIDREF;
    st->value_p = p_BOOL;
  }
  { // 29320 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.MINVALUE
    st = getVariable(29320);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.MINVALUE", 66);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MINVALUE;
    st->value_p = p_LREAL;
  }
  { // 29321 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.MAXVALUE
    st = getVariable(29321);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.MAXVALUE", 66);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXVALUE;
    st->value_p = p_LREAL;
  }
  { // 29322 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.INOPCCOMMANDSDISABLED
    st = getVariable(29322);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.INOPCCOMMANDSDISABLED", 79);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 29323 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.IMIT
    st = getVariable(29323);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.IMIT", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->IMIT;
    st->value_p = p_BOOL;
  }
  { // 29324 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.REMONT
    st = getVariable(29324);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.REMONT", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->REMONT;
    st->value_p = p_BOOL;
  }
  { // 29325 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.NS
    st = getVariable(29325);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.NS", 60);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS;
    st->value_p = p_BOOL;
  }
  { // 29326 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.NS_MIN
    st = getVariable(29326);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.NS_MIN", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS_MIN;
    st->value_p = p_BOOL;
  }
  { // 29327 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.NS_MAX
    st = getVariable(29327);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.NS_MAX", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS_MAX;
    st->value_p = p_BOOL;
  }
  { // 29328 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.INCOMMAND_ALG
    st = getVariable(29328);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.INCOMMAND_ALG", 71);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 29329 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.INCOMMAND_ARM
    st = getVariable(29329);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.INCOMMAND_ARM", 71);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 29330 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DMAXCHANGESPEED
    st = getVariable(29330);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DMAXCHANGESPEED", 73);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DMAXCHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 29331 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DMAXCHANGESPEEDDOWN
    st = getVariable(29331);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.AI.DMAXCHANGESPEEDDOWN", 77);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DMAXCHANGESPEEDDOWN;
    st->value_p = p_LREAL;
  }
  { // 29332 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.CONTROLLIMIT
    st = getVariable(29332);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.CONTROLLIMIT", 74);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BYTE = (BYTE*)&p_STRUCT_AIPROTECTION->CONTROLLIMIT;
    st->value_p = p_BYTE;
  }
  { // 29333 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.DELAY
    st = getVariable(29333);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.DELAY", 67);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_TIME = (TIME*)&p_STRUCT_AIPROTECTION->DELAY;
    st->value_p = p_TIME;
  }
  { // 29334 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.INTAG
    st = getVariable(29334);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.INTAG", 67);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BYTE = (BYTE*)&p_STRUCT_AIPROTECTION->INTAG;
    st->value_p = p_BYTE;
  }
  { // 29335 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.INRUNONSTART
    st = getVariable(29335);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.INRUNONSTART", 74);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->INRUNONSTART;
    st->value_p = p_BOOL;
  }
  { // 29336 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.INCANRUN
    st = getVariable(29336);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.INCANRUN", 70);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->INCANRUN;
    st->value_p = p_BOOL;
  }
  { // 29337 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.INOPCCOMMANDSDISABLED
    st = getVariable(29337);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.INOPCCOMMANDSDISABLED", 83);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 29338 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.INCOMMAND
    st = getVariable(29338);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.INCOMMAND", 71);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_WORD = (WORD*)&p_STRUCT_AIPROTECTION->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 29339 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.INCOMMAND_ALG
    st = getVariable(29339);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.INCOMMAND_ALG", 75);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_WORD = (WORD*)&p_STRUCT_AIPROTECTION->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 29340 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.INCOMMAND_ARM
    st = getVariable(29340);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.INCOMMAND_ARM", 75);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_WORD = (WORD*)&p_STRUCT_AIPROTECTION->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 29341 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.TAG
    st = getVariable(29341);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.TAG", 65);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BYTE = (BYTE*)&p_STRUCT_AIPROTECTION->TAG;
    st->value_p = p_BYTE;
  }
  { // 29342 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.STATUS
    st = getVariable(29342);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.STATUS", 68);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_DWORD = (DWORD*)&p_STRUCT_AIPROTECTION->STATUS;
    st->value_p = p_DWORD;
  }
  { // 29343 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.CANRUN
    st = getVariable(29343);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.CANRUN", 68);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->CANRUN;
    st->value_p = p_BOOL;
  }
  { // 29344 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.OPCCOMMANDSDISABLED
    st = getVariable(29344);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.OPCCOMMANDSDISABLED", 81);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 29345 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.ISRUNNING
    st = getVariable(29345);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.ISRUNNING", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->ISRUNNING;
    st->value_p = p_BOOL;
  }
  { // 29346 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.HASERROR
    st = getVariable(29346);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.HASERROR", 70);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->HASERROR;
    st->value_p = p_BOOL;
  }
  { // 29347 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.ISENDED
    st = getVariable(29347);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.ISENDED", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->ISENDED;
    st->value_p = p_BOOL;
  }
  { // 29348 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.REMONT
    st = getVariable(29348);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.REMONT", 68);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->REMONT;
    st->value_p = p_BOOL;
  }
  { // 29349 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.CHECK
    st = getVariable(29349);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.CHECK", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->CHECK;
    st->value_p = p_BOOL;
  }
  { // 29350 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.SIGNALING
    st = getVariable(29350);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.SIGNALING", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->SIGNALING;
    st->value_p = p_BOOL;
  }
  { // 29351 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.SIGNALINGTP
    st = getVariable(29351);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.SIGNALINGTP", 73);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->SIGNALINGTP;
    st->value_p = p_BOOL;
  }
  { // 29352 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.RUNONSTART
    st = getVariable(29352);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.STRAIP.RUNONSTART", 72);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->RUNONSTART;
    st->value_p = p_BOOL;
  }
  { // 29357 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._SIGNALINGTP.IN
    st = getVariable(29357);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._SIGNALINGTP.IN", 70);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    p_BOOL = (BOOL*)&p_TOF->IN;
    st->value_p = p_BOOL;
  }
  { // 29358 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._SIGNALINGTP.PT
    st = getVariable(29358);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._SIGNALINGTP.PT", 70);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    p_TIME = (TIME*)&p_TOF->PT;
    st->value_p = p_TIME;
  }
  { // 29359 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._SIGNALINGTP.Q
    st = getVariable(29359);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._SIGNALINGTP.Q", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    p_BOOL = (BOOL*)&p_TOF->Q;
    st->value_p = p_BOOL;
  }
  { // 29360 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._SIGNALINGTP.ET
    st = getVariable(29360);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._SIGNALINGTP.ET", 70);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    p_TIME = (TIME*)&p_TOF->ET;
    st->value_p = p_TIME;
  }
  { // 29361 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._SIGNALINGTP
    st = getVariable(29361);
    memcpy(st->IEC_TYPE, "TOF", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._SIGNALINGTP", 67);
    st->size_data = sizeof(TOF);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    st->value_p = (void *)p_TOF;
  }
  { // 29362 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._STATUSAI.NOTDEFINED
    st = getVariable(29362);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._STATUSAI.NOTDEFINED", 75);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NOTDEFINED;
    st->value_p = p_BYTE;
  }
  { // 29363 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._STATUSAI.LL
    st = getVariable(29363);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._STATUSAI.LL", 67);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LL;
    st->value_p = p_BYTE;
  }
  { // 29364 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._STATUSAI.HL
    st = getVariable(29364);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._STATUSAI.HL", 67);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HL;
    st->value_p = p_BYTE;
  }
  { // 29365 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._STATUSAI.NOTRELIABLE
    st = getVariable(29365);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._STATUSAI.NOTRELIABLE", 76);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NOTRELIABLE;
    st->value_p = p_BYTE;
  }
  { // 29366 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._STATUSAI.NORMAL
    st = getVariable(29366);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._STATUSAI.NORMAL", 71);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NORMAL;
    st->value_p = p_BYTE;
  }
  { // 29367 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._STATUSAI.LW
    st = getVariable(29367);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._STATUSAI.LW", 67);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LW;
    st->value_p = p_BYTE;
  }
  { // 29368 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._STATUSAI.HW
    st = getVariable(29368);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._STATUSAI.HW", 67);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HW;
    st->value_p = p_BYTE;
  }
  { // 29369 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._STATUSAI.LA
    st = getVariable(29369);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._STATUSAI.LA", 67);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LA;
    st->value_p = p_BYTE;
  }
  { // 29370 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._STATUSAI.HA
    st = getVariable(29370);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4._STATUSAI.HA", 67);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HA;
    st->value_p = p_BYTE;
  }
  { // 29371 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SOURCE
    st = getVariable(29371);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SOURCE", 61);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->SOURCE;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 29372 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.CMD
    st = getVariable(29372);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.CMD", 58);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->CMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 29373 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.LASTCMD
    st = getVariable(29373);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.LASTCMD", 62);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->LASTCMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 29374 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SOURCE_FOR_STATUS
    st = getVariable(29374);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SOURCE_FOR_STATUS", 72);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->SOURCE_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 29375 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.CMD_FOR_STATUS
    st = getVariable(29375);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.CMD_FOR_STATUS", 69);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->CMD_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 29376 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.COMMAND_ERROR_FOR_STATUS
    st = getVariable(29376);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.COMMAND_ERROR_FOR_STATUS", 79);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->COMMAND_ERROR_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 29377 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.RESETCMDTIMER.IN
    st = getVariable(29377);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.RESETCMDTIMER.IN", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 29378 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.RESETCMDTIMER.PT
    st = getVariable(29378);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.RESETCMDTIMER.PT", 71);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 29379 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.RESETCMDTIMER.Q
    st = getVariable(29379);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.RESETCMDTIMER.Q", 70);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 29380 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.RESETCMDTIMER.ET
    st = getVariable(29380);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.RESETCMDTIMER.ET", 71);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 29381 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.RESETCMDTIMER
    st = getVariable(29381);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.RESETCMDTIMER", 68);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    st->value_p = (void *)p_TON;
  }
  { // 29382 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.RESETCMDTIMERPRIZNAK
    st = getVariable(29382);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.RESETCMDTIMERPRIZNAK", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_BOOL = (BOOL*)&p_FB_AIPROTECTION->RESETCMDTIMERPRIZNAK;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 29383 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SIGNALINTIMER.IN
    st = getVariable(29383);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SIGNALINTIMER.IN", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 29384 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SIGNALINTIMER.PT
    st = getVariable(29384);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SIGNALINTIMER.PT", 71);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 29385 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SIGNALINTIMER.Q
    st = getVariable(29385);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SIGNALINTIMER.Q", 70);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 29386 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SIGNALINTIMER.ET
    st = getVariable(29386);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SIGNALINTIMER.ET", 71);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 29387 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SIGNALINTIMER
    st = getVariable(29387);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SIGNALINTIMER", 68);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    st->value_p = (void *)p_TON;
  }
  { // 29388 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.TIMER.IN
    st = getVariable(29388);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.TIMER.IN", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 29389 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.TIMER.PT
    st = getVariable(29389);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.TIMER.PT", 63);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 29390 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.TIMER.Q
    st = getVariable(29390);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.TIMER.Q", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 29391 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.TIMER.ET
    st = getVariable(29391);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.TIMER.ET", 63);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 29392 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.TIMER
    st = getVariable(29392);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.TIMER", 60);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    st->value_p = (void *)p_TON;
  }
  { // 29393 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SIGNALINGTRIG.CLK
    st = getVariable(29393);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SIGNALINGTRIG.CLK", 72);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_R_TRIG = (R_TRIG*)&p_FB_AIPROTECTION->SIGNALINGTRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 29394 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SIGNALINGTRIG.Q
    st = getVariable(29394);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SIGNALINGTRIG.Q", 70);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_R_TRIG = (R_TRIG*)&p_FB_AIPROTECTION->SIGNALINGTRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 29395 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SIGNALINGTRIG
    st = getVariable(29395);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SIGNALINGTRIG", 68);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_R_TRIG = (R_TRIG*)&p_FB_AIPROTECTION->SIGNALINGTRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 29396 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SIGNALINGFTRIG.CLK
    st = getVariable(29396);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SIGNALINGFTRIG.CLK", 73);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_F_TRIG = (F_TRIG*)&p_FB_AIPROTECTION->SIGNALINGFTRIG;
    p_BOOL = (BOOL*)&p_F_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 29397 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SIGNALINGFTRIG.Q
    st = getVariable(29397);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SIGNALINGFTRIG.Q", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_F_TRIG = (F_TRIG*)&p_FB_AIPROTECTION->SIGNALINGFTRIG;
    p_BOOL = (BOOL*)&p_F_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 29398 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SIGNALINGFTRIG
    st = getVariable(29398);
    memcpy(st->IEC_TYPE, "F_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SIGNALINGFTRIG", 69);
    st->size_data = sizeof(F_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_F_TRIG = (F_TRIG*)&p_FB_AIPROTECTION->SIGNALINGFTRIG;
    st->value_p = (void *)p_F_TRIG;
  }
  { // 29399 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SIGNALINGAI
    st = getVariable(29399);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_KOL_EDT_4.SIGNALINGAI", 66);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_KOL_EDT_4;
    p_BOOL = (BOOL*)&p_FB_AIPROTECTION->SIGNALINGAI;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }

  return 0;
}

// clang-format on
