// clang-format off

#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include "POUS.h"
#include <beremiz/beremiz.h>

#include "iec_types_all.h"
#include "config1.h"

extern PROGRAM0 RESOURCE1__INSTANCE0;

#ifdef DEBUG_PLC
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err][%s:%d]: " _PRNTMSG "\n", __func__, __LINE__, ##__VA_ARGS__)
#else
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err]: " _PRNTMSG "\n", ##__VA_ARGS__)
#endif // DEBUG_PLC

void UnpackVar(void* varp, __IEC_types_enum vartype, void **value_p, void **f_value_p, uint8_t **flags);

int __variables_init_FB_TEN(){
  iec_var_t *st;

  PROGRAM0 *p_PROGRAM0;
  LREAL *p_LREAL;
  ULINT *p_ULINT;
  REAL *p_REAL;
  FB_TIMINGS *p_FB_TIMINGS;
  BOOL *p_BOOL;
  UINT *p_UINT;
  PROC_AI_INIT *p_PROC_AI_INIT;
  FB_AI_INIT *p_FB_AI_INIT;
  TIME *p_TIME;
  STRUCT_AI *p_STRUCT_AI;
  DWORD *p_DWORD;
  BYTE *p_BYTE;
  WORD *p_WORD;
  AICONFIG *p_AICONFIG;
  PROC_AI *p_PROC_AI;
  FB_AISOURCEMLP *p_FB_AISOURCEMLP;
  TITEMAIN *p_TITEMAIN;
  TITEMDIN *p_TITEMDIN;
  TYPE_STATUSAI *p_TYPE_STATUSAI;
  TYPE_COMMANDANALOG *p_TYPE_COMMANDANALOG;
  FB_SUNPACKERCOMMAND *p_FB_SUNPACKERCOMMAND;
  TYPE_ANALOGLIMITFLAGS *p_TYPE_ANALOGLIMITFLAGS;
  TON *p_TON;
  R_TRIG *p_R_TRIG;
  FB_AISOURCEMLP_TIMER *p_FB_AISOURCEMLP_TIMER;
  PROC_AO_INIT *p_PROC_AO_INIT;
  FB_AO_INIT *p_FB_AO_INIT;
  STRUCT_AO *p_STRUCT_AO;
  AOCONFIG *p_AOCONFIG;
  PROC_AO *p_PROC_AO;
  FB_AOSOURCEMLP *p_FB_AOSOURCEMLP;
  TDOUBLEDATA *p_TDOUBLEDATA;
  PROC_DI_INIT *p_PROC_DI_INIT;
  FB_DI_INIT *p_FB_DI_INIT;
  STRUCT_DI *p_STRUCT_DI;
  __IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t *p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t;
  TYPE_RELIABLEBIT *p_TYPE_RELIABLEBIT;
  DICONFIG *p_DICONFIG;
  PROC_DI *p_PROC_DI;
  FB_DISOURCEMLP *p_FB_DISOURCEMLP;
  INT *p_INT;
  UDINT *p_UDINT;
  PROC_DO_INIT *p_PROC_DO_INIT;
  FB_DO_INIT *p_FB_DO_INIT;
  STRUCT_DO *p_STRUCT_DO;
  __IEC___ARRAY_OF_BOOL_16_t *p___IEC___ARRAY_OF_BOOL_16_t;
  DOCONFIG *p_DOCONFIG;
  PROC_DO *p_PROC_DO;
  FB_DOSOURCEMLP *p_FB_DOSOURCEMLP;
  TWORDDATA *p_TWORDDATA;
  OPC_ALGORITMS_SET *p_OPC_ALGORITMS_SET;
  ALGORITMSCONFIG *p_ALGORITMSCONFIG;
  STRUCT_ALG *p_STRUCT_ALG;
  STRUCT_ALGORITMSMANAGER *p_STRUCT_ALGORITMSMANAGER;
  STRUCT_PROTECTIONSMANAGER *p_STRUCT_PROTECTIONSMANAGER;
  STRUCT_ALGTIMERS *p_STRUCT_ALGTIMERS;
  ALGORITMSQUESTIONS *p_ALGORITMSQUESTIONS;
  STRUCT_QUESTION *p_STRUCT_QUESTION;
  OPC_ALGORITMS_GET *p_OPC_ALGORITMS_GET;
  PROC_IM_INIT *p_PROC_IM_INIT;
  FB_KRAN_INIT *p_FB_KRAN_INIT;
  STRUCT_KRAN *p_STRUCT_KRAN;
  FB_SWITCH_INIT *p_FB_SWITCH_INIT;
  STRUCT_SWITCH *p_STRUCT_SWITCH;
  FB_OILPUMP_INIT *p_FB_OILPUMP_INIT;
  STRUCT_OILPUMP *p_STRUCT_OILPUMP;
  FB_SECTIONSWITCH_INIT *p_FB_SECTIONSWITCH_INIT;
  STRUCT_SECTIONSWITCH *p_STRUCT_SECTIONSWITCH;
  FB_ANALOGPARAMETR_INIT *p_FB_ANALOGPARAMETR_INIT;
  STRUCT_ANALOGPARAMETR *p_STRUCT_ANALOGPARAMETR;
  FB_DISCRETPARAMETR_INIT *p_FB_DISCRETPARAMETR_INIT;
  STRUCT_DISCRETPARAMETR *p_STRUCT_DISCRETPARAMETR;
  FB_SINGLESIGNAL_INIT *p_FB_SINGLESIGNAL_INIT;
  STRUCT_SINGLESIGNAL *p_STRUCT_SINGLESIGNAL;
  FB_SINGLEOUTPUT_INIT *p_FB_SINGLEOUTPUT_INIT;
  STRUCT_SINGLEOUTPUT *p_STRUCT_SINGLEOUTPUT;
  IMCONFIG *p_IMCONFIG;
  STRUCT_RESERVEIM *p_STRUCT_RESERVEIM;
  STRUCT_RESERVEIM2 *p_STRUCT_RESERVEIM2;
  IM_SINGLESIGNALS *p_IM_SINGLESIGNALS;
  IM_SINGLEOUTPUTS *p_IM_SINGLEOUTPUTS;
  PROC_IM *p_PROC_IM;
  FB_KRAN *p_FB_KRAN;
  TYPE_STATUSDUALINPUT *p_TYPE_STATUSDUALINPUT;
  TYPE_COMMANDDUALINPUT *p_TYPE_COMMANDDUALINPUT;
  TOF *p_TOF;
  FB_OILPUMP *p_FB_OILPUMP;
  FB_SWITCH *p_FB_SWITCH;
  FB_SECTIONSWITCH *p_FB_SECTIONSWITCH;
  TYPE_BASKETSTATS *p_TYPE_BASKETSTATS;
  FB_MEANDR *p_FB_MEANDR;
  FB_SINGLESIGNAL *p_FB_SINGLESIGNAL;
  FB_SINGLEOUTPUT *p_FB_SINGLEOUTPUT;
  FB_DISCRETPARAMETR *p_FB_DISCRETPARAMETR;
  FB_ANALOGPARAMETR *p_FB_ANALOGPARAMETR;
  OPC_IM_GET *p_OPC_IM_GET;
  OPC_IM_SET *p_OPC_IM_SET;
  PROC_PROTECTIONS_INIT *p_PROC_PROTECTIONS_INIT;
  FB_DIPROTECTION_INIT *p_FB_DIPROTECTION_INIT;
  STRUCT_DIPROTECTION *p_STRUCT_DIPROTECTION;
  FB_AIPROTECTION_INIT *p_FB_AIPROTECTION_INIT;
  STRUCT_AIPROTECTION *p_STRUCT_AIPROTECTION;
  PROTECTIONSCONFIG *p_PROTECTIONSCONFIG;
  TYPE_PROTECTIONTAGS *p_TYPE_PROTECTIONTAGS;
  PROC_PROTECTION *p_PROC_PROTECTION;
  FB_DIPROTECTION *p_FB_DIPROTECTION;
  F_TRIG *p_F_TRIG;
  FB_MVPROTECTION *p_FB_MVPROTECTION;
  FB_KRANOPENPROTECTION *p_FB_KRANOPENPROTECTION;
  FB_AIPROTECTION *p_FB_AIPROTECTION;
  PROC_ALGORITMS *p_PROC_ALGORITMS;
  REMONTALG *p_REMONTALG;
  TYPE_MODEGPA *p_TYPE_MODEGPA;
  TYPE_COMMANDSPOTECTIONSMANAGER *p_TYPE_COMMANDSPOTECTIONSMANAGER;
  TESTPROTECTIONALG *p_TESTPROTECTIONALG;
  TESTIMALG *p_TESTIMALG;
  FB_AUTOTENALG *p_FB_AUTOTENALG;
  FB_AUTOPNSALG *p_FB_AUTOPNSALG;
  FB_AUTOAVOMALG *p_FB_AUTOAVOMALG;
  FB_VIBEGPNSALG *p_FB_VIBEGPNSALG;
  STRUCT_PHASEALGORITM *p_STRUCT_PHASEALGORITM;
  FB_PH_ALGORITM *p_FB_PH_ALGORITM;
  FB_PH_TIMER *p_FB_PH_TIMER;
  FB_QUESTION *p_FB_QUESTION;
  TYPE_ANSWERS *p_TYPE_ANSWERS;
  FB_PH_SWITCH *p_FB_PH_SWITCH;
  FB_PH_CUSTOMPHASE *p_FB_PH_CUSTOMPHASE;
  FB_AUTONUALG *p_FB_AUTONUALG;
  FB_PUSKOILSYSTEMALG *p_FB_PUSKOILSYSTEMALG;
  FB_PH_WAITANALOGVALUE *p_FB_PH_WAITANALOGVALUE;
  FB_PH_OILPUMP *p_FB_PH_OILPUMP;
  FB_ANTIPOMPAGALG *p_FB_ANTIPOMPAGALG;
  FB_TABLEVALUE_MIN *p_FB_TABLEVALUE_MIN;
  __IEC___ARRAY_OF_TYPE_TABLEREC_9_t *p___IEC___ARRAY_OF_TYPE_TABLEREC_9_t;
  TYPE_TABLEREC *p_TYPE_TABLEREC;
  FB_TABLEVALUE_MAX *p_FB_TABLEVALUE_MAX;
  FB_RASHODALG *p_FB_RASHODALG;
  FB_ZAPASALG *p_FB_ZAPASALG;
  NOALG *p_NOALG;
  FB_PH_KRAN *p_FB_PH_KRAN;
  FB_PH_SECTIONSWITCH *p_FB_PH_SECTIONSWITCH;
  AOALG *p_AOALG;
  PPUALG *p_PPUALG;
  FILLINGALG *p_FILLINGALG;
  FB_PH_DIPROTECTION *p_FB_PH_DIPROTECTION;
  ENGINERUNALG *p_ENGINERUNALG;
  PUSKKALG *p_PUSKKALG;
  PUSKVALG *p_PUSKVALG;
  TESTDPMGALG *p_TESTDPMGALG;
  TESTPMSALG *p_TESTPMSALG;
  FB_PH_AIPROTECTION *p_FB_PH_AIPROTECTION;
  APUSKALG *p_APUSKALG;
  SEMIAUTOPUSKALG *p_SEMIAUTOPUSKALG;
  FB_ALGORITMSMANAGER *p_FB_ALGORITMSMANAGER;
  FB_PROTECTIONSMANAGER *p_FB_PROTECTIONSMANAGER;

  { // 22442 PROGRAM0.IM_PROC.FB_TEN.STATON
    st = getVariable(22442);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STATON", 30);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_BOOL = (BOOL*)&p_FB_SWITCH->STATON;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 22443 PROGRAM0.IM_PROC.FB_TEN.STATOFF
    st = getVariable(22443);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STATOFF", 31);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_BOOL = (BOOL*)&p_FB_SWITCH->STATOFF;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 22444 PROGRAM0.IM_PROC.FB_TEN.STATON_RELIABILITY
    st = getVariable(22444);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STATON_RELIABILITY", 42);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_BOOL = (BOOL*)&p_FB_SWITCH->STATON_RELIABILITY;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 22445 PROGRAM0.IM_PROC.FB_TEN.STATOFF_RELIABILITY
    st = getVariable(22445);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STATOFF_RELIABILITY", 43);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_BOOL = (BOOL*)&p_FB_SWITCH->STATOFF_RELIABILITY;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 22446 PROGRAM0.IM_PROC.FB_TEN.STRSW.INCOMMAND
    st = getVariable(22446);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.INCOMMAND", 39);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_WORD = (WORD*)&p_STRUCT_SWITCH->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 22447 PROGRAM0.IM_PROC.FB_TEN.STRSW.STATUS
    st = getVariable(22447);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.STATUS", 36);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_DWORD = (DWORD*)&p_STRUCT_SWITCH->STATUS;
    st->value_p = p_DWORD;
  }
  { // 22448 PROGRAM0.IM_PROC.FB_TEN.STRSW.ONSTATUS
    st = getVariable(22448);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.ONSTATUS", 38);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BYTE = (BYTE*)&p_STRUCT_SWITCH->ONSTATUS;
    st->value_p = p_BYTE;
  }
  { // 22449 PROGRAM0.IM_PROC.FB_TEN.STRSW.INOPCCOMMANDSDISABLED
    st = getVariable(22449);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.INOPCCOMMANDSDISABLED", 51);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 22450 PROGRAM0.IM_PROC.FB_TEN.STRSW.SDVIG
    st = getVariable(22450);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.SDVIG", 35);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->SDVIG;
    st->value_p = p_BOOL;
  }
  { // 22451 PROGRAM0.IM_PROC.FB_TEN.STRSW.NS
    st = getVariable(22451);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.NS", 32);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->NS;
    st->value_p = p_BOOL;
  }
  { // 22452 PROGRAM0.IM_PROC.FB_TEN.STRSW.COMMANDFAULT
    st = getVariable(22452);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.COMMANDFAULT", 42);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->COMMANDFAULT;
    st->value_p = p_BOOL;
  }
  { // 22453 PROGRAM0.IM_PROC.FB_TEN.STRSW.ACCIDENT
    st = getVariable(22453);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.ACCIDENT", 38);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ACCIDENT;
    st->value_p = p_BOOL;
  }
  { // 22454 PROGRAM0.IM_PROC.FB_TEN.STRSW.AUTO
    st = getVariable(22454);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.AUTO", 34);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->AUTO;
    st->value_p = p_BOOL;
  }
  { // 22455 PROGRAM0.IM_PROC.FB_TEN.STRSW.MANUAL
    st = getVariable(22455);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.MANUAL", 36);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->MANUAL;
    st->value_p = p_BOOL;
  }
  { // 22456 PROGRAM0.IM_PROC.FB_TEN.STRSW.LOCAL
    st = getVariable(22456);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.LOCAL", 35);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->LOCAL;
    st->value_p = p_BOOL;
  }
  { // 22457 PROGRAM0.IM_PROC.FB_TEN.STRSW.DISTANCE
    st = getVariable(22457);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.DISTANCE", 38);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->DISTANCE;
    st->value_p = p_BOOL;
  }
  { // 22458 PROGRAM0.IM_PROC.FB_TEN.STRSW.ERRORPOWEROFF
    st = getVariable(22458);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.ERRORPOWEROFF", 43);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ERRORPOWEROFF;
    st->value_p = p_BOOL;
  }
  { // 22459 PROGRAM0.IM_PROC.FB_TEN.STRSW.ERRORBLOCK
    st = getVariable(22459);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.ERRORBLOCK", 40);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ERRORBLOCK;
    st->value_p = p_BOOL;
  }
  { // 22460 PROGRAM0.IM_PROC.FB_TEN.STRSW.BREAKCMDON
    st = getVariable(22460);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.BREAKCMDON", 40);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->BREAKCMDON;
    st->value_p = p_BOOL;
  }
  { // 22461 PROGRAM0.IM_PROC.FB_TEN.STRSW.BREAKCMDOFF
    st = getVariable(22461);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.BREAKCMDOFF", 41);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->BREAKCMDOFF;
    st->value_p = p_BOOL;
  }
  { // 22462 PROGRAM0.IM_PROC.FB_TEN.STRSW.OPCCOMMANDSDISABLED
    st = getVariable(22462);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.OPCCOMMANDSDISABLED", 49);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 22463 PROGRAM0.IM_PROC.FB_TEN.STRSW.LASTCMDISON
    st = getVariable(22463);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.LASTCMDISON", 41);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->LASTCMDISON;
    st->value_p = p_BOOL;
  }
  { // 22464 PROGRAM0.IM_PROC.FB_TEN.STRSW.ISVALIDREF_STATON
    st = getVariable(22464);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.ISVALIDREF_STATON", 47);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ISVALIDREF_STATON;
    st->value_p = p_BOOL;
  }
  { // 22465 PROGRAM0.IM_PROC.FB_TEN.STRSW.ISVALIDREF_STATOFF
    st = getVariable(22465);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.ISVALIDREF_STATOFF", 48);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ISVALIDREF_STATOFF;
    st->value_p = p_BOOL;
  }
  { // 22466 PROGRAM0.IM_PROC.FB_TEN.STRSW.ISVALIDREF_CMDON
    st = getVariable(22466);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.ISVALIDREF_CMDON", 46);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ISVALIDREF_CMDON;
    st->value_p = p_BOOL;
  }
  { // 22467 PROGRAM0.IM_PROC.FB_TEN.STRSW.ISVALIDREF_CMDOFF
    st = getVariable(22467);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.ISVALIDREF_CMDOFF", 47);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ISVALIDREF_CMDOFF;
    st->value_p = p_BOOL;
  }
  { // 22468 PROGRAM0.IM_PROC.FB_TEN.STRSW.ISVALIDREF_INBREAKCMDON
    st = getVariable(22468);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.ISVALIDREF_INBREAKCMDON", 53);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ISVALIDREF_INBREAKCMDON;
    st->value_p = p_BOOL;
  }
  { // 22469 PROGRAM0.IM_PROC.FB_TEN.STRSW.ISVALIDREF_INBREAKCMDOFF
    st = getVariable(22469);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.ISVALIDREF_INBREAKCMDOFF", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ISVALIDREF_INBREAKCMDOFF;
    st->value_p = p_BOOL;
  }
  { // 22470 PROGRAM0.IM_PROC.FB_TEN.STRSW.INCOMMAND_ALG
    st = getVariable(22470);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.INCOMMAND_ALG", 43);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_WORD = (WORD*)&p_STRUCT_SWITCH->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 22471 PROGRAM0.IM_PROC.FB_TEN.STRSW.INCOMMAND_ARM
    st = getVariable(22471);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.INCOMMAND_ARM", 43);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_WORD = (WORD*)&p_STRUCT_SWITCH->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 22472 PROGRAM0.IM_PROC.FB_TEN.STRSW.CMDON
    st = getVariable(22472);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.CMDON", 35);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->CMDON;
    st->value_p = p_BOOL;
  }
  { // 22473 PROGRAM0.IM_PROC.FB_TEN.STRSW.CMDOFF
    st = getVariable(22473);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.CMDOFF", 36);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->CMDOFF;
    st->value_p = p_BOOL;
  }
  { // 22474 PROGRAM0.IM_PROC.FB_TEN.STRSW.RELIABILITY
    st = getVariable(22474);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.STRSW.RELIABILITY", 41);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_SWITCH->STRSW;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 22475 PROGRAM0.IM_PROC.FB_TEN.INNS.VALUE
    st = getVariable(22475);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INNS.VALUE", 34);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INNS;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 22476 PROGRAM0.IM_PROC.FB_TEN.INNS.RELIABILITY
    st = getVariable(22476);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INNS.RELIABILITY", 40);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INNS;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 22477 PROGRAM0.IM_PROC.FB_TEN.INNS._INVERSED
    st = getVariable(22477);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INNS._INVERSED", 38);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INNS;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 22478 PROGRAM0.IM_PROC.FB_TEN.INACCIDENT.VALUE
    st = getVariable(22478);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INACCIDENT.VALUE", 40);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INACCIDENT;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 22479 PROGRAM0.IM_PROC.FB_TEN.INACCIDENT.RELIABILITY
    st = getVariable(22479);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INACCIDENT.RELIABILITY", 46);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INACCIDENT;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 22480 PROGRAM0.IM_PROC.FB_TEN.INACCIDENT._INVERSED
    st = getVariable(22480);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INACCIDENT._INVERSED", 44);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INACCIDENT;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 22481 PROGRAM0.IM_PROC.FB_TEN.INAUTO.VALUE
    st = getVariable(22481);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INAUTO.VALUE", 36);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INAUTO;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 22482 PROGRAM0.IM_PROC.FB_TEN.INAUTO.RELIABILITY
    st = getVariable(22482);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INAUTO.RELIABILITY", 42);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INAUTO;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 22483 PROGRAM0.IM_PROC.FB_TEN.INAUTO._INVERSED
    st = getVariable(22483);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INAUTO._INVERSED", 40);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INAUTO;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 22484 PROGRAM0.IM_PROC.FB_TEN.INMANUAL.VALUE
    st = getVariable(22484);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INMANUAL.VALUE", 38);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INMANUAL;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 22485 PROGRAM0.IM_PROC.FB_TEN.INMANUAL.RELIABILITY
    st = getVariable(22485);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INMANUAL.RELIABILITY", 44);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INMANUAL;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 22486 PROGRAM0.IM_PROC.FB_TEN.INMANUAL._INVERSED
    st = getVariable(22486);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INMANUAL._INVERSED", 42);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INMANUAL;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 22487 PROGRAM0.IM_PROC.FB_TEN.INLOCAL.VALUE
    st = getVariable(22487);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INLOCAL.VALUE", 37);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INLOCAL;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 22488 PROGRAM0.IM_PROC.FB_TEN.INLOCAL.RELIABILITY
    st = getVariable(22488);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INLOCAL.RELIABILITY", 43);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INLOCAL;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 22489 PROGRAM0.IM_PROC.FB_TEN.INLOCAL._INVERSED
    st = getVariable(22489);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INLOCAL._INVERSED", 41);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INLOCAL;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 22490 PROGRAM0.IM_PROC.FB_TEN.INDISTANCE.VALUE
    st = getVariable(22490);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INDISTANCE.VALUE", 40);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INDISTANCE;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 22491 PROGRAM0.IM_PROC.FB_TEN.INDISTANCE.RELIABILITY
    st = getVariable(22491);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INDISTANCE.RELIABILITY", 46);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INDISTANCE;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 22492 PROGRAM0.IM_PROC.FB_TEN.INDISTANCE._INVERSED
    st = getVariable(22492);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INDISTANCE._INVERSED", 44);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INDISTANCE;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 22493 PROGRAM0.IM_PROC.FB_TEN.INERRORPOWEROFF.VALUE
    st = getVariable(22493);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INERRORPOWEROFF.VALUE", 45);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INERRORPOWEROFF;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 22494 PROGRAM0.IM_PROC.FB_TEN.INERRORPOWEROFF.RELIABILITY
    st = getVariable(22494);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INERRORPOWEROFF.RELIABILITY", 51);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INERRORPOWEROFF;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 22495 PROGRAM0.IM_PROC.FB_TEN.INERRORPOWEROFF._INVERSED
    st = getVariable(22495);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INERRORPOWEROFF._INVERSED", 49);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INERRORPOWEROFF;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 22496 PROGRAM0.IM_PROC.FB_TEN.INERRORBLOCK.VALUE
    st = getVariable(22496);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INERRORBLOCK.VALUE", 42);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INERRORBLOCK;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 22497 PROGRAM0.IM_PROC.FB_TEN.INERRORBLOCK.RELIABILITY
    st = getVariable(22497);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INERRORBLOCK.RELIABILITY", 48);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INERRORBLOCK;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 22498 PROGRAM0.IM_PROC.FB_TEN.INERRORBLOCK._INVERSED
    st = getVariable(22498);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INERRORBLOCK._INVERSED", 46);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INERRORBLOCK;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 22499 PROGRAM0.IM_PROC.FB_TEN.INBREAKCMDON.VALUE
    st = getVariable(22499);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INBREAKCMDON.VALUE", 42);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INBREAKCMDON;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 22500 PROGRAM0.IM_PROC.FB_TEN.INBREAKCMDON.RELIABILITY
    st = getVariable(22500);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INBREAKCMDON.RELIABILITY", 48);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INBREAKCMDON;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 22501 PROGRAM0.IM_PROC.FB_TEN.INBREAKCMDON._INVERSED
    st = getVariable(22501);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INBREAKCMDON._INVERSED", 46);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INBREAKCMDON;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 22502 PROGRAM0.IM_PROC.FB_TEN.INBREAKCMDOFF.VALUE
    st = getVariable(22502);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INBREAKCMDOFF.VALUE", 43);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INBREAKCMDOFF;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 22503 PROGRAM0.IM_PROC.FB_TEN.INBREAKCMDOFF.RELIABILITY
    st = getVariable(22503);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INBREAKCMDOFF.RELIABILITY", 49);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INBREAKCMDOFF;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 22504 PROGRAM0.IM_PROC.FB_TEN.INBREAKCMDOFF._INVERSED
    st = getVariable(22504);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.INBREAKCMDOFF._INVERSED", 47);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_RELIABLEBIT = (TYPE_RELIABLEBIT*)&p_FB_SWITCH->INBREAKCMDOFF;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 22505 PROGRAM0.IM_PROC.FB_TEN.ONINIT
    st = getVariable(22505);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.ONINIT", 30);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_BOOL = (BOOL*)&p_FB_SWITCH->ONINIT;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 22506 PROGRAM0.IM_PROC.FB_TEN._STATON
    st = getVariable(22506);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN._STATON", 31);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_BOOL = (BOOL*)&p_FB_SWITCH->_STATON;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 22507 PROGRAM0.IM_PROC.FB_TEN._STATOFF
    st = getVariable(22507);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN._STATOFF", 32);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_BOOL = (BOOL*)&p_FB_SWITCH->_STATOFF;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 22508 PROGRAM0.IM_PROC.FB_TEN.LASTONSTATUS
    st = getVariable(22508);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.LASTONSTATUS", 36);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_BYTE = (BYTE*)&p_FB_SWITCH->LASTONSTATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 22509 PROGRAM0.IM_PROC.FB_TEN.CMD
    st = getVariable(22509);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.CMD", 27);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_BYTE = (BYTE*)&p_FB_SWITCH->CMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 22510 PROGRAM0.IM_PROC.FB_TEN.SOURCE
    st = getVariable(22510);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.SOURCE", 30);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_BYTE = (BYTE*)&p_FB_SWITCH->SOURCE;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 22511 PROGRAM0.IM_PROC.FB_TEN.LASTCMD
    st = getVariable(22511);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.LASTCMD", 31);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_BYTE = (BYTE*)&p_FB_SWITCH->LASTCMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 22512 PROGRAM0.IM_PROC.FB_TEN.SOURCE_FOR_STATUS
    st = getVariable(22512);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.SOURCE_FOR_STATUS", 41);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_BYTE = (BYTE*)&p_FB_SWITCH->SOURCE_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 22513 PROGRAM0.IM_PROC.FB_TEN.CMD_FOR_STATUS
    st = getVariable(22513);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.CMD_FOR_STATUS", 38);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_BYTE = (BYTE*)&p_FB_SWITCH->CMD_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 22514 PROGRAM0.IM_PROC.FB_TEN.COMMAND_ERROR_FOR_STATUS
    st = getVariable(22514);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.COMMAND_ERROR_FOR_STATUS", 48);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_BYTE = (BYTE*)&p_FB_SWITCH->COMMAND_ERROR_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 22519 PROGRAM0.IM_PROC.FB_TEN._STATUSDUALINPUT.STATUS_NOTDEFINED
    st = getVariable(22519);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN._STATUSDUALINPUT.STATUS_NOTDEFINED", 58);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_SWITCH->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_NOTDEFINED;
    st->value_p = p_BYTE;
  }
  { // 22520 PROGRAM0.IM_PROC.FB_TEN._STATUSDUALINPUT.STATUS_ON
    st = getVariable(22520);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN._STATUSDUALINPUT.STATUS_ON", 50);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_SWITCH->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ON;
    st->value_p = p_BYTE;
  }
  { // 22521 PROGRAM0.IM_PROC.FB_TEN._STATUSDUALINPUT.STATUS_OFF
    st = getVariable(22521);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN._STATUSDUALINPUT.STATUS_OFF", 51);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_SWITCH->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_OFF;
    st->value_p = p_BYTE;
  }
  { // 22522 PROGRAM0.IM_PROC.FB_TEN._STATUSDUALINPUT.STATUS_TRANSITIONAL
    st = getVariable(22522);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN._STATUSDUALINPUT.STATUS_TRANSITIONAL", 60);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_SWITCH->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_TRANSITIONAL;
    st->value_p = p_BYTE;
  }
  { // 22523 PROGRAM0.IM_PROC.FB_TEN._STATUSDUALINPUT.STATUS_ERROR
    st = getVariable(22523);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN._STATUSDUALINPUT.STATUS_ERROR", 53);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_SWITCH->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ERROR;
    st->value_p = p_BYTE;
  }
  { // 22524 PROGRAM0.IM_PROC.FB_TEN._COMMANDDUALINPUT.CMD_ON
    st = getVariable(22524);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN._COMMANDDUALINPUT.CMD_ON", 48);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_COMMANDDUALINPUT = (TYPE_COMMANDDUALINPUT*)&p_FB_SWITCH->_COMMANDDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_COMMANDDUALINPUT->CMD_ON;
    st->value_p = p_BYTE;
  }
  { // 22525 PROGRAM0.IM_PROC.FB_TEN._COMMANDDUALINPUT.CMD_OFF
    st = getVariable(22525);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN._COMMANDDUALINPUT.CMD_OFF", 49);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_COMMANDDUALINPUT = (TYPE_COMMANDDUALINPUT*)&p_FB_SWITCH->_COMMANDDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_COMMANDDUALINPUT->CMD_OFF;
    st->value_p = p_BYTE;
  }
  { // 22526 PROGRAM0.IM_PROC.FB_TEN._COMMANDDUALINPUT.CMD_RESET
    st = getVariable(22526);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN._COMMANDDUALINPUT.CMD_RESET", 51);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TYPE_COMMANDDUALINPUT = (TYPE_COMMANDDUALINPUT*)&p_FB_SWITCH->_COMMANDDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_COMMANDDUALINPUT->CMD_RESET;
    st->value_p = p_BYTE;
  }
  { // 22527 PROGRAM0.IM_PROC.FB_TEN._COMMANDERRORTIMER
    st = getVariable(22527);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN._COMMANDERRORTIMER", 42);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_BOOL = (BOOL*)&p_FB_SWITCH->_COMMANDERRORTIMER;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 22528 PROGRAM0.IM_PROC.FB_TEN.RESETERRORTIMER
    st = getVariable(22528);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.RESETERRORTIMER", 39);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_BOOL = (BOOL*)&p_FB_SWITCH->RESETERRORTIMER;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 22529 PROGRAM0.IM_PROC.FB_TEN.GETSDVIG
    st = getVariable(22529);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.GETSDVIG", 32);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_BOOL = (BOOL*)&p_FB_SWITCH->GETSDVIG;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 22530 PROGRAM0.IM_PROC.FB_TEN._CHANGWITHOUTCOMMAND
    st = getVariable(22530);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN._CHANGWITHOUTCOMMAND", 44);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_BOOL = (BOOL*)&p_FB_SWITCH->_CHANGWITHOUTCOMMAND;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 22531 PROGRAM0.IM_PROC.FB_TEN.ERRORCMDTIMER.IN
    st = getVariable(22531);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.ERRORCMDTIMER.IN", 40);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TON = (TON*)&p_FB_SWITCH->ERRORCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 22532 PROGRAM0.IM_PROC.FB_TEN.ERRORCMDTIMER.PT
    st = getVariable(22532);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.ERRORCMDTIMER.PT", 40);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TON = (TON*)&p_FB_SWITCH->ERRORCMDTIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 22533 PROGRAM0.IM_PROC.FB_TEN.ERRORCMDTIMER.Q
    st = getVariable(22533);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.ERRORCMDTIMER.Q", 39);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TON = (TON*)&p_FB_SWITCH->ERRORCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 22534 PROGRAM0.IM_PROC.FB_TEN.ERRORCMDTIMER.ET
    st = getVariable(22534);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.ERRORCMDTIMER.ET", 40);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TON = (TON*)&p_FB_SWITCH->ERRORCMDTIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 22535 PROGRAM0.IM_PROC.FB_TEN.ERRORCMDTIMER
    st = getVariable(22535);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.ERRORCMDTIMER", 37);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TON = (TON*)&p_FB_SWITCH->ERRORCMDTIMER;
    st->value_p = (void *)p_TON;
  }
  { // 22536 PROGRAM0.IM_PROC.FB_TEN.SDVIGRESET.IN
    st = getVariable(22536);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.SDVIGRESET.IN", 37);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TON = (TON*)&p_FB_SWITCH->SDVIGRESET;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 22537 PROGRAM0.IM_PROC.FB_TEN.SDVIGRESET.PT
    st = getVariable(22537);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.SDVIGRESET.PT", 37);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TON = (TON*)&p_FB_SWITCH->SDVIGRESET;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 22538 PROGRAM0.IM_PROC.FB_TEN.SDVIGRESET.Q
    st = getVariable(22538);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.SDVIGRESET.Q", 36);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TON = (TON*)&p_FB_SWITCH->SDVIGRESET;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 22539 PROGRAM0.IM_PROC.FB_TEN.SDVIGRESET.ET
    st = getVariable(22539);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.SDVIGRESET.ET", 37);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TON = (TON*)&p_FB_SWITCH->SDVIGRESET;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 22540 PROGRAM0.IM_PROC.FB_TEN.SDVIGRESET
    st = getVariable(22540);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.SDVIGRESET", 34);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TON = (TON*)&p_FB_SWITCH->SDVIGRESET;
    st->value_p = (void *)p_TON;
  }
  { // 22541 PROGRAM0.IM_PROC.FB_TEN._ERRORRESET.IN
    st = getVariable(22541);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN._ERRORRESET.IN", 38);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TON = (TON*)&p_FB_SWITCH->_ERRORRESET;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 22542 PROGRAM0.IM_PROC.FB_TEN._ERRORRESET.PT
    st = getVariable(22542);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN._ERRORRESET.PT", 38);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TON = (TON*)&p_FB_SWITCH->_ERRORRESET;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 22543 PROGRAM0.IM_PROC.FB_TEN._ERRORRESET.Q
    st = getVariable(22543);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN._ERRORRESET.Q", 37);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TON = (TON*)&p_FB_SWITCH->_ERRORRESET;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 22544 PROGRAM0.IM_PROC.FB_TEN._ERRORRESET.ET
    st = getVariable(22544);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN._ERRORRESET.ET", 38);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TON = (TON*)&p_FB_SWITCH->_ERRORRESET;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 22545 PROGRAM0.IM_PROC.FB_TEN._ERRORRESET
    st = getVariable(22545);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN._ERRORRESET", 35);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TON = (TON*)&p_FB_SWITCH->_ERRORRESET;
    st->value_p = (void *)p_TON;
  }
  { // 22546 PROGRAM0.IM_PROC.FB_TEN.OUTPUTSSETS.IN
    st = getVariable(22546);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.OUTPUTSSETS.IN", 38);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TOF = (TOF*)&p_FB_SWITCH->OUTPUTSSETS;
    p_BOOL = (BOOL*)&p_TOF->IN;
    st->value_p = p_BOOL;
  }
  { // 22547 PROGRAM0.IM_PROC.FB_TEN.OUTPUTSSETS.PT
    st = getVariable(22547);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.OUTPUTSSETS.PT", 38);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TOF = (TOF*)&p_FB_SWITCH->OUTPUTSSETS;
    p_TIME = (TIME*)&p_TOF->PT;
    st->value_p = p_TIME;
  }
  { // 22548 PROGRAM0.IM_PROC.FB_TEN.OUTPUTSSETS.Q
    st = getVariable(22548);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.OUTPUTSSETS.Q", 37);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TOF = (TOF*)&p_FB_SWITCH->OUTPUTSSETS;
    p_BOOL = (BOOL*)&p_TOF->Q;
    st->value_p = p_BOOL;
  }
  { // 22549 PROGRAM0.IM_PROC.FB_TEN.OUTPUTSSETS.ET
    st = getVariable(22549);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.OUTPUTSSETS.ET", 38);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TOF = (TOF*)&p_FB_SWITCH->OUTPUTSSETS;
    p_TIME = (TIME*)&p_TOF->ET;
    st->value_p = p_TIME;
  }
  { // 22550 PROGRAM0.IM_PROC.FB_TEN.OUTPUTSSETS
    st = getVariable(22550);
    memcpy(st->IEC_TYPE, "TOF", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.OUTPUTSSETS", 35);
    st->size_data = sizeof(TOF);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_TOF = (TOF*)&p_FB_SWITCH->OUTPUTSSETS;
    st->value_p = (void *)p_TOF;
  }
  { // 22551 PROGRAM0.IM_PROC.FB_TEN.CMDON
    st = getVariable(22551);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.CMDON", 29);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_BOOL = (BOOL*)&p_FB_SWITCH->CMDON;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 22552 PROGRAM0.IM_PROC.FB_TEN.CMDOFF
    st = getVariable(22552);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.IM_PROC.FB_TEN.CMDOFF", 30);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_IM = (PROC_IM*)&p_PROGRAM0->IM_PROC;
    p_FB_SWITCH = (FB_SWITCH*)&p_PROC_IM->FB_TEN;
    p_BOOL = (BOOL*)&p_FB_SWITCH->CMDOFF;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }

  return 0;
}

// clang-format on
