// clang-format off

#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include "POUS.h"
#include <beremiz/beremiz.h>

#include "iec_types_all.h"
#include "config1.h"

extern PROGRAM0 RESOURCE1__INSTANCE0;

#ifdef DEBUG_PLC
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err][%s:%d]: " _PRNTMSG "\n", __func__, __LINE__, ##__VA_ARGS__)
#else
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err]: " _PRNTMSG "\n", ##__VA_ARGS__)
#endif // DEBUG_PLC

void UnpackVar(void* varp, __IEC_types_enum vartype, void **value_p, void **f_value_p, uint8_t **flags);

int __variables_init_FB_AO_SHU(){
  iec_var_t *st;

  PROGRAM0 *p_PROGRAM0;
  LREAL *p_LREAL;
  ULINT *p_ULINT;
  REAL *p_REAL;
  FB_TIMINGS *p_FB_TIMINGS;
  BOOL *p_BOOL;
  UINT *p_UINT;
  PROC_AI_INIT *p_PROC_AI_INIT;
  FB_AI_INIT *p_FB_AI_INIT;
  TIME *p_TIME;
  STRUCT_AI *p_STRUCT_AI;
  DWORD *p_DWORD;
  BYTE *p_BYTE;
  WORD *p_WORD;
  AICONFIG *p_AICONFIG;
  PROC_AI *p_PROC_AI;
  FB_AISOURCEMLP *p_FB_AISOURCEMLP;
  TITEMAIN *p_TITEMAIN;
  TITEMDIN *p_TITEMDIN;
  TYPE_STATUSAI *p_TYPE_STATUSAI;
  TYPE_COMMANDANALOG *p_TYPE_COMMANDANALOG;
  FB_SUNPACKERCOMMAND *p_FB_SUNPACKERCOMMAND;
  TYPE_ANALOGLIMITFLAGS *p_TYPE_ANALOGLIMITFLAGS;
  TON *p_TON;
  R_TRIG *p_R_TRIG;
  FB_AISOURCEMLP_TIMER *p_FB_AISOURCEMLP_TIMER;
  PROC_AO_INIT *p_PROC_AO_INIT;
  FB_AO_INIT *p_FB_AO_INIT;
  STRUCT_AO *p_STRUCT_AO;
  AOCONFIG *p_AOCONFIG;
  PROC_AO *p_PROC_AO;
  FB_AOSOURCEMLP *p_FB_AOSOURCEMLP;
  TDOUBLEDATA *p_TDOUBLEDATA;
  PROC_DI_INIT *p_PROC_DI_INIT;
  FB_DI_INIT *p_FB_DI_INIT;
  STRUCT_DI *p_STRUCT_DI;
  __IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t *p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t;
  TYPE_RELIABLEBIT *p_TYPE_RELIABLEBIT;
  DICONFIG *p_DICONFIG;
  PROC_DI *p_PROC_DI;
  FB_DISOURCEMLP *p_FB_DISOURCEMLP;
  INT *p_INT;
  UDINT *p_UDINT;
  PROC_DO_INIT *p_PROC_DO_INIT;
  FB_DO_INIT *p_FB_DO_INIT;
  STRUCT_DO *p_STRUCT_DO;
  __IEC___ARRAY_OF_BOOL_16_t *p___IEC___ARRAY_OF_BOOL_16_t;
  DOCONFIG *p_DOCONFIG;
  PROC_DO *p_PROC_DO;
  FB_DOSOURCEMLP *p_FB_DOSOURCEMLP;
  TWORDDATA *p_TWORDDATA;
  OPC_ALGORITMS_SET *p_OPC_ALGORITMS_SET;
  ALGORITMSCONFIG *p_ALGORITMSCONFIG;
  STRUCT_ALG *p_STRUCT_ALG;
  STRUCT_ALGORITMSMANAGER *p_STRUCT_ALGORITMSMANAGER;
  STRUCT_PROTECTIONSMANAGER *p_STRUCT_PROTECTIONSMANAGER;
  STRUCT_ALGTIMERS *p_STRUCT_ALGTIMERS;
  ALGORITMSQUESTIONS *p_ALGORITMSQUESTIONS;
  STRUCT_QUESTION *p_STRUCT_QUESTION;
  OPC_ALGORITMS_GET *p_OPC_ALGORITMS_GET;
  PROC_IM_INIT *p_PROC_IM_INIT;
  FB_KRAN_INIT *p_FB_KRAN_INIT;
  STRUCT_KRAN *p_STRUCT_KRAN;
  FB_SWITCH_INIT *p_FB_SWITCH_INIT;
  STRUCT_SWITCH *p_STRUCT_SWITCH;
  FB_OILPUMP_INIT *p_FB_OILPUMP_INIT;
  STRUCT_OILPUMP *p_STRUCT_OILPUMP;
  FB_SECTIONSWITCH_INIT *p_FB_SECTIONSWITCH_INIT;
  STRUCT_SECTIONSWITCH *p_STRUCT_SECTIONSWITCH;
  FB_ANALOGPARAMETR_INIT *p_FB_ANALOGPARAMETR_INIT;
  STRUCT_ANALOGPARAMETR *p_STRUCT_ANALOGPARAMETR;
  FB_DISCRETPARAMETR_INIT *p_FB_DISCRETPARAMETR_INIT;
  STRUCT_DISCRETPARAMETR *p_STRUCT_DISCRETPARAMETR;
  FB_SINGLESIGNAL_INIT *p_FB_SINGLESIGNAL_INIT;
  STRUCT_SINGLESIGNAL *p_STRUCT_SINGLESIGNAL;
  FB_SINGLEOUTPUT_INIT *p_FB_SINGLEOUTPUT_INIT;
  STRUCT_SINGLEOUTPUT *p_STRUCT_SINGLEOUTPUT;
  IMCONFIG *p_IMCONFIG;
  STRUCT_RESERVEIM *p_STRUCT_RESERVEIM;
  STRUCT_RESERVEIM2 *p_STRUCT_RESERVEIM2;
  IM_SINGLESIGNALS *p_IM_SINGLESIGNALS;
  IM_SINGLEOUTPUTS *p_IM_SINGLEOUTPUTS;
  PROC_IM *p_PROC_IM;
  FB_KRAN *p_FB_KRAN;
  TYPE_STATUSDUALINPUT *p_TYPE_STATUSDUALINPUT;
  TYPE_COMMANDDUALINPUT *p_TYPE_COMMANDDUALINPUT;
  TOF *p_TOF;
  FB_OILPUMP *p_FB_OILPUMP;
  FB_SWITCH *p_FB_SWITCH;
  FB_SECTIONSWITCH *p_FB_SECTIONSWITCH;
  TYPE_BASKETSTATS *p_TYPE_BASKETSTATS;
  FB_MEANDR *p_FB_MEANDR;
  FB_SINGLESIGNAL *p_FB_SINGLESIGNAL;
  FB_SINGLEOUTPUT *p_FB_SINGLEOUTPUT;
  PROC_PROTECTIONS_INIT *p_PROC_PROTECTIONS_INIT;
  FB_DIPROTECTION_INIT *p_FB_DIPROTECTION_INIT;
  STRUCT_DIPROTECTION *p_STRUCT_DIPROTECTION;
  FB_AIPROTECTION_INIT *p_FB_AIPROTECTION_INIT;
  STRUCT_AIPROTECTION *p_STRUCT_AIPROTECTION;
  PROTECTIONSCONFIG *p_PROTECTIONSCONFIG;
  TYPE_PROTECTIONTAGS *p_TYPE_PROTECTIONTAGS;
  PROC_PROTECTION *p_PROC_PROTECTION;
  FB_DIPROTECTION *p_FB_DIPROTECTION;
  F_TRIG *p_F_TRIG;
  FB_MVPROTECTION *p_FB_MVPROTECTION;
  FB_KRANOPENPROTECTION *p_FB_KRANOPENPROTECTION;
  FB_AIPROTECTION *p_FB_AIPROTECTION;
  PROC_ALGORITMS *p_PROC_ALGORITMS;
  REMONTALG *p_REMONTALG;
  TYPE_MODEGPA *p_TYPE_MODEGPA;
  TYPE_COMMANDSPOTECTIONSMANAGER *p_TYPE_COMMANDSPOTECTIONSMANAGER;
  TESTPROTECTIONALG *p_TESTPROTECTIONALG;
  TESTIMALG *p_TESTIMALG;
  FB_AUTOTENALG *p_FB_AUTOTENALG;
  FB_AUTOPNSALG *p_FB_AUTOPNSALG;
  FB_AUTOAVOMALG *p_FB_AUTOAVOMALG;
  FB_VIBEGPNSALG *p_FB_VIBEGPNSALG;
  STRUCT_PHASEALGORITM *p_STRUCT_PHASEALGORITM;
  FB_PH_ALGORITM *p_FB_PH_ALGORITM;
  FB_PH_TIMER *p_FB_PH_TIMER;
  FB_QUESTION *p_FB_QUESTION;
  TYPE_ANSWERS *p_TYPE_ANSWERS;
  FB_PH_SWITCH *p_FB_PH_SWITCH;
  FB_PH_CUSTOMPHASE *p_FB_PH_CUSTOMPHASE;
  FB_AUTONUALG *p_FB_AUTONUALG;
  FB_PUSKOILSYSTEMALG *p_FB_PUSKOILSYSTEMALG;
  FB_PH_WAITANALOGVALUE *p_FB_PH_WAITANALOGVALUE;
  FB_PH_OILPUMP *p_FB_PH_OILPUMP;
  FB_ANTIPOMPAGALG *p_FB_ANTIPOMPAGALG;
  FB_TABLEVALUE_MIN *p_FB_TABLEVALUE_MIN;
  __IEC___ARRAY_OF_TYPE_TABLEREC_9_t *p___IEC___ARRAY_OF_TYPE_TABLEREC_9_t;
  TYPE_TABLEREC *p_TYPE_TABLEREC;
  FB_TABLEVALUE_MAX *p_FB_TABLEVALUE_MAX;
  FB_RASHODALG *p_FB_RASHODALG;
  FB_ZAPASALG *p_FB_ZAPASALG;
  NOALG *p_NOALG;
  FB_PH_KRAN *p_FB_PH_KRAN;
  FB_PH_SECTIONSWITCH *p_FB_PH_SECTIONSWITCH;
  AOALG *p_AOALG;
  PPUALG *p_PPUALG;
  FILLINGALG *p_FILLINGALG;
  FB_PH_DIPROTECTION *p_FB_PH_DIPROTECTION;
  ENGINERUNALG *p_ENGINERUNALG;
  PUSKKALG *p_PUSKKALG;
  PUSKVALG *p_PUSKVALG;
  TESTDPMGALG *p_TESTDPMGALG;
  TESTPMSALG *p_TESTPMSALG;
  FB_PH_AIPROTECTION *p_FB_PH_AIPROTECTION;
  APUSKALG *p_APUSKALG;
  SEMIAUTOPUSKALG *p_SEMIAUTOPUSKALG;
  FB_ALGORITMSMANAGER *p_FB_ALGORITMSMANAGER;
  FB_PROTECTIONSMANAGER *p_FB_PROTECTIONSMANAGER;

  { // 28753 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.DI.RELIABILITY
    st = getVariable(28753);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.DI.RELIABILITY", 50);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_SINGLESIGNAL = (STRUCT_SINGLESIGNAL*)&p_FB_DIPROTECTION->DI;
    p_BOOL = (BOOL*)&p_STRUCT_SINGLESIGNAL->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 28754 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.DI.INVERSE
    st = getVariable(28754);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.DI.INVERSE", 46);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_SINGLESIGNAL = (STRUCT_SINGLESIGNAL*)&p_FB_DIPROTECTION->DI;
    p_BOOL = (BOOL*)&p_STRUCT_SINGLESIGNAL->INVERSE;
    st->value_p = p_BOOL;
  }
  { // 28755 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.DI.DELAYON
    st = getVariable(28755);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.DI.DELAYON", 46);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_SINGLESIGNAL = (STRUCT_SINGLESIGNAL*)&p_FB_DIPROTECTION->DI;
    p_TIME = (TIME*)&p_STRUCT_SINGLESIGNAL->DELAYON;
    st->value_p = p_TIME;
  }
  { // 28756 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.DI.DELAYOFF
    st = getVariable(28756);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.DI.DELAYOFF", 47);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_SINGLESIGNAL = (STRUCT_SINGLESIGNAL*)&p_FB_DIPROTECTION->DI;
    p_TIME = (TIME*)&p_STRUCT_SINGLESIGNAL->DELAYOFF;
    st->value_p = p_TIME;
  }
  { // 28757 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.DI.Q
    st = getVariable(28757);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.DI.Q", 40);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_SINGLESIGNAL = (STRUCT_SINGLESIGNAL*)&p_FB_DIPROTECTION->DI;
    p_BOOL = (BOOL*)&p_STRUCT_SINGLESIGNAL->Q;
    st->value_p = p_BOOL;
  }
  { // 28758 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.DI.STATUS
    st = getVariable(28758);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.DI.STATUS", 45);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_SINGLESIGNAL = (STRUCT_SINGLESIGNAL*)&p_FB_DIPROTECTION->DI;
    p_DWORD = (DWORD*)&p_STRUCT_SINGLESIGNAL->STATUS;
    st->value_p = p_DWORD;
  }
  { // 28759 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.DI.DISABLED_SIG
    st = getVariable(28759);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.DI.DISABLED_SIG", 51);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_SINGLESIGNAL = (STRUCT_SINGLESIGNAL*)&p_FB_DIPROTECTION->DI;
    p_BOOL = (BOOL*)&p_STRUCT_SINGLESIGNAL->DISABLED_SIG;
    st->value_p = p_BOOL;
  }
  { // 28760 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.DELAY
    st = getVariable(28760);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.DELAY", 48);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_TIME = (TIME*)&p_STRUCT_DIPROTECTION->DELAY;
    st->value_p = p_TIME;
  }
  { // 28761 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.INTAG
    st = getVariable(28761);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.INTAG", 48);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BYTE = (BYTE*)&p_STRUCT_DIPROTECTION->INTAG;
    st->value_p = p_BYTE;
  }
  { // 28762 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.INRUNONSTART
    st = getVariable(28762);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.INRUNONSTART", 55);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->INRUNONSTART;
    st->value_p = p_BOOL;
  }
  { // 28763 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.INCANRUN
    st = getVariable(28763);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.INCANRUN", 51);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->INCANRUN;
    st->value_p = p_BOOL;
  }
  { // 28764 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.INOPCCOMMANDSDISABLED
    st = getVariable(28764);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.INOPCCOMMANDSDISABLED", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 28765 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.INCOMMAND
    st = getVariable(28765);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.INCOMMAND", 52);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_WORD = (WORD*)&p_STRUCT_DIPROTECTION->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 28766 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.INCOMMAND_ALG
    st = getVariable(28766);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.INCOMMAND_ALG", 56);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_WORD = (WORD*)&p_STRUCT_DIPROTECTION->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 28767 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.INCOMMAND_ARM
    st = getVariable(28767);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.INCOMMAND_ARM", 56);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_WORD = (WORD*)&p_STRUCT_DIPROTECTION->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 28768 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.TAG
    st = getVariable(28768);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.TAG", 46);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BYTE = (BYTE*)&p_STRUCT_DIPROTECTION->TAG;
    st->value_p = p_BYTE;
  }
  { // 28769 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.STATUS
    st = getVariable(28769);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.STATUS", 49);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_DWORD = (DWORD*)&p_STRUCT_DIPROTECTION->STATUS;
    st->value_p = p_DWORD;
  }
  { // 28770 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.CANRUN
    st = getVariable(28770);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.CANRUN", 49);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->CANRUN;
    st->value_p = p_BOOL;
  }
  { // 28771 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.OPCCOMMANDSDISABLED
    st = getVariable(28771);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.OPCCOMMANDSDISABLED", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 28772 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.ISRUNNING
    st = getVariable(28772);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.ISRUNNING", 52);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->ISRUNNING;
    st->value_p = p_BOOL;
  }
  { // 28773 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.HASERROR
    st = getVariable(28773);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.HASERROR", 51);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->HASERROR;
    st->value_p = p_BOOL;
  }
  { // 28774 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.ISENDED
    st = getVariable(28774);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.ISENDED", 50);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->ISENDED;
    st->value_p = p_BOOL;
  }
  { // 28775 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.REMONT
    st = getVariable(28775);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.REMONT", 49);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->REMONT;
    st->value_p = p_BOOL;
  }
  { // 28776 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.CHECK
    st = getVariable(28776);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.CHECK", 48);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->CHECK;
    st->value_p = p_BOOL;
  }
  { // 28777 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.SIGNALING
    st = getVariable(28777);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.SIGNALING", 52);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->SIGNALING;
    st->value_p = p_BOOL;
  }
  { // 28778 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.SIGNALINGTP
    st = getVariable(28778);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.SIGNALINGTP", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->SIGNALINGTP;
    st->value_p = p_BOOL;
  }
  { // 28779 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.RUNONSTART
    st = getVariable(28779);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.STRDIP.RUNONSTART", 53);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->RUNONSTART;
    st->value_p = p_BOOL;
  }
  { // 28784 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU._PROTECTIONTAGS.NOTHING
    st = getVariable(28784);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU._PROTECTIONTAGS.NOTHING", 59);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_TYPE_PROTECTIONTAGS = (TYPE_PROTECTIONTAGS*)&p_FB_DIPROTECTION->_PROTECTIONTAGS;
    p_BYTE = (BYTE*)&p_TYPE_PROTECTIONTAGS->NOTHING;
    st->value_p = p_BYTE;
  }
  { // 28785 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU._PROTECTIONTAGS.AOB
    st = getVariable(28785);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU._PROTECTIONTAGS.AOB", 55);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_TYPE_PROTECTIONTAGS = (TYPE_PROTECTIONTAGS*)&p_FB_DIPROTECTION->_PROTECTIONTAGS;
    p_BYTE = (BYTE*)&p_TYPE_PROTECTIONTAGS->AOB;
    st->value_p = p_BYTE;
  }
  { // 28786 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU._PROTECTIONTAGS.AOS
    st = getVariable(28786);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU._PROTECTIONTAGS.AOS", 55);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_TYPE_PROTECTIONTAGS = (TYPE_PROTECTIONTAGS*)&p_FB_DIPROTECTION->_PROTECTIONTAGS;
    p_BYTE = (BYTE*)&p_TYPE_PROTECTIONTAGS->AOS;
    st->value_p = p_BYTE;
  }
  { // 28787 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU._PROTECTIONTAGS.AOPOJ
    st = getVariable(28787);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU._PROTECTIONTAGS.AOPOJ", 57);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_TYPE_PROTECTIONTAGS = (TYPE_PROTECTIONTAGS*)&p_FB_DIPROTECTION->_PROTECTIONTAGS;
    p_BYTE = (BYTE*)&p_TYPE_PROTECTIONTAGS->AOPOJ;
    st->value_p = p_BYTE;
  }
  { // 28788 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU._SIGNALINGTP.IN
    st = getVariable(28788);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU._SIGNALINGTP.IN", 51);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_TOF = (TOF*)&p_FB_DIPROTECTION->_SIGNALINGTP;
    p_BOOL = (BOOL*)&p_TOF->IN;
    st->value_p = p_BOOL;
  }
  { // 28789 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU._SIGNALINGTP.PT
    st = getVariable(28789);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU._SIGNALINGTP.PT", 51);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_TOF = (TOF*)&p_FB_DIPROTECTION->_SIGNALINGTP;
    p_TIME = (TIME*)&p_TOF->PT;
    st->value_p = p_TIME;
  }
  { // 28790 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU._SIGNALINGTP.Q
    st = getVariable(28790);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU._SIGNALINGTP.Q", 50);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_TOF = (TOF*)&p_FB_DIPROTECTION->_SIGNALINGTP;
    p_BOOL = (BOOL*)&p_TOF->Q;
    st->value_p = p_BOOL;
  }
  { // 28791 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU._SIGNALINGTP.ET
    st = getVariable(28791);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU._SIGNALINGTP.ET", 51);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_TOF = (TOF*)&p_FB_DIPROTECTION->_SIGNALINGTP;
    p_TIME = (TIME*)&p_TOF->ET;
    st->value_p = p_TIME;
  }
  { // 28792 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU._SIGNALINGTP
    st = getVariable(28792);
    memcpy(st->IEC_TYPE, "TOF", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU._SIGNALINGTP", 48);
    st->size_data = sizeof(TOF);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_TOF = (TOF*)&p_FB_DIPROTECTION->_SIGNALINGTP;
    st->value_p = (void *)p_TOF;
  }
  { // 28793 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.TIMER.IN
    st = getVariable(28793);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.TIMER.IN", 44);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_TON = (TON*)&p_FB_DIPROTECTION->TIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 28794 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.TIMER.PT
    st = getVariable(28794);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.TIMER.PT", 44);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_TON = (TON*)&p_FB_DIPROTECTION->TIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 28795 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.TIMER.Q
    st = getVariable(28795);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.TIMER.Q", 43);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_TON = (TON*)&p_FB_DIPROTECTION->TIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 28796 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.TIMER.ET
    st = getVariable(28796);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.TIMER.ET", 44);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_TON = (TON*)&p_FB_DIPROTECTION->TIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 28797 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.TIMER
    st = getVariable(28797);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.TIMER", 41);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_TON = (TON*)&p_FB_DIPROTECTION->TIMER;
    st->value_p = (void *)p_TON;
  }
  { // 28798 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SIGNALINGTRIG.CLK
    st = getVariable(28798);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SIGNALINGTRIG.CLK", 53);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_R_TRIG = (R_TRIG*)&p_FB_DIPROTECTION->SIGNALINGTRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 28799 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SIGNALINGTRIG.Q
    st = getVariable(28799);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SIGNALINGTRIG.Q", 51);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_R_TRIG = (R_TRIG*)&p_FB_DIPROTECTION->SIGNALINGTRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 28800 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SIGNALINGTRIG
    st = getVariable(28800);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SIGNALINGTRIG", 49);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_R_TRIG = (R_TRIG*)&p_FB_DIPROTECTION->SIGNALINGTRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 28801 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SIGNALINGFTRIG.CLK
    st = getVariable(28801);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SIGNALINGFTRIG.CLK", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_F_TRIG = (F_TRIG*)&p_FB_DIPROTECTION->SIGNALINGFTRIG;
    p_BOOL = (BOOL*)&p_F_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 28802 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SIGNALINGFTRIG.Q
    st = getVariable(28802);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SIGNALINGFTRIG.Q", 52);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_F_TRIG = (F_TRIG*)&p_FB_DIPROTECTION->SIGNALINGFTRIG;
    p_BOOL = (BOOL*)&p_F_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 28803 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SIGNALINGFTRIG
    st = getVariable(28803);
    memcpy(st->IEC_TYPE, "F_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SIGNALINGFTRIG", 50);
    st->size_data = sizeof(F_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_F_TRIG = (F_TRIG*)&p_FB_DIPROTECTION->SIGNALINGFTRIG;
    st->value_p = (void *)p_F_TRIG;
  }
  { // 28804 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SIGNALINGDI
    st = getVariable(28804);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SIGNALINGDI", 47);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_BOOL = (BOOL*)&p_FB_DIPROTECTION->SIGNALINGDI;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 28805 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SOURCE
    st = getVariable(28805);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SOURCE", 42);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_BYTE = (BYTE*)&p_FB_DIPROTECTION->SOURCE;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 28806 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.CMD
    st = getVariable(28806);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.CMD", 39);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_BYTE = (BYTE*)&p_FB_DIPROTECTION->CMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 28807 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.LASTCMD
    st = getVariable(28807);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.LASTCMD", 43);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_BYTE = (BYTE*)&p_FB_DIPROTECTION->LASTCMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 28808 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SOURCE_FOR_STATUS
    st = getVariable(28808);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SOURCE_FOR_STATUS", 53);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_BYTE = (BYTE*)&p_FB_DIPROTECTION->SOURCE_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 28809 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.CMD_FOR_STATUS
    st = getVariable(28809);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.CMD_FOR_STATUS", 50);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_BYTE = (BYTE*)&p_FB_DIPROTECTION->CMD_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 28810 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.COMMAND_ERROR_FOR_STATUS
    st = getVariable(28810);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.COMMAND_ERROR_FOR_STATUS", 60);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_BYTE = (BYTE*)&p_FB_DIPROTECTION->COMMAND_ERROR_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 28811 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.RESETCMDTIMER.IN
    st = getVariable(28811);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.RESETCMDTIMER.IN", 52);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_TON = (TON*)&p_FB_DIPROTECTION->RESETCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 28812 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.RESETCMDTIMER.PT
    st = getVariable(28812);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.RESETCMDTIMER.PT", 52);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_TON = (TON*)&p_FB_DIPROTECTION->RESETCMDTIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 28813 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.RESETCMDTIMER.Q
    st = getVariable(28813);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.RESETCMDTIMER.Q", 51);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_TON = (TON*)&p_FB_DIPROTECTION->RESETCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 28814 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.RESETCMDTIMER.ET
    st = getVariable(28814);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.RESETCMDTIMER.ET", 52);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_TON = (TON*)&p_FB_DIPROTECTION->RESETCMDTIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 28815 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.RESETCMDTIMER
    st = getVariable(28815);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.RESETCMDTIMER", 49);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_TON = (TON*)&p_FB_DIPROTECTION->RESETCMDTIMER;
    st->value_p = (void *)p_TON;
  }
  { // 28816 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.RESETCMDTIMERPRIZNAK
    st = getVariable(28816);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.RESETCMDTIMERPRIZNAK", 56);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_BOOL = (BOOL*)&p_FB_DIPROTECTION->RESETCMDTIMERPRIZNAK;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 28817 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SIGNALINTIMER.IN
    st = getVariable(28817);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SIGNALINTIMER.IN", 52);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_TON = (TON*)&p_FB_DIPROTECTION->SIGNALINTIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 28818 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SIGNALINTIMER.PT
    st = getVariable(28818);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SIGNALINTIMER.PT", 52);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_TON = (TON*)&p_FB_DIPROTECTION->SIGNALINTIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 28819 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SIGNALINTIMER.Q
    st = getVariable(28819);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SIGNALINTIMER.Q", 51);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_TON = (TON*)&p_FB_DIPROTECTION->SIGNALINTIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 28820 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SIGNALINTIMER.ET
    st = getVariable(28820);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SIGNALINTIMER.ET", 52);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_TON = (TON*)&p_FB_DIPROTECTION->SIGNALINTIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 28821 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SIGNALINTIMER
    st = getVariable(28821);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.SIGNALINTIMER", 49);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_TON = (TON*)&p_FB_DIPROTECTION->SIGNALINTIMER;
    st->value_p = (void *)p_TON;
  }
  { // 28822 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.RUNONSTART_TRIG.CLK
    st = getVariable(28822);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.RUNONSTART_TRIG.CLK", 55);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_R_TRIG = (R_TRIG*)&p_FB_DIPROTECTION->RUNONSTART_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 28823 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.RUNONSTART_TRIG.Q
    st = getVariable(28823);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.RUNONSTART_TRIG.Q", 53);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_R_TRIG = (R_TRIG*)&p_FB_DIPROTECTION->RUNONSTART_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 28824 PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.RUNONSTART_TRIG
    st = getVariable(28824);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_AO_SHU.RUNONSTART_TRIG", 51);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_AO_SHU;
    p_R_TRIG = (R_TRIG*)&p_FB_DIPROTECTION->RUNONSTART_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }

  return 0;
}

// clang-format on
