// clang-format off

#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include "POUS.h"
#include <beremiz/beremiz.h>

#include "iec_types_all.h"
#include "config1.h"

extern PROGRAM0 RESOURCE1__INSTANCE0;

#ifdef DEBUG_PLC
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err][%s:%d]: " _PRNTMSG "\n", __func__, __LINE__, ##__VA_ARGS__)
#else
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err]: " _PRNTMSG "\n", ##__VA_ARGS__)
#endif // DEBUG_PLC

void UnpackVar(void* varp, __IEC_types_enum vartype, void **value_p, void **f_value_p, uint8_t **flags);

int __variables_init_FB_DAVLENIJAMASLAPOSLENU(){
  iec_var_t *st;

  PROGRAM0 *p_PROGRAM0;
  LREAL *p_LREAL;
  ULINT *p_ULINT;
  REAL *p_REAL;
  FB_TIMINGS *p_FB_TIMINGS;
  BOOL *p_BOOL;
  UINT *p_UINT;
  PROC_AI_INIT *p_PROC_AI_INIT;
  FB_AI_INIT *p_FB_AI_INIT;
  TIME *p_TIME;
  STRUCT_AI *p_STRUCT_AI;
  DWORD *p_DWORD;
  BYTE *p_BYTE;
  WORD *p_WORD;
  AICONFIG *p_AICONFIG;
  PROC_AI *p_PROC_AI;
  FB_AISOURCEMLP *p_FB_AISOURCEMLP;
  TITEMAIN *p_TITEMAIN;
  TITEMDIN *p_TITEMDIN;
  TYPE_STATUSAI *p_TYPE_STATUSAI;
  TYPE_COMMANDANALOG *p_TYPE_COMMANDANALOG;
  FB_SUNPACKERCOMMAND *p_FB_SUNPACKERCOMMAND;
  TYPE_ANALOGLIMITFLAGS *p_TYPE_ANALOGLIMITFLAGS;
  TON *p_TON;
  R_TRIG *p_R_TRIG;
  FB_AISOURCEMLP_TIMER *p_FB_AISOURCEMLP_TIMER;
  PROC_AO_INIT *p_PROC_AO_INIT;
  FB_AO_INIT *p_FB_AO_INIT;
  STRUCT_AO *p_STRUCT_AO;
  AOCONFIG *p_AOCONFIG;
  PROC_AO *p_PROC_AO;
  FB_AOSOURCEMLP *p_FB_AOSOURCEMLP;
  TDOUBLEDATA *p_TDOUBLEDATA;
  PROC_DI_INIT *p_PROC_DI_INIT;
  FB_DI_INIT *p_FB_DI_INIT;
  STRUCT_DI *p_STRUCT_DI;
  __IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t *p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t;
  TYPE_RELIABLEBIT *p_TYPE_RELIABLEBIT;
  DICONFIG *p_DICONFIG;
  PROC_DI *p_PROC_DI;
  FB_DISOURCEMLP *p_FB_DISOURCEMLP;
  INT *p_INT;
  UDINT *p_UDINT;
  PROC_DO_INIT *p_PROC_DO_INIT;
  FB_DO_INIT *p_FB_DO_INIT;
  STRUCT_DO *p_STRUCT_DO;
  __IEC___ARRAY_OF_BOOL_16_t *p___IEC___ARRAY_OF_BOOL_16_t;
  DOCONFIG *p_DOCONFIG;
  PROC_DO *p_PROC_DO;
  FB_DOSOURCEMLP *p_FB_DOSOURCEMLP;
  TWORDDATA *p_TWORDDATA;
  OPC_ALGORITMS_SET *p_OPC_ALGORITMS_SET;
  ALGORITMSCONFIG *p_ALGORITMSCONFIG;
  STRUCT_ALG *p_STRUCT_ALG;
  STRUCT_ALGORITMSMANAGER *p_STRUCT_ALGORITMSMANAGER;
  STRUCT_PROTECTIONSMANAGER *p_STRUCT_PROTECTIONSMANAGER;
  STRUCT_ALGTIMERS *p_STRUCT_ALGTIMERS;
  ALGORITMSQUESTIONS *p_ALGORITMSQUESTIONS;
  STRUCT_QUESTION *p_STRUCT_QUESTION;
  OPC_ALGORITMS_GET *p_OPC_ALGORITMS_GET;
  PROC_IM_INIT *p_PROC_IM_INIT;
  FB_KRAN_INIT *p_FB_KRAN_INIT;
  STRUCT_KRAN *p_STRUCT_KRAN;
  FB_SWITCH_INIT *p_FB_SWITCH_INIT;
  STRUCT_SWITCH *p_STRUCT_SWITCH;
  FB_OILPUMP_INIT *p_FB_OILPUMP_INIT;
  STRUCT_OILPUMP *p_STRUCT_OILPUMP;
  FB_SECTIONSWITCH_INIT *p_FB_SECTIONSWITCH_INIT;
  STRUCT_SECTIONSWITCH *p_STRUCT_SECTIONSWITCH;
  FB_ANALOGPARAMETR_INIT *p_FB_ANALOGPARAMETR_INIT;
  STRUCT_ANALOGPARAMETR *p_STRUCT_ANALOGPARAMETR;
  FB_DISCRETPARAMETR_INIT *p_FB_DISCRETPARAMETR_INIT;
  STRUCT_DISCRETPARAMETR *p_STRUCT_DISCRETPARAMETR;
  FB_SINGLESIGNAL_INIT *p_FB_SINGLESIGNAL_INIT;
  STRUCT_SINGLESIGNAL *p_STRUCT_SINGLESIGNAL;
  FB_SINGLEOUTPUT_INIT *p_FB_SINGLEOUTPUT_INIT;
  STRUCT_SINGLEOUTPUT *p_STRUCT_SINGLEOUTPUT;
  IMCONFIG *p_IMCONFIG;
  STRUCT_RESERVEIM *p_STRUCT_RESERVEIM;
  STRUCT_RESERVEIM2 *p_STRUCT_RESERVEIM2;
  IM_SINGLESIGNALS *p_IM_SINGLESIGNALS;
  IM_SINGLEOUTPUTS *p_IM_SINGLEOUTPUTS;
  PROC_IM *p_PROC_IM;
  FB_KRAN *p_FB_KRAN;
  TYPE_STATUSDUALINPUT *p_TYPE_STATUSDUALINPUT;
  TYPE_COMMANDDUALINPUT *p_TYPE_COMMANDDUALINPUT;
  TOF *p_TOF;
  FB_OILPUMP *p_FB_OILPUMP;
  FB_SWITCH *p_FB_SWITCH;
  FB_SECTIONSWITCH *p_FB_SECTIONSWITCH;
  TYPE_BASKETSTATS *p_TYPE_BASKETSTATS;
  FB_MEANDR *p_FB_MEANDR;
  FB_SINGLESIGNAL *p_FB_SINGLESIGNAL;
  FB_SINGLEOUTPUT *p_FB_SINGLEOUTPUT;
  PROC_PROTECTIONS_INIT *p_PROC_PROTECTIONS_INIT;
  FB_DIPROTECTION_INIT *p_FB_DIPROTECTION_INIT;
  STRUCT_DIPROTECTION *p_STRUCT_DIPROTECTION;
  FB_AIPROTECTION_INIT *p_FB_AIPROTECTION_INIT;
  STRUCT_AIPROTECTION *p_STRUCT_AIPROTECTION;
  PROTECTIONSCONFIG *p_PROTECTIONSCONFIG;
  TYPE_PROTECTIONTAGS *p_TYPE_PROTECTIONTAGS;
  PROC_PROTECTION *p_PROC_PROTECTION;
  FB_MVPROTECTION *p_FB_MVPROTECTION;
  F_TRIG *p_F_TRIG;
  FB_DIPROTECTION *p_FB_DIPROTECTION;
  FB_KRANOPENPROTECTION *p_FB_KRANOPENPROTECTION;
  FB_AIPROTECTION *p_FB_AIPROTECTION;
  PROC_ALGORITMS *p_PROC_ALGORITMS;
  REMONTALG *p_REMONTALG;
  TYPE_MODEGPA *p_TYPE_MODEGPA;
  TYPE_COMMANDSPOTECTIONSMANAGER *p_TYPE_COMMANDSPOTECTIONSMANAGER;
  TESTPROTECTIONALG *p_TESTPROTECTIONALG;
  TESTIMALG *p_TESTIMALG;
  FB_AUTOTENALG *p_FB_AUTOTENALG;
  FB_AUTOPNSALG *p_FB_AUTOPNSALG;
  FB_AUTOAVOMALG *p_FB_AUTOAVOMALG;
  FB_VIBEGPNSALG *p_FB_VIBEGPNSALG;
  STRUCT_PHASEALGORITM *p_STRUCT_PHASEALGORITM;
  FB_PH_ALGORITM *p_FB_PH_ALGORITM;
  FB_PH_TIMER *p_FB_PH_TIMER;
  FB_QUESTION *p_FB_QUESTION;
  TYPE_ANSWERS *p_TYPE_ANSWERS;
  FB_PH_SWITCH *p_FB_PH_SWITCH;
  FB_PH_CUSTOMPHASE *p_FB_PH_CUSTOMPHASE;
  FB_AUTONUALG *p_FB_AUTONUALG;
  FB_PUSKOILSYSTEMALG *p_FB_PUSKOILSYSTEMALG;
  FB_PH_WAITANALOGVALUE *p_FB_PH_WAITANALOGVALUE;
  FB_PH_OILPUMP *p_FB_PH_OILPUMP;
  FB_ANTIPOMPAGALG *p_FB_ANTIPOMPAGALG;
  FB_TABLEVALUE_MIN *p_FB_TABLEVALUE_MIN;
  __IEC___ARRAY_OF_TYPE_TABLEREC_9_t *p___IEC___ARRAY_OF_TYPE_TABLEREC_9_t;
  TYPE_TABLEREC *p_TYPE_TABLEREC;
  FB_TABLEVALUE_MAX *p_FB_TABLEVALUE_MAX;
  FB_RASHODALG *p_FB_RASHODALG;
  FB_ZAPASALG *p_FB_ZAPASALG;
  NOALG *p_NOALG;
  FB_PH_KRAN *p_FB_PH_KRAN;
  FB_PH_SECTIONSWITCH *p_FB_PH_SECTIONSWITCH;
  AOALG *p_AOALG;
  PPUALG *p_PPUALG;
  FILLINGALG *p_FILLINGALG;
  FB_PH_DIPROTECTION *p_FB_PH_DIPROTECTION;
  ENGINERUNALG *p_ENGINERUNALG;
  PUSKKALG *p_PUSKKALG;
  PUSKVALG *p_PUSKVALG;
  TESTDPMGALG *p_TESTDPMGALG;
  TESTPMSALG *p_TESTPMSALG;
  FB_PH_AIPROTECTION *p_FB_PH_AIPROTECTION;
  APUSKALG *p_APUSKALG;
  SEMIAUTOPUSKALG *p_SEMIAUTOPUSKALG;
  FB_ALGORITMSMANAGER *p_FB_ALGORITMSMANAGER;
  FB_PROTECTIONSMANAGER *p_FB_PROTECTIONSMANAGER;

  { // 8106 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ARAIN.WFLAGS
    st = getVariable(8106);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ARAIN.WFLAGS", 54);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TITEMAIN = (TITEMAIN*)&p_FB_AISOURCEMLP->ARAIN;
    p_UINT = (UINT*)&p_TITEMAIN->WFLAGS;
    st->value_p = p_UINT;
  }
  { // 8107 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ARAIN.WRESERVED
    st = getVariable(8107);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ARAIN.WRESERVED", 57);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TITEMAIN = (TITEMAIN*)&p_FB_AISOURCEMLP->ARAIN;
    p_UINT = (UINT*)&p_TITEMAIN->WRESERVED;
    st->value_p = p_UINT;
  }
  { // 8108 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ARAIN.DBLVALUE
    st = getVariable(8108);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ARAIN.DBLVALUE", 56);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TITEMAIN = (TITEMAIN*)&p_FB_AISOURCEMLP->ARAIN;
    p_LREAL = (LREAL*)&p_TITEMAIN->DBLVALUE;
    st->value_p = p_LREAL;
  }
  { // 8109 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ARAIN.NANOSEC
    st = getVariable(8109);
    memcpy(st->IEC_TYPE, "ULINT", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ARAIN.NANOSEC", 55);
    st->size_data = sizeof(ULINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TITEMAIN = (TITEMAIN*)&p_FB_AISOURCEMLP->ARAIN;
    p_ULINT = (ULINT*)&p_TITEMAIN->NANOSEC;
    st->value_p = p_ULINT;
  }
  { // 8110 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ARAIN.RESERVE
    st = getVariable(8110);
    memcpy(st->IEC_TYPE, "ULINT", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ARAIN.RESERVE", 55);
    st->size_data = sizeof(ULINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TITEMAIN = (TITEMAIN*)&p_FB_AISOURCEMLP->ARAIN;
    p_ULINT = (ULINT*)&p_TITEMAIN->RESERVE;
    st->value_p = p_ULINT;
  }
  { // 8111 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ERR_MOD.WFLAGS
    st = getVariable(8111);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ERR_MOD.WFLAGS", 56);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TITEMDIN = (TITEMDIN*)&p_FB_AISOURCEMLP->ERR_MOD;
    p_UINT = (UINT*)&p_TITEMDIN->WFLAGS;
    st->value_p = p_UINT;
  }
  { // 8112 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ERR_MOD.WVALUE
    st = getVariable(8112);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ERR_MOD.WVALUE", 56);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TITEMDIN = (TITEMDIN*)&p_FB_AISOURCEMLP->ERR_MOD;
    p_UINT = (UINT*)&p_TITEMDIN->WVALUE;
    st->value_p = p_UINT;
  }
  { // 8113 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ERR_MOD.NANOSEC
    st = getVariable(8113);
    memcpy(st->IEC_TYPE, "ULINT", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ERR_MOD.NANOSEC", 57);
    st->size_data = sizeof(ULINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TITEMDIN = (TITEMDIN*)&p_FB_AISOURCEMLP->ERR_MOD;
    p_ULINT = (ULINT*)&p_TITEMDIN->NANOSEC;
    st->value_p = p_ULINT;
  }
  { // 8114 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ERR_MOD.RESERVE
    st = getVariable(8114);
    memcpy(st->IEC_TYPE, "ULINT", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ERR_MOD.RESERVE", 57);
    st->size_data = sizeof(ULINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TITEMDIN = (TITEMDIN*)&p_FB_AISOURCEMLP->ERR_MOD;
    p_ULINT = (ULINT*)&p_TITEMDIN->RESERVE;
    st->value_p = p_ULINT;
  }
  { // 8115 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.VALUE
    st = getVariable(8115);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.VALUE", 53);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->VALUE;
    st->value_p = p_LREAL;
  }
  { // 8116 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.STATUS
    st = getVariable(8116);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.STATUS", 54);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_DWORD = (DWORD*)&p_STRUCT_AI->STATUS;
    st->value_p = p_DWORD;
  }
  { // 8117 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.INTERVAL
    st = getVariable(8117);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.INTERVAL", 56);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BYTE = (BYTE*)&p_STRUCT_AI->INTERVAL;
    st->value_p = p_BYTE;
  }
  { // 8118 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.INCOMMAND
    st = getVariable(8118);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.INCOMMAND", 57);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 8119 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.BLCONNECT
    st = getVariable(8119);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.BLCONNECT", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->BLCONNECT;
    st->value_p = p_BOOL;
  }
  { // 8120 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DLL
    st = getVariable(8120);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DLL", 51);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLL;
    st->value_p = p_LREAL;
  }
  { // 8121 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DHL
    st = getVariable(8121);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DHL", 51);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHL;
    st->value_p = p_LREAL;
  }
  { // 8122 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DLA
    st = getVariable(8122);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DLA", 51);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLA;
    st->value_p = p_LREAL;
  }
  { // 8123 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DHA
    st = getVariable(8123);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DHA", 51);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHA;
    st->value_p = p_LREAL;
  }
  { // 8124 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DLW
    st = getVariable(8124);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DLW", 51);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLW;
    st->value_p = p_LREAL;
  }
  { // 8125 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DHW
    st = getVariable(8125);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DHW", 51);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHW;
    st->value_p = p_LREAL;
  }
  { // 8126 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.LL
    st = getVariable(8126);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.LL", 50);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LL;
    st->value_p = p_LREAL;
  }
  { // 8127 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.HL
    st = getVariable(8127);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.HL", 50);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HL;
    st->value_p = p_LREAL;
  }
  { // 8128 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.LA
    st = getVariable(8128);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.LA", 50);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LA;
    st->value_p = p_LREAL;
  }
  { // 8129 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.HA
    st = getVariable(8129);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.HA", 50);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HA;
    st->value_p = p_LREAL;
  }
  { // 8130 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.LW
    st = getVariable(8130);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.LW", 50);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LW;
    st->value_p = p_LREAL;
  }
  { // 8131 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.HW
    st = getVariable(8131);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.HW", 50);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HW;
    st->value_p = p_LREAL;
  }
  { // 8132 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.ISVALIDREF_LA
    st = getVariable(8132);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.ISVALIDREF_LA", 61);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_LA;
    st->value_p = p_BOOL;
  }
  { // 8133 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.ISVALIDREF_HA
    st = getVariable(8133);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.ISVALIDREF_HA", 61);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_HA;
    st->value_p = p_BOOL;
  }
  { // 8134 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.ISVALIDREF_LW
    st = getVariable(8134);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.ISVALIDREF_LW", 61);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_LW;
    st->value_p = p_BOOL;
  }
  { // 8135 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.ISVALIDREF_HW
    st = getVariable(8135);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.ISVALIDREF_HW", 61);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_HW;
    st->value_p = p_BOOL;
  }
  { // 8136 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.INPLL
    st = getVariable(8136);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.INPLL", 53);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->INPLL;
    st->value_p = p_LREAL;
  }
  { // 8137 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.INPHL
    st = getVariable(8137);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.INPHL", 53);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->INPHL;
    st->value_p = p_LREAL;
  }
  { // 8138 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.CURRENTSHOTCIRCUIT
    st = getVariable(8138);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.CURRENTSHOTCIRCUIT", 66);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CURRENTSHOTCIRCUIT;
    st->value_p = p_LREAL;
  }
  { // 8139 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.CURRENTBREAKCIRCUIT
    st = getVariable(8139);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.CURRENTBREAKCIRCUIT", 67);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CURRENTBREAKCIRCUIT;
    st->value_p = p_LREAL;
  }
  { // 8140 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.MAXCHANGESPEED
    st = getVariable(8140);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.MAXCHANGESPEED", 62);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXCHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 8141 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.MAXCHANGESPEEDDOWN
    st = getVariable(8141);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.MAXCHANGESPEEDDOWN", 66);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXCHANGESPEEDDOWN;
    st->value_p = p_LREAL;
  }
  { // 8142 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.CHANGESPEED
    st = getVariable(8142);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.CHANGESPEED", 59);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 8143 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.HISTERESIS
    st = getVariable(8143);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.HISTERESIS", 58);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HISTERESIS;
    st->value_p = p_LREAL;
  }
  { // 8144 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.APERTURFILTER
    st = getVariable(8144);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.APERTURFILTER", 61);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->APERTURFILTER;
    st->value_p = p_LREAL;
  }
  { // 8145 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.EXPONENTIALFILTER
    st = getVariable(8145);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.EXPONENTIALFILTER", 65);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->EXPONENTIALFILTER;
    st->value_p = p_LREAL;
  }
  { // 8146 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.RASSOGLASOVANIE
    st = getVariable(8146);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.RASSOGLASOVANIE", 63);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->RASSOGLASOVANIE;
    st->value_p = p_LREAL;
  }
  { // 8147 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.OPCCOMMANDSDISABLED
    st = getVariable(8147);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.OPCCOMMANDSDISABLED", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 8148 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DISABLED_LA
    st = getVariable(8148);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DISABLED_LA", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_LA;
    st->value_p = p_BOOL;
  }
  { // 8149 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DISABLED_HA
    st = getVariable(8149);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DISABLED_HA", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_HA;
    st->value_p = p_BOOL;
  }
  { // 8150 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DISABLED_LW
    st = getVariable(8150);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DISABLED_LW", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_LW;
    st->value_p = p_BOOL;
  }
  { // 8151 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DISABLED_HW
    st = getVariable(8151);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DISABLED_HW", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_HW;
    st->value_p = p_BOOL;
  }
  { // 8152 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DELAYLA
    st = getVariable(8152);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DELAYLA", 55);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYLA;
    st->value_p = p_TIME;
  }
  { // 8153 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DELAYLW
    st = getVariable(8153);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DELAYLW", 55);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYLW;
    st->value_p = p_TIME;
  }
  { // 8154 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DELAYHW
    st = getVariable(8154);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DELAYHW", 55);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYHW;
    st->value_p = p_TIME;
  }
  { // 8155 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DELAYHA
    st = getVariable(8155);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DELAYHA", 55);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYHA;
    st->value_p = p_TIME;
  }
  { // 8156 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.MINVALUE_ISVALIDREF
    st = getVariable(8156);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.MINVALUE_ISVALIDREF", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->MINVALUE_ISVALIDREF;
    st->value_p = p_BOOL;
  }
  { // 8157 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.MAXVALUE_ISVALIDREF
    st = getVariable(8157);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.MAXVALUE_ISVALIDREF", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->MAXVALUE_ISVALIDREF;
    st->value_p = p_BOOL;
  }
  { // 8158 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.MINVALUE
    st = getVariable(8158);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.MINVALUE", 56);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MINVALUE;
    st->value_p = p_LREAL;
  }
  { // 8159 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.MAXVALUE
    st = getVariable(8159);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.MAXVALUE", 56);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXVALUE;
    st->value_p = p_LREAL;
  }
  { // 8160 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.INOPCCOMMANDSDISABLED
    st = getVariable(8160);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.INOPCCOMMANDSDISABLED", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 8161 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.IMIT
    st = getVariable(8161);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.IMIT", 52);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->IMIT;
    st->value_p = p_BOOL;
  }
  { // 8162 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.REMONT
    st = getVariable(8162);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.REMONT", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->REMONT;
    st->value_p = p_BOOL;
  }
  { // 8163 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.NS
    st = getVariable(8163);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.NS", 50);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS;
    st->value_p = p_BOOL;
  }
  { // 8164 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.NS_MIN
    st = getVariable(8164);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.NS_MIN", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS_MIN;
    st->value_p = p_BOOL;
  }
  { // 8165 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.NS_MAX
    st = getVariable(8165);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.NS_MAX", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS_MAX;
    st->value_p = p_BOOL;
  }
  { // 8166 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.INCOMMAND_ALG
    st = getVariable(8166);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.INCOMMAND_ALG", 61);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 8167 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.INCOMMAND_ARM
    st = getVariable(8167);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.INCOMMAND_ARM", 61);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 8168 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DMAXCHANGESPEED
    st = getVariable(8168);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DMAXCHANGESPEED", 63);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DMAXCHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 8169 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DMAXCHANGESPEEDDOWN
    st = getVariable(8169);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.STRAI.DMAXCHANGESPEEDDOWN", 67);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DMAXCHANGESPEEDDOWN;
    st->value_p = p_LREAL;
  }
  { // 8170 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._STATUSAI.NOTDEFINED
    st = getVariable(8170);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._STATUSAI.NOTDEFINED", 62);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NOTDEFINED;
    st->value_p = p_BYTE;
  }
  { // 8171 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._STATUSAI.LL
    st = getVariable(8171);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._STATUSAI.LL", 54);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LL;
    st->value_p = p_BYTE;
  }
  { // 8172 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._STATUSAI.HL
    st = getVariable(8172);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._STATUSAI.HL", 54);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HL;
    st->value_p = p_BYTE;
  }
  { // 8173 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._STATUSAI.NOTRELIABLE
    st = getVariable(8173);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._STATUSAI.NOTRELIABLE", 63);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NOTRELIABLE;
    st->value_p = p_BYTE;
  }
  { // 8174 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._STATUSAI.NORMAL
    st = getVariable(8174);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._STATUSAI.NORMAL", 58);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NORMAL;
    st->value_p = p_BYTE;
  }
  { // 8175 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._STATUSAI.LW
    st = getVariable(8175);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._STATUSAI.LW", 54);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LW;
    st->value_p = p_BYTE;
  }
  { // 8176 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._STATUSAI.HW
    st = getVariable(8176);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._STATUSAI.HW", 54);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HW;
    st->value_p = p_BYTE;
  }
  { // 8177 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._STATUSAI.LA
    st = getVariable(8177);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._STATUSAI.LA", 54);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LA;
    st->value_p = p_BYTE;
  }
  { // 8178 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._STATUSAI.HA
    st = getVariable(8178);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._STATUSAI.HA", 54);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HA;
    st->value_p = p_BYTE;
  }
  { // 8179 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._COMMANDANALOG.CMD_SETUSTAVKI
    st = getVariable(8179);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._COMMANDANALOG.CMD_SETUSTAVKI", 71);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TYPE_COMMANDANALOG = (TYPE_COMMANDANALOG*)&p_FB_AISOURCEMLP->_COMMANDANALOG;
    p_WORD = (WORD*)&p_TYPE_COMMANDANALOG->CMD_SETUSTAVKI;
    st->value_p = p_WORD;
  }
  { // 8180 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._COMMANDANALOG.CMD_SETREMONT
    st = getVariable(8180);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._COMMANDANALOG.CMD_SETREMONT", 70);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TYPE_COMMANDANALOG = (TYPE_COMMANDANALOG*)&p_FB_AISOURCEMLP->_COMMANDANALOG;
    p_WORD = (WORD*)&p_TYPE_COMMANDANALOG->CMD_SETREMONT;
    st->value_p = p_WORD;
  }
  { // 8181 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._COMMANDANALOG.CMD_RESETREMONT
    st = getVariable(8181);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._COMMANDANALOG.CMD_RESETREMONT", 72);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TYPE_COMMANDANALOG = (TYPE_COMMANDANALOG*)&p_FB_AISOURCEMLP->_COMMANDANALOG;
    p_WORD = (WORD*)&p_TYPE_COMMANDANALOG->CMD_RESETREMONT;
    st->value_p = p_WORD;
  }
  { // 8182 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._COMMANDANALOG.CMD_KVITNOTRELIABLE
    st = getVariable(8182);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._COMMANDANALOG.CMD_KVITNOTRELIABLE", 76);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TYPE_COMMANDANALOG = (TYPE_COMMANDANALOG*)&p_FB_AISOURCEMLP->_COMMANDANALOG;
    p_WORD = (WORD*)&p_TYPE_COMMANDANALOG->CMD_KVITNOTRELIABLE;
    st->value_p = p_WORD;
  }
  { // 8187 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._ANALOGLIMITFLAGS.NONE
    st = getVariable(8187);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._ANALOGLIMITFLAGS.NONE", 64);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->NONE;
    st->value_p = p_BYTE;
  }
  { // 8188 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._ANALOGLIMITFLAGS.LL
    st = getVariable(8188);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._ANALOGLIMITFLAGS.LL", 62);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->LL;
    st->value_p = p_BYTE;
  }
  { // 8189 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._ANALOGLIMITFLAGS.LW
    st = getVariable(8189);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._ANALOGLIMITFLAGS.LW", 62);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->LW;
    st->value_p = p_BYTE;
  }
  { // 8190 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._ANALOGLIMITFLAGS.HW
    st = getVariable(8190);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._ANALOGLIMITFLAGS.HW", 62);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->HW;
    st->value_p = p_BYTE;
  }
  { // 8191 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._ANALOGLIMITFLAGS.LA
    st = getVariable(8191);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._ANALOGLIMITFLAGS.LA", 62);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->LA;
    st->value_p = p_BYTE;
  }
  { // 8192 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._ANALOGLIMITFLAGS.HA
    st = getVariable(8192);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._ANALOGLIMITFLAGS.HA", 62);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->HA;
    st->value_p = p_BYTE;
  }
  { // 8193 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._ANALOGLIMITFLAGS.HL
    st = getVariable(8193);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._ANALOGLIMITFLAGS.HL", 62);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->HL;
    st->value_p = p_BYTE;
  }
  { // 8194 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._ANALOGLIMITFLAGS.SIPUP
    st = getVariable(8194);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._ANALOGLIMITFLAGS.SIPUP", 65);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->SIPUP;
    st->value_p = p_BYTE;
  }
  { // 8195 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._ANALOGLIMITFLAGS.SIPDOWN
    st = getVariable(8195);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._ANALOGLIMITFLAGS.SIPDOWN", 67);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->SIPDOWN;
    st->value_p = p_BYTE;
  }
  { // 8196 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.NOTRELIABLE
    st = getVariable(8196);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.NOTRELIABLE", 53);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_BOOL = (BOOL*)&p_FB_AISOURCEMLP->NOTRELIABLE;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8197 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._LASTVALUE
    st = getVariable(8197);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._LASTVALUE", 52);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_LREAL = (LREAL*)&p_FB_AISOURCEMLP->_LASTVALUE;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8198 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.RESETCMDTIMER.IN
    st = getVariable(8198);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.RESETCMDTIMER.IN", 58);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TON = (TON*)&p_FB_AISOURCEMLP->RESETCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 8199 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.RESETCMDTIMER.PT
    st = getVariable(8199);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.RESETCMDTIMER.PT", 58);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TON = (TON*)&p_FB_AISOURCEMLP->RESETCMDTIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 8200 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.RESETCMDTIMER.Q
    st = getVariable(8200);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.RESETCMDTIMER.Q", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TON = (TON*)&p_FB_AISOURCEMLP->RESETCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 8201 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.RESETCMDTIMER.ET
    st = getVariable(8201);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.RESETCMDTIMER.ET", 58);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TON = (TON*)&p_FB_AISOURCEMLP->RESETCMDTIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 8202 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.RESETCMDTIMER
    st = getVariable(8202);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.RESETCMDTIMER", 55);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TON = (TON*)&p_FB_AISOURCEMLP->RESETCMDTIMER;
    st->value_p = (void *)p_TON;
  }
  { // 8203 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._LASTVALUETIMER.IN
    st = getVariable(8203);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._LASTVALUETIMER.IN", 60);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TON = (TON*)&p_FB_AISOURCEMLP->_LASTVALUETIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 8204 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._LASTVALUETIMER.PT
    st = getVariable(8204);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._LASTVALUETIMER.PT", 60);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TON = (TON*)&p_FB_AISOURCEMLP->_LASTVALUETIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 8205 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._LASTVALUETIMER.Q
    st = getVariable(8205);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._LASTVALUETIMER.Q", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TON = (TON*)&p_FB_AISOURCEMLP->_LASTVALUETIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 8206 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._LASTVALUETIMER.ET
    st = getVariable(8206);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._LASTVALUETIMER.ET", 60);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TON = (TON*)&p_FB_AISOURCEMLP->_LASTVALUETIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 8207 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._LASTVALUETIMER
    st = getVariable(8207);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU._LASTVALUETIMER", 57);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_TON = (TON*)&p_FB_AISOURCEMLP->_LASTVALUETIMER;
    st->value_p = (void *)p_TON;
  }
  { // 8208 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.RESETCMDTIMERPRIZNAK
    st = getVariable(8208);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.RESETCMDTIMERPRIZNAK", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_BOOL = (BOOL*)&p_FB_AISOURCEMLP->RESETCMDTIMERPRIZNAK;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8209 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.K
    st = getVariable(8209);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.K", 43);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_LREAL = (LREAL*)&p_FB_AISOURCEMLP->K;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8210 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.B
    st = getVariable(8210);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.B", 43);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_LREAL = (LREAL*)&p_FB_AISOURCEMLP->B;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8211 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.AP
    st = getVariable(8211);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.AP", 44);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_LREAL = (LREAL*)&p_FB_AISOURCEMLP->AP;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8212 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.RAZNITSA
    st = getVariable(8212);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.RAZNITSA", 50);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_LREAL = (LREAL*)&p_FB_AISOURCEMLP->RAZNITSA;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8213 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.RABS
    st = getVariable(8213);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.RABS", 46);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_LREAL = (LREAL*)&p_FB_AISOURCEMLP->RABS;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8214 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.H
    st = getVariable(8214);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.H", 43);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_LREAL = (LREAL*)&p_FB_AISOURCEMLP->H;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8215 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.MISMATCH
    st = getVariable(8215);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.MISMATCH", 50);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_LREAL = (LREAL*)&p_FB_AISOURCEMLP->MISMATCH;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8216 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.PARAMETR
    st = getVariable(8216);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.PARAMETR", 50);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_BYTE = (BYTE*)&p_FB_AISOURCEMLP->PARAMETR;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8217 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.SOURCE
    st = getVariable(8217);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.SOURCE", 48);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_BYTE = (BYTE*)&p_FB_AISOURCEMLP->SOURCE;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8218 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.CMD
    st = getVariable(8218);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.CMD", 45);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_BYTE = (BYTE*)&p_FB_AISOURCEMLP->CMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8219 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.LASTCMD
    st = getVariable(8219);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.LASTCMD", 49);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_BYTE = (BYTE*)&p_FB_AISOURCEMLP->LASTCMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8220 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.SOURCE_FOR_STATUS
    st = getVariable(8220);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.SOURCE_FOR_STATUS", 59);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_BYTE = (BYTE*)&p_FB_AISOURCEMLP->SOURCE_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8221 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.CMD_FOR_STATUS
    st = getVariable(8221);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.CMD_FOR_STATUS", 56);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_BYTE = (BYTE*)&p_FB_AISOURCEMLP->CMD_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8222 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.COMMAND_ERROR_FOR_STATUS
    st = getVariable(8222);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.COMMAND_ERROR_FOR_STATUS", 66);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_BYTE = (BYTE*)&p_FB_AISOURCEMLP->COMMAND_ERROR_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8223 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ONINIT
    st = getVariable(8223);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ONINIT", 48);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_BOOL = (BOOL*)&p_FB_AISOURCEMLP->ONINIT;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8224 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.OFF_TRIG.CLK
    st = getVariable(8224);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.OFF_TRIG.CLK", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->OFF_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 8225 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.OFF_TRIG.Q
    st = getVariable(8225);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.OFF_TRIG.Q", 52);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->OFF_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 8226 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.OFF_TRIG
    st = getVariable(8226);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.OFF_TRIG", 50);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->OFF_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 8227 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ON_TRIG.CLK
    st = getVariable(8227);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ON_TRIG.CLK", 53);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->ON_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 8228 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ON_TRIG.Q
    st = getVariable(8228);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ON_TRIG.Q", 51);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->ON_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 8229 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ON_TRIG
    st = getVariable(8229);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.ON_TRIG", 49);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->ON_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 8230 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.REMONT_TRIG.CLK
    st = getVariable(8230);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.REMONT_TRIG.CLK", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->REMONT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 8231 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.REMONT_TRIG.Q
    st = getVariable(8231);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.REMONT_TRIG.Q", 55);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->REMONT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 8232 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.REMONT_TRIG
    st = getVariable(8232);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.REMONT_TRIG", 53);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->REMONT_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 8233 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.LL_TRIG.CLK
    st = getVariable(8233);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.LL_TRIG.CLK", 53);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->LL_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 8234 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.LL_TRIG.Q
    st = getVariable(8234);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.LL_TRIG.Q", 51);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->LL_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 8235 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.LL_TRIG
    st = getVariable(8235);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.LL_TRIG", 49);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->LL_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 8236 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.HL_TRIG.CLK
    st = getVariable(8236);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.HL_TRIG.CLK", 53);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->HL_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 8237 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.HL_TRIG.Q
    st = getVariable(8237);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.HL_TRIG.Q", 51);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->HL_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 8238 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.HL_TRIG
    st = getVariable(8238);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.HL_TRIG", 49);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->HL_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 8239 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.NORMAL_TRIG.CLK
    st = getVariable(8239);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.NORMAL_TRIG.CLK", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->NORMAL_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 8240 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.NORMAL_TRIG.Q
    st = getVariable(8240);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.NORMAL_TRIG.Q", 55);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->NORMAL_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 8241 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.NORMAL_TRIG
    st = getVariable(8241);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.NORMAL_TRIG", 53);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->NORMAL_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 8242 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.NEDOSTOVER_TRIG.CLK
    st = getVariable(8242);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.NEDOSTOVER_TRIG.CLK", 61);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->NEDOSTOVER_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 8243 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.NEDOSTOVER_TRIG.Q
    st = getVariable(8243);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.NEDOSTOVER_TRIG.Q", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->NEDOSTOVER_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 8244 PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.NEDOSTOVER_TRIG
    st = getVariable(8244);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_DAVLENIJAMASLAPOSLENU.NEDOSTOVER_TRIG", 57);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_DAVLENIJAMASLAPOSLENU;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->NEDOSTOVER_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }

  return 0;
}

// clang-format on
