// clang-format off

#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include "POUS.h"
#include <beremiz/beremiz.h>

#include "iec_types_all.h"
#include "config1.h"

extern PROGRAM0 RESOURCE1__INSTANCE0;

#ifdef DEBUG_PLC
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err][%s:%d]: " _PRNTMSG "\n", __func__, __LINE__, ##__VA_ARGS__)
#else
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err]: " _PRNTMSG "\n", ##__VA_ARGS__)
#endif // DEBUG_PLC

void UnpackVar(void* varp, __IEC_types_enum vartype, void **value_p, void **f_value_p, uint8_t **flags);

int __variables_init_FB_TESTUNSUCCESSFUL(){
  iec_var_t *st;

  PROGRAM0 *p_PROGRAM0;
  LREAL *p_LREAL;
  ULINT *p_ULINT;
  REAL *p_REAL;
  FB_TIMINGS *p_FB_TIMINGS;
  BOOL *p_BOOL;
  UINT *p_UINT;
  PROC_AI_INIT *p_PROC_AI_INIT;
  FB_AI_INIT *p_FB_AI_INIT;
  TIME *p_TIME;
  STRUCT_AI *p_STRUCT_AI;
  DWORD *p_DWORD;
  BYTE *p_BYTE;
  WORD *p_WORD;
  AICONFIG *p_AICONFIG;
  PROC_AI *p_PROC_AI;
  FB_AISOURCEMLP *p_FB_AISOURCEMLP;
  TITEMAIN *p_TITEMAIN;
  TITEMDIN *p_TITEMDIN;
  TYPE_STATUSAI *p_TYPE_STATUSAI;
  TYPE_COMMANDANALOG *p_TYPE_COMMANDANALOG;
  FB_SUNPACKERCOMMAND *p_FB_SUNPACKERCOMMAND;
  TYPE_ANALOGLIMITFLAGS *p_TYPE_ANALOGLIMITFLAGS;
  TON *p_TON;
  R_TRIG *p_R_TRIG;
  FB_AISOURCEMLP_TIMER *p_FB_AISOURCEMLP_TIMER;
  PROC_AO_INIT *p_PROC_AO_INIT;
  FB_AO_INIT *p_FB_AO_INIT;
  STRUCT_AO *p_STRUCT_AO;
  AOCONFIG *p_AOCONFIG;
  PROC_AO *p_PROC_AO;
  FB_AOSOURCEMLP *p_FB_AOSOURCEMLP;
  TDOUBLEDATA *p_TDOUBLEDATA;
  PROC_DI_INIT *p_PROC_DI_INIT;
  FB_DI_INIT *p_FB_DI_INIT;
  STRUCT_DI *p_STRUCT_DI;
  __IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t *p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t;
  TYPE_RELIABLEBIT *p_TYPE_RELIABLEBIT;
  DICONFIG *p_DICONFIG;
  PROC_DI *p_PROC_DI;
  FB_DISOURCEMLP *p_FB_DISOURCEMLP;
  INT *p_INT;
  UDINT *p_UDINT;
  PROC_DO_INIT *p_PROC_DO_INIT;
  FB_DO_INIT *p_FB_DO_INIT;
  STRUCT_DO *p_STRUCT_DO;
  __IEC___ARRAY_OF_BOOL_16_t *p___IEC___ARRAY_OF_BOOL_16_t;
  DOCONFIG *p_DOCONFIG;
  PROC_DO *p_PROC_DO;
  FB_DOSOURCEMLP *p_FB_DOSOURCEMLP;
  TWORDDATA *p_TWORDDATA;
  OPC_ALGORITMS_SET *p_OPC_ALGORITMS_SET;
  ALGORITMSCONFIG *p_ALGORITMSCONFIG;
  STRUCT_ALG *p_STRUCT_ALG;
  STRUCT_ALGORITMSMANAGER *p_STRUCT_ALGORITMSMANAGER;
  STRUCT_PROTECTIONSMANAGER *p_STRUCT_PROTECTIONSMANAGER;
  STRUCT_ALGTIMERS *p_STRUCT_ALGTIMERS;
  ALGORITMSQUESTIONS *p_ALGORITMSQUESTIONS;
  STRUCT_QUESTION *p_STRUCT_QUESTION;
  OPC_ALGORITMS_GET *p_OPC_ALGORITMS_GET;
  PROC_IM_INIT *p_PROC_IM_INIT;
  FB_KRAN_INIT *p_FB_KRAN_INIT;
  STRUCT_KRAN *p_STRUCT_KRAN;
  FB_SWITCH_INIT *p_FB_SWITCH_INIT;
  STRUCT_SWITCH *p_STRUCT_SWITCH;
  FB_OILPUMP_INIT *p_FB_OILPUMP_INIT;
  STRUCT_OILPUMP *p_STRUCT_OILPUMP;
  FB_SECTIONSWITCH_INIT *p_FB_SECTIONSWITCH_INIT;
  STRUCT_SECTIONSWITCH *p_STRUCT_SECTIONSWITCH;
  FB_ANALOGPARAMETR_INIT *p_FB_ANALOGPARAMETR_INIT;
  STRUCT_ANALOGPARAMETR *p_STRUCT_ANALOGPARAMETR;
  FB_DISCRETPARAMETR_INIT *p_FB_DISCRETPARAMETR_INIT;
  STRUCT_DISCRETPARAMETR *p_STRUCT_DISCRETPARAMETR;
  FB_SINGLESIGNAL_INIT *p_FB_SINGLESIGNAL_INIT;
  STRUCT_SINGLESIGNAL *p_STRUCT_SINGLESIGNAL;
  FB_SINGLEOUTPUT_INIT *p_FB_SINGLEOUTPUT_INIT;
  STRUCT_SINGLEOUTPUT *p_STRUCT_SINGLEOUTPUT;
  IMCONFIG *p_IMCONFIG;
  STRUCT_RESERVEIM *p_STRUCT_RESERVEIM;
  STRUCT_RESERVEIM2 *p_STRUCT_RESERVEIM2;
  IM_SINGLESIGNALS *p_IM_SINGLESIGNALS;
  IM_SINGLEOUTPUTS *p_IM_SINGLEOUTPUTS;
  PROC_IM *p_PROC_IM;
  FB_KRAN *p_FB_KRAN;
  TYPE_STATUSDUALINPUT *p_TYPE_STATUSDUALINPUT;
  TYPE_COMMANDDUALINPUT *p_TYPE_COMMANDDUALINPUT;
  TOF *p_TOF;
  FB_OILPUMP *p_FB_OILPUMP;
  FB_SWITCH *p_FB_SWITCH;
  FB_SECTIONSWITCH *p_FB_SECTIONSWITCH;
  TYPE_BASKETSTATS *p_TYPE_BASKETSTATS;
  FB_MEANDR *p_FB_MEANDR;
  FB_SINGLESIGNAL *p_FB_SINGLESIGNAL;
  FB_SINGLEOUTPUT *p_FB_SINGLEOUTPUT;
  FB_DISCRETPARAMETR *p_FB_DISCRETPARAMETR;
  FB_ANALOGPARAMETR *p_FB_ANALOGPARAMETR;
  OPC_IM_GET *p_OPC_IM_GET;
  OPC_IM_SET *p_OPC_IM_SET;
  PROC_PROTECTIONS_INIT *p_PROC_PROTECTIONS_INIT;
  FB_DIPROTECTION_INIT *p_FB_DIPROTECTION_INIT;
  STRUCT_DIPROTECTION *p_STRUCT_DIPROTECTION;
  FB_AIPROTECTION_INIT *p_FB_AIPROTECTION_INIT;
  STRUCT_AIPROTECTION *p_STRUCT_AIPROTECTION;
  PROTECTIONSCONFIG *p_PROTECTIONSCONFIG;
  TYPE_PROTECTIONTAGS *p_TYPE_PROTECTIONTAGS;
  PROC_PROTECTION *p_PROC_PROTECTION;
  FB_DIPROTECTION *p_FB_DIPROTECTION;
  F_TRIG *p_F_TRIG;
  FB_MVPROTECTION *p_FB_MVPROTECTION;
  FB_KRANOPENPROTECTION *p_FB_KRANOPENPROTECTION;
  FB_AIPROTECTION *p_FB_AIPROTECTION;
  PROC_ALGORITMS *p_PROC_ALGORITMS;
  REMONTALG *p_REMONTALG;
  TYPE_MODEGPA *p_TYPE_MODEGPA;
  TYPE_COMMANDSPOTECTIONSMANAGER *p_TYPE_COMMANDSPOTECTIONSMANAGER;
  TESTPROTECTIONALG *p_TESTPROTECTIONALG;
  TESTIMALG *p_TESTIMALG;
  FB_AUTOTENALG *p_FB_AUTOTENALG;
  FB_AUTOPNSALG *p_FB_AUTOPNSALG;
  FB_AUTOAVOMALG *p_FB_AUTOAVOMALG;
  FB_VIBEGPNSALG *p_FB_VIBEGPNSALG;
  STRUCT_PHASEALGORITM *p_STRUCT_PHASEALGORITM;
  FB_PH_ALGORITM *p_FB_PH_ALGORITM;
  FB_PH_TIMER *p_FB_PH_TIMER;
  FB_QUESTION *p_FB_QUESTION;
  TYPE_ANSWERS *p_TYPE_ANSWERS;
  FB_PH_SWITCH *p_FB_PH_SWITCH;
  FB_PH_CUSTOMPHASE *p_FB_PH_CUSTOMPHASE;
  FB_AUTONUALG *p_FB_AUTONUALG;
  FB_PUSKOILSYSTEMALG *p_FB_PUSKOILSYSTEMALG;
  FB_PH_WAITANALOGVALUE *p_FB_PH_WAITANALOGVALUE;
  FB_PH_OILPUMP *p_FB_PH_OILPUMP;
  FB_ANTIPOMPAGALG *p_FB_ANTIPOMPAGALG;
  FB_TABLEVALUE_MIN *p_FB_TABLEVALUE_MIN;
  __IEC___ARRAY_OF_TYPE_TABLEREC_9_t *p___IEC___ARRAY_OF_TYPE_TABLEREC_9_t;
  TYPE_TABLEREC *p_TYPE_TABLEREC;
  FB_TABLEVALUE_MAX *p_FB_TABLEVALUE_MAX;
  FB_RASHODALG *p_FB_RASHODALG;
  FB_ZAPASALG *p_FB_ZAPASALG;
  NOALG *p_NOALG;
  FB_PH_KRAN *p_FB_PH_KRAN;
  FB_PH_SECTIONSWITCH *p_FB_PH_SECTIONSWITCH;
  AOALG *p_AOALG;
  PPUALG *p_PPUALG;
  FILLINGALG *p_FILLINGALG;
  FB_PH_DIPROTECTION *p_FB_PH_DIPROTECTION;
  ENGINERUNALG *p_ENGINERUNALG;
  PUSKKALG *p_PUSKKALG;
  PUSKVALG *p_PUSKVALG;
  TESTDPMGALG *p_TESTDPMGALG;
  TESTPMSALG *p_TESTPMSALG;
  FB_PH_AIPROTECTION *p_FB_PH_AIPROTECTION;
  APUSKALG *p_APUSKALG;
  SEMIAUTOPUSKALG *p_SEMIAUTOPUSKALG;
  FB_ALGORITMSMANAGER *p_FB_ALGORITMSMANAGER;
  FB_PROTECTIONSMANAGER *p_FB_PROTECTIONSMANAGER;

  { // 52987 PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.PHASENUMBER
    st = getVariable(52987);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.PHASENUMBER", 72);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_PUSKOILSYSTEMALG = (FB_PUSKOILSYSTEMALG*)&p_PROC_ALGORITMS->FB_PUSKOILSYSTEM;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_FB_PUSKOILSYSTEMALG->FB_TESTUNSUCCESSFUL;
    p_UINT = (UINT*)&p_FB_PH_CUSTOMPHASE->PHASENUMBER;
    UnpackVar(p_UINT, UINT_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 52988 PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.STRPH.RUN
    st = getVariable(52988);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.STRPH.RUN", 70);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_PUSKOILSYSTEMALG = (FB_PUSKOILSYSTEMALG*)&p_PROC_ALGORITMS->FB_PUSKOILSYSTEM;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_FB_PUSKOILSYSTEMALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->RUN;
    st->value_p = p_BOOL;
  }
  { // 52989 PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.STRPH.RESET
    st = getVariable(52989);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.STRPH.RESET", 72);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_PUSKOILSYSTEMALG = (FB_PUSKOILSYSTEMALG*)&p_PROC_ALGORITMS->FB_PUSKOILSYSTEM;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_FB_PUSKOILSYSTEMALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->RESET;
    st->value_p = p_BOOL;
  }
  { // 52990 PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.STRPH.START
    st = getVariable(52990);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.STRPH.START", 72);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_PUSKOILSYSTEMALG = (FB_PUSKOILSYSTEMALG*)&p_PROC_ALGORITMS->FB_PUSKOILSYSTEM;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_FB_PUSKOILSYSTEMALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->START;
    st->value_p = p_BOOL;
  }
  { // 52991 PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.STRPH.ERROR
    st = getVariable(52991);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.STRPH.ERROR", 72);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_PUSKOILSYSTEMALG = (FB_PUSKOILSYSTEMALG*)&p_PROC_ALGORITMS->FB_PUSKOILSYSTEM;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_FB_PUSKOILSYSTEMALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->ERROR;
    st->value_p = p_BOOL;
  }
  { // 52992 PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.STRPH.TOP
    st = getVariable(52992);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.STRPH.TOP", 70);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_PUSKOILSYSTEMALG = (FB_PUSKOILSYSTEMALG*)&p_PROC_ALGORITMS->FB_PUSKOILSYSTEM;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_FB_PUSKOILSYSTEMALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->TOP;
    st->value_p = p_BOOL;
  }
  { // 52993 PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.STRPH.STARTSTATUS
    st = getVariable(52993);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.STRPH.STARTSTATUS", 78);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_PUSKOILSYSTEMALG = (FB_PUSKOILSYSTEMALG*)&p_PROC_ALGORITMS->FB_PUSKOILSYSTEM;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_FB_PUSKOILSYSTEMALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->STARTSTATUS;
    st->value_p = p_DWORD;
  }
  { // 52994 PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.STRPH.ERRORSTATUS
    st = getVariable(52994);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.STRPH.ERRORSTATUS", 78);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_PUSKOILSYSTEMALG = (FB_PUSKOILSYSTEMALG*)&p_PROC_ALGORITMS->FB_PUSKOILSYSTEM;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_FB_PUSKOILSYSTEMALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->ERRORSTATUS;
    st->value_p = p_DWORD;
  }
  { // 52995 PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.STRPH.TOPSTATUS
    st = getVariable(52995);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.STRPH.TOPSTATUS", 76);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_PUSKOILSYSTEMALG = (FB_PUSKOILSYSTEMALG*)&p_PROC_ALGORITMS->FB_PUSKOILSYSTEM;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_FB_PUSKOILSYSTEMALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->TOPSTATUS;
    st->value_p = p_DWORD;
  }
  { // 52996 PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG.CLK
    st = getVariable(52996);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG.CLK", 82);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_PUSKOILSYSTEMALG = (FB_PUSKOILSYSTEMALG*)&p_PROC_ALGORITMS->FB_PUSKOILSYSTEM;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_FB_PUSKOILSYSTEMALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->COMMANDFAULT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 52997 PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG.Q
    st = getVariable(52997);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG.Q", 80);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_PUSKOILSYSTEMALG = (FB_PUSKOILSYSTEMALG*)&p_PROC_ALGORITMS->FB_PUSKOILSYSTEM;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_FB_PUSKOILSYSTEMALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->COMMANDFAULT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 52998 PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG
    st = getVariable(52998);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG", 78);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_PUSKOILSYSTEMALG = (FB_PUSKOILSYSTEMALG*)&p_PROC_ALGORITMS->FB_PUSKOILSYSTEM;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_FB_PUSKOILSYSTEMALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->COMMANDFAULT_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 52999 PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.RESET_TRIG.CLK
    st = getVariable(52999);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.RESET_TRIG.CLK", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_PUSKOILSYSTEMALG = (FB_PUSKOILSYSTEMALG*)&p_PROC_ALGORITMS->FB_PUSKOILSYSTEM;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_FB_PUSKOILSYSTEMALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->RESET_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 53000 PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.RESET_TRIG.Q
    st = getVariable(53000);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.RESET_TRIG.Q", 73);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_PUSKOILSYSTEMALG = (FB_PUSKOILSYSTEMALG*)&p_PROC_ALGORITMS->FB_PUSKOILSYSTEM;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_FB_PUSKOILSYSTEMALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->RESET_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 53001 PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.RESET_TRIG
    st = getVariable(53001);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL.RESET_TRIG", 71);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_PUSKOILSYSTEMALG = (FB_PUSKOILSYSTEMALG*)&p_PROC_ALGORITMS->FB_PUSKOILSYSTEM;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_FB_PUSKOILSYSTEMALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->RESET_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 53002 PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_NOTDEFINED
    st = getVariable(53002);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_NOTDEFINED", 95);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_PUSKOILSYSTEMALG = (FB_PUSKOILSYSTEMALG*)&p_PROC_ALGORITMS->FB_PUSKOILSYSTEM;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_FB_PUSKOILSYSTEMALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_NOTDEFINED;
    st->value_p = p_BYTE;
  }
  { // 53003 PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_ON
    st = getVariable(53003);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_ON", 87);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_PUSKOILSYSTEMALG = (FB_PUSKOILSYSTEMALG*)&p_PROC_ALGORITMS->FB_PUSKOILSYSTEM;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_FB_PUSKOILSYSTEMALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ON;
    st->value_p = p_BYTE;
  }
  { // 53004 PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_OFF
    st = getVariable(53004);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_OFF", 88);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_PUSKOILSYSTEMALG = (FB_PUSKOILSYSTEMALG*)&p_PROC_ALGORITMS->FB_PUSKOILSYSTEM;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_FB_PUSKOILSYSTEMALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_OFF;
    st->value_p = p_BYTE;
  }
  { // 53005 PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_TRANSITIONAL
    st = getVariable(53005);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_TRANSITIONAL", 97);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_PUSKOILSYSTEMALG = (FB_PUSKOILSYSTEMALG*)&p_PROC_ALGORITMS->FB_PUSKOILSYSTEM;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_FB_PUSKOILSYSTEMALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_TRANSITIONAL;
    st->value_p = p_BYTE;
  }
  { // 53006 PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_ERROR
    st = getVariable(53006);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKOILSYSTEM.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_ERROR", 90);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_FB_PUSKOILSYSTEMALG = (FB_PUSKOILSYSTEMALG*)&p_PROC_ALGORITMS->FB_PUSKOILSYSTEM;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_FB_PUSKOILSYSTEMALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ERROR;
    st->value_p = p_BYTE;
  }
  { // 85122 PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.PHASENUMBER
    st = getVariable(85122);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.PHASENUMBER", 71);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_ENGINERUNALG = (ENGINERUNALG*)&p_PROC_ALGORITMS->FB_ENGINERUNALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_ENGINERUNALG->FB_TESTUNSUCCESSFUL;
    p_UINT = (UINT*)&p_FB_PH_CUSTOMPHASE->PHASENUMBER;
    UnpackVar(p_UINT, UINT_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 85123 PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.STRPH.RUN
    st = getVariable(85123);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.STRPH.RUN", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_ENGINERUNALG = (ENGINERUNALG*)&p_PROC_ALGORITMS->FB_ENGINERUNALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_ENGINERUNALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->RUN;
    st->value_p = p_BOOL;
  }
  { // 85124 PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.STRPH.RESET
    st = getVariable(85124);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.STRPH.RESET", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_ENGINERUNALG = (ENGINERUNALG*)&p_PROC_ALGORITMS->FB_ENGINERUNALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_ENGINERUNALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->RESET;
    st->value_p = p_BOOL;
  }
  { // 85125 PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.STRPH.START
    st = getVariable(85125);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.STRPH.START", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_ENGINERUNALG = (ENGINERUNALG*)&p_PROC_ALGORITMS->FB_ENGINERUNALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_ENGINERUNALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->START;
    st->value_p = p_BOOL;
  }
  { // 85126 PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.STRPH.ERROR
    st = getVariable(85126);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.STRPH.ERROR", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_ENGINERUNALG = (ENGINERUNALG*)&p_PROC_ALGORITMS->FB_ENGINERUNALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_ENGINERUNALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->ERROR;
    st->value_p = p_BOOL;
  }
  { // 85127 PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.STRPH.TOP
    st = getVariable(85127);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.STRPH.TOP", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_ENGINERUNALG = (ENGINERUNALG*)&p_PROC_ALGORITMS->FB_ENGINERUNALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_ENGINERUNALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->TOP;
    st->value_p = p_BOOL;
  }
  { // 85128 PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.STRPH.STARTSTATUS
    st = getVariable(85128);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.STRPH.STARTSTATUS", 77);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_ENGINERUNALG = (ENGINERUNALG*)&p_PROC_ALGORITMS->FB_ENGINERUNALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_ENGINERUNALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->STARTSTATUS;
    st->value_p = p_DWORD;
  }
  { // 85129 PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.STRPH.ERRORSTATUS
    st = getVariable(85129);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.STRPH.ERRORSTATUS", 77);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_ENGINERUNALG = (ENGINERUNALG*)&p_PROC_ALGORITMS->FB_ENGINERUNALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_ENGINERUNALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->ERRORSTATUS;
    st->value_p = p_DWORD;
  }
  { // 85130 PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.STRPH.TOPSTATUS
    st = getVariable(85130);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.STRPH.TOPSTATUS", 75);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_ENGINERUNALG = (ENGINERUNALG*)&p_PROC_ALGORITMS->FB_ENGINERUNALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_ENGINERUNALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->TOPSTATUS;
    st->value_p = p_DWORD;
  }
  { // 85131 PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG.CLK
    st = getVariable(85131);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG.CLK", 81);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_ENGINERUNALG = (ENGINERUNALG*)&p_PROC_ALGORITMS->FB_ENGINERUNALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_ENGINERUNALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->COMMANDFAULT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 85132 PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG.Q
    st = getVariable(85132);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG.Q", 79);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_ENGINERUNALG = (ENGINERUNALG*)&p_PROC_ALGORITMS->FB_ENGINERUNALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_ENGINERUNALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->COMMANDFAULT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 85133 PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG
    st = getVariable(85133);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG", 77);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_ENGINERUNALG = (ENGINERUNALG*)&p_PROC_ALGORITMS->FB_ENGINERUNALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_ENGINERUNALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->COMMANDFAULT_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 85134 PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.RESET_TRIG.CLK
    st = getVariable(85134);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.RESET_TRIG.CLK", 74);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_ENGINERUNALG = (ENGINERUNALG*)&p_PROC_ALGORITMS->FB_ENGINERUNALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_ENGINERUNALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->RESET_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 85135 PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.RESET_TRIG.Q
    st = getVariable(85135);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.RESET_TRIG.Q", 72);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_ENGINERUNALG = (ENGINERUNALG*)&p_PROC_ALGORITMS->FB_ENGINERUNALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_ENGINERUNALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->RESET_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 85136 PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.RESET_TRIG
    st = getVariable(85136);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL.RESET_TRIG", 70);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_ENGINERUNALG = (ENGINERUNALG*)&p_PROC_ALGORITMS->FB_ENGINERUNALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_ENGINERUNALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->RESET_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 85137 PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_NOTDEFINED
    st = getVariable(85137);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_NOTDEFINED", 94);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_ENGINERUNALG = (ENGINERUNALG*)&p_PROC_ALGORITMS->FB_ENGINERUNALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_ENGINERUNALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_NOTDEFINED;
    st->value_p = p_BYTE;
  }
  { // 85138 PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_ON
    st = getVariable(85138);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_ON", 86);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_ENGINERUNALG = (ENGINERUNALG*)&p_PROC_ALGORITMS->FB_ENGINERUNALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_ENGINERUNALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ON;
    st->value_p = p_BYTE;
  }
  { // 85139 PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_OFF
    st = getVariable(85139);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_OFF", 87);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_ENGINERUNALG = (ENGINERUNALG*)&p_PROC_ALGORITMS->FB_ENGINERUNALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_ENGINERUNALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_OFF;
    st->value_p = p_BYTE;
  }
  { // 85140 PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_TRANSITIONAL
    st = getVariable(85140);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_TRANSITIONAL", 96);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_ENGINERUNALG = (ENGINERUNALG*)&p_PROC_ALGORITMS->FB_ENGINERUNALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_ENGINERUNALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_TRANSITIONAL;
    st->value_p = p_BYTE;
  }
  { // 85141 PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_ERROR
    st = getVariable(85141);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_ENGINERUNALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_ERROR", 89);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_ENGINERUNALG = (ENGINERUNALG*)&p_PROC_ALGORITMS->FB_ENGINERUNALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_ENGINERUNALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ERROR;
    st->value_p = p_BYTE;
  }
  { // 97361 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.PHASENUMBER
    st = getVariable(97361);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.PHASENUMBER", 67);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_PUSKVALG->FB_TESTUNSUCCESSFUL;
    p_UINT = (UINT*)&p_FB_PH_CUSTOMPHASE->PHASENUMBER;
    UnpackVar(p_UINT, UINT_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 97362 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.STRPH.RUN
    st = getVariable(97362);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.STRPH.RUN", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_PUSKVALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->RUN;
    st->value_p = p_BOOL;
  }
  { // 97363 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.STRPH.RESET
    st = getVariable(97363);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.STRPH.RESET", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_PUSKVALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->RESET;
    st->value_p = p_BOOL;
  }
  { // 97364 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.STRPH.START
    st = getVariable(97364);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.STRPH.START", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_PUSKVALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->START;
    st->value_p = p_BOOL;
  }
  { // 97365 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.STRPH.ERROR
    st = getVariable(97365);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.STRPH.ERROR", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_PUSKVALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->ERROR;
    st->value_p = p_BOOL;
  }
  { // 97366 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.STRPH.TOP
    st = getVariable(97366);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.STRPH.TOP", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_PUSKVALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->TOP;
    st->value_p = p_BOOL;
  }
  { // 97367 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.STRPH.STARTSTATUS
    st = getVariable(97367);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.STRPH.STARTSTATUS", 73);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_PUSKVALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->STARTSTATUS;
    st->value_p = p_DWORD;
  }
  { // 97368 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.STRPH.ERRORSTATUS
    st = getVariable(97368);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.STRPH.ERRORSTATUS", 73);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_PUSKVALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->ERRORSTATUS;
    st->value_p = p_DWORD;
  }
  { // 97369 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.STRPH.TOPSTATUS
    st = getVariable(97369);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.STRPH.TOPSTATUS", 71);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_PUSKVALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->TOPSTATUS;
    st->value_p = p_DWORD;
  }
  { // 97370 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG.CLK
    st = getVariable(97370);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG.CLK", 77);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_PUSKVALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->COMMANDFAULT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 97371 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG.Q
    st = getVariable(97371);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG.Q", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_PUSKVALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->COMMANDFAULT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 97372 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG
    st = getVariable(97372);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG", 73);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_PUSKVALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->COMMANDFAULT_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 97373 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.RESET_TRIG.CLK
    st = getVariable(97373);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.RESET_TRIG.CLK", 70);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_PUSKVALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->RESET_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 97374 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.RESET_TRIG.Q
    st = getVariable(97374);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.RESET_TRIG.Q", 68);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_PUSKVALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->RESET_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 97375 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.RESET_TRIG
    st = getVariable(97375);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL.RESET_TRIG", 66);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_PUSKVALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->RESET_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 97376 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_NOTDEFINED
    st = getVariable(97376);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_NOTDEFINED", 90);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_PUSKVALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_NOTDEFINED;
    st->value_p = p_BYTE;
  }
  { // 97377 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_ON
    st = getVariable(97377);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_ON", 82);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_PUSKVALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ON;
    st->value_p = p_BYTE;
  }
  { // 97378 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_OFF
    st = getVariable(97378);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_OFF", 83);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_PUSKVALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_OFF;
    st->value_p = p_BYTE;
  }
  { // 97379 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_TRANSITIONAL
    st = getVariable(97379);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_TRANSITIONAL", 92);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_PUSKVALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_TRANSITIONAL;
    st->value_p = p_BYTE;
  }
  { // 97380 PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_ERROR
    st = getVariable(97380);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_PUSKVALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_ERROR", 85);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_PUSKVALG = (PUSKVALG*)&p_PROC_ALGORITMS->FB_PUSKVALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_PUSKVALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ERROR;
    st->value_p = p_BYTE;
  }
  { // 103180 PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.PHASENUMBER
    st = getVariable(103180);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.PHASENUMBER", 70);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTDPMGALG = (TESTDPMGALG*)&p_PROC_ALGORITMS->FB_TESTDPMGALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTDPMGALG->FB_TESTUNSUCCESSFUL;
    p_UINT = (UINT*)&p_FB_PH_CUSTOMPHASE->PHASENUMBER;
    UnpackVar(p_UINT, UINT_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 103181 PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.STRPH.RUN
    st = getVariable(103181);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.STRPH.RUN", 68);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTDPMGALG = (TESTDPMGALG*)&p_PROC_ALGORITMS->FB_TESTDPMGALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTDPMGALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->RUN;
    st->value_p = p_BOOL;
  }
  { // 103182 PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.STRPH.RESET
    st = getVariable(103182);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.STRPH.RESET", 70);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTDPMGALG = (TESTDPMGALG*)&p_PROC_ALGORITMS->FB_TESTDPMGALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTDPMGALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->RESET;
    st->value_p = p_BOOL;
  }
  { // 103183 PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.STRPH.START
    st = getVariable(103183);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.STRPH.START", 70);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTDPMGALG = (TESTDPMGALG*)&p_PROC_ALGORITMS->FB_TESTDPMGALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTDPMGALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->START;
    st->value_p = p_BOOL;
  }
  { // 103184 PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.STRPH.ERROR
    st = getVariable(103184);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.STRPH.ERROR", 70);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTDPMGALG = (TESTDPMGALG*)&p_PROC_ALGORITMS->FB_TESTDPMGALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTDPMGALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->ERROR;
    st->value_p = p_BOOL;
  }
  { // 103185 PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.STRPH.TOP
    st = getVariable(103185);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.STRPH.TOP", 68);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTDPMGALG = (TESTDPMGALG*)&p_PROC_ALGORITMS->FB_TESTDPMGALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTDPMGALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->TOP;
    st->value_p = p_BOOL;
  }
  { // 103186 PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.STRPH.STARTSTATUS
    st = getVariable(103186);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.STRPH.STARTSTATUS", 76);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTDPMGALG = (TESTDPMGALG*)&p_PROC_ALGORITMS->FB_TESTDPMGALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTDPMGALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->STARTSTATUS;
    st->value_p = p_DWORD;
  }
  { // 103187 PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.STRPH.ERRORSTATUS
    st = getVariable(103187);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.STRPH.ERRORSTATUS", 76);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTDPMGALG = (TESTDPMGALG*)&p_PROC_ALGORITMS->FB_TESTDPMGALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTDPMGALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->ERRORSTATUS;
    st->value_p = p_DWORD;
  }
  { // 103188 PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.STRPH.TOPSTATUS
    st = getVariable(103188);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.STRPH.TOPSTATUS", 74);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTDPMGALG = (TESTDPMGALG*)&p_PROC_ALGORITMS->FB_TESTDPMGALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTDPMGALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->TOPSTATUS;
    st->value_p = p_DWORD;
  }
  { // 103189 PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG.CLK
    st = getVariable(103189);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG.CLK", 80);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTDPMGALG = (TESTDPMGALG*)&p_PROC_ALGORITMS->FB_TESTDPMGALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTDPMGALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->COMMANDFAULT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 103190 PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG.Q
    st = getVariable(103190);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG.Q", 78);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTDPMGALG = (TESTDPMGALG*)&p_PROC_ALGORITMS->FB_TESTDPMGALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTDPMGALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->COMMANDFAULT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 103191 PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG
    st = getVariable(103191);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG", 76);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTDPMGALG = (TESTDPMGALG*)&p_PROC_ALGORITMS->FB_TESTDPMGALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTDPMGALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->COMMANDFAULT_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 103192 PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.RESET_TRIG.CLK
    st = getVariable(103192);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.RESET_TRIG.CLK", 73);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTDPMGALG = (TESTDPMGALG*)&p_PROC_ALGORITMS->FB_TESTDPMGALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTDPMGALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->RESET_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 103193 PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.RESET_TRIG.Q
    st = getVariable(103193);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.RESET_TRIG.Q", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTDPMGALG = (TESTDPMGALG*)&p_PROC_ALGORITMS->FB_TESTDPMGALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTDPMGALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->RESET_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 103194 PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.RESET_TRIG
    st = getVariable(103194);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL.RESET_TRIG", 69);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTDPMGALG = (TESTDPMGALG*)&p_PROC_ALGORITMS->FB_TESTDPMGALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTDPMGALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->RESET_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 103195 PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_NOTDEFINED
    st = getVariable(103195);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_NOTDEFINED", 93);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTDPMGALG = (TESTDPMGALG*)&p_PROC_ALGORITMS->FB_TESTDPMGALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTDPMGALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_NOTDEFINED;
    st->value_p = p_BYTE;
  }
  { // 103196 PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_ON
    st = getVariable(103196);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_ON", 85);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTDPMGALG = (TESTDPMGALG*)&p_PROC_ALGORITMS->FB_TESTDPMGALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTDPMGALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ON;
    st->value_p = p_BYTE;
  }
  { // 103197 PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_OFF
    st = getVariable(103197);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_OFF", 86);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTDPMGALG = (TESTDPMGALG*)&p_PROC_ALGORITMS->FB_TESTDPMGALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTDPMGALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_OFF;
    st->value_p = p_BYTE;
  }
  { // 103198 PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_TRANSITIONAL
    st = getVariable(103198);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_TRANSITIONAL", 95);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTDPMGALG = (TESTDPMGALG*)&p_PROC_ALGORITMS->FB_TESTDPMGALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTDPMGALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_TRANSITIONAL;
    st->value_p = p_BYTE;
  }
  { // 103199 PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_ERROR
    st = getVariable(103199);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTDPMGALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_ERROR", 88);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTDPMGALG = (TESTDPMGALG*)&p_PROC_ALGORITMS->FB_TESTDPMGALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTDPMGALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ERROR;
    st->value_p = p_BYTE;
  }
  { // 109272 PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.PHASENUMBER
    st = getVariable(109272);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.PHASENUMBER", 69);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTPMSALG = (TESTPMSALG*)&p_PROC_ALGORITMS->FB_TESTPMSALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTPMSALG->FB_TESTUNSUCCESSFUL;
    p_UINT = (UINT*)&p_FB_PH_CUSTOMPHASE->PHASENUMBER;
    UnpackVar(p_UINT, UINT_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 109273 PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.STRPH.RUN
    st = getVariable(109273);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.STRPH.RUN", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTPMSALG = (TESTPMSALG*)&p_PROC_ALGORITMS->FB_TESTPMSALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTPMSALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->RUN;
    st->value_p = p_BOOL;
  }
  { // 109274 PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.STRPH.RESET
    st = getVariable(109274);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.STRPH.RESET", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTPMSALG = (TESTPMSALG*)&p_PROC_ALGORITMS->FB_TESTPMSALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTPMSALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->RESET;
    st->value_p = p_BOOL;
  }
  { // 109275 PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.STRPH.START
    st = getVariable(109275);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.STRPH.START", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTPMSALG = (TESTPMSALG*)&p_PROC_ALGORITMS->FB_TESTPMSALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTPMSALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->START;
    st->value_p = p_BOOL;
  }
  { // 109276 PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.STRPH.ERROR
    st = getVariable(109276);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.STRPH.ERROR", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTPMSALG = (TESTPMSALG*)&p_PROC_ALGORITMS->FB_TESTPMSALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTPMSALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->ERROR;
    st->value_p = p_BOOL;
  }
  { // 109277 PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.STRPH.TOP
    st = getVariable(109277);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.STRPH.TOP", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTPMSALG = (TESTPMSALG*)&p_PROC_ALGORITMS->FB_TESTPMSALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTPMSALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->TOP;
    st->value_p = p_BOOL;
  }
  { // 109278 PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.STRPH.STARTSTATUS
    st = getVariable(109278);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.STRPH.STARTSTATUS", 75);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTPMSALG = (TESTPMSALG*)&p_PROC_ALGORITMS->FB_TESTPMSALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTPMSALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->STARTSTATUS;
    st->value_p = p_DWORD;
  }
  { // 109279 PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.STRPH.ERRORSTATUS
    st = getVariable(109279);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.STRPH.ERRORSTATUS", 75);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTPMSALG = (TESTPMSALG*)&p_PROC_ALGORITMS->FB_TESTPMSALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTPMSALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->ERRORSTATUS;
    st->value_p = p_DWORD;
  }
  { // 109280 PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.STRPH.TOPSTATUS
    st = getVariable(109280);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.STRPH.TOPSTATUS", 73);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTPMSALG = (TESTPMSALG*)&p_PROC_ALGORITMS->FB_TESTPMSALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTPMSALG->FB_TESTUNSUCCESSFUL;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_CUSTOMPHASE->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->TOPSTATUS;
    st->value_p = p_DWORD;
  }
  { // 109281 PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG.CLK
    st = getVariable(109281);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG.CLK", 79);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTPMSALG = (TESTPMSALG*)&p_PROC_ALGORITMS->FB_TESTPMSALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTPMSALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->COMMANDFAULT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 109282 PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG.Q
    st = getVariable(109282);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG.Q", 77);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTPMSALG = (TESTPMSALG*)&p_PROC_ALGORITMS->FB_TESTPMSALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTPMSALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->COMMANDFAULT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 109283 PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG
    st = getVariable(109283);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.COMMANDFAULT_TRIG", 75);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTPMSALG = (TESTPMSALG*)&p_PROC_ALGORITMS->FB_TESTPMSALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTPMSALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->COMMANDFAULT_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 109284 PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.RESET_TRIG.CLK
    st = getVariable(109284);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.RESET_TRIG.CLK", 72);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTPMSALG = (TESTPMSALG*)&p_PROC_ALGORITMS->FB_TESTPMSALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTPMSALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->RESET_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 109285 PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.RESET_TRIG.Q
    st = getVariable(109285);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.RESET_TRIG.Q", 70);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTPMSALG = (TESTPMSALG*)&p_PROC_ALGORITMS->FB_TESTPMSALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTPMSALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->RESET_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 109286 PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.RESET_TRIG
    st = getVariable(109286);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL.RESET_TRIG", 68);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTPMSALG = (TESTPMSALG*)&p_PROC_ALGORITMS->FB_TESTPMSALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTPMSALG->FB_TESTUNSUCCESSFUL;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_CUSTOMPHASE->RESET_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 109287 PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_NOTDEFINED
    st = getVariable(109287);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_NOTDEFINED", 92);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTPMSALG = (TESTPMSALG*)&p_PROC_ALGORITMS->FB_TESTPMSALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTPMSALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_NOTDEFINED;
    st->value_p = p_BYTE;
  }
  { // 109288 PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_ON
    st = getVariable(109288);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_ON", 84);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTPMSALG = (TESTPMSALG*)&p_PROC_ALGORITMS->FB_TESTPMSALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTPMSALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ON;
    st->value_p = p_BYTE;
  }
  { // 109289 PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_OFF
    st = getVariable(109289);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_OFF", 85);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTPMSALG = (TESTPMSALG*)&p_PROC_ALGORITMS->FB_TESTPMSALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTPMSALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_OFF;
    st->value_p = p_BYTE;
  }
  { // 109290 PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_TRANSITIONAL
    st = getVariable(109290);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_TRANSITIONAL", 94);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTPMSALG = (TESTPMSALG*)&p_PROC_ALGORITMS->FB_TESTPMSALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTPMSALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_TRANSITIONAL;
    st->value_p = p_BYTE;
  }
  { // 109291 PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_ERROR
    st = getVariable(109291);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_TESTPMSALG.FB_TESTUNSUCCESSFUL._STATUSDUALINPUT.STATUS_ERROR", 87);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_TESTPMSALG = (TESTPMSALG*)&p_PROC_ALGORITMS->FB_TESTPMSALG;
    p_FB_PH_CUSTOMPHASE = (FB_PH_CUSTOMPHASE*)&p_TESTPMSALG->FB_TESTUNSUCCESSFUL;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_CUSTOMPHASE->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ERROR;
    st->value_p = p_BYTE;
  }

  return 0;
}

// clang-format on
