// clang-format off

#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include "POUS.h"
#include <beremiz/beremiz.h>

#include "iec_types_all.h"
#include "config1.h"

extern PROGRAM0 RESOURCE1__INSTANCE0;

#ifdef DEBUG_PLC
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err][%s:%d]: " _PRNTMSG "\n", __func__, __LINE__, ##__VA_ARGS__)
#else
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err]: " _PRNTMSG "\n", ##__VA_ARGS__)
#endif // DEBUG_PLC

void UnpackVar(void* varp, __IEC_types_enum vartype, void **value_p, void **f_value_p, uint8_t **flags);

int __variables_init_FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1(){
  iec_var_t *st;

  PROGRAM0 *p_PROGRAM0;
  LREAL *p_LREAL;
  ULINT *p_ULINT;
  REAL *p_REAL;
  FB_TIMINGS *p_FB_TIMINGS;
  BOOL *p_BOOL;
  UINT *p_UINT;
  PROC_AI_INIT *p_PROC_AI_INIT;
  FB_AI_INIT *p_FB_AI_INIT;
  STRUCT_AI *p_STRUCT_AI;
  DWORD *p_DWORD;
  BYTE *p_BYTE;
  WORD *p_WORD;
  TIME *p_TIME;
  AICONFIG *p_AICONFIG;
  PROC_AI *p_PROC_AI;
  FB_AISOURCEMLP *p_FB_AISOURCEMLP;
  TITEMAIN *p_TITEMAIN;
  TITEMDIN *p_TITEMDIN;
  TYPE_STATUSAI *p_TYPE_STATUSAI;
  TYPE_COMMANDANALOG *p_TYPE_COMMANDANALOG;
  FB_SUNPACKERCOMMAND *p_FB_SUNPACKERCOMMAND;
  TYPE_ANALOGLIMITFLAGS *p_TYPE_ANALOGLIMITFLAGS;
  TON *p_TON;
  R_TRIG *p_R_TRIG;
  FB_AISOURCEMLP_TIMER *p_FB_AISOURCEMLP_TIMER;
  PROC_AO_INIT *p_PROC_AO_INIT;
  FB_AO_INIT *p_FB_AO_INIT;
  STRUCT_AO *p_STRUCT_AO;
  AOCONFIG *p_AOCONFIG;
  PROC_AO *p_PROC_AO;
  FB_AOSOURCEMLP *p_FB_AOSOURCEMLP;
  TDOUBLEDATA *p_TDOUBLEDATA;
  PROC_DI_INIT *p_PROC_DI_INIT;
  FB_DI_INIT *p_FB_DI_INIT;
  STRUCT_DI *p_STRUCT_DI;
  __IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t *p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t;
  TYPE_RELIABLEBIT *p_TYPE_RELIABLEBIT;
  DICONFIG *p_DICONFIG;
  PROC_DI *p_PROC_DI;
  FB_DISOURCEMLP *p_FB_DISOURCEMLP;
  INT *p_INT;
  UDINT *p_UDINT;
  PROC_DO_INIT *p_PROC_DO_INIT;
  FB_DO_INIT *p_FB_DO_INIT;
  STRUCT_DO *p_STRUCT_DO;
  DOCONFIG *p_DOCONFIG;
  PROC_DO *p_PROC_DO;
  FB_DOSOURCEMLP *p_FB_DOSOURCEMLP;
  TWORDDATA *p_TWORDDATA;
  OPC_ALGORITMS_SET *p_OPC_ALGORITMS_SET;
  ALGORITMSCONFIG *p_ALGORITMSCONFIG;
  STRUCT_ALG *p_STRUCT_ALG;
  STRUCT_ALGORITMSMANAGER *p_STRUCT_ALGORITMSMANAGER;
  STRUCT_PROTECTIONSMANAGER *p_STRUCT_PROTECTIONSMANAGER;
  STRUCT_ALGTIMERS *p_STRUCT_ALGTIMERS;
  ALGORITMSQUESTIONS *p_ALGORITMSQUESTIONS;
  STRUCT_QUESTION *p_STRUCT_QUESTION;
  OPC_ALGORITMS_GET *p_OPC_ALGORITMS_GET;
  PROC_IM_INIT *p_PROC_IM_INIT;
  FB_KRAN_INIT *p_FB_KRAN_INIT;
  STRUCT_KRAN *p_STRUCT_KRAN;
  FB_SWITCH_INIT *p_FB_SWITCH_INIT;
  STRUCT_SWITCH *p_STRUCT_SWITCH;
  FB_OILPUMP_INIT *p_FB_OILPUMP_INIT;
  STRUCT_OILPUMP *p_STRUCT_OILPUMP;
  FB_SECTIONSWITCH_INIT *p_FB_SECTIONSWITCH_INIT;
  STRUCT_SECTIONSWITCH *p_STRUCT_SECTIONSWITCH;
  FB_ANALOGPARAMETR_INIT *p_FB_ANALOGPARAMETR_INIT;
  STRUCT_ANALOGPARAMETR *p_STRUCT_ANALOGPARAMETR;
  FB_DISCRETPARAMETR_INIT *p_FB_DISCRETPARAMETR_INIT;
  STRUCT_DISCRETPARAMETR *p_STRUCT_DISCRETPARAMETR;
  FB_SINGLESIGNAL_INIT *p_FB_SINGLESIGNAL_INIT;
  STRUCT_SINGLESIGNAL *p_STRUCT_SINGLESIGNAL;
  FB_SINGLEOUTPUT_INIT *p_FB_SINGLEOUTPUT_INIT;
  STRUCT_SINGLEOUTPUT *p_STRUCT_SINGLEOUTPUT;
  IMCONFIG *p_IMCONFIG;
  STRUCT_RESERVEIM *p_STRUCT_RESERVEIM;
  STRUCT_RESERVEIM2 *p_STRUCT_RESERVEIM2;
  IM_SINGLESIGNALS *p_IM_SINGLESIGNALS;
  IM_SINGLEOUTPUTS *p_IM_SINGLEOUTPUTS;
  PROC_IM *p_PROC_IM;
  FB_KRAN *p_FB_KRAN;
  TYPE_STATUSDUALINPUT *p_TYPE_STATUSDUALINPUT;
  TYPE_COMMANDDUALINPUT *p_TYPE_COMMANDDUALINPUT;
  TOF *p_TOF;
  FB_OILPUMP *p_FB_OILPUMP;
  FB_SWITCH *p_FB_SWITCH;
  FB_SECTIONSWITCH *p_FB_SECTIONSWITCH;
  TYPE_BASKETSTATS *p_TYPE_BASKETSTATS;
  FB_MEANDR *p_FB_MEANDR;
  FB_SINGLESIGNAL *p_FB_SINGLESIGNAL;
  FB_SINGLEOUTPUT *p_FB_SINGLEOUTPUT;
  PROC_PROTECTIONS_INIT *p_PROC_PROTECTIONS_INIT;
  FB_DIPROTECTION_INIT *p_FB_DIPROTECTION_INIT;
  STRUCT_DIPROTECTION *p_STRUCT_DIPROTECTION;
  FB_AIPROTECTION_INIT *p_FB_AIPROTECTION_INIT;
  STRUCT_AIPROTECTION *p_STRUCT_AIPROTECTION;
  PROTECTIONSCONFIG *p_PROTECTIONSCONFIG;
  TYPE_PROTECTIONTAGS *p_TYPE_PROTECTIONTAGS;
  PROC_PROTECTION *p_PROC_PROTECTION;
  FB_MVPROTECTION *p_FB_MVPROTECTION;
  F_TRIG *p_F_TRIG;
  FB_DIPROTECTION *p_FB_DIPROTECTION;
  FB_KRANOPENPROTECTION *p_FB_KRANOPENPROTECTION;
  FB_AIPROTECTION *p_FB_AIPROTECTION;
  PROC_ALGORITMS *p_PROC_ALGORITMS;
  REMONTALG *p_REMONTALG;
  TYPE_MODEGPA *p_TYPE_MODEGPA;
  TYPE_COMMANDSPOTECTIONSMANAGER *p_TYPE_COMMANDSPOTECTIONSMANAGER;
  TESTPROTECTIONALG *p_TESTPROTECTIONALG;
  TESTIMALG *p_TESTIMALG;
  FB_AUTOTENALG *p_FB_AUTOTENALG;
  FB_AUTOPNSALG *p_FB_AUTOPNSALG;
  FB_AUTOAVOMALG *p_FB_AUTOAVOMALG;
  FB_VIBEGPNSALG *p_FB_VIBEGPNSALG;
  STRUCT_PHASEALGORITM *p_STRUCT_PHASEALGORITM;
  FB_PH_ALGORITM *p_FB_PH_ALGORITM;
  FB_PH_TIMER *p_FB_PH_TIMER;
  FB_QUESTION *p_FB_QUESTION;
  TYPE_ANSWERS *p_TYPE_ANSWERS;
  FB_PH_SWITCH *p_FB_PH_SWITCH;
  FB_PH_CUSTOMPHASE *p_FB_PH_CUSTOMPHASE;
  FB_AUTONUALG *p_FB_AUTONUALG;
  FB_PUSKOILSYSTEMALG *p_FB_PUSKOILSYSTEMALG;
  FB_PH_WAITANALOGVALUE *p_FB_PH_WAITANALOGVALUE;
  FB_PH_OILPUMP *p_FB_PH_OILPUMP;
  FB_ANTIPOMPAGALG *p_FB_ANTIPOMPAGALG;
  FB_TABLEVALUE_MIN *p_FB_TABLEVALUE_MIN;
  __IEC___ARRAY_OF_TYPE_TABLEREC_9_t *p___IEC___ARRAY_OF_TYPE_TABLEREC_9_t;
  TYPE_TABLEREC *p_TYPE_TABLEREC;
  FB_TABLEVALUE_MAX *p_FB_TABLEVALUE_MAX;
  FB_RASHODALG *p_FB_RASHODALG;
  FB_ZAPASALG *p_FB_ZAPASALG;
  NOALG *p_NOALG;
  FB_PH_KRAN *p_FB_PH_KRAN;
  FB_PH_SECTIONSWITCH *p_FB_PH_SECTIONSWITCH;
  AOALG *p_AOALG;
  PPUALG *p_PPUALG;
  FILLINGALG *p_FILLINGALG;
  FB_PH_DIPROTECTION *p_FB_PH_DIPROTECTION;
  ENGINERUNALG *p_ENGINERUNALG;
  PUSKKALG *p_PUSKKALG;
  PUSKVALG *p_PUSKVALG;
  TESTDPMGALG *p_TESTDPMGALG;
  TESTPMSALG *p_TESTPMSALG;
  FB_PH_AIPROTECTION *p_FB_PH_AIPROTECTION;
  APUSKALG *p_APUSKALG;
  SEMIAUTOPUSKALG *p_SEMIAUTOPUSKALG;
  PUSK_FIRST_FAZA1 *p_PUSK_FIRST_FAZA1;
  PUSK_FIRST_FAZA2 *p_PUSK_FIRST_FAZA2;
  PUSK_THIRD_FAZA *p_PUSK_THIRD_FAZA;
  PROV_PMS *p_PROV_PMS;
  PROV_OPRESSOVKA *p_PROV_OPRESSOVKA;
  PUSK_SECOND_FAZA_CHASTOTNY *p_PUSK_SECOND_FAZA_CHASTOTNY;
  PUSK_SECOND_FAZA_REACTOR *p_PUSK_SECOND_FAZA_REACTOR;
  FB_ALGORITMSMANAGER *p_FB_ALGORITMSMANAGER;
  FB_PROTECTIONSMANAGER *p_FB_PROTECTIONSMANAGER;

  { // 29967 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.VALUE
    st = getVariable(29967);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.VALUE", 74);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->VALUE;
    st->value_p = p_LREAL;
  }
  { // 29968 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.STATUS
    st = getVariable(29968);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.STATUS", 75);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_DWORD = (DWORD*)&p_STRUCT_AI->STATUS;
    st->value_p = p_DWORD;
  }
  { // 29969 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.INTERVAL
    st = getVariable(29969);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.INTERVAL", 77);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BYTE = (BYTE*)&p_STRUCT_AI->INTERVAL;
    st->value_p = p_BYTE;
  }
  { // 29970 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.INCOMMAND
    st = getVariable(29970);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.INCOMMAND", 78);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 29971 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.BLCONNECT
    st = getVariable(29971);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.BLCONNECT", 78);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->BLCONNECT;
    st->value_p = p_BOOL;
  }
  { // 29972 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DLL
    st = getVariable(29972);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DLL", 72);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLL;
    st->value_p = p_LREAL;
  }
  { // 29973 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DHL
    st = getVariable(29973);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DHL", 72);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHL;
    st->value_p = p_LREAL;
  }
  { // 29974 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DLA
    st = getVariable(29974);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DLA", 72);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLA;
    st->value_p = p_LREAL;
  }
  { // 29975 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DHA
    st = getVariable(29975);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DHA", 72);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHA;
    st->value_p = p_LREAL;
  }
  { // 29976 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DLW
    st = getVariable(29976);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DLW", 72);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLW;
    st->value_p = p_LREAL;
  }
  { // 29977 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DHW
    st = getVariable(29977);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DHW", 72);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHW;
    st->value_p = p_LREAL;
  }
  { // 29978 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.LL
    st = getVariable(29978);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.LL", 71);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LL;
    st->value_p = p_LREAL;
  }
  { // 29979 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.HL
    st = getVariable(29979);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.HL", 71);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HL;
    st->value_p = p_LREAL;
  }
  { // 29980 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.LA
    st = getVariable(29980);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.LA", 71);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LA;
    st->value_p = p_LREAL;
  }
  { // 29981 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.HA
    st = getVariable(29981);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.HA", 71);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HA;
    st->value_p = p_LREAL;
  }
  { // 29982 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.LW
    st = getVariable(29982);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.LW", 71);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LW;
    st->value_p = p_LREAL;
  }
  { // 29983 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.HW
    st = getVariable(29983);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.HW", 71);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HW;
    st->value_p = p_LREAL;
  }
  { // 29984 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.ISVALIDREF_LA
    st = getVariable(29984);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.ISVALIDREF_LA", 82);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_LA;
    st->value_p = p_BOOL;
  }
  { // 29985 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.ISVALIDREF_HA
    st = getVariable(29985);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.ISVALIDREF_HA", 82);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_HA;
    st->value_p = p_BOOL;
  }
  { // 29986 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.ISVALIDREF_LW
    st = getVariable(29986);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.ISVALIDREF_LW", 82);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_LW;
    st->value_p = p_BOOL;
  }
  { // 29987 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.ISVALIDREF_HW
    st = getVariable(29987);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.ISVALIDREF_HW", 82);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_HW;
    st->value_p = p_BOOL;
  }
  { // 29988 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.INPLL
    st = getVariable(29988);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.INPLL", 74);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->INPLL;
    st->value_p = p_LREAL;
  }
  { // 29989 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.INPHL
    st = getVariable(29989);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.INPHL", 74);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->INPHL;
    st->value_p = p_LREAL;
  }
  { // 29990 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.CURRENTSHOTCIRCUIT
    st = getVariable(29990);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.CURRENTSHOTCIRCUIT", 87);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CURRENTSHOTCIRCUIT;
    st->value_p = p_LREAL;
  }
  { // 29991 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.CURRENTBREAKCIRCUIT
    st = getVariable(29991);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.CURRENTBREAKCIRCUIT", 88);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CURRENTBREAKCIRCUIT;
    st->value_p = p_LREAL;
  }
  { // 29992 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.MAXCHANGESPEED
    st = getVariable(29992);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.MAXCHANGESPEED", 83);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXCHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 29993 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.MAXCHANGESPEEDDOWN
    st = getVariable(29993);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.MAXCHANGESPEEDDOWN", 87);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXCHANGESPEEDDOWN;
    st->value_p = p_LREAL;
  }
  { // 29994 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.CHANGESPEED
    st = getVariable(29994);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.CHANGESPEED", 80);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 29995 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.HISTERESIS
    st = getVariable(29995);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.HISTERESIS", 79);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HISTERESIS;
    st->value_p = p_LREAL;
  }
  { // 29996 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.APERTURFILTER
    st = getVariable(29996);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.APERTURFILTER", 82);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->APERTURFILTER;
    st->value_p = p_LREAL;
  }
  { // 29997 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.EXPONENTIALFILTER
    st = getVariable(29997);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.EXPONENTIALFILTER", 86);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->EXPONENTIALFILTER;
    st->value_p = p_LREAL;
  }
  { // 29998 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.RASSOGLASOVANIE
    st = getVariable(29998);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.RASSOGLASOVANIE", 84);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->RASSOGLASOVANIE;
    st->value_p = p_LREAL;
  }
  { // 29999 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.OPCCOMMANDSDISABLED
    st = getVariable(29999);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.OPCCOMMANDSDISABLED", 88);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 30000 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DISABLED_LA
    st = getVariable(30000);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DISABLED_LA", 80);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_LA;
    st->value_p = p_BOOL;
  }
  { // 30001 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DISABLED_HA
    st = getVariable(30001);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DISABLED_HA", 80);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_HA;
    st->value_p = p_BOOL;
  }
  { // 30002 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DISABLED_LW
    st = getVariable(30002);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DISABLED_LW", 80);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_LW;
    st->value_p = p_BOOL;
  }
  { // 30003 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DISABLED_HW
    st = getVariable(30003);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DISABLED_HW", 80);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_HW;
    st->value_p = p_BOOL;
  }
  { // 30004 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DELAYLA
    st = getVariable(30004);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DELAYLA", 76);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYLA;
    st->value_p = p_TIME;
  }
  { // 30005 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DELAYLW
    st = getVariable(30005);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DELAYLW", 76);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYLW;
    st->value_p = p_TIME;
  }
  { // 30006 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DELAYHW
    st = getVariable(30006);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DELAYHW", 76);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYHW;
    st->value_p = p_TIME;
  }
  { // 30007 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DELAYHA
    st = getVariable(30007);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DELAYHA", 76);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYHA;
    st->value_p = p_TIME;
  }
  { // 30008 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.MINVALUE_ISVALIDREF
    st = getVariable(30008);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.MINVALUE_ISVALIDREF", 88);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->MINVALUE_ISVALIDREF;
    st->value_p = p_BOOL;
  }
  { // 30009 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.MAXVALUE_ISVALIDREF
    st = getVariable(30009);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.MAXVALUE_ISVALIDREF", 88);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->MAXVALUE_ISVALIDREF;
    st->value_p = p_BOOL;
  }
  { // 30010 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.MINVALUE
    st = getVariable(30010);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.MINVALUE", 77);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MINVALUE;
    st->value_p = p_LREAL;
  }
  { // 30011 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.MAXVALUE
    st = getVariable(30011);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.MAXVALUE", 77);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXVALUE;
    st->value_p = p_LREAL;
  }
  { // 30012 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.INOPCCOMMANDSDISABLED
    st = getVariable(30012);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.INOPCCOMMANDSDISABLED", 90);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 30013 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.IMIT
    st = getVariable(30013);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.IMIT", 73);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->IMIT;
    st->value_p = p_BOOL;
  }
  { // 30014 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.REMONT
    st = getVariable(30014);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.REMONT", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->REMONT;
    st->value_p = p_BOOL;
  }
  { // 30015 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.NS
    st = getVariable(30015);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.NS", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS;
    st->value_p = p_BOOL;
  }
  { // 30016 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.NS_MIN
    st = getVariable(30016);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.NS_MIN", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS_MIN;
    st->value_p = p_BOOL;
  }
  { // 30017 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.NS_MAX
    st = getVariable(30017);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.NS_MAX", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS_MAX;
    st->value_p = p_BOOL;
  }
  { // 30018 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.INCOMMAND_ALG
    st = getVariable(30018);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.INCOMMAND_ALG", 82);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 30019 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.INCOMMAND_ARM
    st = getVariable(30019);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.INCOMMAND_ARM", 82);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 30020 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DMAXCHANGESPEED
    st = getVariable(30020);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DMAXCHANGESPEED", 84);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DMAXCHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 30021 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DMAXCHANGESPEEDDOWN
    st = getVariable(30021);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.AI.DMAXCHANGESPEEDDOWN", 88);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DMAXCHANGESPEEDDOWN;
    st->value_p = p_LREAL;
  }
  { // 30022 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.CONTROLLIMIT
    st = getVariable(30022);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.CONTROLLIMIT", 85);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BYTE = (BYTE*)&p_STRUCT_AIPROTECTION->CONTROLLIMIT;
    st->value_p = p_BYTE;
  }
  { // 30023 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.DELAY
    st = getVariable(30023);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.DELAY", 78);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_TIME = (TIME*)&p_STRUCT_AIPROTECTION->DELAY;
    st->value_p = p_TIME;
  }
  { // 30024 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.INTAG
    st = getVariable(30024);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.INTAG", 78);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BYTE = (BYTE*)&p_STRUCT_AIPROTECTION->INTAG;
    st->value_p = p_BYTE;
  }
  { // 30025 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.INRUNONSTART
    st = getVariable(30025);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.INRUNONSTART", 85);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->INRUNONSTART;
    st->value_p = p_BOOL;
  }
  { // 30026 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.INCANRUN
    st = getVariable(30026);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.INCANRUN", 81);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->INCANRUN;
    st->value_p = p_BOOL;
  }
  { // 30027 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.INOPCCOMMANDSDISABLED
    st = getVariable(30027);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.INOPCCOMMANDSDISABLED", 94);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 30028 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.INCOMMAND
    st = getVariable(30028);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.INCOMMAND", 82);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_WORD = (WORD*)&p_STRUCT_AIPROTECTION->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 30029 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.INCOMMAND_ALG
    st = getVariable(30029);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.INCOMMAND_ALG", 86);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_WORD = (WORD*)&p_STRUCT_AIPROTECTION->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 30030 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.INCOMMAND_ARM
    st = getVariable(30030);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.INCOMMAND_ARM", 86);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_WORD = (WORD*)&p_STRUCT_AIPROTECTION->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 30031 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.TAG
    st = getVariable(30031);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.TAG", 76);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BYTE = (BYTE*)&p_STRUCT_AIPROTECTION->TAG;
    st->value_p = p_BYTE;
  }
  { // 30032 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.STATUS
    st = getVariable(30032);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.STATUS", 79);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_DWORD = (DWORD*)&p_STRUCT_AIPROTECTION->STATUS;
    st->value_p = p_DWORD;
  }
  { // 30033 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.CANRUN
    st = getVariable(30033);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.CANRUN", 79);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->CANRUN;
    st->value_p = p_BOOL;
  }
  { // 30034 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.OPCCOMMANDSDISABLED
    st = getVariable(30034);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.OPCCOMMANDSDISABLED", 92);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 30035 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.ISRUNNING
    st = getVariable(30035);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.ISRUNNING", 82);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->ISRUNNING;
    st->value_p = p_BOOL;
  }
  { // 30036 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.HASERROR
    st = getVariable(30036);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.HASERROR", 81);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->HASERROR;
    st->value_p = p_BOOL;
  }
  { // 30037 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.ISENDED
    st = getVariable(30037);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.ISENDED", 80);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->ISENDED;
    st->value_p = p_BOOL;
  }
  { // 30038 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.REMONT
    st = getVariable(30038);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.REMONT", 79);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->REMONT;
    st->value_p = p_BOOL;
  }
  { // 30039 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.CHECK
    st = getVariable(30039);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.CHECK", 78);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->CHECK;
    st->value_p = p_BOOL;
  }
  { // 30040 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.SIGNALING
    st = getVariable(30040);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.SIGNALING", 82);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->SIGNALING;
    st->value_p = p_BOOL;
  }
  { // 30041 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.SIGNALINGTP
    st = getVariable(30041);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.SIGNALINGTP", 84);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->SIGNALINGTP;
    st->value_p = p_BOOL;
  }
  { // 30042 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.RUNONSTART
    st = getVariable(30042);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.STRAIP.RUNONSTART", 83);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->RUNONSTART;
    st->value_p = p_BOOL;
  }
  { // 30047 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._SIGNALINGTP.IN
    st = getVariable(30047);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._SIGNALINGTP.IN", 81);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    p_BOOL = (BOOL*)&p_TOF->IN;
    st->value_p = p_BOOL;
  }
  { // 30048 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._SIGNALINGTP.PT
    st = getVariable(30048);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._SIGNALINGTP.PT", 81);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    p_TIME = (TIME*)&p_TOF->PT;
    st->value_p = p_TIME;
  }
  { // 30049 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._SIGNALINGTP.Q
    st = getVariable(30049);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._SIGNALINGTP.Q", 80);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    p_BOOL = (BOOL*)&p_TOF->Q;
    st->value_p = p_BOOL;
  }
  { // 30050 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._SIGNALINGTP.ET
    st = getVariable(30050);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._SIGNALINGTP.ET", 81);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    p_TIME = (TIME*)&p_TOF->ET;
    st->value_p = p_TIME;
  }
  { // 30051 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._SIGNALINGTP
    st = getVariable(30051);
    memcpy(st->IEC_TYPE, "TOF", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._SIGNALINGTP", 78);
    st->size_data = sizeof(TOF);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    st->value_p = (void *)p_TOF;
  }
  { // 30052 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._STATUSAI.NOTDEFINED
    st = getVariable(30052);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._STATUSAI.NOTDEFINED", 86);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NOTDEFINED;
    st->value_p = p_BYTE;
  }
  { // 30053 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._STATUSAI.LL
    st = getVariable(30053);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._STATUSAI.LL", 78);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LL;
    st->value_p = p_BYTE;
  }
  { // 30054 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._STATUSAI.HL
    st = getVariable(30054);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._STATUSAI.HL", 78);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HL;
    st->value_p = p_BYTE;
  }
  { // 30055 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._STATUSAI.NOTRELIABLE
    st = getVariable(30055);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._STATUSAI.NOTRELIABLE", 87);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NOTRELIABLE;
    st->value_p = p_BYTE;
  }
  { // 30056 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._STATUSAI.NORMAL
    st = getVariable(30056);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._STATUSAI.NORMAL", 82);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NORMAL;
    st->value_p = p_BYTE;
  }
  { // 30057 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._STATUSAI.LW
    st = getVariable(30057);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._STATUSAI.LW", 78);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LW;
    st->value_p = p_BYTE;
  }
  { // 30058 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._STATUSAI.HW
    st = getVariable(30058);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._STATUSAI.HW", 78);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HW;
    st->value_p = p_BYTE;
  }
  { // 30059 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._STATUSAI.LA
    st = getVariable(30059);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._STATUSAI.LA", 78);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LA;
    st->value_p = p_BYTE;
  }
  { // 30060 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._STATUSAI.HA
    st = getVariable(30060);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1._STATUSAI.HA", 78);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HA;
    st->value_p = p_BYTE;
  }
  { // 30061 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SOURCE
    st = getVariable(30061);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SOURCE", 72);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->SOURCE;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 30062 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.CMD
    st = getVariable(30062);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.CMD", 69);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->CMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 30063 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.LASTCMD
    st = getVariable(30063);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.LASTCMD", 73);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->LASTCMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 30064 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SOURCE_FOR_STATUS
    st = getVariable(30064);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SOURCE_FOR_STATUS", 83);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->SOURCE_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 30065 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.CMD_FOR_STATUS
    st = getVariable(30065);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.CMD_FOR_STATUS", 80);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->CMD_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 30066 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.COMMAND_ERROR_FOR_STATUS
    st = getVariable(30066);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.COMMAND_ERROR_FOR_STATUS", 90);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->COMMAND_ERROR_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 30067 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.RESETCMDTIMER.IN
    st = getVariable(30067);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.RESETCMDTIMER.IN", 82);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 30068 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.RESETCMDTIMER.PT
    st = getVariable(30068);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.RESETCMDTIMER.PT", 82);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 30069 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.RESETCMDTIMER.Q
    st = getVariable(30069);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.RESETCMDTIMER.Q", 81);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 30070 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.RESETCMDTIMER.ET
    st = getVariable(30070);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.RESETCMDTIMER.ET", 82);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 30071 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.RESETCMDTIMER
    st = getVariable(30071);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.RESETCMDTIMER", 79);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    st->value_p = (void *)p_TON;
  }
  { // 30072 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.RESETCMDTIMERPRIZNAK
    st = getVariable(30072);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.RESETCMDTIMERPRIZNAK", 86);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_BOOL = (BOOL*)&p_FB_AIPROTECTION->RESETCMDTIMERPRIZNAK;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 30073 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SIGNALINTIMER.IN
    st = getVariable(30073);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SIGNALINTIMER.IN", 82);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 30074 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SIGNALINTIMER.PT
    st = getVariable(30074);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SIGNALINTIMER.PT", 82);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 30075 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SIGNALINTIMER.Q
    st = getVariable(30075);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SIGNALINTIMER.Q", 81);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 30076 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SIGNALINTIMER.ET
    st = getVariable(30076);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SIGNALINTIMER.ET", 82);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 30077 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SIGNALINTIMER
    st = getVariable(30077);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SIGNALINTIMER", 79);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    st->value_p = (void *)p_TON;
  }
  { // 30078 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.TIMER.IN
    st = getVariable(30078);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.TIMER.IN", 74);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 30079 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.TIMER.PT
    st = getVariable(30079);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.TIMER.PT", 74);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 30080 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.TIMER.Q
    st = getVariable(30080);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.TIMER.Q", 73);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 30081 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.TIMER.ET
    st = getVariable(30081);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.TIMER.ET", 74);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 30082 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.TIMER
    st = getVariable(30082);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.TIMER", 71);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    st->value_p = (void *)p_TON;
  }
  { // 30083 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SIGNALINGTRIG.CLK
    st = getVariable(30083);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SIGNALINGTRIG.CLK", 83);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_R_TRIG = (R_TRIG*)&p_FB_AIPROTECTION->SIGNALINGTRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 30084 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SIGNALINGTRIG.Q
    st = getVariable(30084);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SIGNALINGTRIG.Q", 81);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_R_TRIG = (R_TRIG*)&p_FB_AIPROTECTION->SIGNALINGTRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 30085 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SIGNALINGTRIG
    st = getVariable(30085);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SIGNALINGTRIG", 79);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_R_TRIG = (R_TRIG*)&p_FB_AIPROTECTION->SIGNALINGTRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 30086 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SIGNALINGFTRIG.CLK
    st = getVariable(30086);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SIGNALINGFTRIG.CLK", 84);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_F_TRIG = (F_TRIG*)&p_FB_AIPROTECTION->SIGNALINGFTRIG;
    p_BOOL = (BOOL*)&p_F_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 30087 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SIGNALINGFTRIG.Q
    st = getVariable(30087);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SIGNALINGFTRIG.Q", 82);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_F_TRIG = (F_TRIG*)&p_FB_AIPROTECTION->SIGNALINGFTRIG;
    p_BOOL = (BOOL*)&p_F_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 30088 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SIGNALINGFTRIG
    st = getVariable(30088);
    memcpy(st->IEC_TYPE, "F_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SIGNALINGFTRIG", 80);
    st->size_data = sizeof(F_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_F_TRIG = (F_TRIG*)&p_FB_AIPROTECTION->SIGNALINGFTRIG;
    st->value_p = (void *)p_F_TRIG;
  }
  { // 30089 PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SIGNALINGAI
    st = getVariable(30089);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1.SIGNALINGAI", 77);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_TOY_PODSHIPNIKA_SVOBOD_KONCA_EDT_8_1;
    p_BOOL = (BOOL*)&p_FB_AIPROTECTION->SIGNALINGAI;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }

  return 0;
}

// clang-format on
