// clang-format off

#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include "POUS.h"
#include <beremiz/beremiz.h>

#include "iec_types_all.h"
#include "config1.h"

extern PROGRAM0 RESOURCE1__INSTANCE0;

#ifdef DEBUG_PLC
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err][%s:%d]: " _PRNTMSG "\n", __func__, __LINE__, ##__VA_ARGS__)
#else
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err]: " _PRNTMSG "\n", ##__VA_ARGS__)
#endif // DEBUG_PLC

void UnpackVar(void* varp, __IEC_types_enum vartype, void **value_p, void **f_value_p, uint8_t **flags);

int __variables_init_FB_OSSDVIGNAGNETATELJA_MINUS(){
  iec_var_t *st;

  PROGRAM0 *p_PROGRAM0;
  LREAL *p_LREAL;
  ULINT *p_ULINT;
  REAL *p_REAL;
  FB_TIMINGS *p_FB_TIMINGS;
  BOOL *p_BOOL;
  UINT *p_UINT;
  PROC_AI_INIT *p_PROC_AI_INIT;
  FB_AI_INIT *p_FB_AI_INIT;
  TIME *p_TIME;
  STRUCT_AI *p_STRUCT_AI;
  DWORD *p_DWORD;
  BYTE *p_BYTE;
  WORD *p_WORD;
  AICONFIG *p_AICONFIG;
  PROC_AI *p_PROC_AI;
  FB_AISOURCEMLP *p_FB_AISOURCEMLP;
  TITEMAIN *p_TITEMAIN;
  TITEMDIN *p_TITEMDIN;
  TYPE_STATUSAI *p_TYPE_STATUSAI;
  TYPE_COMMANDANALOG *p_TYPE_COMMANDANALOG;
  FB_SUNPACKERCOMMAND *p_FB_SUNPACKERCOMMAND;
  TYPE_ANALOGLIMITFLAGS *p_TYPE_ANALOGLIMITFLAGS;
  TON *p_TON;
  R_TRIG *p_R_TRIG;
  FB_AISOURCEMLP_TIMER *p_FB_AISOURCEMLP_TIMER;
  PROC_AO_INIT *p_PROC_AO_INIT;
  FB_AO_INIT *p_FB_AO_INIT;
  STRUCT_AO *p_STRUCT_AO;
  AOCONFIG *p_AOCONFIG;
  PROC_AO *p_PROC_AO;
  FB_AOSOURCEMLP *p_FB_AOSOURCEMLP;
  TDOUBLEDATA *p_TDOUBLEDATA;
  PROC_DI_INIT *p_PROC_DI_INIT;
  FB_DI_INIT *p_FB_DI_INIT;
  STRUCT_DI *p_STRUCT_DI;
  __IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t *p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t;
  TYPE_RELIABLEBIT *p_TYPE_RELIABLEBIT;
  DICONFIG *p_DICONFIG;
  PROC_DI *p_PROC_DI;
  FB_DISOURCEMLP *p_FB_DISOURCEMLP;
  INT *p_INT;
  UDINT *p_UDINT;
  PROC_DO_INIT *p_PROC_DO_INIT;
  FB_DO_INIT *p_FB_DO_INIT;
  STRUCT_DO *p_STRUCT_DO;
  __IEC___ARRAY_OF_BOOL_16_t *p___IEC___ARRAY_OF_BOOL_16_t;
  DOCONFIG *p_DOCONFIG;
  PROC_DO *p_PROC_DO;
  FB_DOSOURCEMLP *p_FB_DOSOURCEMLP;
  TWORDDATA *p_TWORDDATA;
  OPC_ALGORITMS_SET *p_OPC_ALGORITMS_SET;
  ALGORITMSCONFIG *p_ALGORITMSCONFIG;
  STRUCT_ALG *p_STRUCT_ALG;
  STRUCT_ALGORITMSMANAGER *p_STRUCT_ALGORITMSMANAGER;
  STRUCT_PROTECTIONSMANAGER *p_STRUCT_PROTECTIONSMANAGER;
  STRUCT_ALGTIMERS *p_STRUCT_ALGTIMERS;
  ALGORITMSQUESTIONS *p_ALGORITMSQUESTIONS;
  STRUCT_QUESTION *p_STRUCT_QUESTION;
  OPC_ALGORITMS_GET *p_OPC_ALGORITMS_GET;
  PROC_IM_INIT *p_PROC_IM_INIT;
  FB_KRAN_INIT *p_FB_KRAN_INIT;
  STRUCT_KRAN *p_STRUCT_KRAN;
  FB_SWITCH_INIT *p_FB_SWITCH_INIT;
  STRUCT_SWITCH *p_STRUCT_SWITCH;
  FB_OILPUMP_INIT *p_FB_OILPUMP_INIT;
  STRUCT_OILPUMP *p_STRUCT_OILPUMP;
  FB_SECTIONSWITCH_INIT *p_FB_SECTIONSWITCH_INIT;
  STRUCT_SECTIONSWITCH *p_STRUCT_SECTIONSWITCH;
  FB_ANALOGPARAMETR_INIT *p_FB_ANALOGPARAMETR_INIT;
  STRUCT_ANALOGPARAMETR *p_STRUCT_ANALOGPARAMETR;
  FB_DISCRETPARAMETR_INIT *p_FB_DISCRETPARAMETR_INIT;
  STRUCT_DISCRETPARAMETR *p_STRUCT_DISCRETPARAMETR;
  FB_SINGLESIGNAL_INIT *p_FB_SINGLESIGNAL_INIT;
  STRUCT_SINGLESIGNAL *p_STRUCT_SINGLESIGNAL;
  FB_SINGLEOUTPUT_INIT *p_FB_SINGLEOUTPUT_INIT;
  STRUCT_SINGLEOUTPUT *p_STRUCT_SINGLEOUTPUT;
  IMCONFIG *p_IMCONFIG;
  STRUCT_RESERVEIM *p_STRUCT_RESERVEIM;
  STRUCT_RESERVEIM2 *p_STRUCT_RESERVEIM2;
  IM_SINGLESIGNALS *p_IM_SINGLESIGNALS;
  IM_SINGLEOUTPUTS *p_IM_SINGLEOUTPUTS;
  PROC_IM *p_PROC_IM;
  FB_KRAN *p_FB_KRAN;
  TYPE_STATUSDUALINPUT *p_TYPE_STATUSDUALINPUT;
  TYPE_COMMANDDUALINPUT *p_TYPE_COMMANDDUALINPUT;
  TOF *p_TOF;
  FB_OILPUMP *p_FB_OILPUMP;
  FB_SWITCH *p_FB_SWITCH;
  FB_SECTIONSWITCH *p_FB_SECTIONSWITCH;
  TYPE_BASKETSTATS *p_TYPE_BASKETSTATS;
  FB_MEANDR *p_FB_MEANDR;
  FB_SINGLESIGNAL *p_FB_SINGLESIGNAL;
  FB_SINGLEOUTPUT *p_FB_SINGLEOUTPUT;
  PROC_PROTECTIONS_INIT *p_PROC_PROTECTIONS_INIT;
  FB_DIPROTECTION_INIT *p_FB_DIPROTECTION_INIT;
  STRUCT_DIPROTECTION *p_STRUCT_DIPROTECTION;
  FB_AIPROTECTION_INIT *p_FB_AIPROTECTION_INIT;
  STRUCT_AIPROTECTION *p_STRUCT_AIPROTECTION;
  PROTECTIONSCONFIG *p_PROTECTIONSCONFIG;
  TYPE_PROTECTIONTAGS *p_TYPE_PROTECTIONTAGS;
  PROC_PROTECTION *p_PROC_PROTECTION;
  FB_MVPROTECTION *p_FB_MVPROTECTION;
  F_TRIG *p_F_TRIG;
  FB_DIPROTECTION *p_FB_DIPROTECTION;
  FB_KRANOPENPROTECTION *p_FB_KRANOPENPROTECTION;
  FB_AIPROTECTION *p_FB_AIPROTECTION;
  PROC_ALGORITMS *p_PROC_ALGORITMS;
  REMONTALG *p_REMONTALG;
  TYPE_MODEGPA *p_TYPE_MODEGPA;
  TYPE_COMMANDSPOTECTIONSMANAGER *p_TYPE_COMMANDSPOTECTIONSMANAGER;
  TESTPROTECTIONALG *p_TESTPROTECTIONALG;
  TESTIMALG *p_TESTIMALG;
  FB_AUTOTENALG *p_FB_AUTOTENALG;
  FB_AUTOPNSALG *p_FB_AUTOPNSALG;
  FB_AUTOAVOMALG *p_FB_AUTOAVOMALG;
  FB_VIBEGPNSALG *p_FB_VIBEGPNSALG;
  STRUCT_PHASEALGORITM *p_STRUCT_PHASEALGORITM;
  FB_PH_ALGORITM *p_FB_PH_ALGORITM;
  FB_PH_TIMER *p_FB_PH_TIMER;
  FB_QUESTION *p_FB_QUESTION;
  TYPE_ANSWERS *p_TYPE_ANSWERS;
  FB_PH_SWITCH *p_FB_PH_SWITCH;
  FB_PH_CUSTOMPHASE *p_FB_PH_CUSTOMPHASE;
  FB_AUTONUALG *p_FB_AUTONUALG;
  FB_PUSKOILSYSTEMALG *p_FB_PUSKOILSYSTEMALG;
  FB_PH_WAITANALOGVALUE *p_FB_PH_WAITANALOGVALUE;
  FB_PH_OILPUMP *p_FB_PH_OILPUMP;
  FB_ANTIPOMPAGALG *p_FB_ANTIPOMPAGALG;
  FB_TABLEVALUE_MIN *p_FB_TABLEVALUE_MIN;
  __IEC___ARRAY_OF_TYPE_TABLEREC_9_t *p___IEC___ARRAY_OF_TYPE_TABLEREC_9_t;
  TYPE_TABLEREC *p_TYPE_TABLEREC;
  FB_TABLEVALUE_MAX *p_FB_TABLEVALUE_MAX;
  FB_RASHODALG *p_FB_RASHODALG;
  FB_ZAPASALG *p_FB_ZAPASALG;
  NOALG *p_NOALG;
  FB_PH_KRAN *p_FB_PH_KRAN;
  FB_PH_SECTIONSWITCH *p_FB_PH_SECTIONSWITCH;
  AOALG *p_AOALG;
  PPUALG *p_PPUALG;
  FILLINGALG *p_FILLINGALG;
  FB_PH_DIPROTECTION *p_FB_PH_DIPROTECTION;
  ENGINERUNALG *p_ENGINERUNALG;
  PUSKKALG *p_PUSKKALG;
  PUSKVALG *p_PUSKVALG;
  TESTDPMGALG *p_TESTDPMGALG;
  TESTPMSALG *p_TESTPMSALG;
  FB_PH_AIPROTECTION *p_FB_PH_AIPROTECTION;
  APUSKALG *p_APUSKALG;
  SEMIAUTOPUSKALG *p_SEMIAUTOPUSKALG;
  FB_ALGORITMSMANAGER *p_FB_ALGORITMSMANAGER;
  FB_PROTECTIONSMANAGER *p_FB_PROTECTIONSMANAGER;

  { // 8523 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ARAIN.WFLAGS
    st = getVariable(8523);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ARAIN.WFLAGS", 58);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TITEMAIN = (TITEMAIN*)&p_FB_AISOURCEMLP->ARAIN;
    p_UINT = (UINT*)&p_TITEMAIN->WFLAGS;
    st->value_p = p_UINT;
  }
  { // 8524 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ARAIN.WRESERVED
    st = getVariable(8524);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ARAIN.WRESERVED", 61);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TITEMAIN = (TITEMAIN*)&p_FB_AISOURCEMLP->ARAIN;
    p_UINT = (UINT*)&p_TITEMAIN->WRESERVED;
    st->value_p = p_UINT;
  }
  { // 8525 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ARAIN.DBLVALUE
    st = getVariable(8525);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ARAIN.DBLVALUE", 60);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TITEMAIN = (TITEMAIN*)&p_FB_AISOURCEMLP->ARAIN;
    p_LREAL = (LREAL*)&p_TITEMAIN->DBLVALUE;
    st->value_p = p_LREAL;
  }
  { // 8526 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ARAIN.NANOSEC
    st = getVariable(8526);
    memcpy(st->IEC_TYPE, "ULINT", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ARAIN.NANOSEC", 59);
    st->size_data = sizeof(ULINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TITEMAIN = (TITEMAIN*)&p_FB_AISOURCEMLP->ARAIN;
    p_ULINT = (ULINT*)&p_TITEMAIN->NANOSEC;
    st->value_p = p_ULINT;
  }
  { // 8527 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ARAIN.RESERVE
    st = getVariable(8527);
    memcpy(st->IEC_TYPE, "ULINT", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ARAIN.RESERVE", 59);
    st->size_data = sizeof(ULINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TITEMAIN = (TITEMAIN*)&p_FB_AISOURCEMLP->ARAIN;
    p_ULINT = (ULINT*)&p_TITEMAIN->RESERVE;
    st->value_p = p_ULINT;
  }
  { // 8528 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ERR_MOD.WFLAGS
    st = getVariable(8528);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ERR_MOD.WFLAGS", 60);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TITEMDIN = (TITEMDIN*)&p_FB_AISOURCEMLP->ERR_MOD;
    p_UINT = (UINT*)&p_TITEMDIN->WFLAGS;
    st->value_p = p_UINT;
  }
  { // 8529 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ERR_MOD.WVALUE
    st = getVariable(8529);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ERR_MOD.WVALUE", 60);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TITEMDIN = (TITEMDIN*)&p_FB_AISOURCEMLP->ERR_MOD;
    p_UINT = (UINT*)&p_TITEMDIN->WVALUE;
    st->value_p = p_UINT;
  }
  { // 8530 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ERR_MOD.NANOSEC
    st = getVariable(8530);
    memcpy(st->IEC_TYPE, "ULINT", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ERR_MOD.NANOSEC", 61);
    st->size_data = sizeof(ULINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TITEMDIN = (TITEMDIN*)&p_FB_AISOURCEMLP->ERR_MOD;
    p_ULINT = (ULINT*)&p_TITEMDIN->NANOSEC;
    st->value_p = p_ULINT;
  }
  { // 8531 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ERR_MOD.RESERVE
    st = getVariable(8531);
    memcpy(st->IEC_TYPE, "ULINT", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ERR_MOD.RESERVE", 61);
    st->size_data = sizeof(ULINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TITEMDIN = (TITEMDIN*)&p_FB_AISOURCEMLP->ERR_MOD;
    p_ULINT = (ULINT*)&p_TITEMDIN->RESERVE;
    st->value_p = p_ULINT;
  }
  { // 8532 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.VALUE
    st = getVariable(8532);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.VALUE", 57);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->VALUE;
    st->value_p = p_LREAL;
  }
  { // 8533 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.STATUS
    st = getVariable(8533);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.STATUS", 58);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_DWORD = (DWORD*)&p_STRUCT_AI->STATUS;
    st->value_p = p_DWORD;
  }
  { // 8534 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.INTERVAL
    st = getVariable(8534);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.INTERVAL", 60);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BYTE = (BYTE*)&p_STRUCT_AI->INTERVAL;
    st->value_p = p_BYTE;
  }
  { // 8535 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.INCOMMAND
    st = getVariable(8535);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.INCOMMAND", 61);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 8536 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.BLCONNECT
    st = getVariable(8536);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.BLCONNECT", 61);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->BLCONNECT;
    st->value_p = p_BOOL;
  }
  { // 8537 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DLL
    st = getVariable(8537);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DLL", 55);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLL;
    st->value_p = p_LREAL;
  }
  { // 8538 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DHL
    st = getVariable(8538);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DHL", 55);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHL;
    st->value_p = p_LREAL;
  }
  { // 8539 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DLA
    st = getVariable(8539);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DLA", 55);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLA;
    st->value_p = p_LREAL;
  }
  { // 8540 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DHA
    st = getVariable(8540);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DHA", 55);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHA;
    st->value_p = p_LREAL;
  }
  { // 8541 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DLW
    st = getVariable(8541);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DLW", 55);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLW;
    st->value_p = p_LREAL;
  }
  { // 8542 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DHW
    st = getVariable(8542);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DHW", 55);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHW;
    st->value_p = p_LREAL;
  }
  { // 8543 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.LL
    st = getVariable(8543);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.LL", 54);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LL;
    st->value_p = p_LREAL;
  }
  { // 8544 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.HL
    st = getVariable(8544);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.HL", 54);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HL;
    st->value_p = p_LREAL;
  }
  { // 8545 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.LA
    st = getVariable(8545);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.LA", 54);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LA;
    st->value_p = p_LREAL;
  }
  { // 8546 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.HA
    st = getVariable(8546);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.HA", 54);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HA;
    st->value_p = p_LREAL;
  }
  { // 8547 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.LW
    st = getVariable(8547);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.LW", 54);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LW;
    st->value_p = p_LREAL;
  }
  { // 8548 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.HW
    st = getVariable(8548);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.HW", 54);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HW;
    st->value_p = p_LREAL;
  }
  { // 8549 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.ISVALIDREF_LA
    st = getVariable(8549);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.ISVALIDREF_LA", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_LA;
    st->value_p = p_BOOL;
  }
  { // 8550 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.ISVALIDREF_HA
    st = getVariable(8550);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.ISVALIDREF_HA", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_HA;
    st->value_p = p_BOOL;
  }
  { // 8551 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.ISVALIDREF_LW
    st = getVariable(8551);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.ISVALIDREF_LW", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_LW;
    st->value_p = p_BOOL;
  }
  { // 8552 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.ISVALIDREF_HW
    st = getVariable(8552);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.ISVALIDREF_HW", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_HW;
    st->value_p = p_BOOL;
  }
  { // 8553 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.INPLL
    st = getVariable(8553);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.INPLL", 57);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->INPLL;
    st->value_p = p_LREAL;
  }
  { // 8554 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.INPHL
    st = getVariable(8554);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.INPHL", 57);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->INPHL;
    st->value_p = p_LREAL;
  }
  { // 8555 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.CURRENTSHOTCIRCUIT
    st = getVariable(8555);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.CURRENTSHOTCIRCUIT", 70);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CURRENTSHOTCIRCUIT;
    st->value_p = p_LREAL;
  }
  { // 8556 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.CURRENTBREAKCIRCUIT
    st = getVariable(8556);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.CURRENTBREAKCIRCUIT", 71);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CURRENTBREAKCIRCUIT;
    st->value_p = p_LREAL;
  }
  { // 8557 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.MAXCHANGESPEED
    st = getVariable(8557);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.MAXCHANGESPEED", 66);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXCHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 8558 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.MAXCHANGESPEEDDOWN
    st = getVariable(8558);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.MAXCHANGESPEEDDOWN", 70);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXCHANGESPEEDDOWN;
    st->value_p = p_LREAL;
  }
  { // 8559 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.CHANGESPEED
    st = getVariable(8559);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.CHANGESPEED", 63);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 8560 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.HISTERESIS
    st = getVariable(8560);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.HISTERESIS", 62);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HISTERESIS;
    st->value_p = p_LREAL;
  }
  { // 8561 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.APERTURFILTER
    st = getVariable(8561);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.APERTURFILTER", 65);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->APERTURFILTER;
    st->value_p = p_LREAL;
  }
  { // 8562 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.EXPONENTIALFILTER
    st = getVariable(8562);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.EXPONENTIALFILTER", 69);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->EXPONENTIALFILTER;
    st->value_p = p_LREAL;
  }
  { // 8563 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.RASSOGLASOVANIE
    st = getVariable(8563);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.RASSOGLASOVANIE", 67);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->RASSOGLASOVANIE;
    st->value_p = p_LREAL;
  }
  { // 8564 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.OPCCOMMANDSDISABLED
    st = getVariable(8564);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.OPCCOMMANDSDISABLED", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 8565 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DISABLED_LA
    st = getVariable(8565);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DISABLED_LA", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_LA;
    st->value_p = p_BOOL;
  }
  { // 8566 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DISABLED_HA
    st = getVariable(8566);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DISABLED_HA", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_HA;
    st->value_p = p_BOOL;
  }
  { // 8567 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DISABLED_LW
    st = getVariable(8567);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DISABLED_LW", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_LW;
    st->value_p = p_BOOL;
  }
  { // 8568 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DISABLED_HW
    st = getVariable(8568);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DISABLED_HW", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_HW;
    st->value_p = p_BOOL;
  }
  { // 8569 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DELAYLA
    st = getVariable(8569);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DELAYLA", 59);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYLA;
    st->value_p = p_TIME;
  }
  { // 8570 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DELAYLW
    st = getVariable(8570);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DELAYLW", 59);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYLW;
    st->value_p = p_TIME;
  }
  { // 8571 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DELAYHW
    st = getVariable(8571);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DELAYHW", 59);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYHW;
    st->value_p = p_TIME;
  }
  { // 8572 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DELAYHA
    st = getVariable(8572);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DELAYHA", 59);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYHA;
    st->value_p = p_TIME;
  }
  { // 8573 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.MINVALUE_ISVALIDREF
    st = getVariable(8573);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.MINVALUE_ISVALIDREF", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->MINVALUE_ISVALIDREF;
    st->value_p = p_BOOL;
  }
  { // 8574 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.MAXVALUE_ISVALIDREF
    st = getVariable(8574);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.MAXVALUE_ISVALIDREF", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->MAXVALUE_ISVALIDREF;
    st->value_p = p_BOOL;
  }
  { // 8575 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.MINVALUE
    st = getVariable(8575);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.MINVALUE", 60);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MINVALUE;
    st->value_p = p_LREAL;
  }
  { // 8576 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.MAXVALUE
    st = getVariable(8576);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.MAXVALUE", 60);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXVALUE;
    st->value_p = p_LREAL;
  }
  { // 8577 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.INOPCCOMMANDSDISABLED
    st = getVariable(8577);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.INOPCCOMMANDSDISABLED", 73);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 8578 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.IMIT
    st = getVariable(8578);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.IMIT", 56);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->IMIT;
    st->value_p = p_BOOL;
  }
  { // 8579 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.REMONT
    st = getVariable(8579);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.REMONT", 58);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->REMONT;
    st->value_p = p_BOOL;
  }
  { // 8580 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.NS
    st = getVariable(8580);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.NS", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS;
    st->value_p = p_BOOL;
  }
  { // 8581 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.NS_MIN
    st = getVariable(8581);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.NS_MIN", 58);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS_MIN;
    st->value_p = p_BOOL;
  }
  { // 8582 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.NS_MAX
    st = getVariable(8582);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.NS_MAX", 58);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS_MAX;
    st->value_p = p_BOOL;
  }
  { // 8583 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.INCOMMAND_ALG
    st = getVariable(8583);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.INCOMMAND_ALG", 65);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 8584 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.INCOMMAND_ARM
    st = getVariable(8584);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.INCOMMAND_ARM", 65);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 8585 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DMAXCHANGESPEED
    st = getVariable(8585);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DMAXCHANGESPEED", 67);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DMAXCHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 8586 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DMAXCHANGESPEEDDOWN
    st = getVariable(8586);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.STRAI.DMAXCHANGESPEEDDOWN", 71);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AISOURCEMLP->STRAI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DMAXCHANGESPEEDDOWN;
    st->value_p = p_LREAL;
  }
  { // 8587 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._STATUSAI.NOTDEFINED
    st = getVariable(8587);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._STATUSAI.NOTDEFINED", 66);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NOTDEFINED;
    st->value_p = p_BYTE;
  }
  { // 8588 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._STATUSAI.LL
    st = getVariable(8588);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._STATUSAI.LL", 58);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LL;
    st->value_p = p_BYTE;
  }
  { // 8589 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._STATUSAI.HL
    st = getVariable(8589);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._STATUSAI.HL", 58);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HL;
    st->value_p = p_BYTE;
  }
  { // 8590 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._STATUSAI.NOTRELIABLE
    st = getVariable(8590);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._STATUSAI.NOTRELIABLE", 67);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NOTRELIABLE;
    st->value_p = p_BYTE;
  }
  { // 8591 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._STATUSAI.NORMAL
    st = getVariable(8591);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._STATUSAI.NORMAL", 62);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NORMAL;
    st->value_p = p_BYTE;
  }
  { // 8592 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._STATUSAI.LW
    st = getVariable(8592);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._STATUSAI.LW", 58);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LW;
    st->value_p = p_BYTE;
  }
  { // 8593 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._STATUSAI.HW
    st = getVariable(8593);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._STATUSAI.HW", 58);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HW;
    st->value_p = p_BYTE;
  }
  { // 8594 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._STATUSAI.LA
    st = getVariable(8594);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._STATUSAI.LA", 58);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LA;
    st->value_p = p_BYTE;
  }
  { // 8595 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._STATUSAI.HA
    st = getVariable(8595);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._STATUSAI.HA", 58);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AISOURCEMLP->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HA;
    st->value_p = p_BYTE;
  }
  { // 8596 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._COMMANDANALOG.CMD_SETUSTAVKI
    st = getVariable(8596);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._COMMANDANALOG.CMD_SETUSTAVKI", 75);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TYPE_COMMANDANALOG = (TYPE_COMMANDANALOG*)&p_FB_AISOURCEMLP->_COMMANDANALOG;
    p_WORD = (WORD*)&p_TYPE_COMMANDANALOG->CMD_SETUSTAVKI;
    st->value_p = p_WORD;
  }
  { // 8597 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._COMMANDANALOG.CMD_SETREMONT
    st = getVariable(8597);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._COMMANDANALOG.CMD_SETREMONT", 74);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TYPE_COMMANDANALOG = (TYPE_COMMANDANALOG*)&p_FB_AISOURCEMLP->_COMMANDANALOG;
    p_WORD = (WORD*)&p_TYPE_COMMANDANALOG->CMD_SETREMONT;
    st->value_p = p_WORD;
  }
  { // 8598 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._COMMANDANALOG.CMD_RESETREMONT
    st = getVariable(8598);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._COMMANDANALOG.CMD_RESETREMONT", 76);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TYPE_COMMANDANALOG = (TYPE_COMMANDANALOG*)&p_FB_AISOURCEMLP->_COMMANDANALOG;
    p_WORD = (WORD*)&p_TYPE_COMMANDANALOG->CMD_RESETREMONT;
    st->value_p = p_WORD;
  }
  { // 8599 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._COMMANDANALOG.CMD_KVITNOTRELIABLE
    st = getVariable(8599);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._COMMANDANALOG.CMD_KVITNOTRELIABLE", 80);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TYPE_COMMANDANALOG = (TYPE_COMMANDANALOG*)&p_FB_AISOURCEMLP->_COMMANDANALOG;
    p_WORD = (WORD*)&p_TYPE_COMMANDANALOG->CMD_KVITNOTRELIABLE;
    st->value_p = p_WORD;
  }
  { // 8604 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._ANALOGLIMITFLAGS.NONE
    st = getVariable(8604);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._ANALOGLIMITFLAGS.NONE", 68);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->NONE;
    st->value_p = p_BYTE;
  }
  { // 8605 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._ANALOGLIMITFLAGS.LL
    st = getVariable(8605);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._ANALOGLIMITFLAGS.LL", 66);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->LL;
    st->value_p = p_BYTE;
  }
  { // 8606 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._ANALOGLIMITFLAGS.LW
    st = getVariable(8606);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._ANALOGLIMITFLAGS.LW", 66);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->LW;
    st->value_p = p_BYTE;
  }
  { // 8607 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._ANALOGLIMITFLAGS.HW
    st = getVariable(8607);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._ANALOGLIMITFLAGS.HW", 66);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->HW;
    st->value_p = p_BYTE;
  }
  { // 8608 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._ANALOGLIMITFLAGS.LA
    st = getVariable(8608);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._ANALOGLIMITFLAGS.LA", 66);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->LA;
    st->value_p = p_BYTE;
  }
  { // 8609 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._ANALOGLIMITFLAGS.HA
    st = getVariable(8609);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._ANALOGLIMITFLAGS.HA", 66);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->HA;
    st->value_p = p_BYTE;
  }
  { // 8610 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._ANALOGLIMITFLAGS.HL
    st = getVariable(8610);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._ANALOGLIMITFLAGS.HL", 66);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->HL;
    st->value_p = p_BYTE;
  }
  { // 8611 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._ANALOGLIMITFLAGS.SIPUP
    st = getVariable(8611);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._ANALOGLIMITFLAGS.SIPUP", 69);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->SIPUP;
    st->value_p = p_BYTE;
  }
  { // 8612 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._ANALOGLIMITFLAGS.SIPDOWN
    st = getVariable(8612);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._ANALOGLIMITFLAGS.SIPDOWN", 71);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TYPE_ANALOGLIMITFLAGS = (TYPE_ANALOGLIMITFLAGS*)&p_FB_AISOURCEMLP->_ANALOGLIMITFLAGS;
    p_BYTE = (BYTE*)&p_TYPE_ANALOGLIMITFLAGS->SIPDOWN;
    st->value_p = p_BYTE;
  }
  { // 8613 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.NOTRELIABLE
    st = getVariable(8613);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.NOTRELIABLE", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_BOOL = (BOOL*)&p_FB_AISOURCEMLP->NOTRELIABLE;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8614 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._LASTVALUE
    st = getVariable(8614);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._LASTVALUE", 56);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_LREAL = (LREAL*)&p_FB_AISOURCEMLP->_LASTVALUE;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8615 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.RESETCMDTIMER.IN
    st = getVariable(8615);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.RESETCMDTIMER.IN", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TON = (TON*)&p_FB_AISOURCEMLP->RESETCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 8616 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.RESETCMDTIMER.PT
    st = getVariable(8616);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.RESETCMDTIMER.PT", 62);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TON = (TON*)&p_FB_AISOURCEMLP->RESETCMDTIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 8617 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.RESETCMDTIMER.Q
    st = getVariable(8617);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.RESETCMDTIMER.Q", 61);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TON = (TON*)&p_FB_AISOURCEMLP->RESETCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 8618 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.RESETCMDTIMER.ET
    st = getVariable(8618);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.RESETCMDTIMER.ET", 62);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TON = (TON*)&p_FB_AISOURCEMLP->RESETCMDTIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 8619 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.RESETCMDTIMER
    st = getVariable(8619);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.RESETCMDTIMER", 59);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TON = (TON*)&p_FB_AISOURCEMLP->RESETCMDTIMER;
    st->value_p = (void *)p_TON;
  }
  { // 8620 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._LASTVALUETIMER.IN
    st = getVariable(8620);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._LASTVALUETIMER.IN", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TON = (TON*)&p_FB_AISOURCEMLP->_LASTVALUETIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 8621 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._LASTVALUETIMER.PT
    st = getVariable(8621);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._LASTVALUETIMER.PT", 64);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TON = (TON*)&p_FB_AISOURCEMLP->_LASTVALUETIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 8622 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._LASTVALUETIMER.Q
    st = getVariable(8622);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._LASTVALUETIMER.Q", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TON = (TON*)&p_FB_AISOURCEMLP->_LASTVALUETIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 8623 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._LASTVALUETIMER.ET
    st = getVariable(8623);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._LASTVALUETIMER.ET", 64);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TON = (TON*)&p_FB_AISOURCEMLP->_LASTVALUETIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 8624 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._LASTVALUETIMER
    st = getVariable(8624);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS._LASTVALUETIMER", 61);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_TON = (TON*)&p_FB_AISOURCEMLP->_LASTVALUETIMER;
    st->value_p = (void *)p_TON;
  }
  { // 8625 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.RESETCMDTIMERPRIZNAK
    st = getVariable(8625);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.RESETCMDTIMERPRIZNAK", 66);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_BOOL = (BOOL*)&p_FB_AISOURCEMLP->RESETCMDTIMERPRIZNAK;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8626 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.K
    st = getVariable(8626);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.K", 47);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_LREAL = (LREAL*)&p_FB_AISOURCEMLP->K;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8627 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.B
    st = getVariable(8627);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.B", 47);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_LREAL = (LREAL*)&p_FB_AISOURCEMLP->B;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8628 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.AP
    st = getVariable(8628);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.AP", 48);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_LREAL = (LREAL*)&p_FB_AISOURCEMLP->AP;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8629 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.RAZNITSA
    st = getVariable(8629);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.RAZNITSA", 54);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_LREAL = (LREAL*)&p_FB_AISOURCEMLP->RAZNITSA;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8630 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.RABS
    st = getVariable(8630);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.RABS", 50);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_LREAL = (LREAL*)&p_FB_AISOURCEMLP->RABS;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8631 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.H
    st = getVariable(8631);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.H", 47);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_LREAL = (LREAL*)&p_FB_AISOURCEMLP->H;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8632 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.MISMATCH
    st = getVariable(8632);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.MISMATCH", 54);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_LREAL = (LREAL*)&p_FB_AISOURCEMLP->MISMATCH;
    UnpackVar(p_LREAL, LREAL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8633 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.PARAMETR
    st = getVariable(8633);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.PARAMETR", 54);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_BYTE = (BYTE*)&p_FB_AISOURCEMLP->PARAMETR;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8634 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.SOURCE
    st = getVariable(8634);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.SOURCE", 52);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_BYTE = (BYTE*)&p_FB_AISOURCEMLP->SOURCE;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8635 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.CMD
    st = getVariable(8635);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.CMD", 49);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_BYTE = (BYTE*)&p_FB_AISOURCEMLP->CMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8636 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.LASTCMD
    st = getVariable(8636);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.LASTCMD", 53);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_BYTE = (BYTE*)&p_FB_AISOURCEMLP->LASTCMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8637 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.SOURCE_FOR_STATUS
    st = getVariable(8637);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.SOURCE_FOR_STATUS", 63);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_BYTE = (BYTE*)&p_FB_AISOURCEMLP->SOURCE_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8638 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.CMD_FOR_STATUS
    st = getVariable(8638);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.CMD_FOR_STATUS", 60);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_BYTE = (BYTE*)&p_FB_AISOURCEMLP->CMD_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8639 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.COMMAND_ERROR_FOR_STATUS
    st = getVariable(8639);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.COMMAND_ERROR_FOR_STATUS", 70);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_BYTE = (BYTE*)&p_FB_AISOURCEMLP->COMMAND_ERROR_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8640 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ONINIT
    st = getVariable(8640);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ONINIT", 52);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_BOOL = (BOOL*)&p_FB_AISOURCEMLP->ONINIT;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 8641 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.OFF_TRIG.CLK
    st = getVariable(8641);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.OFF_TRIG.CLK", 58);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->OFF_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 8642 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.OFF_TRIG.Q
    st = getVariable(8642);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.OFF_TRIG.Q", 56);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->OFF_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 8643 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.OFF_TRIG
    st = getVariable(8643);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.OFF_TRIG", 54);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->OFF_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 8644 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ON_TRIG.CLK
    st = getVariable(8644);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ON_TRIG.CLK", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->ON_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 8645 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ON_TRIG.Q
    st = getVariable(8645);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ON_TRIG.Q", 55);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->ON_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 8646 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ON_TRIG
    st = getVariable(8646);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.ON_TRIG", 53);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->ON_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 8647 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.REMONT_TRIG.CLK
    st = getVariable(8647);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.REMONT_TRIG.CLK", 61);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->REMONT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 8648 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.REMONT_TRIG.Q
    st = getVariable(8648);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.REMONT_TRIG.Q", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->REMONT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 8649 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.REMONT_TRIG
    st = getVariable(8649);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.REMONT_TRIG", 57);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->REMONT_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 8650 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.LL_TRIG.CLK
    st = getVariable(8650);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.LL_TRIG.CLK", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->LL_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 8651 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.LL_TRIG.Q
    st = getVariable(8651);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.LL_TRIG.Q", 55);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->LL_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 8652 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.LL_TRIG
    st = getVariable(8652);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.LL_TRIG", 53);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->LL_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 8653 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.HL_TRIG.CLK
    st = getVariable(8653);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.HL_TRIG.CLK", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->HL_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 8654 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.HL_TRIG.Q
    st = getVariable(8654);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.HL_TRIG.Q", 55);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->HL_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 8655 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.HL_TRIG
    st = getVariable(8655);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.HL_TRIG", 53);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->HL_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 8656 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.NORMAL_TRIG.CLK
    st = getVariable(8656);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.NORMAL_TRIG.CLK", 61);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->NORMAL_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 8657 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.NORMAL_TRIG.Q
    st = getVariable(8657);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.NORMAL_TRIG.Q", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->NORMAL_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 8658 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.NORMAL_TRIG
    st = getVariable(8658);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.NORMAL_TRIG", 57);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->NORMAL_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 8659 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.NEDOSTOVER_TRIG.CLK
    st = getVariable(8659);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.NEDOSTOVER_TRIG.CLK", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->NEDOSTOVER_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 8660 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.NEDOSTOVER_TRIG.Q
    st = getVariable(8660);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.NEDOSTOVER_TRIG.Q", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->NEDOSTOVER_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 8661 PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.NEDOSTOVER_TRIG
    st = getVariable(8661);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.AI_PROC.FB_OSSDVIGNAGNETATELJA_MINUS.NEDOSTOVER_TRIG", 61);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_AI = (PROC_AI*)&p_PROGRAM0->AI_PROC;
    p_FB_AISOURCEMLP = (FB_AISOURCEMLP*)&p_PROC_AI->FB_OSSDVIGNAGNETATELJA_MINUS;
    p_R_TRIG = (R_TRIG*)&p_FB_AISOURCEMLP->NEDOSTOVER_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }

  return 0;
}

// clang-format on
