// clang-format off

#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include "POUS.h"
#include <beremiz/beremiz.h>

#include "iec_types_all.h"
#include "config1.h"

extern PROGRAM0 RESOURCE1__INSTANCE0;

#ifdef DEBUG_PLC
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err][%s:%d]: " _PRNTMSG "\n", __func__, __LINE__, ##__VA_ARGS__)
#else
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err]: " _PRNTMSG "\n", ##__VA_ARGS__)
#endif // DEBUG_PLC

void UnpackVar(void* varp, __IEC_types_enum vartype, void **value_p, void **f_value_p, uint8_t **flags);

int __variables_init_FB_PMASLO_SM_VYSOKOE(){
  iec_var_t *st;

  PROGRAM0 *p_PROGRAM0;
  LREAL *p_LREAL;
  ULINT *p_ULINT;
  REAL *p_REAL;
  FB_TIMINGS *p_FB_TIMINGS;
  BOOL *p_BOOL;
  UINT *p_UINT;
  PROC_AI_INIT *p_PROC_AI_INIT;
  FB_AI_INIT *p_FB_AI_INIT;
  STRUCT_AI *p_STRUCT_AI;
  DWORD *p_DWORD;
  BYTE *p_BYTE;
  WORD *p_WORD;
  TIME *p_TIME;
  AICONFIG *p_AICONFIG;
  PROC_AI *p_PROC_AI;
  FB_AISOURCEMLP *p_FB_AISOURCEMLP;
  TITEMAIN *p_TITEMAIN;
  TITEMDIN *p_TITEMDIN;
  TYPE_STATUSAI *p_TYPE_STATUSAI;
  TYPE_COMMANDANALOG *p_TYPE_COMMANDANALOG;
  FB_SUNPACKERCOMMAND *p_FB_SUNPACKERCOMMAND;
  TYPE_ANALOGLIMITFLAGS *p_TYPE_ANALOGLIMITFLAGS;
  TON *p_TON;
  R_TRIG *p_R_TRIG;
  FB_AISOURCEMLP_TIMER *p_FB_AISOURCEMLP_TIMER;
  PROC_AO_INIT *p_PROC_AO_INIT;
  FB_AO_INIT *p_FB_AO_INIT;
  STRUCT_AO *p_STRUCT_AO;
  AOCONFIG *p_AOCONFIG;
  PROC_AO *p_PROC_AO;
  FB_AOSOURCEMLP *p_FB_AOSOURCEMLP;
  TDOUBLEDATA *p_TDOUBLEDATA;
  PROC_DI_INIT *p_PROC_DI_INIT;
  FB_DI_INIT *p_FB_DI_INIT;
  STRUCT_DI *p_STRUCT_DI;
  __IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t *p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t;
  TYPE_RELIABLEBIT *p_TYPE_RELIABLEBIT;
  DICONFIG *p_DICONFIG;
  PROC_DI *p_PROC_DI;
  FB_DISOURCEMLP *p_FB_DISOURCEMLP;
  INT *p_INT;
  UDINT *p_UDINT;
  PROC_DO_INIT *p_PROC_DO_INIT;
  FB_DO_INIT *p_FB_DO_INIT;
  STRUCT_DO *p_STRUCT_DO;
  DOCONFIG *p_DOCONFIG;
  PROC_DO *p_PROC_DO;
  FB_DOSOURCEMLP *p_FB_DOSOURCEMLP;
  TWORDDATA *p_TWORDDATA;
  OPC_ALGORITMS_SET *p_OPC_ALGORITMS_SET;
  ALGORITMSCONFIG *p_ALGORITMSCONFIG;
  STRUCT_ALG *p_STRUCT_ALG;
  STRUCT_ALGORITMSMANAGER *p_STRUCT_ALGORITMSMANAGER;
  STRUCT_PROTECTIONSMANAGER *p_STRUCT_PROTECTIONSMANAGER;
  STRUCT_ALGTIMERS *p_STRUCT_ALGTIMERS;
  ALGORITMSQUESTIONS *p_ALGORITMSQUESTIONS;
  STRUCT_QUESTION *p_STRUCT_QUESTION;
  OPC_ALGORITMS_GET *p_OPC_ALGORITMS_GET;
  PROC_IM_INIT *p_PROC_IM_INIT;
  FB_KRAN_INIT *p_FB_KRAN_INIT;
  STRUCT_KRAN *p_STRUCT_KRAN;
  FB_SWITCH_INIT *p_FB_SWITCH_INIT;
  STRUCT_SWITCH *p_STRUCT_SWITCH;
  FB_OILPUMP_INIT *p_FB_OILPUMP_INIT;
  STRUCT_OILPUMP *p_STRUCT_OILPUMP;
  FB_SECTIONSWITCH_INIT *p_FB_SECTIONSWITCH_INIT;
  STRUCT_SECTIONSWITCH *p_STRUCT_SECTIONSWITCH;
  FB_ANALOGPARAMETR_INIT *p_FB_ANALOGPARAMETR_INIT;
  STRUCT_ANALOGPARAMETR *p_STRUCT_ANALOGPARAMETR;
  FB_DISCRETPARAMETR_INIT *p_FB_DISCRETPARAMETR_INIT;
  STRUCT_DISCRETPARAMETR *p_STRUCT_DISCRETPARAMETR;
  FB_SINGLESIGNAL_INIT *p_FB_SINGLESIGNAL_INIT;
  STRUCT_SINGLESIGNAL *p_STRUCT_SINGLESIGNAL;
  FB_SINGLEOUTPUT_INIT *p_FB_SINGLEOUTPUT_INIT;
  STRUCT_SINGLEOUTPUT *p_STRUCT_SINGLEOUTPUT;
  IMCONFIG *p_IMCONFIG;
  STRUCT_RESERVEIM *p_STRUCT_RESERVEIM;
  STRUCT_RESERVEIM2 *p_STRUCT_RESERVEIM2;
  IM_SINGLESIGNALS *p_IM_SINGLESIGNALS;
  IM_SINGLEOUTPUTS *p_IM_SINGLEOUTPUTS;
  PROC_IM *p_PROC_IM;
  FB_KRAN *p_FB_KRAN;
  TYPE_STATUSDUALINPUT *p_TYPE_STATUSDUALINPUT;
  TYPE_COMMANDDUALINPUT *p_TYPE_COMMANDDUALINPUT;
  TOF *p_TOF;
  FB_OILPUMP *p_FB_OILPUMP;
  FB_SWITCH *p_FB_SWITCH;
  FB_SECTIONSWITCH *p_FB_SECTIONSWITCH;
  TYPE_BASKETSTATS *p_TYPE_BASKETSTATS;
  FB_MEANDR *p_FB_MEANDR;
  FB_SINGLESIGNAL *p_FB_SINGLESIGNAL;
  FB_SINGLEOUTPUT *p_FB_SINGLEOUTPUT;
  PROC_PROTECTIONS_INIT *p_PROC_PROTECTIONS_INIT;
  FB_DIPROTECTION_INIT *p_FB_DIPROTECTION_INIT;
  STRUCT_DIPROTECTION *p_STRUCT_DIPROTECTION;
  FB_AIPROTECTION_INIT *p_FB_AIPROTECTION_INIT;
  STRUCT_AIPROTECTION *p_STRUCT_AIPROTECTION;
  PROTECTIONSCONFIG *p_PROTECTIONSCONFIG;
  TYPE_PROTECTIONTAGS *p_TYPE_PROTECTIONTAGS;
  PROC_PROTECTION *p_PROC_PROTECTION;
  FB_MVPROTECTION *p_FB_MVPROTECTION;
  F_TRIG *p_F_TRIG;
  FB_DIPROTECTION *p_FB_DIPROTECTION;
  FB_KRANOPENPROTECTION *p_FB_KRANOPENPROTECTION;
  FB_AIPROTECTION *p_FB_AIPROTECTION;
  PROC_ALGORITMS *p_PROC_ALGORITMS;
  REMONTALG *p_REMONTALG;
  TYPE_MODEGPA *p_TYPE_MODEGPA;
  TYPE_COMMANDSPOTECTIONSMANAGER *p_TYPE_COMMANDSPOTECTIONSMANAGER;
  TESTPROTECTIONALG *p_TESTPROTECTIONALG;
  TESTIMALG *p_TESTIMALG;
  FB_AUTOTENALG *p_FB_AUTOTENALG;
  FB_AUTOPNSALG *p_FB_AUTOPNSALG;
  FB_AUTOAVOMALG *p_FB_AUTOAVOMALG;
  FB_VIBEGPNSALG *p_FB_VIBEGPNSALG;
  STRUCT_PHASEALGORITM *p_STRUCT_PHASEALGORITM;
  FB_PH_ALGORITM *p_FB_PH_ALGORITM;
  FB_PH_TIMER *p_FB_PH_TIMER;
  FB_QUESTION *p_FB_QUESTION;
  TYPE_ANSWERS *p_TYPE_ANSWERS;
  FB_PH_SWITCH *p_FB_PH_SWITCH;
  FB_PH_CUSTOMPHASE *p_FB_PH_CUSTOMPHASE;
  FB_AUTONUALG *p_FB_AUTONUALG;
  FB_PUSKOILSYSTEMALG *p_FB_PUSKOILSYSTEMALG;
  FB_PH_WAITANALOGVALUE *p_FB_PH_WAITANALOGVALUE;
  FB_PH_OILPUMP *p_FB_PH_OILPUMP;
  FB_ANTIPOMPAGALG *p_FB_ANTIPOMPAGALG;
  FB_TABLEVALUE_MIN *p_FB_TABLEVALUE_MIN;
  __IEC___ARRAY_OF_TYPE_TABLEREC_9_t *p___IEC___ARRAY_OF_TYPE_TABLEREC_9_t;
  TYPE_TABLEREC *p_TYPE_TABLEREC;
  FB_TABLEVALUE_MAX *p_FB_TABLEVALUE_MAX;
  FB_RASHODALG *p_FB_RASHODALG;
  FB_ZAPASALG *p_FB_ZAPASALG;
  NOALG *p_NOALG;
  FB_PH_KRAN *p_FB_PH_KRAN;
  FB_PH_SECTIONSWITCH *p_FB_PH_SECTIONSWITCH;
  AOALG *p_AOALG;
  PPUALG *p_PPUALG;
  FILLINGALG *p_FILLINGALG;
  FB_PH_DIPROTECTION *p_FB_PH_DIPROTECTION;
  ENGINERUNALG *p_ENGINERUNALG;
  PUSKKALG *p_PUSKKALG;
  PUSKVALG *p_PUSKVALG;
  TESTDPMGALG *p_TESTDPMGALG;
  TESTPMSALG *p_TESTPMSALG;
  FB_PH_AIPROTECTION *p_FB_PH_AIPROTECTION;
  APUSKALG *p_APUSKALG;
  SEMIAUTOPUSKALG *p_SEMIAUTOPUSKALG;
  PUSK_FIRST_FAZA1 *p_PUSK_FIRST_FAZA1;
  PUSK_FIRST_FAZA2 *p_PUSK_FIRST_FAZA2;
  PUSK_THIRD_FAZA *p_PUSK_THIRD_FAZA;
  PROV_PMS *p_PROV_PMS;
  PROV_OPRESSOVKA *p_PROV_OPRESSOVKA;
  PUSK_SECOND_FAZA_CHASTOTNY *p_PUSK_SECOND_FAZA_CHASTOTNY;
  PUSK_SECOND_FAZA_REACTOR *p_PUSK_SECOND_FAZA_REACTOR;
  FB_ALGORITMSMANAGER *p_FB_ALGORITMSMANAGER;
  FB_PROTECTIONSMANAGER *p_FB_PROTECTIONSMANAGER;

  { // 32721 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.VALUE
    st = getVariable(32721);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.VALUE", 55);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->VALUE;
    st->value_p = p_LREAL;
  }
  { // 32722 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.STATUS
    st = getVariable(32722);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.STATUS", 56);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_DWORD = (DWORD*)&p_STRUCT_AI->STATUS;
    st->value_p = p_DWORD;
  }
  { // 32723 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.INTERVAL
    st = getVariable(32723);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.INTERVAL", 58);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BYTE = (BYTE*)&p_STRUCT_AI->INTERVAL;
    st->value_p = p_BYTE;
  }
  { // 32724 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.INCOMMAND
    st = getVariable(32724);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.INCOMMAND", 59);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 32725 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.BLCONNECT
    st = getVariable(32725);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.BLCONNECT", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->BLCONNECT;
    st->value_p = p_BOOL;
  }
  { // 32726 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DLL
    st = getVariable(32726);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DLL", 53);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLL;
    st->value_p = p_LREAL;
  }
  { // 32727 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DHL
    st = getVariable(32727);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DHL", 53);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHL;
    st->value_p = p_LREAL;
  }
  { // 32728 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DLA
    st = getVariable(32728);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DLA", 53);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLA;
    st->value_p = p_LREAL;
  }
  { // 32729 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DHA
    st = getVariable(32729);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DHA", 53);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHA;
    st->value_p = p_LREAL;
  }
  { // 32730 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DLW
    st = getVariable(32730);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DLW", 53);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DLW;
    st->value_p = p_LREAL;
  }
  { // 32731 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DHW
    st = getVariable(32731);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DHW", 53);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DHW;
    st->value_p = p_LREAL;
  }
  { // 32732 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.LL
    st = getVariable(32732);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.LL", 52);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LL;
    st->value_p = p_LREAL;
  }
  { // 32733 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.HL
    st = getVariable(32733);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.HL", 52);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HL;
    st->value_p = p_LREAL;
  }
  { // 32734 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.LA
    st = getVariable(32734);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.LA", 52);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LA;
    st->value_p = p_LREAL;
  }
  { // 32735 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.HA
    st = getVariable(32735);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.HA", 52);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HA;
    st->value_p = p_LREAL;
  }
  { // 32736 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.LW
    st = getVariable(32736);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.LW", 52);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->LW;
    st->value_p = p_LREAL;
  }
  { // 32737 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.HW
    st = getVariable(32737);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.HW", 52);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HW;
    st->value_p = p_LREAL;
  }
  { // 32738 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.ISVALIDREF_LA
    st = getVariable(32738);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.ISVALIDREF_LA", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_LA;
    st->value_p = p_BOOL;
  }
  { // 32739 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.ISVALIDREF_HA
    st = getVariable(32739);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.ISVALIDREF_HA", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_HA;
    st->value_p = p_BOOL;
  }
  { // 32740 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.ISVALIDREF_LW
    st = getVariable(32740);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.ISVALIDREF_LW", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_LW;
    st->value_p = p_BOOL;
  }
  { // 32741 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.ISVALIDREF_HW
    st = getVariable(32741);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.ISVALIDREF_HW", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->ISVALIDREF_HW;
    st->value_p = p_BOOL;
  }
  { // 32742 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.INPLL
    st = getVariable(32742);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.INPLL", 55);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->INPLL;
    st->value_p = p_LREAL;
  }
  { // 32743 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.INPHL
    st = getVariable(32743);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.INPHL", 55);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->INPHL;
    st->value_p = p_LREAL;
  }
  { // 32744 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.CURRENTSHOTCIRCUIT
    st = getVariable(32744);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.CURRENTSHOTCIRCUIT", 68);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CURRENTSHOTCIRCUIT;
    st->value_p = p_LREAL;
  }
  { // 32745 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.CURRENTBREAKCIRCUIT
    st = getVariable(32745);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.CURRENTBREAKCIRCUIT", 69);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CURRENTBREAKCIRCUIT;
    st->value_p = p_LREAL;
  }
  { // 32746 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.MAXCHANGESPEED
    st = getVariable(32746);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.MAXCHANGESPEED", 64);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXCHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 32747 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.MAXCHANGESPEEDDOWN
    st = getVariable(32747);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.MAXCHANGESPEEDDOWN", 68);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXCHANGESPEEDDOWN;
    st->value_p = p_LREAL;
  }
  { // 32748 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.CHANGESPEED
    st = getVariable(32748);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.CHANGESPEED", 61);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->CHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 32749 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.HISTERESIS
    st = getVariable(32749);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.HISTERESIS", 60);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->HISTERESIS;
    st->value_p = p_LREAL;
  }
  { // 32750 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.APERTURFILTER
    st = getVariable(32750);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.APERTURFILTER", 63);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->APERTURFILTER;
    st->value_p = p_LREAL;
  }
  { // 32751 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.EXPONENTIALFILTER
    st = getVariable(32751);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.EXPONENTIALFILTER", 67);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->EXPONENTIALFILTER;
    st->value_p = p_LREAL;
  }
  { // 32752 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.RASSOGLASOVANIE
    st = getVariable(32752);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.RASSOGLASOVANIE", 65);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->RASSOGLASOVANIE;
    st->value_p = p_LREAL;
  }
  { // 32753 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.OPCCOMMANDSDISABLED
    st = getVariable(32753);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.OPCCOMMANDSDISABLED", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 32754 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DISABLED_LA
    st = getVariable(32754);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DISABLED_LA", 61);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_LA;
    st->value_p = p_BOOL;
  }
  { // 32755 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DISABLED_HA
    st = getVariable(32755);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DISABLED_HA", 61);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_HA;
    st->value_p = p_BOOL;
  }
  { // 32756 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DISABLED_LW
    st = getVariable(32756);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DISABLED_LW", 61);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_LW;
    st->value_p = p_BOOL;
  }
  { // 32757 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DISABLED_HW
    st = getVariable(32757);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DISABLED_HW", 61);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->DISABLED_HW;
    st->value_p = p_BOOL;
  }
  { // 32758 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DELAYLA
    st = getVariable(32758);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DELAYLA", 57);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYLA;
    st->value_p = p_TIME;
  }
  { // 32759 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DELAYLW
    st = getVariable(32759);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DELAYLW", 57);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYLW;
    st->value_p = p_TIME;
  }
  { // 32760 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DELAYHW
    st = getVariable(32760);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DELAYHW", 57);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYHW;
    st->value_p = p_TIME;
  }
  { // 32761 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DELAYHA
    st = getVariable(32761);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DELAYHA", 57);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_TIME = (TIME*)&p_STRUCT_AI->DELAYHA;
    st->value_p = p_TIME;
  }
  { // 32762 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.MINVALUE_ISVALIDREF
    st = getVariable(32762);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.MINVALUE_ISVALIDREF", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->MINVALUE_ISVALIDREF;
    st->value_p = p_BOOL;
  }
  { // 32763 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.MAXVALUE_ISVALIDREF
    st = getVariable(32763);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.MAXVALUE_ISVALIDREF", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->MAXVALUE_ISVALIDREF;
    st->value_p = p_BOOL;
  }
  { // 32764 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.MINVALUE
    st = getVariable(32764);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.MINVALUE", 58);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MINVALUE;
    st->value_p = p_LREAL;
  }
  { // 32765 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.MAXVALUE
    st = getVariable(32765);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.MAXVALUE", 58);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->MAXVALUE;
    st->value_p = p_LREAL;
  }
  { // 32766 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.INOPCCOMMANDSDISABLED
    st = getVariable(32766);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.INOPCCOMMANDSDISABLED", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 32767 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.IMIT
    st = getVariable(32767);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.IMIT", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->IMIT;
    st->value_p = p_BOOL;
  }
  { // 32768 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.REMONT
    st = getVariable(32768);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.REMONT", 56);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->REMONT;
    st->value_p = p_BOOL;
  }
  { // 32769 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.NS
    st = getVariable(32769);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.NS", 52);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS;
    st->value_p = p_BOOL;
  }
  { // 32770 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.NS_MIN
    st = getVariable(32770);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.NS_MIN", 56);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS_MIN;
    st->value_p = p_BOOL;
  }
  { // 32771 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.NS_MAX
    st = getVariable(32771);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.NS_MAX", 56);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_BOOL = (BOOL*)&p_STRUCT_AI->NS_MAX;
    st->value_p = p_BOOL;
  }
  { // 32772 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.INCOMMAND_ALG
    st = getVariable(32772);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.INCOMMAND_ALG", 63);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 32773 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.INCOMMAND_ARM
    st = getVariable(32773);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.INCOMMAND_ARM", 63);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_WORD = (WORD*)&p_STRUCT_AI->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 32774 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DMAXCHANGESPEED
    st = getVariable(32774);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DMAXCHANGESPEED", 65);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DMAXCHANGESPEED;
    st->value_p = p_LREAL;
  }
  { // 32775 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DMAXCHANGESPEEDDOWN
    st = getVariable(32775);
    memcpy(st->IEC_TYPE, "LREAL", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.AI.DMAXCHANGESPEEDDOWN", 69);
    st->size_data = sizeof(LREAL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AI = (STRUCT_AI*)&p_FB_AIPROTECTION->AI;
    p_LREAL = (LREAL*)&p_STRUCT_AI->DMAXCHANGESPEEDDOWN;
    st->value_p = p_LREAL;
  }
  { // 32776 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.CONTROLLIMIT
    st = getVariable(32776);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.CONTROLLIMIT", 66);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BYTE = (BYTE*)&p_STRUCT_AIPROTECTION->CONTROLLIMIT;
    st->value_p = p_BYTE;
  }
  { // 32777 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.DELAY
    st = getVariable(32777);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.DELAY", 59);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_TIME = (TIME*)&p_STRUCT_AIPROTECTION->DELAY;
    st->value_p = p_TIME;
  }
  { // 32778 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.INTAG
    st = getVariable(32778);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.INTAG", 59);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BYTE = (BYTE*)&p_STRUCT_AIPROTECTION->INTAG;
    st->value_p = p_BYTE;
  }
  { // 32779 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.INRUNONSTART
    st = getVariable(32779);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.INRUNONSTART", 66);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->INRUNONSTART;
    st->value_p = p_BOOL;
  }
  { // 32780 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.INCANRUN
    st = getVariable(32780);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.INCANRUN", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->INCANRUN;
    st->value_p = p_BOOL;
  }
  { // 32781 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.INOPCCOMMANDSDISABLED
    st = getVariable(32781);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.INOPCCOMMANDSDISABLED", 75);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 32782 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.INCOMMAND
    st = getVariable(32782);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.INCOMMAND", 63);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_WORD = (WORD*)&p_STRUCT_AIPROTECTION->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 32783 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.INCOMMAND_ALG
    st = getVariable(32783);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.INCOMMAND_ALG", 67);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_WORD = (WORD*)&p_STRUCT_AIPROTECTION->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 32784 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.INCOMMAND_ARM
    st = getVariable(32784);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.INCOMMAND_ARM", 67);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_WORD = (WORD*)&p_STRUCT_AIPROTECTION->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 32785 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.TAG
    st = getVariable(32785);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.TAG", 57);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BYTE = (BYTE*)&p_STRUCT_AIPROTECTION->TAG;
    st->value_p = p_BYTE;
  }
  { // 32786 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.STATUS
    st = getVariable(32786);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.STATUS", 60);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_DWORD = (DWORD*)&p_STRUCT_AIPROTECTION->STATUS;
    st->value_p = p_DWORD;
  }
  { // 32787 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.CANRUN
    st = getVariable(32787);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.CANRUN", 60);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->CANRUN;
    st->value_p = p_BOOL;
  }
  { // 32788 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.OPCCOMMANDSDISABLED
    st = getVariable(32788);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.OPCCOMMANDSDISABLED", 73);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 32789 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.ISRUNNING
    st = getVariable(32789);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.ISRUNNING", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->ISRUNNING;
    st->value_p = p_BOOL;
  }
  { // 32790 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.HASERROR
    st = getVariable(32790);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.HASERROR", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->HASERROR;
    st->value_p = p_BOOL;
  }
  { // 32791 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.ISENDED
    st = getVariable(32791);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.ISENDED", 61);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->ISENDED;
    st->value_p = p_BOOL;
  }
  { // 32792 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.REMONT
    st = getVariable(32792);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.REMONT", 60);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->REMONT;
    st->value_p = p_BOOL;
  }
  { // 32793 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.CHECK
    st = getVariable(32793);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.CHECK", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->CHECK;
    st->value_p = p_BOOL;
  }
  { // 32794 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.SIGNALING
    st = getVariable(32794);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.SIGNALING", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->SIGNALING;
    st->value_p = p_BOOL;
  }
  { // 32795 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.SIGNALINGTP
    st = getVariable(32795);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.SIGNALINGTP", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->SIGNALINGTP;
    st->value_p = p_BOOL;
  }
  { // 32796 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.RUNONSTART
    st = getVariable(32796);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.STRAIP.RUNONSTART", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_STRUCT_AIPROTECTION = (STRUCT_AIPROTECTION*)&p_FB_AIPROTECTION->STRAIP;
    p_BOOL = (BOOL*)&p_STRUCT_AIPROTECTION->RUNONSTART;
    st->value_p = p_BOOL;
  }
  { // 32801 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._SIGNALINGTP.IN
    st = getVariable(32801);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._SIGNALINGTP.IN", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    p_BOOL = (BOOL*)&p_TOF->IN;
    st->value_p = p_BOOL;
  }
  { // 32802 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._SIGNALINGTP.PT
    st = getVariable(32802);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._SIGNALINGTP.PT", 62);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    p_TIME = (TIME*)&p_TOF->PT;
    st->value_p = p_TIME;
  }
  { // 32803 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._SIGNALINGTP.Q
    st = getVariable(32803);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._SIGNALINGTP.Q", 61);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    p_BOOL = (BOOL*)&p_TOF->Q;
    st->value_p = p_BOOL;
  }
  { // 32804 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._SIGNALINGTP.ET
    st = getVariable(32804);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._SIGNALINGTP.ET", 62);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    p_TIME = (TIME*)&p_TOF->ET;
    st->value_p = p_TIME;
  }
  { // 32805 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._SIGNALINGTP
    st = getVariable(32805);
    memcpy(st->IEC_TYPE, "TOF", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._SIGNALINGTP", 59);
    st->size_data = sizeof(TOF);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TOF = (TOF*)&p_FB_AIPROTECTION->_SIGNALINGTP;
    st->value_p = (void *)p_TOF;
  }
  { // 32806 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._STATUSAI.NOTDEFINED
    st = getVariable(32806);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._STATUSAI.NOTDEFINED", 67);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NOTDEFINED;
    st->value_p = p_BYTE;
  }
  { // 32807 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._STATUSAI.LL
    st = getVariable(32807);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._STATUSAI.LL", 59);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LL;
    st->value_p = p_BYTE;
  }
  { // 32808 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._STATUSAI.HL
    st = getVariable(32808);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._STATUSAI.HL", 59);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HL;
    st->value_p = p_BYTE;
  }
  { // 32809 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._STATUSAI.NOTRELIABLE
    st = getVariable(32809);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._STATUSAI.NOTRELIABLE", 68);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NOTRELIABLE;
    st->value_p = p_BYTE;
  }
  { // 32810 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._STATUSAI.NORMAL
    st = getVariable(32810);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._STATUSAI.NORMAL", 63);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->NORMAL;
    st->value_p = p_BYTE;
  }
  { // 32811 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._STATUSAI.LW
    st = getVariable(32811);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._STATUSAI.LW", 59);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LW;
    st->value_p = p_BYTE;
  }
  { // 32812 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._STATUSAI.HW
    st = getVariable(32812);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._STATUSAI.HW", 59);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HW;
    st->value_p = p_BYTE;
  }
  { // 32813 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._STATUSAI.LA
    st = getVariable(32813);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._STATUSAI.LA", 59);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->LA;
    st->value_p = p_BYTE;
  }
  { // 32814 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._STATUSAI.HA
    st = getVariable(32814);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE._STATUSAI.HA", 59);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TYPE_STATUSAI = (TYPE_STATUSAI*)&p_FB_AIPROTECTION->_STATUSAI;
    p_BYTE = (BYTE*)&p_TYPE_STATUSAI->HA;
    st->value_p = p_BYTE;
  }
  { // 32815 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SOURCE
    st = getVariable(32815);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SOURCE", 53);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->SOURCE;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 32816 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.CMD
    st = getVariable(32816);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.CMD", 50);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->CMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 32817 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.LASTCMD
    st = getVariable(32817);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.LASTCMD", 54);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->LASTCMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 32818 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SOURCE_FOR_STATUS
    st = getVariable(32818);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SOURCE_FOR_STATUS", 64);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->SOURCE_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 32819 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.CMD_FOR_STATUS
    st = getVariable(32819);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.CMD_FOR_STATUS", 61);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->CMD_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 32820 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.COMMAND_ERROR_FOR_STATUS
    st = getVariable(32820);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.COMMAND_ERROR_FOR_STATUS", 71);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_BYTE = (BYTE*)&p_FB_AIPROTECTION->COMMAND_ERROR_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 32821 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.RESETCMDTIMER.IN
    st = getVariable(32821);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.RESETCMDTIMER.IN", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 32822 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.RESETCMDTIMER.PT
    st = getVariable(32822);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.RESETCMDTIMER.PT", 63);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 32823 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.RESETCMDTIMER.Q
    st = getVariable(32823);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.RESETCMDTIMER.Q", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 32824 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.RESETCMDTIMER.ET
    st = getVariable(32824);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.RESETCMDTIMER.ET", 63);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 32825 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.RESETCMDTIMER
    st = getVariable(32825);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.RESETCMDTIMER", 60);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TON = (TON*)&p_FB_AIPROTECTION->RESETCMDTIMER;
    st->value_p = (void *)p_TON;
  }
  { // 32826 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.RESETCMDTIMERPRIZNAK
    st = getVariable(32826);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.RESETCMDTIMERPRIZNAK", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_BOOL = (BOOL*)&p_FB_AIPROTECTION->RESETCMDTIMERPRIZNAK;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 32827 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SIGNALINTIMER.IN
    st = getVariable(32827);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SIGNALINTIMER.IN", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 32828 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SIGNALINTIMER.PT
    st = getVariable(32828);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SIGNALINTIMER.PT", 63);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 32829 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SIGNALINTIMER.Q
    st = getVariable(32829);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SIGNALINTIMER.Q", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 32830 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SIGNALINTIMER.ET
    st = getVariable(32830);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SIGNALINTIMER.ET", 63);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 32831 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SIGNALINTIMER
    st = getVariable(32831);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SIGNALINTIMER", 60);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TON = (TON*)&p_FB_AIPROTECTION->SIGNALINTIMER;
    st->value_p = (void *)p_TON;
  }
  { // 32832 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.TIMER.IN
    st = getVariable(32832);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.TIMER.IN", 55);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 32833 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.TIMER.PT
    st = getVariable(32833);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.TIMER.PT", 55);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 32834 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.TIMER.Q
    st = getVariable(32834);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.TIMER.Q", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 32835 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.TIMER.ET
    st = getVariable(32835);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.TIMER.ET", 55);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 32836 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.TIMER
    st = getVariable(32836);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.TIMER", 52);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_TON = (TON*)&p_FB_AIPROTECTION->TIMER;
    st->value_p = (void *)p_TON;
  }
  { // 32837 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SIGNALINGTRIG.CLK
    st = getVariable(32837);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SIGNALINGTRIG.CLK", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_R_TRIG = (R_TRIG*)&p_FB_AIPROTECTION->SIGNALINGTRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 32838 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SIGNALINGTRIG.Q
    st = getVariable(32838);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SIGNALINGTRIG.Q", 62);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_R_TRIG = (R_TRIG*)&p_FB_AIPROTECTION->SIGNALINGTRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 32839 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SIGNALINGTRIG
    st = getVariable(32839);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SIGNALINGTRIG", 60);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_R_TRIG = (R_TRIG*)&p_FB_AIPROTECTION->SIGNALINGTRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 32840 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SIGNALINGFTRIG.CLK
    st = getVariable(32840);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SIGNALINGFTRIG.CLK", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_F_TRIG = (F_TRIG*)&p_FB_AIPROTECTION->SIGNALINGFTRIG;
    p_BOOL = (BOOL*)&p_F_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 32841 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SIGNALINGFTRIG.Q
    st = getVariable(32841);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SIGNALINGFTRIG.Q", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_F_TRIG = (F_TRIG*)&p_FB_AIPROTECTION->SIGNALINGFTRIG;
    p_BOOL = (BOOL*)&p_F_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 32842 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SIGNALINGFTRIG
    st = getVariable(32842);
    memcpy(st->IEC_TYPE, "F_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SIGNALINGFTRIG", 61);
    st->size_data = sizeof(F_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_F_TRIG = (F_TRIG*)&p_FB_AIPROTECTION->SIGNALINGFTRIG;
    st->value_p = (void *)p_F_TRIG;
  }
  { // 32843 PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SIGNALINGAI
    st = getVariable(32843);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_PMASLO_SM_VYSOKOE.SIGNALINGAI", 58);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_AIPROTECTION = (FB_AIPROTECTION*)&p_PROC_PROTECTION->FB_PMASLO_SM_VYSOKOE;
    p_BOOL = (BOOL*)&p_FB_AIPROTECTION->SIGNALINGAI;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }

  return 0;
}

// clang-format on
