// clang-format off

#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include "POUS.h"
#include <beremiz/beremiz.h>

#include "iec_types_all.h"
#include "config1.h"

extern PROGRAM0 RESOURCE1__INSTANCE0;

#ifdef DEBUG_PLC
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err][%s:%d]: " _PRNTMSG "\n", __func__, __LINE__, ##__VA_ARGS__)
#else
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err]: " _PRNTMSG "\n", ##__VA_ARGS__)
#endif // DEBUG_PLC

void UnpackVar(void* varp, __IEC_types_enum vartype, void **value_p, void **f_value_p, uint8_t **flags);

int __variables_init_FB_EAO_PRU(){
  iec_var_t *st;

  PROGRAM0 *p_PROGRAM0;
  LREAL *p_LREAL;
  ULINT *p_ULINT;
  REAL *p_REAL;
  FB_TIMINGS *p_FB_TIMINGS;
  BOOL *p_BOOL;
  UINT *p_UINT;
  PROC_AI_INIT *p_PROC_AI_INIT;
  FB_AI_INIT *p_FB_AI_INIT;
  TIME *p_TIME;
  STRUCT_AI *p_STRUCT_AI;
  DWORD *p_DWORD;
  BYTE *p_BYTE;
  WORD *p_WORD;
  AICONFIG *p_AICONFIG;
  PROC_AI *p_PROC_AI;
  FB_AISOURCEMLP *p_FB_AISOURCEMLP;
  TITEMAIN *p_TITEMAIN;
  TITEMDIN *p_TITEMDIN;
  TYPE_STATUSAI *p_TYPE_STATUSAI;
  TYPE_COMMANDANALOG *p_TYPE_COMMANDANALOG;
  FB_SUNPACKERCOMMAND *p_FB_SUNPACKERCOMMAND;
  TYPE_ANALOGLIMITFLAGS *p_TYPE_ANALOGLIMITFLAGS;
  TON *p_TON;
  R_TRIG *p_R_TRIG;
  FB_AISOURCEMLP_TIMER *p_FB_AISOURCEMLP_TIMER;
  PROC_AO_INIT *p_PROC_AO_INIT;
  FB_AO_INIT *p_FB_AO_INIT;
  STRUCT_AO *p_STRUCT_AO;
  AOCONFIG *p_AOCONFIG;
  PROC_AO *p_PROC_AO;
  FB_AOSOURCEMLP *p_FB_AOSOURCEMLP;
  TDOUBLEDATA *p_TDOUBLEDATA;
  PROC_DI_INIT *p_PROC_DI_INIT;
  FB_DI_INIT *p_FB_DI_INIT;
  STRUCT_DI *p_STRUCT_DI;
  __IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t *p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t;
  TYPE_RELIABLEBIT *p_TYPE_RELIABLEBIT;
  DICONFIG *p_DICONFIG;
  PROC_DI *p_PROC_DI;
  FB_DISOURCEMLP *p_FB_DISOURCEMLP;
  INT *p_INT;
  UDINT *p_UDINT;
  PROC_DO_INIT *p_PROC_DO_INIT;
  FB_DO_INIT *p_FB_DO_INIT;
  STRUCT_DO *p_STRUCT_DO;
  __IEC___ARRAY_OF_BOOL_16_t *p___IEC___ARRAY_OF_BOOL_16_t;
  DOCONFIG *p_DOCONFIG;
  PROC_DO *p_PROC_DO;
  FB_DOSOURCEMLP *p_FB_DOSOURCEMLP;
  TWORDDATA *p_TWORDDATA;
  OPC_ALGORITMS_SET *p_OPC_ALGORITMS_SET;
  ALGORITMSCONFIG *p_ALGORITMSCONFIG;
  STRUCT_ALG *p_STRUCT_ALG;
  STRUCT_ALGORITMSMANAGER *p_STRUCT_ALGORITMSMANAGER;
  STRUCT_PROTECTIONSMANAGER *p_STRUCT_PROTECTIONSMANAGER;
  STRUCT_ALGTIMERS *p_STRUCT_ALGTIMERS;
  ALGORITMSQUESTIONS *p_ALGORITMSQUESTIONS;
  STRUCT_QUESTION *p_STRUCT_QUESTION;
  OPC_ALGORITMS_GET *p_OPC_ALGORITMS_GET;
  PROC_IM_INIT *p_PROC_IM_INIT;
  FB_KRAN_INIT *p_FB_KRAN_INIT;
  STRUCT_KRAN *p_STRUCT_KRAN;
  FB_SWITCH_INIT *p_FB_SWITCH_INIT;
  STRUCT_SWITCH *p_STRUCT_SWITCH;
  FB_OILPUMP_INIT *p_FB_OILPUMP_INIT;
  STRUCT_OILPUMP *p_STRUCT_OILPUMP;
  FB_SECTIONSWITCH_INIT *p_FB_SECTIONSWITCH_INIT;
  STRUCT_SECTIONSWITCH *p_STRUCT_SECTIONSWITCH;
  FB_ANALOGPARAMETR_INIT *p_FB_ANALOGPARAMETR_INIT;
  STRUCT_ANALOGPARAMETR *p_STRUCT_ANALOGPARAMETR;
  FB_DISCRETPARAMETR_INIT *p_FB_DISCRETPARAMETR_INIT;
  STRUCT_DISCRETPARAMETR *p_STRUCT_DISCRETPARAMETR;
  FB_SINGLESIGNAL_INIT *p_FB_SINGLESIGNAL_INIT;
  STRUCT_SINGLESIGNAL *p_STRUCT_SINGLESIGNAL;
  FB_SINGLEOUTPUT_INIT *p_FB_SINGLEOUTPUT_INIT;
  STRUCT_SINGLEOUTPUT *p_STRUCT_SINGLEOUTPUT;
  IMCONFIG *p_IMCONFIG;
  STRUCT_RESERVEIM *p_STRUCT_RESERVEIM;
  STRUCT_RESERVEIM2 *p_STRUCT_RESERVEIM2;
  IM_SINGLESIGNALS *p_IM_SINGLESIGNALS;
  IM_SINGLEOUTPUTS *p_IM_SINGLEOUTPUTS;
  PROC_IM *p_PROC_IM;
  FB_KRAN *p_FB_KRAN;
  TYPE_STATUSDUALINPUT *p_TYPE_STATUSDUALINPUT;
  TYPE_COMMANDDUALINPUT *p_TYPE_COMMANDDUALINPUT;
  TOF *p_TOF;
  FB_OILPUMP *p_FB_OILPUMP;
  FB_SWITCH *p_FB_SWITCH;
  FB_SECTIONSWITCH *p_FB_SECTIONSWITCH;
  TYPE_BASKETSTATS *p_TYPE_BASKETSTATS;
  FB_MEANDR *p_FB_MEANDR;
  FB_SINGLESIGNAL *p_FB_SINGLESIGNAL;
  FB_SINGLEOUTPUT *p_FB_SINGLEOUTPUT;
  FB_DISCRETPARAMETR *p_FB_DISCRETPARAMETR;
  FB_ANALOGPARAMETR *p_FB_ANALOGPARAMETR;
  OPC_IM_GET *p_OPC_IM_GET;
  OPC_IM_SET *p_OPC_IM_SET;
  PROC_PROTECTIONS_INIT *p_PROC_PROTECTIONS_INIT;
  FB_DIPROTECTION_INIT *p_FB_DIPROTECTION_INIT;
  STRUCT_DIPROTECTION *p_STRUCT_DIPROTECTION;
  FB_AIPROTECTION_INIT *p_FB_AIPROTECTION_INIT;
  STRUCT_AIPROTECTION *p_STRUCT_AIPROTECTION;
  PROTECTIONSCONFIG *p_PROTECTIONSCONFIG;
  TYPE_PROTECTIONTAGS *p_TYPE_PROTECTIONTAGS;
  PROC_PROTECTION *p_PROC_PROTECTION;
  FB_DIPROTECTION *p_FB_DIPROTECTION;
  F_TRIG *p_F_TRIG;
  FB_MVPROTECTION *p_FB_MVPROTECTION;
  FB_KRANOPENPROTECTION *p_FB_KRANOPENPROTECTION;
  FB_AIPROTECTION *p_FB_AIPROTECTION;
  PROC_ALGORITMS *p_PROC_ALGORITMS;
  REMONTALG *p_REMONTALG;
  TYPE_MODEGPA *p_TYPE_MODEGPA;
  TYPE_COMMANDSPOTECTIONSMANAGER *p_TYPE_COMMANDSPOTECTIONSMANAGER;
  TESTPROTECTIONALG *p_TESTPROTECTIONALG;
  TESTIMALG *p_TESTIMALG;
  FB_AUTOTENALG *p_FB_AUTOTENALG;
  FB_AUTOPNSALG *p_FB_AUTOPNSALG;
  FB_AUTOAVOMALG *p_FB_AUTOAVOMALG;
  FB_VIBEGPNSALG *p_FB_VIBEGPNSALG;
  STRUCT_PHASEALGORITM *p_STRUCT_PHASEALGORITM;
  FB_PH_ALGORITM *p_FB_PH_ALGORITM;
  FB_PH_TIMER *p_FB_PH_TIMER;
  FB_QUESTION *p_FB_QUESTION;
  TYPE_ANSWERS *p_TYPE_ANSWERS;
  FB_PH_SWITCH *p_FB_PH_SWITCH;
  FB_PH_CUSTOMPHASE *p_FB_PH_CUSTOMPHASE;
  FB_AUTONUALG *p_FB_AUTONUALG;
  FB_PUSKOILSYSTEMALG *p_FB_PUSKOILSYSTEMALG;
  FB_PH_WAITANALOGVALUE *p_FB_PH_WAITANALOGVALUE;
  FB_PH_OILPUMP *p_FB_PH_OILPUMP;
  FB_ANTIPOMPAGALG *p_FB_ANTIPOMPAGALG;
  FB_TABLEVALUE_MIN *p_FB_TABLEVALUE_MIN;
  __IEC___ARRAY_OF_TYPE_TABLEREC_9_t *p___IEC___ARRAY_OF_TYPE_TABLEREC_9_t;
  TYPE_TABLEREC *p_TYPE_TABLEREC;
  FB_TABLEVALUE_MAX *p_FB_TABLEVALUE_MAX;
  FB_RASHODALG *p_FB_RASHODALG;
  FB_ZAPASALG *p_FB_ZAPASALG;
  NOALG *p_NOALG;
  FB_PH_KRAN *p_FB_PH_KRAN;
  FB_PH_SECTIONSWITCH *p_FB_PH_SECTIONSWITCH;
  AOALG *p_AOALG;
  PPUALG *p_PPUALG;
  FILLINGALG *p_FILLINGALG;
  FB_PH_DIPROTECTION *p_FB_PH_DIPROTECTION;
  ENGINERUNALG *p_ENGINERUNALG;
  PUSKKALG *p_PUSKKALG;
  PUSKVALG *p_PUSKVALG;
  TESTDPMGALG *p_TESTDPMGALG;
  TESTPMSALG *p_TESTPMSALG;
  FB_PH_AIPROTECTION *p_FB_PH_AIPROTECTION;
  APUSKALG *p_APUSKALG;
  SEMIAUTOPUSKALG *p_SEMIAUTOPUSKALG;
  FB_ALGORITMSMANAGER *p_FB_ALGORITMSMANAGER;
  FB_PROTECTIONSMANAGER *p_FB_PROTECTIONSMANAGER;

  { // 30892 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.DI.RELIABILITY
    st = getVariable(30892);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.DI.RELIABILITY", 51);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_SINGLESIGNAL = (STRUCT_SINGLESIGNAL*)&p_FB_DIPROTECTION->DI;
    p_BOOL = (BOOL*)&p_STRUCT_SINGLESIGNAL->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 30893 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.DI.INVERSE
    st = getVariable(30893);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.DI.INVERSE", 47);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_SINGLESIGNAL = (STRUCT_SINGLESIGNAL*)&p_FB_DIPROTECTION->DI;
    p_BOOL = (BOOL*)&p_STRUCT_SINGLESIGNAL->INVERSE;
    st->value_p = p_BOOL;
  }
  { // 30894 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.DI.DELAYON
    st = getVariable(30894);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.DI.DELAYON", 47);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_SINGLESIGNAL = (STRUCT_SINGLESIGNAL*)&p_FB_DIPROTECTION->DI;
    p_TIME = (TIME*)&p_STRUCT_SINGLESIGNAL->DELAYON;
    st->value_p = p_TIME;
  }
  { // 30895 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.DI.DELAYOFF
    st = getVariable(30895);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.DI.DELAYOFF", 48);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_SINGLESIGNAL = (STRUCT_SINGLESIGNAL*)&p_FB_DIPROTECTION->DI;
    p_TIME = (TIME*)&p_STRUCT_SINGLESIGNAL->DELAYOFF;
    st->value_p = p_TIME;
  }
  { // 30896 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.DI.Q
    st = getVariable(30896);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.DI.Q", 41);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_SINGLESIGNAL = (STRUCT_SINGLESIGNAL*)&p_FB_DIPROTECTION->DI;
    p_BOOL = (BOOL*)&p_STRUCT_SINGLESIGNAL->Q;
    st->value_p = p_BOOL;
  }
  { // 30897 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.DI.STATUS
    st = getVariable(30897);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.DI.STATUS", 46);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_SINGLESIGNAL = (STRUCT_SINGLESIGNAL*)&p_FB_DIPROTECTION->DI;
    p_DWORD = (DWORD*)&p_STRUCT_SINGLESIGNAL->STATUS;
    st->value_p = p_DWORD;
  }
  { // 30898 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.DI.DISABLED_SIG
    st = getVariable(30898);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.DI.DISABLED_SIG", 52);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_SINGLESIGNAL = (STRUCT_SINGLESIGNAL*)&p_FB_DIPROTECTION->DI;
    p_BOOL = (BOOL*)&p_STRUCT_SINGLESIGNAL->DISABLED_SIG;
    st->value_p = p_BOOL;
  }
  { // 30899 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.DELAY
    st = getVariable(30899);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.DELAY", 49);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_TIME = (TIME*)&p_STRUCT_DIPROTECTION->DELAY;
    st->value_p = p_TIME;
  }
  { // 30900 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.INTAG
    st = getVariable(30900);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.INTAG", 49);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BYTE = (BYTE*)&p_STRUCT_DIPROTECTION->INTAG;
    st->value_p = p_BYTE;
  }
  { // 30901 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.INRUNONSTART
    st = getVariable(30901);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.INRUNONSTART", 56);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->INRUNONSTART;
    st->value_p = p_BOOL;
  }
  { // 30902 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.INCANRUN
    st = getVariable(30902);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.INCANRUN", 52);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->INCANRUN;
    st->value_p = p_BOOL;
  }
  { // 30903 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.INOPCCOMMANDSDISABLED
    st = getVariable(30903);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.INOPCCOMMANDSDISABLED", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 30904 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.INCOMMAND
    st = getVariable(30904);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.INCOMMAND", 53);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_WORD = (WORD*)&p_STRUCT_DIPROTECTION->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 30905 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.INCOMMAND_ALG
    st = getVariable(30905);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.INCOMMAND_ALG", 57);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_WORD = (WORD*)&p_STRUCT_DIPROTECTION->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 30906 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.INCOMMAND_ARM
    st = getVariable(30906);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.INCOMMAND_ARM", 57);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_WORD = (WORD*)&p_STRUCT_DIPROTECTION->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 30907 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.TAG
    st = getVariable(30907);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.TAG", 47);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BYTE = (BYTE*)&p_STRUCT_DIPROTECTION->TAG;
    st->value_p = p_BYTE;
  }
  { // 30908 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.STATUS
    st = getVariable(30908);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.STATUS", 50);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_DWORD = (DWORD*)&p_STRUCT_DIPROTECTION->STATUS;
    st->value_p = p_DWORD;
  }
  { // 30909 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.CANRUN
    st = getVariable(30909);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.CANRUN", 50);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->CANRUN;
    st->value_p = p_BOOL;
  }
  { // 30910 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.OPCCOMMANDSDISABLED
    st = getVariable(30910);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.OPCCOMMANDSDISABLED", 63);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 30911 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.ISRUNNING
    st = getVariable(30911);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.ISRUNNING", 53);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->ISRUNNING;
    st->value_p = p_BOOL;
  }
  { // 30912 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.HASERROR
    st = getVariable(30912);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.HASERROR", 52);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->HASERROR;
    st->value_p = p_BOOL;
  }
  { // 30913 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.ISENDED
    st = getVariable(30913);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.ISENDED", 51);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->ISENDED;
    st->value_p = p_BOOL;
  }
  { // 30914 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.REMONT
    st = getVariable(30914);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.REMONT", 50);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->REMONT;
    st->value_p = p_BOOL;
  }
  { // 30915 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.CHECK
    st = getVariable(30915);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.CHECK", 49);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->CHECK;
    st->value_p = p_BOOL;
  }
  { // 30916 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.SIGNALING
    st = getVariable(30916);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.SIGNALING", 53);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->SIGNALING;
    st->value_p = p_BOOL;
  }
  { // 30917 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.SIGNALINGTP
    st = getVariable(30917);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.SIGNALINGTP", 55);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->SIGNALINGTP;
    st->value_p = p_BOOL;
  }
  { // 30918 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.RUNONSTART
    st = getVariable(30918);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.STRDIP.RUNONSTART", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_STRUCT_DIPROTECTION = (STRUCT_DIPROTECTION*)&p_FB_DIPROTECTION->STRDIP;
    p_BOOL = (BOOL*)&p_STRUCT_DIPROTECTION->RUNONSTART;
    st->value_p = p_BOOL;
  }
  { // 30923 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU._PROTECTIONTAGS.NOTHING
    st = getVariable(30923);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU._PROTECTIONTAGS.NOTHING", 60);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_TYPE_PROTECTIONTAGS = (TYPE_PROTECTIONTAGS*)&p_FB_DIPROTECTION->_PROTECTIONTAGS;
    p_BYTE = (BYTE*)&p_TYPE_PROTECTIONTAGS->NOTHING;
    st->value_p = p_BYTE;
  }
  { // 30924 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU._PROTECTIONTAGS.AOB
    st = getVariable(30924);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU._PROTECTIONTAGS.AOB", 56);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_TYPE_PROTECTIONTAGS = (TYPE_PROTECTIONTAGS*)&p_FB_DIPROTECTION->_PROTECTIONTAGS;
    p_BYTE = (BYTE*)&p_TYPE_PROTECTIONTAGS->AOB;
    st->value_p = p_BYTE;
  }
  { // 30925 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU._PROTECTIONTAGS.AOS
    st = getVariable(30925);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU._PROTECTIONTAGS.AOS", 56);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_TYPE_PROTECTIONTAGS = (TYPE_PROTECTIONTAGS*)&p_FB_DIPROTECTION->_PROTECTIONTAGS;
    p_BYTE = (BYTE*)&p_TYPE_PROTECTIONTAGS->AOS;
    st->value_p = p_BYTE;
  }
  { // 30926 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU._PROTECTIONTAGS.AOPOJ
    st = getVariable(30926);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU._PROTECTIONTAGS.AOPOJ", 58);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_TYPE_PROTECTIONTAGS = (TYPE_PROTECTIONTAGS*)&p_FB_DIPROTECTION->_PROTECTIONTAGS;
    p_BYTE = (BYTE*)&p_TYPE_PROTECTIONTAGS->AOPOJ;
    st->value_p = p_BYTE;
  }
  { // 30927 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU._SIGNALINGTP.IN
    st = getVariable(30927);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU._SIGNALINGTP.IN", 52);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_TOF = (TOF*)&p_FB_DIPROTECTION->_SIGNALINGTP;
    p_BOOL = (BOOL*)&p_TOF->IN;
    st->value_p = p_BOOL;
  }
  { // 30928 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU._SIGNALINGTP.PT
    st = getVariable(30928);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU._SIGNALINGTP.PT", 52);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_TOF = (TOF*)&p_FB_DIPROTECTION->_SIGNALINGTP;
    p_TIME = (TIME*)&p_TOF->PT;
    st->value_p = p_TIME;
  }
  { // 30929 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU._SIGNALINGTP.Q
    st = getVariable(30929);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU._SIGNALINGTP.Q", 51);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_TOF = (TOF*)&p_FB_DIPROTECTION->_SIGNALINGTP;
    p_BOOL = (BOOL*)&p_TOF->Q;
    st->value_p = p_BOOL;
  }
  { // 30930 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU._SIGNALINGTP.ET
    st = getVariable(30930);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU._SIGNALINGTP.ET", 52);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_TOF = (TOF*)&p_FB_DIPROTECTION->_SIGNALINGTP;
    p_TIME = (TIME*)&p_TOF->ET;
    st->value_p = p_TIME;
  }
  { // 30931 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU._SIGNALINGTP
    st = getVariable(30931);
    memcpy(st->IEC_TYPE, "TOF", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU._SIGNALINGTP", 49);
    st->size_data = sizeof(TOF);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_TOF = (TOF*)&p_FB_DIPROTECTION->_SIGNALINGTP;
    st->value_p = (void *)p_TOF;
  }
  { // 30932 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.TIMER.IN
    st = getVariable(30932);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.TIMER.IN", 45);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_TON = (TON*)&p_FB_DIPROTECTION->TIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 30933 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.TIMER.PT
    st = getVariable(30933);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.TIMER.PT", 45);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_TON = (TON*)&p_FB_DIPROTECTION->TIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 30934 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.TIMER.Q
    st = getVariable(30934);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.TIMER.Q", 44);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_TON = (TON*)&p_FB_DIPROTECTION->TIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 30935 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.TIMER.ET
    st = getVariable(30935);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.TIMER.ET", 45);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_TON = (TON*)&p_FB_DIPROTECTION->TIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 30936 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.TIMER
    st = getVariable(30936);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.TIMER", 42);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_TON = (TON*)&p_FB_DIPROTECTION->TIMER;
    st->value_p = (void *)p_TON;
  }
  { // 30937 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SIGNALINGTRIG.CLK
    st = getVariable(30937);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SIGNALINGTRIG.CLK", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_R_TRIG = (R_TRIG*)&p_FB_DIPROTECTION->SIGNALINGTRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 30938 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SIGNALINGTRIG.Q
    st = getVariable(30938);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SIGNALINGTRIG.Q", 52);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_R_TRIG = (R_TRIG*)&p_FB_DIPROTECTION->SIGNALINGTRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 30939 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SIGNALINGTRIG
    st = getVariable(30939);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SIGNALINGTRIG", 50);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_R_TRIG = (R_TRIG*)&p_FB_DIPROTECTION->SIGNALINGTRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 30940 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SIGNALINGFTRIG.CLK
    st = getVariable(30940);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SIGNALINGFTRIG.CLK", 55);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_F_TRIG = (F_TRIG*)&p_FB_DIPROTECTION->SIGNALINGFTRIG;
    p_BOOL = (BOOL*)&p_F_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 30941 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SIGNALINGFTRIG.Q
    st = getVariable(30941);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SIGNALINGFTRIG.Q", 53);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_F_TRIG = (F_TRIG*)&p_FB_DIPROTECTION->SIGNALINGFTRIG;
    p_BOOL = (BOOL*)&p_F_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 30942 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SIGNALINGFTRIG
    st = getVariable(30942);
    memcpy(st->IEC_TYPE, "F_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SIGNALINGFTRIG", 51);
    st->size_data = sizeof(F_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_F_TRIG = (F_TRIG*)&p_FB_DIPROTECTION->SIGNALINGFTRIG;
    st->value_p = (void *)p_F_TRIG;
  }
  { // 30943 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SIGNALINGDI
    st = getVariable(30943);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SIGNALINGDI", 48);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_BOOL = (BOOL*)&p_FB_DIPROTECTION->SIGNALINGDI;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 30944 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SOURCE
    st = getVariable(30944);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SOURCE", 43);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_BYTE = (BYTE*)&p_FB_DIPROTECTION->SOURCE;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 30945 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.CMD
    st = getVariable(30945);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.CMD", 40);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_BYTE = (BYTE*)&p_FB_DIPROTECTION->CMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 30946 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.LASTCMD
    st = getVariable(30946);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.LASTCMD", 44);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_BYTE = (BYTE*)&p_FB_DIPROTECTION->LASTCMD;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 30947 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SOURCE_FOR_STATUS
    st = getVariable(30947);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SOURCE_FOR_STATUS", 54);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_BYTE = (BYTE*)&p_FB_DIPROTECTION->SOURCE_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 30948 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.CMD_FOR_STATUS
    st = getVariable(30948);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.CMD_FOR_STATUS", 51);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_BYTE = (BYTE*)&p_FB_DIPROTECTION->CMD_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 30949 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.COMMAND_ERROR_FOR_STATUS
    st = getVariable(30949);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.COMMAND_ERROR_FOR_STATUS", 61);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_BYTE = (BYTE*)&p_FB_DIPROTECTION->COMMAND_ERROR_FOR_STATUS;
    UnpackVar(p_BYTE, BYTE_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 30950 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.RESETCMDTIMER.IN
    st = getVariable(30950);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.RESETCMDTIMER.IN", 53);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_TON = (TON*)&p_FB_DIPROTECTION->RESETCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 30951 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.RESETCMDTIMER.PT
    st = getVariable(30951);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.RESETCMDTIMER.PT", 53);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_TON = (TON*)&p_FB_DIPROTECTION->RESETCMDTIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 30952 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.RESETCMDTIMER.Q
    st = getVariable(30952);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.RESETCMDTIMER.Q", 52);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_TON = (TON*)&p_FB_DIPROTECTION->RESETCMDTIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 30953 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.RESETCMDTIMER.ET
    st = getVariable(30953);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.RESETCMDTIMER.ET", 53);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_TON = (TON*)&p_FB_DIPROTECTION->RESETCMDTIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 30954 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.RESETCMDTIMER
    st = getVariable(30954);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.RESETCMDTIMER", 50);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_TON = (TON*)&p_FB_DIPROTECTION->RESETCMDTIMER;
    st->value_p = (void *)p_TON;
  }
  { // 30955 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.RESETCMDTIMERPRIZNAK
    st = getVariable(30955);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.RESETCMDTIMERPRIZNAK", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_BOOL = (BOOL*)&p_FB_DIPROTECTION->RESETCMDTIMERPRIZNAK;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 30956 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SIGNALINTIMER.IN
    st = getVariable(30956);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SIGNALINTIMER.IN", 53);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_TON = (TON*)&p_FB_DIPROTECTION->SIGNALINTIMER;
    p_BOOL = (BOOL*)&p_TON->IN;
    st->value_p = p_BOOL;
  }
  { // 30957 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SIGNALINTIMER.PT
    st = getVariable(30957);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SIGNALINTIMER.PT", 53);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_TON = (TON*)&p_FB_DIPROTECTION->SIGNALINTIMER;
    p_TIME = (TIME*)&p_TON->PT;
    st->value_p = p_TIME;
  }
  { // 30958 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SIGNALINTIMER.Q
    st = getVariable(30958);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SIGNALINTIMER.Q", 52);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_TON = (TON*)&p_FB_DIPROTECTION->SIGNALINTIMER;
    p_BOOL = (BOOL*)&p_TON->Q;
    st->value_p = p_BOOL;
  }
  { // 30959 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SIGNALINTIMER.ET
    st = getVariable(30959);
    memcpy(st->IEC_TYPE, "TIME", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SIGNALINTIMER.ET", 53);
    st->size_data = sizeof(TIME);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_TON = (TON*)&p_FB_DIPROTECTION->SIGNALINTIMER;
    p_TIME = (TIME*)&p_TON->ET;
    st->value_p = p_TIME;
  }
  { // 30960 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SIGNALINTIMER
    st = getVariable(30960);
    memcpy(st->IEC_TYPE, "TON", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.SIGNALINTIMER", 50);
    st->size_data = sizeof(TON);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_TON = (TON*)&p_FB_DIPROTECTION->SIGNALINTIMER;
    st->value_p = (void *)p_TON;
  }
  { // 30961 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.RUNONSTART_TRIG.CLK
    st = getVariable(30961);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.RUNONSTART_TRIG.CLK", 56);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_R_TRIG = (R_TRIG*)&p_FB_DIPROTECTION->RUNONSTART_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 30962 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.RUNONSTART_TRIG.Q
    st = getVariable(30962);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.RUNONSTART_TRIG.Q", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_R_TRIG = (R_TRIG*)&p_FB_DIPROTECTION->RUNONSTART_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 30963 PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.RUNONSTART_TRIG
    st = getVariable(30963);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.PROTECTIONS_PROC.FB_EAO_PRU.RUNONSTART_TRIG", 52);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_PROTECTION = (PROC_PROTECTION*)&p_PROGRAM0->PROTECTIONS_PROC;
    p_FB_DIPROTECTION = (FB_DIPROTECTION*)&p_PROC_PROTECTION->FB_EAO_PRU;
    p_R_TRIG = (R_TRIG*)&p_FB_DIPROTECTION->RUNONSTART_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }

  return 0;
}

// clang-format on
