// clang-format off

#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include "POUS.h"
#include <beremiz/beremiz.h>

#include "iec_types_all.h"
#include "config1.h"

extern PROGRAM0 RESOURCE1__INSTANCE0;

#ifdef DEBUG_PLC
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err][%s:%d]: " _PRNTMSG "\n", __func__, __LINE__, ##__VA_ARGS__)
#else
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err]: " _PRNTMSG "\n", ##__VA_ARGS__)
#endif // DEBUG_PLC

void UnpackVar(void* varp, __IEC_types_enum vartype, void **value_p, void **f_value_p, uint8_t **flags);

int __variables_init_FB_AVOM3OFF(){
  iec_var_t *st;

  PROGRAM0 *p_PROGRAM0;
  LREAL *p_LREAL;
  ULINT *p_ULINT;
  REAL *p_REAL;
  FB_TIMINGS *p_FB_TIMINGS;
  BOOL *p_BOOL;
  UINT *p_UINT;
  PROC_AI_INIT *p_PROC_AI_INIT;
  FB_AI_INIT *p_FB_AI_INIT;
  STRUCT_AI *p_STRUCT_AI;
  DWORD *p_DWORD;
  BYTE *p_BYTE;
  WORD *p_WORD;
  TIME *p_TIME;
  AICONFIG *p_AICONFIG;
  PROC_AI *p_PROC_AI;
  FB_AISOURCEMLP *p_FB_AISOURCEMLP;
  TITEMAIN *p_TITEMAIN;
  TITEMDIN *p_TITEMDIN;
  TYPE_STATUSAI *p_TYPE_STATUSAI;
  TYPE_COMMANDANALOG *p_TYPE_COMMANDANALOG;
  FB_SUNPACKERCOMMAND *p_FB_SUNPACKERCOMMAND;
  TYPE_ANALOGLIMITFLAGS *p_TYPE_ANALOGLIMITFLAGS;
  TON *p_TON;
  R_TRIG *p_R_TRIG;
  FB_AISOURCEMLP_TIMER *p_FB_AISOURCEMLP_TIMER;
  PROC_AO_INIT *p_PROC_AO_INIT;
  FB_AO_INIT *p_FB_AO_INIT;
  STRUCT_AO *p_STRUCT_AO;
  AOCONFIG *p_AOCONFIG;
  PROC_AO *p_PROC_AO;
  FB_AOSOURCEMLP *p_FB_AOSOURCEMLP;
  TDOUBLEDATA *p_TDOUBLEDATA;
  PROC_DI_INIT *p_PROC_DI_INIT;
  FB_DI_INIT *p_FB_DI_INIT;
  STRUCT_DI *p_STRUCT_DI;
  __IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t *p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t;
  TYPE_RELIABLEBIT *p_TYPE_RELIABLEBIT;
  DICONFIG *p_DICONFIG;
  PROC_DI *p_PROC_DI;
  FB_DISOURCEMLP *p_FB_DISOURCEMLP;
  INT *p_INT;
  UDINT *p_UDINT;
  PROC_DO_INIT *p_PROC_DO_INIT;
  FB_DO_INIT *p_FB_DO_INIT;
  STRUCT_DO *p_STRUCT_DO;
  DOCONFIG *p_DOCONFIG;
  PROC_DO *p_PROC_DO;
  FB_DOSOURCEMLP *p_FB_DOSOURCEMLP;
  TWORDDATA *p_TWORDDATA;
  OPC_ALGORITMS_SET *p_OPC_ALGORITMS_SET;
  ALGORITMSCONFIG *p_ALGORITMSCONFIG;
  STRUCT_ALG *p_STRUCT_ALG;
  STRUCT_ALGORITMSMANAGER *p_STRUCT_ALGORITMSMANAGER;
  STRUCT_PROTECTIONSMANAGER *p_STRUCT_PROTECTIONSMANAGER;
  STRUCT_ALGTIMERS *p_STRUCT_ALGTIMERS;
  ALGORITMSQUESTIONS *p_ALGORITMSQUESTIONS;
  STRUCT_QUESTION *p_STRUCT_QUESTION;
  OPC_ALGORITMS_GET *p_OPC_ALGORITMS_GET;
  PROC_IM_INIT *p_PROC_IM_INIT;
  FB_KRAN_INIT *p_FB_KRAN_INIT;
  STRUCT_KRAN *p_STRUCT_KRAN;
  FB_SWITCH_INIT *p_FB_SWITCH_INIT;
  STRUCT_SWITCH *p_STRUCT_SWITCH;
  FB_OILPUMP_INIT *p_FB_OILPUMP_INIT;
  STRUCT_OILPUMP *p_STRUCT_OILPUMP;
  FB_SECTIONSWITCH_INIT *p_FB_SECTIONSWITCH_INIT;
  STRUCT_SECTIONSWITCH *p_STRUCT_SECTIONSWITCH;
  FB_ANALOGPARAMETR_INIT *p_FB_ANALOGPARAMETR_INIT;
  STRUCT_ANALOGPARAMETR *p_STRUCT_ANALOGPARAMETR;
  FB_DISCRETPARAMETR_INIT *p_FB_DISCRETPARAMETR_INIT;
  STRUCT_DISCRETPARAMETR *p_STRUCT_DISCRETPARAMETR;
  FB_SINGLESIGNAL_INIT *p_FB_SINGLESIGNAL_INIT;
  STRUCT_SINGLESIGNAL *p_STRUCT_SINGLESIGNAL;
  FB_SINGLEOUTPUT_INIT *p_FB_SINGLEOUTPUT_INIT;
  STRUCT_SINGLEOUTPUT *p_STRUCT_SINGLEOUTPUT;
  IMCONFIG *p_IMCONFIG;
  STRUCT_RESERVEIM *p_STRUCT_RESERVEIM;
  STRUCT_RESERVEIM2 *p_STRUCT_RESERVEIM2;
  IM_SINGLESIGNALS *p_IM_SINGLESIGNALS;
  IM_SINGLEOUTPUTS *p_IM_SINGLEOUTPUTS;
  PROC_IM *p_PROC_IM;
  FB_KRAN *p_FB_KRAN;
  TYPE_STATUSDUALINPUT *p_TYPE_STATUSDUALINPUT;
  TYPE_COMMANDDUALINPUT *p_TYPE_COMMANDDUALINPUT;
  TOF *p_TOF;
  FB_OILPUMP *p_FB_OILPUMP;
  FB_SWITCH *p_FB_SWITCH;
  FB_SECTIONSWITCH *p_FB_SECTIONSWITCH;
  TYPE_BASKETSTATS *p_TYPE_BASKETSTATS;
  FB_MEANDR *p_FB_MEANDR;
  FB_SINGLESIGNAL *p_FB_SINGLESIGNAL;
  FB_SINGLEOUTPUT *p_FB_SINGLEOUTPUT;
  PROC_PROTECTIONS_INIT *p_PROC_PROTECTIONS_INIT;
  FB_DIPROTECTION_INIT *p_FB_DIPROTECTION_INIT;
  STRUCT_DIPROTECTION *p_STRUCT_DIPROTECTION;
  FB_AIPROTECTION_INIT *p_FB_AIPROTECTION_INIT;
  STRUCT_AIPROTECTION *p_STRUCT_AIPROTECTION;
  PROTECTIONSCONFIG *p_PROTECTIONSCONFIG;
  TYPE_PROTECTIONTAGS *p_TYPE_PROTECTIONTAGS;
  PROC_PROTECTION *p_PROC_PROTECTION;
  FB_MVPROTECTION *p_FB_MVPROTECTION;
  F_TRIG *p_F_TRIG;
  FB_DIPROTECTION *p_FB_DIPROTECTION;
  FB_KRANOPENPROTECTION *p_FB_KRANOPENPROTECTION;
  FB_AIPROTECTION *p_FB_AIPROTECTION;
  PROC_ALGORITMS *p_PROC_ALGORITMS;
  REMONTALG *p_REMONTALG;
  TYPE_MODEGPA *p_TYPE_MODEGPA;
  TYPE_COMMANDSPOTECTIONSMANAGER *p_TYPE_COMMANDSPOTECTIONSMANAGER;
  TESTPROTECTIONALG *p_TESTPROTECTIONALG;
  TESTIMALG *p_TESTIMALG;
  FB_AUTOTENALG *p_FB_AUTOTENALG;
  FB_AUTOPNSALG *p_FB_AUTOPNSALG;
  FB_AUTOAVOMALG *p_FB_AUTOAVOMALG;
  FB_VIBEGPNSALG *p_FB_VIBEGPNSALG;
  STRUCT_PHASEALGORITM *p_STRUCT_PHASEALGORITM;
  FB_PH_ALGORITM *p_FB_PH_ALGORITM;
  FB_PH_TIMER *p_FB_PH_TIMER;
  FB_QUESTION *p_FB_QUESTION;
  TYPE_ANSWERS *p_TYPE_ANSWERS;
  FB_PH_SWITCH *p_FB_PH_SWITCH;
  FB_PH_CUSTOMPHASE *p_FB_PH_CUSTOMPHASE;
  FB_AUTONUALG *p_FB_AUTONUALG;
  FB_PUSKOILSYSTEMALG *p_FB_PUSKOILSYSTEMALG;
  FB_PH_WAITANALOGVALUE *p_FB_PH_WAITANALOGVALUE;
  FB_PH_OILPUMP *p_FB_PH_OILPUMP;
  FB_ANTIPOMPAGALG *p_FB_ANTIPOMPAGALG;
  FB_TABLEVALUE_MIN *p_FB_TABLEVALUE_MIN;
  __IEC___ARRAY_OF_TYPE_TABLEREC_9_t *p___IEC___ARRAY_OF_TYPE_TABLEREC_9_t;
  TYPE_TABLEREC *p_TYPE_TABLEREC;
  FB_TABLEVALUE_MAX *p_FB_TABLEVALUE_MAX;
  FB_RASHODALG *p_FB_RASHODALG;
  FB_ZAPASALG *p_FB_ZAPASALG;
  NOALG *p_NOALG;
  FB_PH_KRAN *p_FB_PH_KRAN;
  FB_PH_SECTIONSWITCH *p_FB_PH_SECTIONSWITCH;
  AOALG *p_AOALG;
  PPUALG *p_PPUALG;
  FILLINGALG *p_FILLINGALG;
  FB_PH_DIPROTECTION *p_FB_PH_DIPROTECTION;
  ENGINERUNALG *p_ENGINERUNALG;
  PUSKKALG *p_PUSKKALG;
  PUSKVALG *p_PUSKVALG;
  TESTDPMGALG *p_TESTDPMGALG;
  TESTPMSALG *p_TESTPMSALG;
  FB_PH_AIPROTECTION *p_FB_PH_AIPROTECTION;
  APUSKALG *p_APUSKALG;
  SEMIAUTOPUSKALG *p_SEMIAUTOPUSKALG;
  FB_ALGORITMSMANAGER *p_FB_ALGORITMSMANAGER;
  FB_PROTECTIONSMANAGER *p_FB_PROTECTIONSMANAGER;

  { // 61476 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.INCOMMAND
    st = getVariable(61476);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.INCOMMAND", 57);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_WORD = (WORD*)&p_STRUCT_SWITCH->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 61477 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.STATUS
    st = getVariable(61477);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.STATUS", 54);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_DWORD = (DWORD*)&p_STRUCT_SWITCH->STATUS;
    st->value_p = p_DWORD;
  }
  { // 61478 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.ONSTATUS
    st = getVariable(61478);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.ONSTATUS", 56);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BYTE = (BYTE*)&p_STRUCT_SWITCH->ONSTATUS;
    st->value_p = p_BYTE;
  }
  { // 61479 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.INOPCCOMMANDSDISABLED
    st = getVariable(61479);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.INOPCCOMMANDSDISABLED", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 61480 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.SDVIG
    st = getVariable(61480);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.SDVIG", 53);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->SDVIG;
    st->value_p = p_BOOL;
  }
  { // 61481 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.NS
    st = getVariable(61481);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.NS", 50);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->NS;
    st->value_p = p_BOOL;
  }
  { // 61482 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.COMMANDFAULT
    st = getVariable(61482);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.COMMANDFAULT", 60);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->COMMANDFAULT;
    st->value_p = p_BOOL;
  }
  { // 61483 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.ACCIDENT
    st = getVariable(61483);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.ACCIDENT", 56);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ACCIDENT;
    st->value_p = p_BOOL;
  }
  { // 61484 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.AUTO
    st = getVariable(61484);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.AUTO", 52);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->AUTO;
    st->value_p = p_BOOL;
  }
  { // 61485 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.MANUAL
    st = getVariable(61485);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.MANUAL", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->MANUAL;
    st->value_p = p_BOOL;
  }
  { // 61486 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.LOCAL
    st = getVariable(61486);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.LOCAL", 53);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->LOCAL;
    st->value_p = p_BOOL;
  }
  { // 61487 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.DISTANCE
    st = getVariable(61487);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.DISTANCE", 56);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->DISTANCE;
    st->value_p = p_BOOL;
  }
  { // 61488 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.ERRORPOWEROFF
    st = getVariable(61488);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.ERRORPOWEROFF", 61);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ERRORPOWEROFF;
    st->value_p = p_BOOL;
  }
  { // 61489 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.ERRORBLOCK
    st = getVariable(61489);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.ERRORBLOCK", 58);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ERRORBLOCK;
    st->value_p = p_BOOL;
  }
  { // 61490 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.BREAKCMDON
    st = getVariable(61490);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.BREAKCMDON", 58);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->BREAKCMDON;
    st->value_p = p_BOOL;
  }
  { // 61491 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.BREAKCMDOFF
    st = getVariable(61491);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.BREAKCMDOFF", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->BREAKCMDOFF;
    st->value_p = p_BOOL;
  }
  { // 61492 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.OPCCOMMANDSDISABLED
    st = getVariable(61492);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.OPCCOMMANDSDISABLED", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 61493 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.LASTCMDISON
    st = getVariable(61493);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.LASTCMDISON", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->LASTCMDISON;
    st->value_p = p_BOOL;
  }
  { // 61494 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.ISVALIDREF_STATON
    st = getVariable(61494);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.ISVALIDREF_STATON", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ISVALIDREF_STATON;
    st->value_p = p_BOOL;
  }
  { // 61495 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.ISVALIDREF_STATOFF
    st = getVariable(61495);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.ISVALIDREF_STATOFF", 66);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ISVALIDREF_STATOFF;
    st->value_p = p_BOOL;
  }
  { // 61496 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.ISVALIDREF_CMDON
    st = getVariable(61496);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.ISVALIDREF_CMDON", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ISVALIDREF_CMDON;
    st->value_p = p_BOOL;
  }
  { // 61497 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.ISVALIDREF_CMDOFF
    st = getVariable(61497);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.ISVALIDREF_CMDOFF", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ISVALIDREF_CMDOFF;
    st->value_p = p_BOOL;
  }
  { // 61498 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.ISVALIDREF_INBREAKCMDON
    st = getVariable(61498);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.ISVALIDREF_INBREAKCMDON", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ISVALIDREF_INBREAKCMDON;
    st->value_p = p_BOOL;
  }
  { // 61499 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.ISVALIDREF_INBREAKCMDOFF
    st = getVariable(61499);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.ISVALIDREF_INBREAKCMDOFF", 72);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ISVALIDREF_INBREAKCMDOFF;
    st->value_p = p_BOOL;
  }
  { // 61500 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.INCOMMAND_ALG
    st = getVariable(61500);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.INCOMMAND_ALG", 61);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_WORD = (WORD*)&p_STRUCT_SWITCH->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 61501 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.INCOMMAND_ARM
    st = getVariable(61501);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.INCOMMAND_ARM", 61);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_WORD = (WORD*)&p_STRUCT_SWITCH->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 61502 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.CMDON
    st = getVariable(61502);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.CMDON", 53);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->CMDON;
    st->value_p = p_BOOL;
  }
  { // 61503 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.CMDOFF
    st = getVariable(61503);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.CMDOFF", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->CMDOFF;
    st->value_p = p_BOOL;
  }
  { // 61504 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.RELIABILITY
    st = getVariable(61504);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.IM.RELIABILITY", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 61505 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.PHASENUMBER
    st = getVariable(61505);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.PHASENUMBER", 56);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_UINT = (UINT*)&p_FB_PH_SWITCH->PHASENUMBER;
    UnpackVar(p_UINT, UINT_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 61506 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.STRPH.RUN
    st = getVariable(61506);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.STRPH.RUN", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_SWITCH->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->RUN;
    st->value_p = p_BOOL;
  }
  { // 61507 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.STRPH.RESET
    st = getVariable(61507);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.STRPH.RESET", 56);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_SWITCH->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->RESET;
    st->value_p = p_BOOL;
  }
  { // 61508 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.STRPH.START
    st = getVariable(61508);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.STRPH.START", 56);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_SWITCH->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->START;
    st->value_p = p_BOOL;
  }
  { // 61509 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.STRPH.ERROR
    st = getVariable(61509);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.STRPH.ERROR", 56);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_SWITCH->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->ERROR;
    st->value_p = p_BOOL;
  }
  { // 61510 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.STRPH.TOP
    st = getVariable(61510);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.STRPH.TOP", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_SWITCH->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->TOP;
    st->value_p = p_BOOL;
  }
  { // 61511 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.STRPH.STARTSTATUS
    st = getVariable(61511);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.STRPH.STARTSTATUS", 62);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_SWITCH->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->STARTSTATUS;
    st->value_p = p_DWORD;
  }
  { // 61512 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.STRPH.ERRORSTATUS
    st = getVariable(61512);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.STRPH.ERRORSTATUS", 62);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_SWITCH->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->ERRORSTATUS;
    st->value_p = p_DWORD;
  }
  { // 61513 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.STRPH.TOPSTATUS
    st = getVariable(61513);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.STRPH.TOPSTATUS", 60);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_SWITCH->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->TOPSTATUS;
    st->value_p = p_DWORD;
  }
  { // 61514 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.COMMANDFAULT_TRIG.CLK
    st = getVariable(61514);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.COMMANDFAULT_TRIG.CLK", 66);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_SWITCH->COMMANDFAULT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 61515 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.COMMANDFAULT_TRIG.Q
    st = getVariable(61515);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.COMMANDFAULT_TRIG.Q", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_SWITCH->COMMANDFAULT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 61516 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.COMMANDFAULT_TRIG
    st = getVariable(61516);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.COMMANDFAULT_TRIG", 62);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_SWITCH->COMMANDFAULT_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 61517 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.RESET_TRIG.CLK
    st = getVariable(61517);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.RESET_TRIG.CLK", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_SWITCH->RESET_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 61518 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.RESET_TRIG.Q
    st = getVariable(61518);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.RESET_TRIG.Q", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_SWITCH->RESET_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 61519 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.RESET_TRIG
    st = getVariable(61519);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF.RESET_TRIG", 55);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_SWITCH->RESET_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 61520 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF._STATUSDUALINPUT.STATUS_NOTDEFINED
    st = getVariable(61520);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF._STATUSDUALINPUT.STATUS_NOTDEFINED", 79);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_SWITCH->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_NOTDEFINED;
    st->value_p = p_BYTE;
  }
  { // 61521 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF._STATUSDUALINPUT.STATUS_ON
    st = getVariable(61521);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF._STATUSDUALINPUT.STATUS_ON", 71);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_SWITCH->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ON;
    st->value_p = p_BYTE;
  }
  { // 61522 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF._STATUSDUALINPUT.STATUS_OFF
    st = getVariable(61522);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF._STATUSDUALINPUT.STATUS_OFF", 72);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_SWITCH->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_OFF;
    st->value_p = p_BYTE;
  }
  { // 61523 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF._STATUSDUALINPUT.STATUS_TRANSITIONAL
    st = getVariable(61523);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF._STATUSDUALINPUT.STATUS_TRANSITIONAL", 81);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_SWITCH->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_TRANSITIONAL;
    st->value_p = p_BYTE;
  }
  { // 61524 PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF._STATUSDUALINPUT.STATUS_ERROR
    st = getVariable(61524);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_NOALG.FB_AVOM3OFF._STATUSDUALINPUT.STATUS_ERROR", 74);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_NOALG = (NOALG*)&p_PROC_ALGORITMS->FB_NOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_NOALG->FB_AVOM3OFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_SWITCH->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ERROR;
    st->value_p = p_BYTE;
  }
  { // 68180 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.INCOMMAND
    st = getVariable(68180);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.INCOMMAND", 57);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_WORD = (WORD*)&p_STRUCT_SWITCH->INCOMMAND;
    st->value_p = p_WORD;
  }
  { // 68181 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.STATUS
    st = getVariable(68181);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.STATUS", 54);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_DWORD = (DWORD*)&p_STRUCT_SWITCH->STATUS;
    st->value_p = p_DWORD;
  }
  { // 68182 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.ONSTATUS
    st = getVariable(68182);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.ONSTATUS", 56);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BYTE = (BYTE*)&p_STRUCT_SWITCH->ONSTATUS;
    st->value_p = p_BYTE;
  }
  { // 68183 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.INOPCCOMMANDSDISABLED
    st = getVariable(68183);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.INOPCCOMMANDSDISABLED", 69);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->INOPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 68184 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.SDVIG
    st = getVariable(68184);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.SDVIG", 53);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->SDVIG;
    st->value_p = p_BOOL;
  }
  { // 68185 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.NS
    st = getVariable(68185);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.NS", 50);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->NS;
    st->value_p = p_BOOL;
  }
  { // 68186 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.COMMANDFAULT
    st = getVariable(68186);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.COMMANDFAULT", 60);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->COMMANDFAULT;
    st->value_p = p_BOOL;
  }
  { // 68187 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.ACCIDENT
    st = getVariable(68187);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.ACCIDENT", 56);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ACCIDENT;
    st->value_p = p_BOOL;
  }
  { // 68188 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.AUTO
    st = getVariable(68188);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.AUTO", 52);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->AUTO;
    st->value_p = p_BOOL;
  }
  { // 68189 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.MANUAL
    st = getVariable(68189);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.MANUAL", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->MANUAL;
    st->value_p = p_BOOL;
  }
  { // 68190 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.LOCAL
    st = getVariable(68190);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.LOCAL", 53);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->LOCAL;
    st->value_p = p_BOOL;
  }
  { // 68191 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.DISTANCE
    st = getVariable(68191);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.DISTANCE", 56);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->DISTANCE;
    st->value_p = p_BOOL;
  }
  { // 68192 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.ERRORPOWEROFF
    st = getVariable(68192);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.ERRORPOWEROFF", 61);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ERRORPOWEROFF;
    st->value_p = p_BOOL;
  }
  { // 68193 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.ERRORBLOCK
    st = getVariable(68193);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.ERRORBLOCK", 58);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ERRORBLOCK;
    st->value_p = p_BOOL;
  }
  { // 68194 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.BREAKCMDON
    st = getVariable(68194);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.BREAKCMDON", 58);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->BREAKCMDON;
    st->value_p = p_BOOL;
  }
  { // 68195 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.BREAKCMDOFF
    st = getVariable(68195);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.BREAKCMDOFF", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->BREAKCMDOFF;
    st->value_p = p_BOOL;
  }
  { // 68196 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.OPCCOMMANDSDISABLED
    st = getVariable(68196);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.OPCCOMMANDSDISABLED", 67);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->OPCCOMMANDSDISABLED;
    st->value_p = p_BOOL;
  }
  { // 68197 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.LASTCMDISON
    st = getVariable(68197);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.LASTCMDISON", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->LASTCMDISON;
    st->value_p = p_BOOL;
  }
  { // 68198 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.ISVALIDREF_STATON
    st = getVariable(68198);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.ISVALIDREF_STATON", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ISVALIDREF_STATON;
    st->value_p = p_BOOL;
  }
  { // 68199 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.ISVALIDREF_STATOFF
    st = getVariable(68199);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.ISVALIDREF_STATOFF", 66);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ISVALIDREF_STATOFF;
    st->value_p = p_BOOL;
  }
  { // 68200 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.ISVALIDREF_CMDON
    st = getVariable(68200);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.ISVALIDREF_CMDON", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ISVALIDREF_CMDON;
    st->value_p = p_BOOL;
  }
  { // 68201 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.ISVALIDREF_CMDOFF
    st = getVariable(68201);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.ISVALIDREF_CMDOFF", 65);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ISVALIDREF_CMDOFF;
    st->value_p = p_BOOL;
  }
  { // 68202 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.ISVALIDREF_INBREAKCMDON
    st = getVariable(68202);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.ISVALIDREF_INBREAKCMDON", 71);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ISVALIDREF_INBREAKCMDON;
    st->value_p = p_BOOL;
  }
  { // 68203 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.ISVALIDREF_INBREAKCMDOFF
    st = getVariable(68203);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.ISVALIDREF_INBREAKCMDOFF", 72);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->ISVALIDREF_INBREAKCMDOFF;
    st->value_p = p_BOOL;
  }
  { // 68204 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.INCOMMAND_ALG
    st = getVariable(68204);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.INCOMMAND_ALG", 61);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_WORD = (WORD*)&p_STRUCT_SWITCH->INCOMMAND_ALG;
    st->value_p = p_WORD;
  }
  { // 68205 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.INCOMMAND_ARM
    st = getVariable(68205);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.INCOMMAND_ARM", 61);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_WORD = (WORD*)&p_STRUCT_SWITCH->INCOMMAND_ARM;
    st->value_p = p_WORD;
  }
  { // 68206 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.CMDON
    st = getVariable(68206);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.CMDON", 53);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->CMDON;
    st->value_p = p_BOOL;
  }
  { // 68207 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.CMDOFF
    st = getVariable(68207);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.CMDOFF", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->CMDOFF;
    st->value_p = p_BOOL;
  }
  { // 68208 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.RELIABILITY
    st = getVariable(68208);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.IM.RELIABILITY", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_SWITCH = (STRUCT_SWITCH*)&p_FB_PH_SWITCH->IM;
    p_BOOL = (BOOL*)&p_STRUCT_SWITCH->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 68209 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.PHASENUMBER
    st = getVariable(68209);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.PHASENUMBER", 56);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_UINT = (UINT*)&p_FB_PH_SWITCH->PHASENUMBER;
    UnpackVar(p_UINT, UINT_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 68210 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.STRPH.RUN
    st = getVariable(68210);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.STRPH.RUN", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_SWITCH->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->RUN;
    st->value_p = p_BOOL;
  }
  { // 68211 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.STRPH.RESET
    st = getVariable(68211);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.STRPH.RESET", 56);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_SWITCH->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->RESET;
    st->value_p = p_BOOL;
  }
  { // 68212 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.STRPH.START
    st = getVariable(68212);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.STRPH.START", 56);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_SWITCH->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->START;
    st->value_p = p_BOOL;
  }
  { // 68213 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.STRPH.ERROR
    st = getVariable(68213);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.STRPH.ERROR", 56);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_SWITCH->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->ERROR;
    st->value_p = p_BOOL;
  }
  { // 68214 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.STRPH.TOP
    st = getVariable(68214);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.STRPH.TOP", 54);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_SWITCH->STRPH;
    p_BOOL = (BOOL*)&p_STRUCT_PHASEALGORITM->TOP;
    st->value_p = p_BOOL;
  }
  { // 68215 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.STRPH.STARTSTATUS
    st = getVariable(68215);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.STRPH.STARTSTATUS", 62);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_SWITCH->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->STARTSTATUS;
    st->value_p = p_DWORD;
  }
  { // 68216 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.STRPH.ERRORSTATUS
    st = getVariable(68216);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.STRPH.ERRORSTATUS", 62);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_SWITCH->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->ERRORSTATUS;
    st->value_p = p_DWORD;
  }
  { // 68217 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.STRPH.TOPSTATUS
    st = getVariable(68217);
    memcpy(st->IEC_TYPE, "DWORD", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.STRPH.TOPSTATUS", 60);
    st->size_data = sizeof(DWORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_STRUCT_PHASEALGORITM = (STRUCT_PHASEALGORITM*)&p_FB_PH_SWITCH->STRPH;
    p_DWORD = (DWORD*)&p_STRUCT_PHASEALGORITM->TOPSTATUS;
    st->value_p = p_DWORD;
  }
  { // 68218 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.COMMANDFAULT_TRIG.CLK
    st = getVariable(68218);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.COMMANDFAULT_TRIG.CLK", 66);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_SWITCH->COMMANDFAULT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 68219 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.COMMANDFAULT_TRIG.Q
    st = getVariable(68219);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.COMMANDFAULT_TRIG.Q", 64);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_SWITCH->COMMANDFAULT_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 68220 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.COMMANDFAULT_TRIG
    st = getVariable(68220);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.COMMANDFAULT_TRIG", 62);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_SWITCH->COMMANDFAULT_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 68221 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.RESET_TRIG.CLK
    st = getVariable(68221);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.RESET_TRIG.CLK", 59);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_SWITCH->RESET_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->CLK;
    st->value_p = p_BOOL;
  }
  { // 68222 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.RESET_TRIG.Q
    st = getVariable(68222);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.RESET_TRIG.Q", 57);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_SWITCH->RESET_TRIG;
    p_BOOL = (BOOL*)&p_R_TRIG->Q;
    st->value_p = p_BOOL;
  }
  { // 68223 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.RESET_TRIG
    st = getVariable(68223);
    memcpy(st->IEC_TYPE, "R_TRIG", 6);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF.RESET_TRIG", 55);
    st->size_data = sizeof(R_TRIG);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_R_TRIG = (R_TRIG*)&p_FB_PH_SWITCH->RESET_TRIG;
    st->value_p = (void *)p_R_TRIG;
  }
  { // 68224 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF._STATUSDUALINPUT.STATUS_NOTDEFINED
    st = getVariable(68224);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF._STATUSDUALINPUT.STATUS_NOTDEFINED", 79);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_SWITCH->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_NOTDEFINED;
    st->value_p = p_BYTE;
  }
  { // 68225 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF._STATUSDUALINPUT.STATUS_ON
    st = getVariable(68225);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF._STATUSDUALINPUT.STATUS_ON", 71);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_SWITCH->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ON;
    st->value_p = p_BYTE;
  }
  { // 68226 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF._STATUSDUALINPUT.STATUS_OFF
    st = getVariable(68226);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF._STATUSDUALINPUT.STATUS_OFF", 72);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_SWITCH->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_OFF;
    st->value_p = p_BYTE;
  }
  { // 68227 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF._STATUSDUALINPUT.STATUS_TRANSITIONAL
    st = getVariable(68227);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF._STATUSDUALINPUT.STATUS_TRANSITIONAL", 81);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_SWITCH->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_TRANSITIONAL;
    st->value_p = p_BYTE;
  }
  { // 68228 PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF._STATUSDUALINPUT.STATUS_ERROR
    st = getVariable(68228);
    memcpy(st->IEC_TYPE, "BYTE", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.ALGORITMS_PROC.FB_AOALG.FB_AVOM3OFF._STATUSDUALINPUT.STATUS_ERROR", 74);
    st->size_data = sizeof(BYTE);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_ALGORITMS = (PROC_ALGORITMS*)&p_PROGRAM0->ALGORITMS_PROC;
    p_AOALG = (AOALG*)&p_PROC_ALGORITMS->FB_AOALG;
    p_FB_PH_SWITCH = (FB_PH_SWITCH*)&p_AOALG->FB_AVOM3OFF;
    p_TYPE_STATUSDUALINPUT = (TYPE_STATUSDUALINPUT*)&p_FB_PH_SWITCH->_STATUSDUALINPUT;
    p_BYTE = (BYTE*)&p_TYPE_STATUSDUALINPUT->STATUS_ERROR;
    st->value_p = p_BYTE;
  }

  return 0;
}

// clang-format on
