// clang-format off

#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>

#include "POUS.h"
#include <beremiz/beremiz.h>

#include "iec_types_all.h"
#include "config1.h"

extern PROGRAM0 RESOURCE1__INSTANCE0;

#ifdef DEBUG_PLC
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err][%s:%d]: " _PRNTMSG "\n", __func__, __LINE__, ##__VA_ARGS__)
#else
#define err(_PRNTMSG, ...) fprintf(stderr, "[VARIABLES][err]: " _PRNTMSG "\n", ##__VA_ARGS__)
#endif // DEBUG_PLC

void UnpackVar(void* varp, __IEC_types_enum vartype, void **value_p, void **f_value_p, uint8_t **flags);

int __variables_init_DI_3(){
  iec_var_t *st;

  PROGRAM0 *p_PROGRAM0;
  LREAL *p_LREAL;
  ULINT *p_ULINT;
  REAL *p_REAL;
  FB_TIMINGS *p_FB_TIMINGS;
  BOOL *p_BOOL;
  UINT *p_UINT;
  PROC_AI_INIT *p_PROC_AI_INIT;
  FB_AI_INIT *p_FB_AI_INIT;
  TIME *p_TIME;
  STRUCT_AI *p_STRUCT_AI;
  DWORD *p_DWORD;
  BYTE *p_BYTE;
  WORD *p_WORD;
  AICONFIG *p_AICONFIG;
  PROC_AI *p_PROC_AI;
  FB_AISOURCEMLP *p_FB_AISOURCEMLP;
  TITEMAIN *p_TITEMAIN;
  TITEMDIN *p_TITEMDIN;
  TYPE_STATUSAI *p_TYPE_STATUSAI;
  TYPE_COMMANDANALOG *p_TYPE_COMMANDANALOG;
  FB_SUNPACKERCOMMAND *p_FB_SUNPACKERCOMMAND;
  TYPE_ANALOGLIMITFLAGS *p_TYPE_ANALOGLIMITFLAGS;
  TON *p_TON;
  R_TRIG *p_R_TRIG;
  FB_AISOURCEMLP_TIMER *p_FB_AISOURCEMLP_TIMER;
  PROC_AO_INIT *p_PROC_AO_INIT;
  FB_AO_INIT *p_FB_AO_INIT;
  STRUCT_AO *p_STRUCT_AO;
  AOCONFIG *p_AOCONFIG;
  PROC_AO *p_PROC_AO;
  FB_AOSOURCEMLP *p_FB_AOSOURCEMLP;
  TDOUBLEDATA *p_TDOUBLEDATA;
  PROC_DI_INIT *p_PROC_DI_INIT;
  FB_DI_INIT *p_FB_DI_INIT;
  STRUCT_DI *p_STRUCT_DI;
  __IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t *p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t;
  TYPE_RELIABLEBIT *p_TYPE_RELIABLEBIT;
  DICONFIG *p_DICONFIG;
  PROC_DI *p_PROC_DI;
  FB_DISOURCEMLP *p_FB_DISOURCEMLP;
  INT *p_INT;
  UDINT *p_UDINT;
  PROC_DO_INIT *p_PROC_DO_INIT;
  FB_DO_INIT *p_FB_DO_INIT;
  STRUCT_DO *p_STRUCT_DO;
  __IEC___ARRAY_OF_BOOL_16_t *p___IEC___ARRAY_OF_BOOL_16_t;
  DOCONFIG *p_DOCONFIG;
  PROC_DO *p_PROC_DO;
  FB_DOSOURCEMLP *p_FB_DOSOURCEMLP;
  TWORDDATA *p_TWORDDATA;
  OPC_ALGORITMS_SET *p_OPC_ALGORITMS_SET;
  ALGORITMSCONFIG *p_ALGORITMSCONFIG;
  STRUCT_ALG *p_STRUCT_ALG;
  STRUCT_ALGORITMSMANAGER *p_STRUCT_ALGORITMSMANAGER;
  STRUCT_PROTECTIONSMANAGER *p_STRUCT_PROTECTIONSMANAGER;
  STRUCT_ALGTIMERS *p_STRUCT_ALGTIMERS;
  ALGORITMSQUESTIONS *p_ALGORITMSQUESTIONS;
  STRUCT_QUESTION *p_STRUCT_QUESTION;
  OPC_ALGORITMS_GET *p_OPC_ALGORITMS_GET;
  PROC_IM_INIT *p_PROC_IM_INIT;
  FB_KRAN_INIT *p_FB_KRAN_INIT;
  STRUCT_KRAN *p_STRUCT_KRAN;
  FB_SWITCH_INIT *p_FB_SWITCH_INIT;
  STRUCT_SWITCH *p_STRUCT_SWITCH;
  FB_OILPUMP_INIT *p_FB_OILPUMP_INIT;
  STRUCT_OILPUMP *p_STRUCT_OILPUMP;
  FB_SECTIONSWITCH_INIT *p_FB_SECTIONSWITCH_INIT;
  STRUCT_SECTIONSWITCH *p_STRUCT_SECTIONSWITCH;
  FB_ANALOGPARAMETR_INIT *p_FB_ANALOGPARAMETR_INIT;
  STRUCT_ANALOGPARAMETR *p_STRUCT_ANALOGPARAMETR;
  FB_DISCRETPARAMETR_INIT *p_FB_DISCRETPARAMETR_INIT;
  STRUCT_DISCRETPARAMETR *p_STRUCT_DISCRETPARAMETR;
  FB_SINGLESIGNAL_INIT *p_FB_SINGLESIGNAL_INIT;
  STRUCT_SINGLESIGNAL *p_STRUCT_SINGLESIGNAL;
  FB_SINGLEOUTPUT_INIT *p_FB_SINGLEOUTPUT_INIT;
  STRUCT_SINGLEOUTPUT *p_STRUCT_SINGLEOUTPUT;
  IMCONFIG *p_IMCONFIG;
  STRUCT_RESERVEIM *p_STRUCT_RESERVEIM;
  STRUCT_RESERVEIM2 *p_STRUCT_RESERVEIM2;
  IM_SINGLESIGNALS *p_IM_SINGLESIGNALS;
  IM_SINGLEOUTPUTS *p_IM_SINGLEOUTPUTS;
  PROC_IM *p_PROC_IM;
  FB_KRAN *p_FB_KRAN;
  TYPE_STATUSDUALINPUT *p_TYPE_STATUSDUALINPUT;
  TYPE_COMMANDDUALINPUT *p_TYPE_COMMANDDUALINPUT;
  TOF *p_TOF;
  FB_OILPUMP *p_FB_OILPUMP;
  FB_SWITCH *p_FB_SWITCH;
  FB_SECTIONSWITCH *p_FB_SECTIONSWITCH;
  TYPE_BASKETSTATS *p_TYPE_BASKETSTATS;
  FB_MEANDR *p_FB_MEANDR;
  FB_SINGLESIGNAL *p_FB_SINGLESIGNAL;
  FB_SINGLEOUTPUT *p_FB_SINGLEOUTPUT;
  FB_DISCRETPARAMETR *p_FB_DISCRETPARAMETR;
  FB_ANALOGPARAMETR *p_FB_ANALOGPARAMETR;
  OPC_IM_GET *p_OPC_IM_GET;
  OPC_IM_SET *p_OPC_IM_SET;
  PROC_PROTECTIONS_INIT *p_PROC_PROTECTIONS_INIT;
  FB_DIPROTECTION_INIT *p_FB_DIPROTECTION_INIT;
  STRUCT_DIPROTECTION *p_STRUCT_DIPROTECTION;
  FB_AIPROTECTION_INIT *p_FB_AIPROTECTION_INIT;
  STRUCT_AIPROTECTION *p_STRUCT_AIPROTECTION;
  PROTECTIONSCONFIG *p_PROTECTIONSCONFIG;
  TYPE_PROTECTIONTAGS *p_TYPE_PROTECTIONTAGS;
  PROC_PROTECTION *p_PROC_PROTECTION;
  FB_DIPROTECTION *p_FB_DIPROTECTION;
  F_TRIG *p_F_TRIG;
  FB_MVPROTECTION *p_FB_MVPROTECTION;
  FB_KRANOPENPROTECTION *p_FB_KRANOPENPROTECTION;
  FB_AIPROTECTION *p_FB_AIPROTECTION;
  PROC_ALGORITMS *p_PROC_ALGORITMS;
  REMONTALG *p_REMONTALG;
  TYPE_MODEGPA *p_TYPE_MODEGPA;
  TYPE_COMMANDSPOTECTIONSMANAGER *p_TYPE_COMMANDSPOTECTIONSMANAGER;
  TESTPROTECTIONALG *p_TESTPROTECTIONALG;
  TESTIMALG *p_TESTIMALG;
  FB_AUTOTENALG *p_FB_AUTOTENALG;
  FB_AUTOPNSALG *p_FB_AUTOPNSALG;
  FB_AUTOAVOMALG *p_FB_AUTOAVOMALG;
  FB_VIBEGPNSALG *p_FB_VIBEGPNSALG;
  STRUCT_PHASEALGORITM *p_STRUCT_PHASEALGORITM;
  FB_PH_ALGORITM *p_FB_PH_ALGORITM;
  FB_PH_TIMER *p_FB_PH_TIMER;
  FB_QUESTION *p_FB_QUESTION;
  TYPE_ANSWERS *p_TYPE_ANSWERS;
  FB_PH_SWITCH *p_FB_PH_SWITCH;
  FB_PH_CUSTOMPHASE *p_FB_PH_CUSTOMPHASE;
  FB_AUTONUALG *p_FB_AUTONUALG;
  FB_PUSKOILSYSTEMALG *p_FB_PUSKOILSYSTEMALG;
  FB_PH_WAITANALOGVALUE *p_FB_PH_WAITANALOGVALUE;
  FB_PH_OILPUMP *p_FB_PH_OILPUMP;
  FB_ANTIPOMPAGALG *p_FB_ANTIPOMPAGALG;
  FB_TABLEVALUE_MIN *p_FB_TABLEVALUE_MIN;
  __IEC___ARRAY_OF_TYPE_TABLEREC_9_t *p___IEC___ARRAY_OF_TYPE_TABLEREC_9_t;
  TYPE_TABLEREC *p_TYPE_TABLEREC;
  FB_TABLEVALUE_MAX *p_FB_TABLEVALUE_MAX;
  FB_RASHODALG *p_FB_RASHODALG;
  FB_ZAPASALG *p_FB_ZAPASALG;
  NOALG *p_NOALG;
  FB_PH_KRAN *p_FB_PH_KRAN;
  FB_PH_SECTIONSWITCH *p_FB_PH_SECTIONSWITCH;
  AOALG *p_AOALG;
  PPUALG *p_PPUALG;
  FILLINGALG *p_FILLINGALG;
  FB_PH_DIPROTECTION *p_FB_PH_DIPROTECTION;
  ENGINERUNALG *p_ENGINERUNALG;
  PUSKKALG *p_PUSKKALG;
  PUSKVALG *p_PUSKVALG;
  TESTDPMGALG *p_TESTDPMGALG;
  TESTPMSALG *p_TESTPMSALG;
  FB_PH_AIPROTECTION *p_FB_PH_AIPROTECTION;
  APUSKALG *p_APUSKALG;
  SEMIAUTOPUSKALG *p_SEMIAUTOPUSKALG;
  FB_ALGORITMSMANAGER *p_FB_ALGORITMSMANAGER;
  FB_PROTECTIONSMANAGER *p_FB_PROTECTIONSMANAGER;

  { // 15559 PROGRAM0.DI_PROC.DI_3.ARDIN.WFLAGS
    st = getVariable(15559);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.ARDIN.WFLAGS", 34);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_TITEMDIN = (TITEMDIN*)&p_FB_DISOURCEMLP->ARDIN;
    p_UINT = (UINT*)&p_TITEMDIN->WFLAGS;
    st->value_p = p_UINT;
  }
  { // 15560 PROGRAM0.DI_PROC.DI_3.ARDIN.WVALUE
    st = getVariable(15560);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.ARDIN.WVALUE", 34);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_TITEMDIN = (TITEMDIN*)&p_FB_DISOURCEMLP->ARDIN;
    p_UINT = (UINT*)&p_TITEMDIN->WVALUE;
    st->value_p = p_UINT;
  }
  { // 15561 PROGRAM0.DI_PROC.DI_3.ARDIN.NANOSEC
    st = getVariable(15561);
    memcpy(st->IEC_TYPE, "ULINT", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.ARDIN.NANOSEC", 35);
    st->size_data = sizeof(ULINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_TITEMDIN = (TITEMDIN*)&p_FB_DISOURCEMLP->ARDIN;
    p_ULINT = (ULINT*)&p_TITEMDIN->NANOSEC;
    st->value_p = p_ULINT;
  }
  { // 15562 PROGRAM0.DI_PROC.DI_3.ARDIN.RESERVE
    st = getVariable(15562);
    memcpy(st->IEC_TYPE, "ULINT", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.ARDIN.RESERVE", 35);
    st->size_data = sizeof(ULINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_TITEMDIN = (TITEMDIN*)&p_FB_DISOURCEMLP->ARDIN;
    p_ULINT = (ULINT*)&p_TITEMDIN->RESERVE;
    st->value_p = p_ULINT;
  }
  { // 15563 PROGRAM0.DI_PROC.DI_3.ERR_MOD.WFLAGS
    st = getVariable(15563);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.ERR_MOD.WFLAGS", 36);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_TITEMDIN = (TITEMDIN*)&p_FB_DISOURCEMLP->ERR_MOD;
    p_UINT = (UINT*)&p_TITEMDIN->WFLAGS;
    st->value_p = p_UINT;
  }
  { // 15564 PROGRAM0.DI_PROC.DI_3.ERR_MOD.WVALUE
    st = getVariable(15564);
    memcpy(st->IEC_TYPE, "UINT", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.ERR_MOD.WVALUE", 36);
    st->size_data = sizeof(UINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_TITEMDIN = (TITEMDIN*)&p_FB_DISOURCEMLP->ERR_MOD;
    p_UINT = (UINT*)&p_TITEMDIN->WVALUE;
    st->value_p = p_UINT;
  }
  { // 15565 PROGRAM0.DI_PROC.DI_3.ERR_MOD.NANOSEC
    st = getVariable(15565);
    memcpy(st->IEC_TYPE, "ULINT", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.ERR_MOD.NANOSEC", 37);
    st->size_data = sizeof(ULINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_TITEMDIN = (TITEMDIN*)&p_FB_DISOURCEMLP->ERR_MOD;
    p_ULINT = (ULINT*)&p_TITEMDIN->NANOSEC;
    st->value_p = p_ULINT;
  }
  { // 15566 PROGRAM0.DI_PROC.DI_3.ERR_MOD.RESERVE
    st = getVariable(15566);
    memcpy(st->IEC_TYPE, "ULINT", 5);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.ERR_MOD.RESERVE", 37);
    st->size_data = sizeof(ULINT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_TITEMDIN = (TITEMDIN*)&p_FB_DISOURCEMLP->ERR_MOD;
    p_ULINT = (ULINT*)&p_TITEMDIN->RESERVE;
    st->value_p = p_ULINT;
  }
  { // 15567 PROGRAM0.DI_PROC.DI_3.STRDI.IMIT
    st = getVariable(15567);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.IMIT", 32);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p_BOOL = (BOOL*)&p_STRUCT_DI->IMIT;
    st->value_p = p_BOOL;
  }
  { // 15568 PROGRAM0.DI_PROC.DI_3.STRDI.VALUE
    st = getVariable(15568);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.VALUE", 33);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p_WORD = (WORD*)&p_STRUCT_DI->VALUE;
    st->value_p = p_WORD;
  }
  { // 15569 PROGRAM0.DI_PROC.DI_3.STRDI.RELIABILITY
    st = getVariable(15569);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.RELIABILITY", 39);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p_WORD = (WORD*)&p_STRUCT_DI->RELIABILITY;
    st->value_p = p_WORD;
  }
  { // 15570 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[0].VALUE
    st = getVariable(15570);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[0].VALUE", 41);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[0];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 15571 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[0].RELIABILITY
    st = getVariable(15571);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[0].RELIABILITY", 47);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[0];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 15572 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[0]._INVERSED
    st = getVariable(15572);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[0]._INVERSED", 45);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[0];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 15573 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[1].VALUE
    st = getVariable(15573);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[1].VALUE", 41);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[1];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 15574 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[1].RELIABILITY
    st = getVariable(15574);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[1].RELIABILITY", 47);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[1];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 15575 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[1]._INVERSED
    st = getVariable(15575);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[1]._INVERSED", 45);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[1];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 15576 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[2].VALUE
    st = getVariable(15576);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[2].VALUE", 41);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[2];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 15577 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[2].RELIABILITY
    st = getVariable(15577);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[2].RELIABILITY", 47);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[2];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 15578 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[2]._INVERSED
    st = getVariable(15578);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[2]._INVERSED", 45);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[2];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 15579 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[3].VALUE
    st = getVariable(15579);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[3].VALUE", 41);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[3];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 15580 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[3].RELIABILITY
    st = getVariable(15580);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[3].RELIABILITY", 47);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[3];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 15581 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[3]._INVERSED
    st = getVariable(15581);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[3]._INVERSED", 45);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[3];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 15582 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[4].VALUE
    st = getVariable(15582);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[4].VALUE", 41);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[4];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 15583 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[4].RELIABILITY
    st = getVariable(15583);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[4].RELIABILITY", 47);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[4];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 15584 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[4]._INVERSED
    st = getVariable(15584);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[4]._INVERSED", 45);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[4];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 15585 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[5].VALUE
    st = getVariable(15585);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[5].VALUE", 41);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[5];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 15586 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[5].RELIABILITY
    st = getVariable(15586);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[5].RELIABILITY", 47);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[5];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 15587 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[5]._INVERSED
    st = getVariable(15587);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[5]._INVERSED", 45);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[5];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 15588 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[6].VALUE
    st = getVariable(15588);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[6].VALUE", 41);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[6];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 15589 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[6].RELIABILITY
    st = getVariable(15589);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[6].RELIABILITY", 47);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[6];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 15590 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[6]._INVERSED
    st = getVariable(15590);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[6]._INVERSED", 45);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[6];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 15591 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[7].VALUE
    st = getVariable(15591);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[7].VALUE", 41);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[7];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 15592 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[7].RELIABILITY
    st = getVariable(15592);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[7].RELIABILITY", 47);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[7];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 15593 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[7]._INVERSED
    st = getVariable(15593);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[7]._INVERSED", 45);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[7];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 15594 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[8].VALUE
    st = getVariable(15594);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[8].VALUE", 41);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[8];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 15595 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[8].RELIABILITY
    st = getVariable(15595);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[8].RELIABILITY", 47);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[8];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 15596 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[8]._INVERSED
    st = getVariable(15596);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[8]._INVERSED", 45);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[8];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 15597 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[9].VALUE
    st = getVariable(15597);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[9].VALUE", 41);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[9];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 15598 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[9].RELIABILITY
    st = getVariable(15598);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[9].RELIABILITY", 47);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[9];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 15599 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[9]._INVERSED
    st = getVariable(15599);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[9]._INVERSED", 45);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[9];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 15600 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[10].VALUE
    st = getVariable(15600);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[10].VALUE", 42);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[10];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 15601 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[10].RELIABILITY
    st = getVariable(15601);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[10].RELIABILITY", 48);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[10];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 15602 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[10]._INVERSED
    st = getVariable(15602);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[10]._INVERSED", 46);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[10];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 15603 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[11].VALUE
    st = getVariable(15603);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[11].VALUE", 42);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[11];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 15604 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[11].RELIABILITY
    st = getVariable(15604);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[11].RELIABILITY", 48);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[11];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 15605 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[11]._INVERSED
    st = getVariable(15605);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[11]._INVERSED", 46);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[11];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 15606 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[12].VALUE
    st = getVariable(15606);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[12].VALUE", 42);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[12];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 15607 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[12].RELIABILITY
    st = getVariable(15607);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[12].RELIABILITY", 48);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[12];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 15608 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[12]._INVERSED
    st = getVariable(15608);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[12]._INVERSED", 46);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[12];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 15609 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[13].VALUE
    st = getVariable(15609);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[13].VALUE", 42);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[13];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 15610 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[13].RELIABILITY
    st = getVariable(15610);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[13].RELIABILITY", 48);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[13];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 15611 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[13]._INVERSED
    st = getVariable(15611);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[13]._INVERSED", 46);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[13];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 15612 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[14].VALUE
    st = getVariable(15612);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[14].VALUE", 42);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[14];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 15613 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[14].RELIABILITY
    st = getVariable(15613);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[14].RELIABILITY", 48);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[14];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 15614 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[14]._INVERSED
    st = getVariable(15614);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[14]._INVERSED", 46);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[14];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 15615 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[15].VALUE
    st = getVariable(15615);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[15].VALUE", 42);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[15];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->VALUE;
    st->value_p = p_BOOL;
  }
  { // 15616 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[15].RELIABILITY
    st = getVariable(15616);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[15].RELIABILITY", 48);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[15];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->RELIABILITY;
    st->value_p = p_BOOL;
  }
  { // 15617 PROGRAM0.DI_PROC.DI_3.STRDI.BITS[15]._INVERSED
    st = getVariable(15617);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BITS[15]._INVERSED", 46);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t = (__IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t*)&p_STRUCT_DI->BITS;
    p_TYPE_RELIABLEBIT = &p___IEC___ARRAY_OF_TYPE_RELIABLEBIT_16_t->value.table[15];;
    p_BOOL = (BOOL*)&p_TYPE_RELIABLEBIT->_INVERSED;
    st->value_p = p_BOOL;
  }
  { // 15618 PROGRAM0.DI_PROC.DI_3.STRDI.BLCONNECT
    st = getVariable(15618);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.STRDI.BLCONNECT", 37);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_STRUCT_DI = (STRUCT_DI*)&p_FB_DISOURCEMLP->STRDI;
    p_BOOL = (BOOL*)&p_STRUCT_DI->BLCONNECT;
    st->value_p = p_BOOL;
  }
  { // 15619 PROGRAM0.DI_PROC.DI_3.BOUNCE
    st = getVariable(15619);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.BOUNCE", 28);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_BOOL = (BOOL*)&p_FB_DISOURCEMLP->BOUNCE;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 15620 PROGRAM0.DI_PROC.DI_3._VALUE
    st = getVariable(15620);
    memcpy(st->IEC_TYPE, "WORD", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3._VALUE", 28);
    st->size_data = sizeof(WORD);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_WORD = (WORD*)&p_FB_DISOURCEMLP->_VALUE;
    UnpackVar(p_WORD, WORD_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 15621 PROGRAM0.DI_PROC.DI_3._RELIABILITY
    st = getVariable(15621);
    memcpy(st->IEC_TYPE, "BOOL", 4);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3._RELIABILITY", 34);
    st->size_data = sizeof(BOOL);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_BOOL = (BOOL*)&p_FB_DISOURCEMLP->_RELIABILITY;
    UnpackVar(p_BOOL, BOOL_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 15622 PROGRAM0.DI_PROC.DI_3.BITNUMBER
    st = getVariable(15622);
    memcpy(st->IEC_TYPE, "INT", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.BITNUMBER", 31);
    st->size_data = sizeof(INT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_INT = (INT*)&p_FB_DISOURCEMLP->BITNUMBER;
    UnpackVar(p_INT, INT_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }
  { // 15623 PROGRAM0.DI_PROC.DI_3.BITNUM
    st = getVariable(15623);
    memcpy(st->IEC_TYPE, "INT", 3);
    memcpy(st->IEC_VAR_NAME, "PROGRAM0.DI_PROC.DI_3.BITNUM", 28);
    st->size_data = sizeof(INT);
    p_PROGRAM0 = &RESOURCE1__INSTANCE0;
    p_PROC_DI = (PROC_DI*)&p_PROGRAM0->DI_PROC;
    p_FB_DISOURCEMLP = (FB_DISOURCEMLP*)&p_PROC_DI->DI_3;
    p_INT = (INT*)&p_FB_DISOURCEMLP->BITNUM;
    UnpackVar(p_INT, INT_ENUM, &st->value_p, &st->f_value_p, &st->flags);
  }

  return 0;
}

// clang-format on
